### ISSUE TITLE
New installing

### ISSUE THREAD

**Issue by Crillox** [MJRLegends/Space-Astronomy-Feedback-#1004]
### ---Issue Report---
** if i want to start the modpack i need to install it every time i closed twitch luncher and all my worlds are deleted **

**Have you checked the Known Issues page :** [Yes]

**Have you checked Open/Closed Issues ** [Yes]
### Description of Issue
 if i want to start the modpack i need to install it every time i closed twitch luncher and all my worlds are deleted

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Contact twitch app support nothing i can do for you
