### ISSUE TITLE
Game crash on load

### ISSUE THREAD

**Issue by t3rr0r99** [MJRLegends/Space-Astronomy-Feedback-#1005]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes
### Description of Issue
[Description of the issue] Whenever I attempt to load the modpack it goes through all 7 stages to take me to the main menu but right as it finishes loading the game crashes.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
https://pastebin.com/4btnEeBG
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.5.5
**Where did this bug happen:** [Single Player or Server]
Singleplayer
### Additional Information
[Any other information that may be able to help me with the problem]
When reading the crash report it suggests to use a lower resolution resource pack but I don't have any resource packs installed

**Comment by MJRLegends** [comment]
Basically the crash is due to not enough video card ram to store all the textures. In basic terms your graphics card is to old. Sorry without unofficially editing the pack which i dont support you wont be able to play the pack.

You will most likely see this crash in other packs its not limited to just my pack.

**Comment by t3rr0r99** [comment]
I used twitch app to allocate over 8 gigs of ram to the game, can that still be the issue even with that much ram?

**Comment by MJRLegends** [comment]
Thats cpu ram not video card ram. You can only increase your video ram with upgrading your graphics card or buying a dedicated graphics card if your using integrated graphics from your cpu

**Comment by t3rr0r99** [comment]
ah i see, thanks

**Comment by MJRLegends** [comment]
If i remember later after i finish work i will try and link you to some more detail on your issue

**Comment by MJRLegends** [comment]
Could try updating your graphics card drivers too
