### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Sari1988** [MJRLegends/Space-Astronomy-Feedback-#1008]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Steps to Reproduce Issue
1. Open twitch launcher
2. Click install (it attempts to install but then cancels listing Object reference not set to an instance of an object).

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> No crash log available

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/47727011/58475613-cc56ea80-8191-11e9-9ac1-a37c7bcb6029.png)

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.7.7

**Where did this bug happen:** On attempting to install onto another PC

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Nothing to do with me please contact twitch app support
