### ISSUE TITLE
I'm trying to join a server made by my friends: Invalid Session

### ISSUE THREAD

**Issue by THEFlash7** [MJRLegends/Space-Astronomy-Feedback-#1009]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes
### Description of Issue
So I am trying to play with my friends over a VPN server called Hamachi. And when I to enter the port and IP address, it tries to enter, and then responds with "Invalid Session [Try Restarting Your Game!] This also happened when I tried to go into the premade servers that came with the download of the modpack.

### Steps to Reproduce Issue
Load Modpack Space Astronomy. Go to Multiplayer. Go to either Direct Connect or either of the premade servers. If went to direct connect, enter in this:"25.78.52.136:(Port that I get from my brother). Click Join Server. Screen says:"Failed to Login: Invalid Session (Try Restarting Your Game!)

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
v1.7.7
**Where did this bug happen:** [Single Player or Server]
Server
### Additional Information
[Any other information that may be able to help me with the problem]
It works if I go to single player and open lan game, but I don't want to lose all my progress in their server pls help me!

**Comment by MJRLegends** [comment]
This is a vanilla minecraft thing and not a mod pack issue sorry i cant help you here
