### ISSUE TITLE
Iron Backpacks

### ISSUE THREAD

**Issue by chasegr4h4m** [MJRLegends/Space-Astronomy-Feedback-#1011]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
[Iron Backpacks mod does not respond to known hotkeys. Cannot shift+click or shift+right click which is needed to add upgrade components. This prevents null filters, fuzzy filters, nested containers, etc. The only shift related hotkey opens the rename prompt which is mostly useless without nested backpacks.]

### Steps to Reproduce Issue
1. [Equip Iron Backpack backpack]
2. [Shift+click the backpack]

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [Space Astronomy (v1.7.7) Minecraft Version 1.7.10 By MJRLegends]

**Where did this bug happen:** [Single Player]

**Comment by MJRLegends** [comment]
Just change the key bind to something else.
