### ISSUE TITLE
ME System Randomly deleting expensive to make items

### ISSUE THREAD

**Issue by TheaStark** [MJRLegends/Space-Astronomy-Feedback-#1012]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
[Have recently put various items in the ME System and they've gone make.  These were expensive items to make and I doubt I'm going to be able to replicate them.]

### Steps to Reproduce Issue
1. [Place item in ME system]
2. [Item vanishes without a trace]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.7.7]

**Where did this bug happen:** [Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Sorry nothing i can do for you, this is a old mod pack and mods dont get updated and i fairly sure i can never update this pack again
