### ISSUE TITLE
Minecraft load up stops at Fabricated Circuits (5/7 Mod 93)

### ISSUE THREAD

**Issue by Doctor9256** [MJRLegends/Space-Astronomy-Feedback-#1014]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes 

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
I get smoe errors in the Feed the Beast log..  Okay its a quite a few errors, and there is also lots of yellow, it used to load up fine, I have tried re-downloading the mod and seems to only get worse.

### Steps to Reproduce Issue
1. Download modpack
2. Launch.. then it just stops at fabricated circuits

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them] https://pastebin.com/ccFcaytQ
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.7.10
**Where did this bug happen:** Single Player 

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
No idea seems to be a issue on your side. The pack has been u changed in months and has been downloaded 10000+ times without a issue
