### ISSUE TITLE
Guide Book bug

### ISSUE THREAD

**Issue by willscholl** [MJRLegends/Space-Astronomy-Feedback-#1015]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] 
Yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]
Yes

### Steps to Reproduce Issue
1. [First step]
2. [Second step]
I completed the second quest of the tool and weapons, to make patterns for tinker tools.
It won't give me the claim reward button but the quest is 100% complete

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 
<img width="1439" alt="Screen Shot 2019-09-18 at 6 48 13 AM" src="https://user-images.githubusercontent.com/46074146/65150323-2568b980-d9e1-11e9-8665-e3eb267e643b.png">

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
V1.7.7

**Where did this bug happen:** [Single Player or Server]
single player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You have a second task to do on that quest
