### ISSUE TITLE
Optifine kills framerate

### ISSUE THREAD

**Issue by Doom-Bee** [MJRLegends/Space-Astronomy-Feedback-#1016]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes, have

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes
### Description of Issue
[Description of the issue]
Optfine totally kills framerate, without it I get around 15-25fps, with it it's like 1-5fps.

### Steps to Reproduce Issue
1. [First step]
Use optifine?
2. [Second step]
Load in game.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
v1.7.7 the one of the FTB launcher
**Where did this bug happen:** [Single Player or Server]
Single player
### Additional Information
[Any other information that may be able to help me with the problem]
Using a shitty laptop, GPU is AMD Radeon(TM) R4 Graphics (Integrated yeah) 80MB VRAM DDR4 933mhz, 
CPU is AMD A6-9225 RADEON R4, 5 COMPUTE CORES 2C+3G
2 Cores, 4GB RAM

So I'd imagine its something to do with hardware compatability? Optifine works fine on other modpacks, same version etc, latest 1.7.10 optifine version.

**Comment by MJRLegends** [comment]
Yea optifine not supported
