### ISSUE TITLE
crash before the game loads

### ISSUE THREAD

**Issue by ksagameng1** [MJRLegends/Space-Astronomy-Feedback-#1017]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]: yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]: yes
### Description of Issue
minecraft crashes before the game boots up

### Steps to Reproduce Issue
1. run the modpack (curse forge version)
2. hit the play button and wait until it opens the minecraft launcher with the crash pop up

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.7.7

**Where did this bug happen:** none

### Additional Information
my rams are 4 gb and the installation settings are the default one
and the minecraft launcher version is the latest

**Comment by MJRLegends** [comment]
You havent included the crash log, please include it or we cant help you

**Comment by ksagameng1** [comment]
the how to get crash log link doesnt exist

**Comment by MJRLegends** [comment]
Try doing this on the mod pack instance 

![](https://i.gyazo.com/5ebfcc6b1d9c198ba2dd2cedd0449aed.png)

if not backup and saves you have and delete and reinstall the mod pack instance

**Comment by ksagameng1** [comment]
nope not working also mentioning that its the first time i open this modpack

**Comment by MJRLegends** [comment]
Does any other mc 1.10.2 pack load?

**Comment by ksagameng1** [comment]
haven't tried but theres a 1.6.4 pack that works, i will update you soon

**Comment by ksagameng1** [comment]
updating you
sorry for the long wait but i know that the problem is happening to all 1.7.10 packs

**Comment by ksagameng1** [comment]
got the issue fixed, the issue is the 1.7.10 file was broken but the game couldn't verify it so the game loads the file and boom crash
anyway the fix is open 1.7.10 vannila and wait for it to open and then close it and run the pack and it should work fine
