### ISSUE TITLE
Text: a.aa} crashes the game

### ISSUE THREAD

**Issue by plerros** [MJRLegends/Space-Astronomy-Feedback-#1019]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
Game crashes when type a text

### Steps to Reproduce Issue
1. type a.aa}
2. game crashed

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.7.7

**Where did this bug happen:** Both Single Player and Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You havent even bothered to include crash log..... Please include it

**Comment by plerros** [comment]
Pastebin doesn't want to cooperate. I'll send it as a .txt
[bugreport.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/4277895/bugreport.txt)

**Comment by MJRLegends** [comment]
You have edited the pack sorry, you will need to submit a crash log without changing the pack to get support 

`PackGuard: ADDED: ChickenChunks v1.3.4.19`

**Comment by MJRLegends** [comment]
Also looks like someone posted a link or something in chat that minecraft doesnt like which makes it nothing to do with the pack im sorry again nothing can be done for you due to both reasons above

**Comment by plerros** [comment]
I disabled the mod, and the bug persists.
[bugreport.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/4277938/bugreport.txt)

**Comment by plerros** [comment]
True, this isn't a modpack specific bug.
