### ISSUE TITLE
Slice'n'splice overly expensive to use

### ISSUE THREAD

**Issue by kilyo** [MJRLegends/Space-Astronomy-Feedback-#102]
The Ender IO Slice'n'splice uses an axe as part of the operation, and draws durability from the tool. Tinkers' Construct axes are not allowed, and since vanilla tools have 0 durability, it takes 1 iron axe per operation. 

It also uses shears in the same manner, but the shears aren't customized in this pack, and it takes about 20 operations to break.

**Comment by MJRLegends** [comment]
Theres nothing i can do to fix this, so idk what i can do

**Comment by kilyo** [comment]
Make an exception for the iron axe? Give it a slight durability so it doesn't take a stack of axes to make items? It would still not be worth while to make them for use as tools, which i believe was the point of removing the durability from the vanilla tools.

**Comment by MJRLegends** [comment]
There isn't a option to add a certain amount of durability, with how im making them have 2 hits durability

**Comment by kilyo** [comment]
Can you return the iron axe to a normal tool then?

**Comment by MJRLegends** [comment]
I dont have the ability to just make the axe not have the 2 hits durability. As its all the vanilla tools

**Comment by MJRLegends** [comment]
I will try and find a way...

**Comment by Korvynus** [comment]
Dark Axe from EnderIO itself works fine for me. No need to change whatever. Axes from MekanismTools works too!

**Comment by MJRLegends** [comment]
Sorted then
