### ISSUE TITLE
Enderstorage error when loading world

### ISSUE THREAD

**Issue by joe1296** [MJRLegends/Space-Astronomy-Feedback-#1021]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
Try to load world and enderstorage throws tons of errors and shuts down the server loading. World worked yesterday now it doesnt

### Steps to Reproduce Issue
1.  Loading World
2. enderstorage errors in log

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]

https://drive.google.com/file/d/1fVp_cnPw_Tm-z6T0K0qw58D7ELUdfMGM/view?usp=sharing
(Errors at the very end)

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.7.7

**Where did this bug happen:** [Single Player or Server]
Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Your error log isnt accessible it needs permission to access. Please upload a public error log that requires no permission to acesss

**Comment by joe1296** [comment]
i will copy it into the next reply to make it a bit easier

**Comment by joe1296** [comment]
you should be able to open it now

**Comment by MJRLegends** [comment]
Delete all the files in the EnderStorage folder in your saves folder as they are corrupted
