### ISSUE TITLE
Game crashes when loading the world

### ISSUE THREAD

**Issue by CreeperHappy** [MJRLegends/Space-Astronomy-Feedback-#1022]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
The computer froze and after about a minute of waiting the computer restarted, now the game launches with no issues but crashes when I try to load the world.

### Steps to Reproduce Issue
1. Open said World
2. Crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]  
https://pastebin.com/P9xZ0KwP

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.7.7-1.7.10

**Where did this bug happen:** Single Player

### Additional Information
The game and computer froze precisely when I was about to release M2 to use the special lunge ability of the longsword against the wall of an underground ravine to gain height, I don't know if this is related to the crash. The game works correctly and won't crash on a new world. The save if it helps: https://drive.google.com/drive/folders/13HBVI6ympgbqJ5PyACjy0KX7NnmaDA-4?usp=sharing

**Comment by MJRLegends** [comment]
This is a known issue, Delete this folder "world/elec332/"

**Comment by MJRLegends** [comment]
Double of #979 

Listed in Known issues already #1
