### ISSUE TITLE
My world keeps crashing everytime i try to load it

### ISSUE THREAD

**Issue by Flame438** [MJRLegends/Space-Astronomy-Feedback-#1023]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
Everytime I try and load up my world it brings me to a screen where it tell me that I need to backup the world because if I keep playing I could permanently damage or corrupt the world, but everytime I click yes it crashes with the java.lang.ArrayIndexOutOfBoundsException: 1 error. I'm pretty sure it is elec332 but when I check the modpacks folder there is no world/elec332/ folder in it. I've checked every folder (I think) and I can't find it.

### Steps to Reproduce Issue
1. Open world
2. Click yes on the backup creation screen
3. crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]

https://pastebin.com/EZUGvNqJ

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.7.7

**Where did this bug happen:** Single Player

### Additional Information
My computer blue screened while playing and then this started happening. I don't know if that helps

**Comment by Tomsn16** [comment]
I have exactly the same problem, you crash log seems indentical with mine https://pastebin.com/4Qh69yqJ.. i like the world and i dont know what to do..

**Comment by Tomsn16** [comment]
i have solved it by deleting some of these files
![image](https://user-images.githubusercontent.com/90585861/133158769-813e24ea-a66f-4a99-b531-cc26c77f63f1.png)
i have all items, all builds.. only thing that i lost are quests probably and minimap waypoints but hey! i dont need to start over!

**Comment by MJRLegends** [comment]
Yea delete elec332 folder to fix
