### ISSUE TITLE
Invalid Biome id

### ISSUE THREAD

**Issue by radiocrack** [MJRLegends/Space-Astronomy-Feedback-#103]
I was using an enhanced portal between earth and space station and crashed with this biome id error.  When i re-launched the client the space biome was called quagmire instead of "space".
My earth base is at a biome called "mining biome" from bop i think.

I was playing single player so unsure if this is a server crash or client.

crash report here
http://pastebin.com/jX1DWu1d

**Comment by MJRLegends** [comment]
I will fix for the next update as I didn't know this to now as there has been no error last in the console
