### ISSUE TITLE
endless end

### ISSUE THREAD

**Issue by letschanator** [MJRLegends/Space-Astronomy-Feedback-#106]
version 1.2.9

log http://pastebin.com/8c6dKc9g 

I just got to the end and when I got there I discovered that it is endless with infinite healing towers and no ender dragon witch means no way out I am on a single player world so It's not just someone already killed

**Comment by MJRLegends** [comment]
Please can you post the full log and are you sure it's not in peaceful mode?

**Comment by letschanator** [comment]
I think I did post the full log but I went flying around a little bit and found the dragon but is the end suppose to be endless with infinite healing towers? It made him extremely hard to kill and required flight

**Comment by MJRLegends** [comment]
Its not the full log and can you send me a picture of this

**Comment by letschanator** [comment]
It would be hard to get pics of it but I looks like the normal end just infinite

**Comment by MJRLegends** [comment]
This is being caused by the ChromatiCraft mod which is being removed in the next update so will be fixed then...
