### ISSUE TITLE
[SUGGESTION] Adding a new mod to the pack (if possible)

### ISSUE THREAD

**Issue by Korvynus** [MJRLegends/Space-Astronomy-Feedback-#107]
ModularPowersuitsAddons to fit with his main mod. I see you added Inteligent Energistic wich is an excelent addon for AE2. So why not MPSA ? :)

**Comment by MJRLegends** [comment]
I have tried to add it but it causes crashes due to problem in compatibility between ModularPowersuits and ModularPowersuitsAddons

**Comment by Korvynus** [comment]
Well, I google'd a while and I found this:
https://github.com/lehjr/MachineMusePowersuits/releases

Maybe it can help you? This guy merged MPSA with MPS. Pretty cool ! Just needs to replace MachineMuse's mod with this one.

**Comment by MJRLegends** [comment]
I will take a look at it

**Comment by Korvynus** [comment]
Thanks you very much!

**Comment by MJRLegends** [comment]
This will likely be added in v1.3.1 not v1.3.0
