### ISSUE TITLE
Starting a Basic Turbine Quest Part 2

### ISSUE THREAD

**Issue by phattpks** [MJRLegends/Space-Astronomy-Feedback-#108]
Part 2 of the Quest : Adding a Coil
The Quest wants 8 Enderium Blocks.

I used my tinkers Smelter to pour the Enderium Blocks and the quest would not complete. It took me a while to see that it wanted me to craft the blocks. I broke the blocks into ingots and recrafted the blocks and quest completed.

Maybe this should be a detect quest and not a crafting quest.

Everything else is working great so far!!! Thanks for a fun pack!

**Comment by MJRLegends** [comment]
Thanks i will make the change for the next update.
