### ISSUE TITLE
[SUGGESTION] Adding some recipes for the NASA Workbench Schematics...

### ISSUE THREAD

**Issue by Korvynus** [MJRLegends/Space-Astronomy-Feedback-#109]
Why? Simply if a server has worldborder enabled and/or too much raided dungeon on a planet or moon, it become difficult to find the NASA Workbench Schematics.

Just some examples of recipes in mind:
http://i.imgur.com/y52yVI9.png (Moon Buggy)
http://i.imgur.com/AjNF8qK.png (Tier 2 Rocket)

More to come as I found ways to make good recipes for the other tiers... Or maybe you?

**Comment by MJRLegends** [comment]
I have thought about it but im not not adding recipes for them as people wont go to explore the dungeons and just do the recipes.

**Comment by Korvynus** [comment]
There is a way to edit boss loot or increase chest loot? It would really help!

**Comment by rye2121** [comment]
Portable Oil Extractor is not in the game please fix

**Comment by MJRLegends** [comment]
@rye2121 one why are you posting this in someone elses issue/suggestion. you should make another issue for this and this has been posted already so please look at the known issues and closed issues before posting see #98 as this is where it was posted.

**Comment by MJRLegends** [comment]
@Korvynus not really, this is more of a thing to ask the galacticraft developers as its their mod and they can make theses changes.
