### ISSUE TITLE
Mekanism

### ISSUE THREAD

**Issue by Dakuen** [MJRLegends/Space-Astronomy-Feedback-#11]
There is a bug i found about Mekanism.
If i type in TMI "Mek" it crashes me imediatly so i can't even search directly for the mod itself.. it is kinda annoying cause i have to look the items up from my remembrance and that is not possible all the time..

**Comment by MJRLegends** [comment]
i'll look at it now

**Comment by MJRLegends** [comment]
Could you send me the crash log?

**Comment by Dakuen** [comment]
That is weird.. i tried to reproduce the bug and it does not crash on me now.. it all works fine..

**Comment by MJRLegends** [comment]
are you able to go in to the crash reports folder and find the crash log and send it to me using pastebin so i can find the problem.

**Comment by Dakuen** [comment]
http://pastebin.com/J0YATtFb Here it is i think..

**Comment by Dakuen** [comment]
http://pastebin.com/02ZvsJHk Or this one

**Comment by MJRLegends** [comment]
Seems to be a issue from buildcraft, but the mod pack doesnt have the latest version. And a new update will be out soon with mod updates and more.

**Comment by Dakuen** [comment]
Okay thank you very much! This Pack is awesome BTW!

**Comment by MJRLegends** [comment]
Thank you :D
