### ISSUE TITLE
pneumatic craft bug

### ISSUE THREAD

**Issue by Joorrddy** [MJRLegends/Space-Astronomy-Feedback-#111]
your are not able to craft lubericant from pneumatic craft it turns into rotary craft lubericant

**Comment by MJRLegends** [comment]
You should be able to use either lubricants in each of the mods

**Comment by Joorrddy** [comment]
Doesnt work

**Comment by MJRLegends** [comment]
Still working on this problem.

**Comment by MJRLegends** [comment]
https://github.com/MineMaarten/PneumaticCraft/issues/633

**Comment by MJRLegends** [comment]
Will be fixed in v1.3.2

**Comment by Joorrddy** [comment]
Thanks
