### ISSUE TITLE
crash on ubuntu

### ISSUE THREAD

**Issue by ANTBR14** [MJRLegends/Space-Astronomy-Feedback-#113]
crashes after step 7 of loading screen
[crash report 11-23-15 850 pm.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/42344/crash.report.11-23-15.850.pm.txt)

**Comment by MJRLegends** [comment]
Can you run any other mod pack?

**Comment by MJRLegends** [comment]
??
