### ISSUE TITLE
Right clicking Big Reactor controller with Tinkers Construct tool crashes game

### ISSUE THREAD

**Issue by Serpardum** [MJRLegends/Space-Astronomy-Feedback-#114]
I wanted to check my reactor so I right clicked the reactor with an iron mattock and the game crashed. I restarted and it crashed again. I restarted, broke the controller, put it back, right clicked it with an empty hand and everything was fine. I closed the controller, selected an iron pickaxe and right clicked the controller and the game crashed again. Attached is the last crash report.
[crash-2015-11-24_11.58.35-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/43160/crash-2015-11-24_11.58.35-server.txt)

**Comment by MJRLegends** [comment]
The crash is a memory related crash so it has nothing to do with "ight clicked the reactor with an iron mattock and the game crashed"

**Comment by Serpardum** [comment]
I may have "nothing to do with" right clicking the reactor with an iron mattock or pickaxe, yet I can play the game for hours doing everything fine. As soon as I right click the reactor controller, the game crashes. Do I need to make a recording of it?

**Comment by MJRLegends** [comment]
Does it happen every time you right click the iron mattock on the reactor? Or did it just happen that once time.

**Comment by Serpardum** [comment]
Every time.

**Comment by MJRLegends** [comment]
Does it only do it with a iron mattock and no other tools?

**Comment by Serpardum** [comment]
iron mattock and iron pickaxe. I can try others. I have an iron hammer I'll try to

**Comment by Serpardum** [comment]
My suspicion is that it has something to do with tinkers construct right clicking with a tool to place a block. Because that's what the function erroring on is, something about blockplace. testing...

**Comment by Serpardum** [comment]
Well, I tried all my tools and it crashed when I used the pickaxe this time and not with the other tools. Let me try to see if I can get it to crash with the mattock again.

**Comment by Serpardum** [comment]
Okay, it seems to only be crashing while using my pickaxe. Every time. I'll create a creative world and test more.

**Comment by Serpardum** [comment]
I couldn't duplicate it in a creative world, and when I went back to my survival it works now.

**Comment by Serpardum** [comment]
I couldn't duplicate it in a creative world, and when I went back to my survival it works now. If it happens again and I figure out exactly the steps to reproduce it I'll reopen.

**Comment by MJRLegends** [comment]
Ok yeah i think its just a minecraft/memory issue.
