### ISSUE TITLE
Some issues with the new quests in v1.3.0

### ISSUE THREAD

**Issue by Korvynus** [MJRLegends/Space-Astronomy-Feedback-#115]
Tested quests: Cloning Yourself, Base Thermal Protection, ...

Tried to craft the required items either in a crafting terminal (from applied energistics) or crafting station (from tinker construct) doesn't work. The book doesn't take in count that the items have been created. Unfortunately, I already bypass those quests with /hqm edit ... I'll report if it does work with a vanilla crafting table for other quests.

**Comment by Korvynus** [comment]
Well it seems that all quests for me are unable to be completed. I decided to reach Diona and Koentus yesterday. Same problem happened, the quest book doesn't take in coutn that I reach those planets. Does the quest book need to be reset every updates of the modpack?

**Comment by MJRLegends** [comment]
Does it do it in a new world?
