### ISSUE TITLE
Can't turn the music off...

### ISSUE THREAD

**Issue by grizeldi** [MJRLegends/Space-Astronomy-Feedback-#116]
I changed music setting to off, but music kept playing no matter what I did.

**Comment by MJRLegends** [comment]
Which music was playing and what was your volumes

**Comment by grizeldi** [comment]
Minecraft vanilla (I think it was vanilla) music was playing, and my music volume was set to 0, all others to 100%.

**Comment by MJRLegends** [comment]
Try setting the music volume to 100% then go back to the game then pause it again and change back to 0%

**Comment by grizeldi** [comment]
Restart of Minecraft fixed it.

**Comment by MJRLegends** [comment]
Yeah I think it's just a minecraft bug
