### ISSUE TITLE
Issue between Sync and Galacticraft.

### ISSUE THREAD

**Issue by Korvynus** [MJRLegends/Space-Astronomy-Feedback-#118]
Since I made a clone of myself, everytime I switch between my main and my clone, it's like I'm in a permanent landing (like it does with a parachute on some planets). And in that state, I can't jump anymore, I can't fly and I fall slowly when falling from a high altitude. Also there is the opening sound of the parachute everytime I try to jump.

The only ways to fix that is by either restarting the server or using /dimensiontp and landing on earth.

**Comment by MJRLegends** [comment]
I will report this to the mod developer
