### ISSUE TITLE
Wither killer dupe of wither skulls 

### ISSUE THREAD

**Issue by Shadowolfe** [MJRLegends/Space-Astronomy-Feedback-#119]
if you put 1 wither skull in wither killer than try to shift click it out it just  moves to an empty spot and duplicates itself, nest shift click gets 4, than 8 than 16. Here is a youtube post about it. 25  minutes into the video shows the dupe in action
https://www.youtube.com/watch?v=VRANAV0mOdQ
Works on Space Astronomy also, checked it out.

**Comment by MJRLegends** [comment]
Haha thanks will report it to the mod developer

**Comment by Shadowolfe** [comment]
I found a post on his forum about it said it will be fixed in 2.0 version page 14
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2181911-practicalities-0-6-2?page=14

**Comment by MJRLegends** [comment]
Ok thanks for reporting it I will at it to the main issues on the kitchen known issues pastebin
