### ISSUE TITLE
Another Bug

### ISSUE THREAD

**Issue by Dakuen** [MJRLegends/Space-Astronomy-Feedback-#12]
It Crashed me as i wrenched the resonant energy Cell
http://pastebin.com/VTeB6Gh0

**Comment by MJRLegends** [comment]
Thats the same crash as you had before. I will see what i can do for the next update. Sorry for it crashing in the mean time.

**Comment by Dakuen** [comment]
And now it Crashes me while doing nothing..
That's no fun..http://pastebin.com/cQiAecFg

**Comment by MJRLegends** [comment]
Do you have optfine? and if so what do you have the "Chunk Loading" option to in the video settings?

**Comment by Dakuen** [comment]
Yes i have cause of other visual glitches wich got fixed with optifine but it was fine from beginning, just like my past 2h of gameplay it crases me.
Im not sure now wich setting i use ill see it later and look if changing it solves it

**Comment by MJRLegends** [comment]
Ok let me know.
