### ISSUE TITLE
Food pixels

### ISSUE THREAD

**Issue by Regner6** [MJRLegends/Space-Astronomy-Feedback-#122]
Food pixels rendering are not showing how there supposed too.

**Comment by MJRLegends** [comment]
#136

**Comment by MJRLegends** [comment]
This problem is a problem between Fastcraft and ChromatiCraft

**Comment by WalaoEgg0424** [comment]
so it will not have fix unless either fastcraft or chromaticraft fix this?

**Comment by MJRLegends** [comment]
Nope but its a rare crash
