### ISSUE TITLE
internal server crash?

### ISSUE THREAD

**Issue by ImelchorI** [MJRLegends/Space-Astronomy-Feedback-#125]
i dont know how else to discribe it. ive been running the pack for a while in single player and it went fine. but all of a sudden, i cant interact with most of the world anymore. when i start up the world i am able to move around, but cant open chests, furnaces, or the tinker and glacticraft tabs in my inventory. F3 shows 0 chunk updates. trying to close the game comes with the message "shutting down internal server" as usual, without the game actually shutting down. it just freezes with this screen.

it feels really awkward, as the symptoms look like the same as extreme server lag, even though im not actually playing on a server.

sometimes if i take a couple of steps i  will just fall through the floor and keep falling into the void (not taking damage though).

on a side note, taking an ender io wrench into your hand apparantly crashes the client.

**Comment by MJRLegends** [comment]
I need the crash log? ??

**Comment by MJRLegends** [comment]
Please reopen once you have posted the crash log! :D
