### ISSUE TITLE
/dev/null not working

### ISSUE THREAD

**Issue by DaneD96** [MJRLegends/Space-Astronomy-Feedback-#126]
the /dev/null doesn't seem to be picking up items. for instance, if I threw in cobble into the devnull inventory, and tried to pick up cobble thats on the ground, the items would just go into my regular inventory.

**Comment by MJRLegends** [comment]
what is  /dev/null ???

**Comment by DaneD96** [comment]
http://ftb.gamepedia.com/User:TheSatanicSanta/Sandbox/null

It's an item in open blocks. It voids a certain item when you have a stack of it in the dev null inventory.

**Comment by MJRLegends** [comment]
I will have a look when i get a chance

**Comment by helium2s1** [comment]
It's been reported to the mod author, they couldn't reproduce. https://github.com/OpenMods/OpenBlocks/issues/729

**Comment by MJRLegends** [comment]
Reported to the More Planet developer
