### ISSUE TITLE
game crashes after starting world 

### ISSUE THREAD

**Issue by nschinagl** [MJRLegends/Space-Astronomy-Feedback-#127]
Hi,

my game crashes right after I start the world. These are my chrash reports. Please, can you help me.

[crash-2015-12-04_21.47.19-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/52521/crash-2015-12-04_21.47.19-server.txt)
[crash-2015-12-04_21.47.25-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/52520/crash-2015-12-04_21.47.25-client.txt)

**Comment by MJRLegends** [comment]
Does it work if you restart the mod pack?

**Comment by nschinagl** [comment]
Hi. I restarted the mod pack, restarted the pc and also de- and reinstalled the mod pack via curse.

**Comment by MJRLegends** [comment]
Did it work after trying all that?

**Comment by nschinagl** [comment]
No. I get the same error immediatly after starting the world. I have a 2 week old backup, that is working. I hope there is a way to fix this, I don't want to investigate the 2 weeks again. Thank you.

**Comment by MJRLegends** [comment]
Can you send me a copy of the world so i can try and find the source but theres not really much i can do. Also give the world a try in the new update v1.3.1 see if it works now

**Comment by WalaoEgg0424** [comment]
nschinagl , lower your render distance to maybe like 10 - 12 and try it.

**Comment by Regner6** [comment]
Make sure you are using the correct Java version and not over doing your RAM, Every modpack crashes on a world start up due to a JVM tick

**Comment by Souls93** [comment]
Same Here Just updated it today and immediately as soon i click on my world on singleplayer then try and load it get the brown screen when it loads then 20 seconds later just crashes back to launcher. 
I did notice that you got rid of some plugins to do with NEI (stated so in the changelog) i use NEI so not sure whether it may be something to do with that. but i have just put it back to v1.3.0 and it has re-installed 80 mods into the pack which weren't in the list when it was v1.3.1
[crash-2015-12-10_17.36.10-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/58445/crash-2015-12-10_17.36.10-server.txt)

**Comment by MJRLegends** [comment]
@Souls93 this has been posted multiple times #139 . Please make sure you look at the issue tracker/known issues and the closed issues!

**Comment by MJRLegends** [comment]
@Souls93 yours is different crash to @nschinagl so you shouldn't of posted it here

**Comment by nschinagl** [comment]
Hi, I tried the lower the render distance and I update to v1.3.1. Here ist the new crash report:
[crash-2015-12-08_20.42.23-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/58584/crash-2015-12-08_20.42.23-server.txt)

Which Java Version should I use? I use Java 7 Update 45 (64 bit). 
I have 8 GB RAM installed and use 4 GB to play.

Download for my world: http://we.tl/RausUtI9aS

I hope you can help me. Thanks a lot.

**Comment by WalaoEgg0424** [comment]
nschinagl , its the HQM bug , the fix is on the Issue Tracker Page http://pastebin.com/R73aBeqA

**Comment by MJRLegends** [comment]
Will be fixed in the next version

**Comment by nschinagl** [comment]
@WalaoEgg0424 Hi, I deleted the HardcoreQuesting folder in my world folder. Then I restarted the Curse Lancher and started the game again. Right after the world is showing up (1 seconds) the game crashes with the same error as before:
[crash-2015-12-11_10.42.33-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/59221/crash-2015-12-11_10.42.33-server.txt)

**Comment by WalaoEgg0424** [comment]
@nschinagl This is not the same error i think. Im reading it right now.

**Comment by WalaoEgg0424** [comment]
The modpack will have an update later , maybe after updating the modpack then it will works. If its still not working , post the latest crash log.
