### ISSUE TITLE
Disbalanced recipes for paper from sawdust

### ISSUE THREAD

**Issue by nmakoto** [MJRLegends/Space-Astronomy-Feedback-#128]
There's 4 disbalanced recipes for making paper from sawdust.
1) 1 water + 4 sawdust = 2 paper
2) 1 quicklime + 1 water + 1 sawdust = 1 paper
3) 3 sawdust = 6 paper
4) 1 water + 3 sawdust + 3 stone = 8 paper (this **only works** with sawdust from *RotaryCraft*!)

If you look all recipes for paper, you should notice that they all *little* disbalanced. And this is just for making paper :)

**Comment by MJRLegends** [comment]
Thanks will fix for v1.3.3
