### ISSUE TITLE
Getting Fuel quest

### ISSUE THREAD

**Issue by cogscreamsrage** [MJRLegends/Space-Astronomy-Feedback-#129]
The Getting Fuel quest will not complete, i've taken 20 buckets and collected oil, and it wont accept.

**Comment by MJRLegends** [comment]
I need more details on this?? Which tasks can you complete and what oil did you get(From what mod)? What's the bucket Id?

**Comment by Kastor91** [comment]
Hey, I have the same issue. The task that does not complete is "Collect two buckets of oil". 
When I collect oil in the world with a bucket I got the oil bucket from Galactricraft core (id 6821).

I hope this can help, without this quest the whole "Exploring the universe" part isn't available :(

**Comment by MJRLegends** [comment]
Will be fixed for v1.3.2
