### ISSUE TITLE
Crash while starting my world

### ISSUE THREAD

**Issue by WalaoEgg0424** [MJRLegends/Space-Astronomy-Feedback-#130]
when i start to play my world , it crashed for no reason.
[crash-2015-12-07_18.07.25-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/53731/crash-2015-12-07_18.07.25-server.txt)

**Comment by MJRLegends** [comment]
https://github.com/lorddusk/HQM/issues/84

**Comment by WalaoEgg0424** [comment]
ljfa-ag commented 2 minutes ago
supposedly caused by Pneumaticcraft, should be fixed in the upcoming version
