### ISSUE TITLE
Shutdown after startup

### ISSUE THREAD

**Issue by kaghy** [MJRLegends/Space-Astronomy-Feedback-#132]
I'm getting a shutdown of the server when I try to start it, it's telling me it has to do with Hardcore Questing.

**Comment by MJRLegends** [comment]
This is lacking in detail, i need more detail on this and i need the crash log or log via a pastebin?

**Comment by kaghy** [comment]
[crash-2015-12-07_17.04.00-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/54179/crash-2015-12-07_17.04.00-server.txt)

**Comment by MJRLegends** [comment]
Please make sure you look at the known issues here http://pastebin.com/R73aBeqA. The issue your having is number 1 at the top

**Comment by kaghy** [comment]
Oh lol sorry, didn't see that when i scrolled through. My apologies!!!

**Comment by MJRLegends** [comment]
:P

**Comment by MJRLegends** [comment]
See https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/130
