### ISSUE TITLE
Cursed earth not spawning creatures

### ISSUE THREAD

**Issue by SynapticStatic** [MJRLegends/Space-Astronomy-Feedback-#133]
I made a recessed (underground but not covered) box that contained grass. Created the altar (ench table + ring of redstone dust) per the instructions. I killed a cow at midnight and activated the sigil I had. It did form cursed earth, with lightning and the evil laughter. But the cursed earth doesn't seem to be spawning any creatures at all.

I'm pretty sure the biome is plains, and creatures do spawn at night elsewhere nearby, but never in the cursed earth. I even made sure absolutely no light was getting in by removing all candles and verifying all squares were red in F7.

One thing to note is I did break the redstone/altar afterwards. I don't feel like this is the cause, as I have done similar on other modpacks and it's worked fine.

**Comment by WalaoEgg0424** [comment]
Did you put project red lamp there?If yes then it might be the lamp problem . If not then MJRLegends will find out whats causing the cursed earth not spawning creatures.

**Comment by SynapticStatic** [comment]
No project red lamp. I misspoke, I only had torches nearby, not candles. Tried both covered (day/night) and open to the sky (night).

**Comment by WalaoEgg0424** [comment]
Try do the ritual again , if you dont wanna find the sigil again , go Open To LAN , then allow cheats on , gamemode 1 take the division sigil thats not activated, do the ritual again. If it doesnt work , then maybe make a world backup then reinstall the modpack.

**Comment by MJRLegends** [comment]
Reopen if you any anymore issues but from what i can its working
