### ISSUE TITLE
Recipe look up crash

### ISSUE THREAD

**Issue by Hirix** [MJRLegends/Space-Astronomy-Feedback-#134]
Seems when I look up any recipes after updating to 1.3.1 crashes the client now.
[crash-2015-12-07_11.15.56-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/54467/crash-2015-12-07_11.15.56-client.txt)

**Comment by MJRLegends** [comment]
I know I'm trying to fix it

**Comment by MJRLegends** [comment]
See https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/450
