### ISSUE TITLE
Food rending issue is anyone else having this issue

### ISSUE THREAD

**Issue by Regner6** [MJRLegends/Space-Astronomy-Feedback-#136]
Is anyone else getting this issue. I reported it to MJR but he said no one else has reported it yet

![284ee7ff2d41f7e2a3bfda98c51aed58](https://cloud.githubusercontent.com/assets/16054126/11658168/5371b5ee-9d8f-11e5-8e30-36cae107cce2.gif)
![e33b340252ae5c282b74a219e1d8ee0e](https://cloud.githubusercontent.com/assets/16054126/11658169/537e3eae-9d8f-11e5-85e2-701e1af61c96.gif)
![Uploading 8d7044c9d4a23f2df20fed9f27882e47.gif…]()
![2344683a5f9de81c9c14fe1bad0479e9](https://cloud.githubusercontent.com/assets/16054126/11658170/53868fb4-9d8f-11e5-9be9-1dcd11886638.gif)
![c184b2c8f9d0bb6ae3f27b02567c626e](https://cloud.githubusercontent.com/assets/16054126/11658172/5387b178-9d8f-11e5-8b64-03032ef07397.gif)

**Comment by Regner6** [comment]
Looks like the issue may be chromatic craft. As soon as i remove chromatic craft the food rendering is normal

**Comment by MJRLegends** [comment]
Yeah, i cant reproduce this my self but i will try and find a fix, for this with you over skype soon

**Comment by Regner6** [comment]
updated screen shot's to gifs

**Comment by MJRLegends** [comment]
See https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/452
