### ISSUE TITLE
Crash with 1.3.1

### ISSUE THREAD

**Issue by exmex** [MJRLegends/Space-Astronomy-Feedback-#139]
World doesn't load anymore.

[crash-2015-12-08_09.20.02-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/55156/crash-2015-12-08_09.20.02-server.txt)

Reverting back to 1.3.0, and the world works again..

**Comment by WalaoEgg0424** [comment]
This is a HQM Bug i think , MJRLegends is currently asking the mod creator to fix this bug.

**Comment by WalaoEgg0424** [comment]
This bug is actually written down on the Issues Tracker Page http://pastebin.com/R73aBeqA

**Comment by MJRLegends** [comment]
Yeah i think this crash is happening more in the newest version of hqm so will probably roll back a version for the next mod pack update
