### ISSUE TITLE
Me again 1.2.4

### ISSUE THREAD

**Issue by Dakuen** [MJRLegends/Space-Astronomy-Feedback-#14]
I played the pack yesterday and everything was all right. As i updated it today to 1.2.4 and wanted to load my world it would not let me do it. It just stops at: "Loading World" screen and does nothing.
As it does not crash there is no crash report. Also i am using the FTB Launcher.

**Comment by MJRLegends** [comment]
See known issues as it's on there under current bugs

**Comment by Dakuen** [comment]
Tried it with the Curse launcher too. Aswell with java 7 and java 8 in both launchers. Still no loading possible.

**Comment by MJRLegends** [comment]
Did you find the what to do in the "Known issues" after ?

**Comment by Dakuen** [comment]
Yes i found it afterwards. It sucks thoe that you loose all of your progress..

**Comment by MJRLegends** [comment]
Yeah sorry about that, its a HQM Mod bug and nothing i can do to stop it happening.
