### ISSUE TITLE
Servercrash since update 1.3.1

### ISSUE THREAD

**Issue by Bomberman2010** [MJRLegends/Space-Astronomy-Feedback-#140]
after the update on 1.3.1 my server crash: http://www.mediafire.com/download/cgn78sdtykel4up/crash.zip
server can't start.

i use only the map from 1.3.0, all other folder i have deletet.

**Comment by phattpks** [comment]
Same here single player crashes at launch and the server wont start.

Here is the crash report:

[crash-2015-12-08_20.35.33-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/56357/crash-2015-12-08_20.35.33-server.txt)

**Comment by WalaoEgg0424** [comment]
Bomberman2010 , might be the HQM Bug.See http://pastebin.com/R73aBeqA for the fix

phattpks , yours issue is also HQM Bug . See http://pastebin.com/R73aBeqA for the fix
