### ISSUE TITLE
Nibiru planet gives me a crash (atleast thats where it happens even before login.)

### ISSUE THREAD

**Issue by kaghy** [MJRLegends/Space-Astronomy-Feedback-#141]
So, I had the crash this afternoon, although I just played MC a while on the planet of Nibiru, mining ores and stuff. Still crashes the server I have with some friends. I have attached the crash log from the previous crash, which is the same as other crashes which I will upload aswell.

Do you maybe have an idea what this can be?
[crash-2015-12-08_19.34.52-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/55864/crash-2015-12-08_19.34.52-server.txt)
[crash-2015-12-08_16.24.58-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/55881/crash-2015-12-08_16.24.58-server.txt)
[crash-2015-12-08_19.07.37-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/55880/crash-2015-12-08_19.07.37-server.txt)
[crash-2015-12-08_19.32.25-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/55882/crash-2015-12-08_19.32.25-server.txt)

**Comment by WalaoEgg0424** [comment]
You and your friend is in the different planets in the world?

**Comment by kaghy** [comment]
Well yesterday afternoon we were, so that can explain one crash, but the three later crashes happened when I was playing on my own on the server.

I was able to leave the planet, but I couldn't do proper mining and dungeon hunting on the planet because of the crashes (that's the reason I decided to leave the planet eventually.)

**Comment by WalaoEgg0424** [comment]
u mean the 19.34.52 and the other 19.xx.xx crash log is ur playing ur own in the server?

**Comment by WalaoEgg0424** [comment]
Can you launch the server and recreate the crash log? I need the latest crash log on your server so i doesnt messed up that 3 crash log.

**Comment by kaghy** [comment]
Momentarily I cannot launch the server as I am at work, I will launch it this evening at home and recreate the crash log.

You'll hear from me.

**Comment by WalaoEgg0424** [comment]
Okay, I'll keep my eyes on the github.

**Comment by kaghy** [comment]
Sooo, I just got home and tried to recreate the crash, which was successful. Enclosed you'll find the crash log from about a minute ago 17:01.
I hope it helps you.

[crash-2015-12-09_17.01.52-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/57000/crash-2015-12-09_17.01.52-server.txt)

**Comment by MJRLegends** [comment]
Ok thanks Does it do it on any other planet?

**Comment by kaghy** [comment]
No, the only planet it happened on was Nibiru. All other planets (so far I can access, because of quests :P) it doesn't happen, and that's when I played with my friends even aswell as solo. Even the Dark Asteroid belt was accessible, only Nibiru is giving me trouble.

**Comment by MJRLegends** [comment]
I will take a look and i will report the crash to the mod developer

**Comment by kaghy** [comment]
Thank you! I hope to hear from you soon!

**Comment by MJRLegends** [comment]
Also are you able to test with v1.3.1 version of the mod pack as this has the latest version of the mod that the crash is from.

**Comment by kaghy** [comment]
I will make a 1.3.1 server now and test it out!

**Comment by kaghy** [comment]
Okay, So I'm now on ver 1.3.1 and so far nothing has happened yet. Though I'm playing solo now, it's not crashing so I'm happy..

So the bug still is in ver 1.3.0.

**Comment by kaghy** [comment]
Do you maybe know the issue of the client crashing when trying to access a recipe for an item? (any item that has a recipe makes me crash)

**Comment by WalaoEgg0424** [comment]
This issue has been reported before , if u wanna to prevent crash from accidentely pressing the recipe , press O to disable it and search for recipe by google it XDD

**Comment by MJRLegends** [comment]
@kaghy this is a known bug and it will be fixed in the next update for the mod pack that will be out within 48hrs

**Comment by SteveKunG** [comment]
Please re-generating world on the Nibiru. I'm not sure about this.
