### ISSUE TITLE
Game Crashes when clicking on any NEI item

### ISSUE THREAD

**Issue by phattpks** [MJRLegends/Space-Astronomy-Feedback-#144]
Just upgraded to 1.3.1

Left and Right Click on any NEI item crashes game in single player and all members on server having same issue on server.

I found this post but not sure if its the same issue.
https://www.reddit.com/r/feedthebeast/comments/3w5jzw/space_astronomy_crash_nei/

I have uninstalled client and reinstalled and still does the same thing. do I need to make a mod change?

Thx for the help

[crash-2015-12-10_14.52.39-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/58853/crash-2015-12-10_14.52.39-client.txt)

**Comment by MJRLegends** [comment]
Please check the knows issues. It's been reported about 10 times now
