### ISSUE TITLE
Ender IO Game Crash

### ISSUE THREAD

**Issue by cilx** [MJRLegends/Space-Astronomy-Feedback-#146]
When ever I login I crash. I suspect it is the yatta wrench
http://pastebin.com/fzG0RUj1

**Comment by MJRLegends** [comment]
Yeah this will be fixed in v1.3.3

**Comment by cilx** [comment]
When will that be? I can't login. Could I get an inventory wipe or a character wipe the one from the rewards shop dose not work.

**Comment by cilx** [comment]
http://www.devcoftb.com/dashboard/account/ticket?code=18a26f2b

**Comment by MJRLegends** [comment]
In the next week

**Comment by cilx** [comment]
So I am stranded till then?

**Comment by MJRLegends** [comment]
Are you playing on a single player world

**Comment by cilx** [comment]
No the West Server, ING: Dark_Cilx

**Comment by MJRLegends** [comment]
Well the only thing I can suggest is contact the server support and get them to remove the wrench from your inventory

**Comment by cilx** [comment]
Is there a direct way to contact them? I have already summited a tecket

**Comment by MJRLegends** [comment]
Umm not really.

**Comment by MJRLegends** [comment]
You should be able to connect now
