### ISSUE TITLE
No rewards in reward bag

### ISSUE THREAD

**Issue by xyzabc198** [MJRLegends/Space-Astronomy-Feedback-#147]
Hi I just started with this modpack, got my first reward bag, a Good one too, but I was heartbroken to find nothing inside :( Seems like a poor reward to me :P So I went into creative and gave myself 64 to test, and all of them were empty...not so much empty but rather, nothing happens when I right click them but the reward bag disappears...

**Comment by WalaoEgg0424** [comment]
@xyzabc198 Are you using the v1.3.2? If not then update it , MJR has fixed the reward bag problem.

**Comment by MJRLegends** [comment]
Yeah because there working for me in v1.3.2 https://gyazo.com/9d33fc0eaaf8d957c69a01b7cd27ecc8

**Comment by xyzabc198** [comment]
Ah I see, has 1.3.2 not been added to Curse yet?

**Comment by xyzabc198** [comment]
Nevermind I just noticed the message, ignore everything im just blind :) sorry!

**Comment by MJRLegends** [comment]
No there is problems with it as its not synced to the curse launcher correctly, i am waiting for the ftb team to fix it... Btw it does say like everywhere even on the curse launcher https://gyazo.com/c953ef0b037ae8acd5db5a8fd286fcf6

**Comment by MJRLegends** [comment]
No problem its not your fault
