### ISSUE TITLE
Z-Fighting

### ISSUE THREAD

**Issue by WolfLeader116** [MJRLegends/Space-Astronomy-Feedback-#149]
Tons of Z-Fighting... Not much I can say about it, but I can't figure out what's causing it and it started since 1.3.1 I'm pretty sure and I haven't been able to find any other complaints.
![2015-12-12_18 11 29](https://cloud.githubusercontent.com/assets/7216500/11764982/f264f3cc-a0fb-11e5-9601-2315e6338520.png)
![2015-12-12_18 11 43](https://cloud.githubusercontent.com/assets/7216500/11764979/f1bdd100-a0fb-11e5-9e4e-16f9120f69ea.png)
![2015-12-12_18 11 19](https://cloud.githubusercontent.com/assets/7216500/11764980/f1c0b906-a0fb-11e5-8fcc-dda48a55e625.png)
![2015-12-12_18 11 25](https://cloud.githubusercontent.com/assets/7216500/11764981/f1c4954e-a0fb-11e5-9258-020d4977d8c6.png)

**Comment by WalaoEgg0424** [comment]
You mean FPS drop or what?( Im using phone cant really see those pictures)

**Comment by WalaoEgg0424** [comment]
This is a weird problem.Seems like your dealing with FPS problem cuz u turn down every settings to low , try Vsync off , Bobbing Off , clouds off . That will increase ur FPS

**Comment by MJRLegends** [comment]
@WolfLeader116 are you using optifine?

**Comment by WalaoEgg0424** [comment]
Just about to ask that question XDD

**Comment by WolfLeader116** [comment]
As you can see with the options image, I am not using OptiFine. Hm I usually turn v-sync off though, but personally I like the clouds and bobbing. I've got other programs open too so that slows it, but I'm still at 30fps which is fine for me even though 60 is what I'd want. I'm using an AMD Radeon HD 6670 graphics card with the latest regular release of Catalyst Control Center, 15.201.1151-150821a-188665E. I didn't have a driver update or anything between when it was working right and when it started, but I was hoping the newest version would solve it. It appears to only be on this installation of Minecraft, but it happens on Curse and FTB. I'm not sure if it's because of the AMD graphics card or not, but the graphics card isn't dying and there's nothing physically wrong with my computer, so it may be a driver problem or perhaps a mod.

**Comment by WolfLeader116** [comment]
Ok I just tried switching to fancy graphics to see if it was a problem with fast graphics and it seemed to solve it, but switching back to fast, the z-fighting is no longer present for some time, but then returned after about a minute. Fancy graphics seems to solve the problem however and from testing, it doesn't really help my FPS all that much to be on fast graphics so I will just stick with this...

**Comment by WalaoEgg0424** [comment]
Glad that you solved it , I dont usually play in fast graphics because i trust my pc XDD
