### ISSUE TITLE
Je n'arrive pas à lancer mon minecraft

### ISSUE THREAD

**Issue by HellFulll** [MJRLegends/Space-Astronomy-Feedback-#150]
Quand je lance mon minecraft sa m'affiche ça :
[minecraft.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/60470/minecraft.txt)

**Comment by MJRLegends** [comment]
Have you added any mods?

**Comment by MJRLegends** [comment]
Also you have updated the forge why?

**Comment by WalaoEgg0424** [comment]
Dont Edit Anything Inside The Modpack , unless your installing mods that are not interupting mods function inside the modpack and dont update the forge by urself , cuz some mods might not support your current forge version.

**Comment by HellFulll** [comment]
j'ai mit à jour forge et j'ai installé touts les mods.

**Comment by HellFulll** [comment]
![space1](https://cloud.githubusercontent.com/assets/16277269/11914260/e6d9df60-a67b-11e5-9a56-979ecf458fcc.PNG)
![space2](https://cloud.githubusercontent.com/assets/16277269/11914261/e6da53f0-a67b-11e5-9f3a-64665a9a6e1c.PNG)
Où je dois mettre chaque fichiers svp
