### ISSUE TITLE
Permanent World Hole

### ISSUE THREAD

**Issue by WorkmanMM** [MJRLegends/Space-Astronomy-Feedback-#152]
My game crashed once, and now there is this chunk that is a complete hole, and it had a few of my things in there. I've tried saving and quitting and restarting minecraft but it just stays there.  
![2015-12-14_18 01 04](https://cloud.githubusercontent.com/assets/14667740/11798928/b7de9c34-a28c-11e5-8692-1a18eb8ae39a.png)

**Comment by WalaoEgg0424** [comment]
This might be Chunk Corrupter or World Corrupter , I cant find any fix for this, if all your important stuff like the whole me system is at there , i suggest you create another world . If you have backup then use backup world.

**Comment by MJRLegends** [comment]
Yeah this isnt a mod pack issue its just a minecraft/forge problem where chucks can get corrupted.
