### ISSUE TITLE
Lava Power! - Ender Tanks don't register

### ISSUE THREAD

**Issue by tybot3k** [MJRLegends/Space-Astronomy-Feedback-#153]
Crafting the 2 Ender Tanks does not fulfill the requirements for Lava Power!. I did notice that when I tried to import the recipe into the crafting table via WAILA it didn't complete even though I had all the ingredients, and had to craft it manually. Might have something to do with the color wool I used to craft it with?

**Comment by WalaoEgg0424** [comment]
Yeah , use white wool , dont use other color.

**Comment by WalaoEgg0424** [comment]
via WAILA or NEI* lol

**Comment by MJRLegends** [comment]
Yeah you need to use white wool in the crafting recipe for the ender tanks, i will see what i can do to fix this.

**Comment by tybot3k** [comment]
Yup, meant to say NEI. I went into creative to give myself replacement materials and white wool and it did serve as a workaround.

**Comment by WalaoEgg0424** [comment]
Well , i did this mistake too XDD

**Comment by MJRLegends** [comment]
I dont think there is anything i can do to fix this.

**Comment by MJRLegends** [comment]
I will make it more clear that you need white wool for the quest in v1.3.4
