### ISSUE TITLE
Crash Report (v 1.3.3)

### ISSUE THREAD

**Issue by Darsam** [MJRLegends/Space-Astronomy-Feedback-#155]
Fine with the new update of my favorite modpack, i detect a small problem : 
I  start my modpack, Singleplayer, Play Selected World... Forge Mod Loader detected missing blocks/items. Okay, good, i click "Yes" and... it's the crash. 

http://pastebin.com/Y9cxCC5J

**Comment by Darsam** [comment]
For information, i play the modpack with curse.

And sorry for my bad english, i'm french ^^'

**Comment by WalaoEgg0424** [comment]
Its HQM error ,  next time use pastebin or upload the crash log

**Comment by WalaoEgg0424** [comment]
see issue tracker for the fix

**Comment by Darsam** [comment]
Okay, thanks for the fast comment !

Sorry if i'm a noob, but how to use issue tracker ?

**Comment by WalaoEgg0424** [comment]
Well your not a noob, your just new to the modpack , http://pastebin.com/R73aBeqA
This is the link to Issue Tracker , it has written down the solution to fix the HQM Bug and some known bugs.

**Comment by WalaoEgg0424** [comment]
If its working , i'll tell the modpack author to close this issue.

**Comment by Darsam** [comment]
Uh... Wait... the only reported HQM bug is fixed in 1.3.2 normally ...

**Comment by WalaoEgg0424** [comment]
@Darsam
 1. If your world wont load and gets stuck when loading the dimensions, after updating. OR Getting this crash http://pastebin.com/VDNpxfBy
 **********This is a HQM Mod bug not a mod pack bug!**********
Solution 1: Delete this folder "ftblauncher\SpaceAstronomy\minecraft\Saves\YOURSAVE\HardcoreQuesting" replace "YOURSAVE" with your world folder name. (You will lose all your quest progress!!!) But you can use "/hqm edit" command to complete the quests you did before!!!
Solution 2: Start a new world.

**Comment by WalaoEgg0424** [comment]
@Darsam If theres something that you dont know , add me on skype --- yimer1821 / RazorBlade0424

**Comment by Darsam** [comment]
Oh... i'm blinded, i think xD

Thanks, i'll see if it works ;)

**Comment by WalaoEgg0424** [comment]
@Darsam Your Welcome :)

**Comment by Darsam** [comment]
My modpack work, thanks :)

**Comment by WalaoEgg0424** [comment]
@Darsam Your Welcome :)

**Comment by WalaoEgg0424** [comment]
world*
