### ISSUE TITLE
Quest "Getting Fuel" (1.3.3)

### ISSUE THREAD

**Issue by Darsam** [MJRLegends/Space-Astronomy-Feedback-#156]
This quest was not to work in 1.3.2 ?

The Quest "Getting Fuel" (Exploring The Universe) we demand to have 2 oil bucket. So, the quest is valid when CRAFT ONE oil bucket... This is impossible. This is not a bug, but a error of the modpack creator... This error will be fix in 1.3.4 ?

**Comment by WalaoEgg0424** [comment]
@Darsam Hi , we met again. The Modpack Author , MJRLegends , is still finding way to fix this quest, BuildCraft oil and the Galaticraft oil is messing up , when you collect oil with a bucket from oil pocket , it will give you Galaticraft oil, the only solution to get pass this quest is 

1) Get 2 bucket of oil from oil bucket
2) Craft a refinery from Galaticraft
3) Craft a canister to fill the fuel
4) Put the oil bucket inside the refinery to fill 1 bucket - 2 bucket of oil , then Refined it
5) Put canister inside then change the refine setting to filling
6) After you get 1 fuel canister , do " /hqm edit " and then Shift + Left click , mark that quest to be done.

This is my solution for how to get pass that quest.
Hope you know what i mean :)

**Comment by Darsam** [comment]
Okay, thank you :)

**Comment by WalaoEgg0424** [comment]
@Darsam Your Welcome :)

**Comment by MJRLegends** [comment]
The type of task for the oil part will be changed in v1.3.4
