### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Williamkers** [MJRLegends/Space-Astronomy-Feedback-#159]
Where can I find this solution, sorry I'm a noob but can send the link to it??

**Comment by WalaoEgg0424** [comment]
Are you using curse launcher?

**Comment by WalaoEgg0424** [comment]
@Williamkers Heres the solution from thr Issue Tracker.


2. "java.lang.NoClassDefFoundError: com/typesafe/config/ConfigMergeable" crash. 

This crash is a problem with the curse lanucher, and is to do with the installing of forge and i am in the process of fixing this with the FTB Team. This is not a pack related bug!!!

Solution 1: Use the FTB Launcher.

Solution 2: Disable/delete the Open Computers mod

Solution 3: Try this - http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293018-opencomputers-v1-5-16?comment=1298

**Comment by Williamkers** [comment]
[crash-2015-12-20_14.16.00-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/67807/crash-2015-12-20_14.16.00-client.txt)

this is a crash with FTB, what's happening?

**Comment by WalaoEgg0424** [comment]
@Williamkers   I looking through it now

**Comment by Williamkers** [comment]
oke all right

**Comment by WalaoEgg0424** [comment]
@Williamkers Try add more ram , how much ram are u using right now to run the modpack?

**Comment by Williamkers** [comment]
where can I see this?

**Comment by Williamkers** [comment]
is 6 gig of ram enough?

**Comment by WalaoEgg0424** [comment]
well 4 gig of ram is enough.

**Comment by Williamkers** [comment]
oke, how can I chanche it?

**Comment by WalaoEgg0424** [comment]
Open your FTB Launcher , Options , theres Ram Maximum (MB)

Put it 4096

**Comment by Williamkers** [comment]
wait, I see the problem

**Comment by Williamkers** [comment]
I have a 32 bit Java

**Comment by Williamkers** [comment]
so 1,5 is the highest setting

**Comment by Williamkers** [comment]
let me try to download java 64 bits

**Comment by Williamkers** [comment]
sorry man

**Comment by WalaoEgg0424** [comment]
hmm 32 bit Java , i only know that 32bit Java only can set less Ram that you have installed in your pc.Try 64bit.

**Comment by Williamkers** [comment]
yes, I'm downloading it right now
haha

**Comment by WalaoEgg0424** [comment]
@Williamkers Nvm , its ok. I didnt saw that your using 32bit Java XDD

**Comment by Williamkers** [comment]
hahaha, this a stupid crashes

**Comment by WalaoEgg0424** [comment]
@Williamkers Nah , its not .

**Comment by Williamkers** [comment]
set to 4 right?

**Comment by WalaoEgg0424** [comment]
Yeah , i set it to 4gb ram to run it

**Comment by WalaoEgg0424** [comment]
If its fixed , please close the issue by urself. Thx

**Comment by Williamkers** [comment]
oke, nice.
I like this modpack

**Comment by Williamkers** [comment]
wait a minute

**Comment by WalaoEgg0424** [comment]
@Williamkers Same :)

**Comment by Williamkers** [comment]
If I was alone I can't play it

**Comment by MJRLegends** [comment]
Yeah that second crash is to do with running out of memory

**Comment by Williamkers** [comment]
oke thanks, I can't belive right now that I'm speaking with a modpack maker with over 40 k downloads

**Comment by WalaoEgg0424** [comment]
@Williamkers If you have anymore issue , ask MJRLegends , he is the modpack author , im on phone right now , gtg bed.

**Comment by Williamkers** [comment]
oke

**Comment by WalaoEgg0424** [comment]
GoodLuck Have Fun Guys

**Comment by Williamkers** [comment]
thanks

**Comment by WalaoEgg0424** [comment]
Your Welcome :)

**Comment by MJRLegends** [comment]
No problem
