### ISSUE TITLE
IC2 to Mekanism connection

### ISSUE THREAD

**Issue by nathanenns** [MJRLegends/Space-Astronomy-Feedback-#161]
When connecting IC2s glass fibre cable to Mekanisms induction matrix, after a restart the cable forgets the connection.  You have to break and replace the cable for it to connect again.  I tried placing a lever to force block update, but it showed a visual connection, but no power connection.

**Comment by MJRLegends** [comment]
Are you able to provide pictures so it will make it easier when reporting to the mod dev

**Comment by nathanenns** [comment]
I will set up my system so I can show it for the next scheduled server restart in 2 hours.

**Comment by MJRLegends** [comment]
Ok also can you see if it does it with any other engery cable

**Comment by nathanenns** [comment]
Okay, universal cables connect fine, as expected.  Thermal expansion cables visually are disconnected, but still move power in/out.  So just IC2s cables, or at least just the glass fibre ones are visually disconnected and stop moving power in/out.

http://imgur.com/a/t7I7H  First image shows cyro stabilized cable visually disconnected but still sending power.  2nd image is after hooking up the glass fibre, connected and sending power.  The third shows after loading it is both visually disconnected and no power being sent.

**Comment by MJRLegends** [comment]
Yeah i would say this is a IC2 problem

**Comment by MJRLegends** [comment]
Reported http://bt.industrial-craft.net/view.php?id=1790
