### ISSUE TITLE
Molecular Transformer Crafting

### ISSUE THREAD

**Issue by nightstick24** [MJRLegends/Space-Astronomy-Feedback-#162]
Thick Neutron Reflectors from IC2 craft with a metadata of :1 but the ones needed to craft the MT Core for the Molecular Transformer need Think Neutron Reflectors without any metadata.

I noticed this in the closed issues section, with you making a note on it Nov 8, however as of Space Astronomy 1.3.2 the recipe still seems to be bugged, sorry if I'm missing something.

**Comment by MJRLegends** [comment]
I will fix for v1.3.4

**Comment by MJRLegends** [comment]
Looking at this more closely, the recipe is fine as im editing it with mod tweaker due to the recipe being broken in the first place
