### ISSUE TITLE
game crash/ not opening save anymore

### ISSUE THREAD

**Issue by ognjen92** [MJRLegends/Space-Astronomy-Feedback-#164]
game crashed and i coudnt open save again, here is crash report 
[crash-2015-12-21_20.52.25-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/68934/crash-2015-12-21_20.52.25-server.txt)

**Comment by ognjen92** [comment]
i am using v1.3.3 on ftb

**Comment by MJRLegends** [comment]
See issue 1 here http://pastebin.com/R73aBeqA
