### ISSUE TITLE
recipe issue 1.3.3

### ISSUE THREAD

**Issue by Itho741** [MJRLegends/Space-Astronomy-Feedback-#167]
when i want to see the recipe of a object minecraft crash 
here the crash log and i think it crashes cause of Reika's mods
http://pastebin.com/jPWBraWZ

**Comment by Itho741** [comment]
?????

**Comment by MJRLegends** [comment]
Please check known issues tracker and closed issues because it's been posted loads #142 #143 #144 #145 #157

**Comment by Itho741** [comment]
okok ty

**Comment by MJRLegends** [comment]
Also #134
