### ISSUE TITLE
Magical wood recipe bug

### ISSUE THREAD

**Issue by helium2s1** [MJRLegends/Space-Astronomy-Feedback-#168]
Magical wood (needed for the Ender Quarry) is supposed to give additional pieces per craft when using higher-level enchanted books. Currently only gives 1 piece of wood per craft, regardless of book level. This existed in 1.3.0 and is still in 1.3.4.

**Comment by MJRLegends** [comment]
Thats because the recipe is probably changed in the new versions of the mods

**Comment by MJRLegends** [comment]
Plus its not really a bug just makes the recipe harder
