### ISSUE TITLE
Pluto/ Dark Asteroids Quests

### ISSUE THREAD

**Issue by Xephen** [MJRLegends/Space-Astronomy-Feedback-#170]
I am at Pluto, but the quest says that I did not visit it. It also does not allow me to go to the Dark Asteroids even though I am in the Tier 5 rocket.

**Comment by MJRLegends** [comment]
I need more information on this.

**Comment by MJRLegends** [comment]
The Pluto quest seems fine to me and i still need more information for both your issues.

**Comment by Xephen** [comment]
here are screenshots for the dark asteroids. http://imgur.com/a/JTsu1
As you can see, i have a tier 5 rocket, but when i launch, i cannot actually go to them.

**Comment by MJRLegends** [comment]
Yeah right I've had a look in the More Planets addons coding and it seems you have to use a Tier 6 rocket and above even though it says Tier 5 in the in game screen. I will report the problem to the developer as it's probably just a mistake.

**Comment by MJRLegends** [comment]
Reported to the developer of More Planets

**Comment by SteveKunG** [comment]
OK. That is my mistake. -.-
Will be fixed in the next version. Dark Asteroids now required Tier 5 rocket.
