### ISSUE TITLE
Optifine bug

### ISSUE THREAD

**Issue by splitface2811** [MJRLegends/Space-Astronomy-Feedback-#175]
I don't have a very good computer so I use optifine and it really helps but for some reason when I try to load the game from the ftb launcher with optifine I doesn't load the game and shows no crash report or anything in the ftb console. Hopefully this gets fixed.

**Comment by MJRLegends** [comment]
Saying it doesn't load isn't helpful at all because it works fine with OptiFine for me?

**Comment by splitface2811** [comment]
Sorry but I added optifine to the modpack on ftb and pressed launch the launcher disappeared then reappeared I looked through the console and found nothing and there were no crash reports and removing optifine solved the problem but made the game too laggy for me to play.

**Comment by MJRLegends** [comment]
Send me your log via pastebin.com

**Comment by Regner6** [comment]
Doesn't look like it's just optifine. It's the compatibility to dragon api, and maybe Ender IO

http://pastebin.com/PtQHNUd5

**Comment by MJRLegends** [comment]
@Regner6 thats not even related to this problem

**Comment by MJRLegends** [comment]
@splitface2811 are you able to send me the log?

**Comment by splitface2811** [comment]
sorry I've been busy with school lately. ill see if i can reproduce the results/

**Comment by splitface2811** [comment]
ok so i updated to the newest version and added optifine then launched the game. after a 40 min load time it appears that it deleted optifine and launched. ftb says the pasebin file is too large and it wont copy to clipboard so i have no idea what to do.

**Comment by MJRLegends** [comment]
Tbh I don't really understand what's not working for you

**Comment by MJRLegends** [comment]
Did you manage to fix this @splitface2811

**Comment by splitface2811** [comment]
No it's super weird but I haven't been able to play much anyways. I'm honing to look more into it on he weekend.

**Comment by MJRLegends** [comment]
Ok I would need the full console log after trying to load the mod pack so I can see what the problem is

**Comment by aiventimptner** [comment]
For me it worked neither. There is no crash report created by ftb launcher but this is latest log of the console.
[https://pastebin.com/rWJErRLT](url)

**Comment by MJRLegends** [comment]
@aiventimptner have you tried to run Optifine with another mod pack

**Comment by aiventimptner** [comment]
Well forget it. Runs smooth and clean. (Beside the fact that optifine and modpacks hate each other in generell and the first thing to do if there is a problem would be to remove optifine :D ). 
At my first try I picked an old version of Optifine which was hanging around in my download folder but with the newest Version (1.7.10 HD Ultra C1) there are no problems.
