### ISSUE TITLE
can't start from FTB Launcher on patch 1.3.4

### ISSUE THREAD

**Issue by Bomberman2010** [MJRLegends/Space-Astronomy-Feedback-#176]
i push play and if forge load it crash... console say:

"EnderIO: Found the following problem(s) with your installation: "An unsupportted old RF API is installed (1.7.10R1.0.1 from Railcraft_1.7.10-9.8.0.0.jar). Ender IO needs at least 1.7.10R1.0.2 and will NOT work with older versions." This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it."

maybe this is the problem?

**Comment by WalaoEgg0424** [comment]
Post the whole long on pastebin.com then show us the full crash log

**Comment by WalaoEgg0424** [comment]
log*

**Comment by MJRLegends** [comment]
yeah ^^

**Comment by Bomberman2010** [comment]
i havnt a pro account for pastebin.... 
"You have exceeded the maximum paste size of 512 kilobytes per paste. PRO users don't have this limit!"

**Comment by WalaoEgg0424** [comment]
you can just upload the crashlog to here

**Comment by WalaoEgg0424** [comment]
i'll download it and see through it

**Comment by Bomberman2010** [comment]
here: 
[fml-client-1.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/75928/fml-client-1.txt)

**Comment by MJRLegends** [comment]
thats not the crash your getting a "Reika.DragonAPI.Exception.InstallationException: ChromatiCraft was not installed correctly:
" crash

**Comment by MJRLegends** [comment]
See issue 3 on the main section here http://pastebin.com/R73aBeqA

**Comment by WalaoEgg0424** [comment]
yeah , thats not a crash log

**Comment by Bomberman2010** [comment]
ok, thanks for the fast help =)

**Comment by MJRLegends** [comment]
@Bomberman2010 no problem this is a problem which everyone is getting thanks to Reika (ChromatiCraft  developer) Im trying to sort it out but its a mod problem but try the solutions
