### ISSUE TITLE
Can't start the game

### ISSUE THREAD

**Issue by sigur123** [MJRLegends/Space-Astronomy-Feedback-#177]
Please can you help me? I don't  know where to put the arguments.
http://pastebin.com/uJqeRdA3

**Comment by MJRLegends** [comment]
See issue 3 on the main here http://pastebin.com/R73aBeqA

**Comment by sigur123** [comment]
Sorry, it wasn't doing it on 1.3.3

**Comment by MJRLegends** [comment]
Yeah the mod developer Reika broke it all :D
