### ISSUE TITLE
IF YOUR GAME/SERVER CRASHES READ THIS!!! - Best solution right now is to use v1.3.3

### ISSUE THREAD

**Issue by MJRLegends** [MJRLegends/Space-Astronomy-Feedback-#178]
Im having some major problems with the mod pack atm!!

Im not really sure on a full solution to all these problems because if i downgrade the mod versions all the older bugs come back up and if I remove them then the world messes up due to dragon api.

*********Best solution right now is to use v1.3.3*********

Issue 1: If your getting this crash "Reika.DragonAPI.Exception.InstallationException: ChromatiCraft was not installed correctly:"
(http://pastebin.com/riTzdJ2t)
This is a ChromatiCraft Mod issue not a mod pack bug!
Solution 1: Add "-XX:+UseG1GC" to your launchers launch arguments! (Might have to remove "-XX:+UseConcMarkSweepGC" as well)
Solution 2: Only fix seems to be to use java 7

Issue 2: Servers using KCauldron cant load there server because it just crashes when dragon api and its child mods is in the mod pack.

I have reported issue 2 here https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/541

**Comment by MJRLegends** [comment]
**********Best solution right now is to use v1.3.3**********

**Comment by ReikaKalseki** [comment]
If you start claiming things are bugs when they are not, trying to get your users to harass me, I will pull your pack permissions. Choose wisely.

**Comment by MJRLegends** [comment]
@ReikaKalseki They are bugs within in my mod pack but there not from a mod developers point of view and im not getting people to harass you just its impossible for people to upgrade there servers to play my mod pack since the latest update for the mod pack which includes the v10+ of your mods. Due to the second issue listed above which you know about

**Comment by ReikaKalseki** [comment]
I was talking about how you attach the "mod bug" label to just about every issue you have, regardless of whether it is on the mod's end.

**Comment by MJRLegends** [comment]
@ReikaKalseki Its just a general label because its related to mods and not a recipe or a quest book issue.

**Comment by Ryloth** [comment]
Here are a couple of workarounds for the client and server that work under Java 1.8
- In the FTB launcher, in the Advanced Options, add the '-XX:+UseG1GC' argument, then uncheck 'Use Optimization Arguments for fast computers?'.
- In the ServerStart.bat file, add the argument '-XX:+UseG1GC' and removed both the ' -XX:+UseParNewGC' and '-XX:+UseConcMarkSweepGC' arguments.

**Comment by spannerman79** [comment]
@MJRLegends you may want to take a look at https://gitlab.prok.pw/KCauldron/KCauldron/wikis/patched-mods

**Comment by ReikaKalseki** [comment]
If you deliberately use unofficial versions of the mods you will lose pack permissions **permanently**.

**Comment by MJRLegends** [comment]
@ReikaKalseki Yeah I don't plan on supporting or caring about unofficial versions

**Comment by djoveryde** [comment]
Reika, instead of throwing threats to players perhaps take note of what has been fixed in the "unofficial version" and perhaps incorporate it into your official version. 
Most players use KCauldron for the main reason that its the only thing that supports both mods/plugins. Theres no other options out there. 

Just think instead of being unhappy with the situation try and help it perhaps. 

I've seen too many mod developers say "I dont support cauldron and never will!" yet things like that end up having players abandon their mods because they dont want to help in patching the issue.

Just my 2 cents. Delete it if you feel unhappy with what I've said. I'm just trying to help you out here

**Comment by ReikaKalseki** [comment]
> @ReikaKalseki , instead of throwing threats to players perhaps take note of what has been fixed in the "unofficial version" and perhaps incorporate it into your official version.
Most players use KCauldron for the main reason that its the only thing that supports both mods/plugins. Theres no other options out there. 

I looked at its source, but the nature of compilation and obfuscation makes it almost entirely unusable, doubly so when I had no idea where to look among the almost 300K lines of code in DragonAPI. On top of that, I actually *have* contacted them with an offer to work together on solving it on my end.
