### ISSUE TITLE
Enhanced Portals 3 crash

### ISSUE THREAD

**Issue by helium2s1** [MJRLegends/Space-Astronomy-Feedback-#181]
Reported "crash" bug (server doesn't crash, just locks up so that it is completely non-responsive) to mod author. The bug occurs when using the redstone interface to open a portal (I know it occurs when the interface is set to "dial specific identifier (2)", may occur with others). 

See https://github.com/enhancedportals/enhancedportals/issues/12 for more details.

**Comment by MJRLegends** [comment]
Yeah seems to be a mod problem so we will wait to see what they come back with.
