### ISSUE TITLE
Server not starting (Mac)

### ISSUE THREAD

**Issue by Handy-Andy** [MJRLegends/Space-Astronomy-Feedback-#183]
I'm trying to set up a server to play with a friend, so I downloaded the server pack from the FTB Launcher and put it in a folder I made for it.
Then I ran the ServerStart.sh file in Terminal, and it gives me an error. Here's the Terminal log (I edited out my computername and username btw.)

[SpaceAstronomy Server Crash Log.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/81913/SpaceAstronomy.Server.Crash.Log.txt)

I'm sorry if it's just something I'm doing wrong, I'm new to modded servers.

**Comment by MJRLegends** [comment]
Yeah i dont think the ServerStart.sh works you will need to edit the file

**Comment by Handy-Andy** [comment]
Wow! Thanks for the quick response :)
What do I need to edit the file to? I researched it for about 4 hours and couldn't find anything complete. I only found bits and pieces of things, and I'm not very comfortable hacking around in Terminal trying to figure it out.

**Comment by MJRLegends** [comment]
open the ServerStart.sh file
and remove the following 
"
 if [ ! -f minecraft_server.1.7.10.jar ]; then
    echo "running install script!"
    ./FTBInstall.sh
fi
"

**Comment by Handy-Andy** [comment]
That fixed the first problem, but it still says this:

[Server Crash Log 2.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/81952/Server.Crash.Log.2.txt)

**Comment by MJRLegends** [comment]
Do you have "forge-1.7.10-10.13.4.1517-1.7.10-universal.jar" file where you have the ServerStart.sh file

**Comment by Handy-Andy** [comment]
Yes, same folder.

**Comment by MJRLegends** [comment]
oh well its saying it cant find the "forge-1.7.10-10.13.4.1517-1.7.10-universal.jar" file

**Comment by Handy-Andy** [comment]
It says it can't access it, so maybe it's a permission problem? I'm not sure how to change that though...
Also here's a screenshot of the folder

![screen shot 2016-01-07 at 7 48 17 pm](https://cloud.githubusercontent.com/assets/16595767/12187187/aef2c494-b577-11e5-93bf-1ddc3d2d1edb.png)

**Comment by MJRLegends** [comment]
yeah im not sure as i dont have a MAC

**Comment by Handy-Andy** [comment]
Did some research, I just set all the permissions to read-write-execute, still the same problem, so maybe it's something else?

**Comment by Handy-Andy** [comment]
Also FTBInfinity server has a Settings.sh and a FTBInstall.sh file. I don't know what they do, but could they have something to do with it?

**Comment by MJRLegends** [comment]
Im really not sure as i've never owned a mac so dont know how they work

**Comment by Handy-Andy** [comment]
That's fine, I appreciate the help you gave me :)
I'll keep looking and if I find anything I'll post it here.

**Comment by MJRLegends** [comment]
No problem, please reopen the issue if you need any more help :)
