### ISSUE TITLE
Crash upon startup in 1.3.4

### ISSUE THREAD

**Issue by natelovesyou** [MJRLegends/Space-Astronomy-Feedback-#184]
Here is the crash report: http://pastebin.com/PhC9RF9p

I updated from the previous version today before it crashed. I will try to delete the pack and redownload it all in case there may have been an issue with the download. I just updated Java a few days ago and have had no issues with other modpacks regarding Java it seems.

**Comment by natelovesyou** [comment]
Ah, I kept reading other posts and saw this issue is known and I need to roll back or use Java 7. Thank you. I will close the issue as it may not help you any. Good luck, and keep up the good work!

**Comment by MJRLegends** [comment]
No problem
