### ISSUE TITLE
FTB Crash on Mojang Screen Mac

### ISSUE THREAD

**Issue by VioletFire** [MJRLegends/Space-Astronomy-Feedback-#185]
Hi - whenever I launch (any) FTB game I get to the loading screen and about half-way through it, it crashes to desktop. I've tried updating the launcher, restarting, and updating Java. I don't know what else to try. 

Please Help!

**Comment by MJRLegends** [comment]
Telling me it crashes doesnt help one bit i need the crash log!!!

**Comment by VioletFire** [comment]
Oh, duh... sorry...


[crash-2016-01-08_09.22.25-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/83458/crash-2016-01-08_09.22.25-client.txt)

**Comment by VioletFire** [comment]
uh not sure if that attached or no...

**Comment by MJRLegends** [comment]
#178

**Comment by VioletFire** [comment]
... oh :/

thanks for your help!
