### ISSUE TITLE
Extra Utilities

### ISSUE THREAD

**Issue by TheOnlySurvivor1** [MJRLegends/Space-Astronomy-Feedback-#186]
golden bag of holding doesn't open

**Comment by WalaoEgg0424** [comment]
It opens now?

**Comment by TheOnlySurvivor1** [comment]
i will answer a litlle bit later srry not gaming right now but thanx for
the help

**Comment by MJRLegends** [comment]
Golden bag of holding opens for me just fine both in single player and on a server?

**Comment by WalaoEgg0424** [comment]
Maybe some bag opening lagging issue , thats wat im thinking

**Comment by TheOnlySurvivor1** [comment]
Ok thanx
