### ISSUE TITLE
Poor Framerate

### ISSUE THREAD

**Issue by ForgedSnow** [MJRLegends/Space-Astronomy-Feedback-#187]
This mod-pack is unplayable for me right now. With all the settings on low and the render distance on tiny I keep getting frame-rate drops in the low single digits and it tops off at like 15 fps. And this is while in the wilderness without any machinery or anything near by. I tried running it with 12 gigs of ram (out of my 16) and that didn't help. Still laggy when I tried using 4, 6, and 8 gigs of ram. I hope there is something I'm forgetting to do to make it actually playable.

btw. My processor is an i7 4ghz quadcore and my gpu is a gtx980, so my pc isnt the problem.
Note: I've tried using Java 8 u 45 but it randomly crashes, so I went back to java 7 u 80. Still very much laggy

**Comment by WalaoEgg0424** [comment]
Thats weird because my pc specs is more crappier than urs , can you take a screenshot ingame with f3 enabled?

**Comment by ForgedSnow** [comment]
I just went to go screenshot my client, and the wackiest thing happened, it was running smooth! Like 200 times better then I usually get in FTB. I switched my maxPermSize to 2048M and I went from averaging 14fps to averaging 430+ fps.
CONSIDER IT RESOLVED :D

**Comment by WalaoEgg0424** [comment]
you increased the Perm size , nice.Glad that ur fps increased now.I put my perm size to 512mb only and it runs smooth for me.

**Comment by WalaoEgg0424** [comment]
Can you close the issue please? :)

**Comment by WalaoEgg0424** [comment]
OO ,MJR ur here
