### ISSUE TITLE
NEI Recipe Crash

### ISSUE THREAD

**Issue by miki1741** [MJRLegends/Space-Astronomy-Feedback-#188]
After I had updated Space Astronowy to version 1.3.5, game crashes when I try to check the recipe of Big Reactors or RotaryCraft

**Comment by MJRLegends** [comment]
I need the crash log???

**Comment by miki1741** [comment]
http://pastebin.com/C6TQNrHb

**Comment by MJRLegends** [comment]
Yeah this is a known bug but it was fixed in 1.3.4 but i had to downgrade a version in RotaryCraft, Reactorcraft, Dragon API and that, and its now back again see #134

**Comment by MJRLegends** [comment]
Sorry there not much i can do atm because the latest versions of RotaryCraft, Reactorcraft, Dragon API and that have issues with KCauldron so i cant use them.

**Comment by BlackSymbol** [comment]
Will update a bit: crashing when trying to look up Extra Utilities recipes (twice in a row for me). Also friend crashed when tried to look up IC2 recipe.

**Comment by MJRLegends** [comment]
To fix this problem use  Remove Rotarycraft

**Comment by MJRLegends** [comment]
See the change log - http://pastebin.com/Zmx3n72i
