### ISSUE TITLE
Power Armour Quest doesn't work

### ISSUE THREAD

**Issue by DragonBale** [MJRLegends/Space-Astronomy-Feedback-#19]
If I craft the Power Armour in the questline Getting Started -> Power Armour -> Craft the Armour it won't accept my crafted armour.

**Comment by MJRLegends** [comment]
Thanks this problem has been fixed for the next update and someone else already submitted a issue that is now in the closed section. But thanks for letting me know :D

**Comment by DragonBale** [comment]
Ok nice, can't wait =)
