### ISSUE TITLE
More Planets Slimes Spawn

### ISSUE THREAD

**Issue by BlackSymbol** [MJRLegends/Space-Astronomy-Feedback-#190]
After updating to 1.3.5 slimes from More Planets started to spawn in ridiculous amounts in slime chunk. This wasn't an issue before updating. I don't see any option in More Planets config file to disable them and don't see anything concerning slimes in changelog, so I have no idea why they suddenly decided to have a party. Is there any way to turn them off except using 3rd party mod (if there's any disabling slimes)?

P.s. I guess I can install sound mufflers around the base, but that's not really a nice way out.

Thanks,

**Comment by MJRLegends** [comment]
Was it a blood moon?

**Comment by BlackSymbol** [comment]
There party seem to dissolve a bit by now, though they;re still there. Wasn't a Blood Moon.

**Comment by MJRLegends** [comment]
Ok idk it doesn't happen on my world or my server

**Comment by BlackSymbol** [comment]
Not a real issue, bit it's a bit irritating. They of course should spawn in slime chunk, but it didn't happen in that quantities before update. I will close this for now hoping they will dissolve, if the issue will persist I'll reopen.
