### ISSUE TITLE
Nei crash

### ISSUE THREAD

**Issue by TheLogan** [MJRLegends/Space-Astronomy-Feedback-#191]
I started a game under 1.3.1 or 1.3.3, I don't remember which one though. I've finally decided to update to 1.3.5, I had to delete the hqm folder per the instructions of the "known issues" text.
After going through the quest edit book to fix all the quests I've completed so far I got an emerald (my first in the game so far), so I decided to see if there were ways to create them my self, so I clicked R while hovering over, but instead of getting the recipe I got a crash, details are on pastebin:

http://pastebin.com/UHKM1RGw
I'll dig further and see if I can come up with more details, but for now this is the only item that has crashed. I'm really not skilled at reading the minecraft error report, but I take it it has something to do with rotary craft..?

**Comment by TheLogan** [comment]
It seems to be most recipes, the error btw is seems to be the same, so I won't repost the crash log unless someone explicitly asks for it =)

**Comment by MJRLegends** [comment]
Already posted about 100 times #188
