### ISSUE TITLE
Raw Koentus Meteoric Iron

### ISSUE THREAD

**Issue by RogerManuel007** [MJRLegends/Space-Astronomy-Feedback-#193]
Hi.

Each time I harves a meteor in Koentus, I receive "Raw Meteoric Iron" but the quest said that I need: "Raw Koentus Meteoric Iron"

Any help?

Regards.

**Comment by RogerManuel007** [comment]
Solved.
I got "Raw Koentus Meteoric Iron"  in Diona.
Maybe you need change the quest's test.
Thx.

**Comment by MJRLegends** [comment]
Yeah I will get it changed
