### ISSUE TITLE
Server crash when joining

### ISSUE THREAD

**Issue by ProxyPlayerHD** [MJRLegends/Space-Astronomy-Feedback-#194]
the Admins didn't really want me to post this here because they are not Sure if this only Applies to me, as other Players can freely join/leave the Server, while my Connecting Crashes it entirly.

this Happend after the Newest Update (1.3.6) where the 3 mods, (Rotarycraft, Electricraft and Reactorcraft) got Deleted for seemingly no reason. eitherway, Rotarycraft blocks/Items are Everywhere on my Base on the Server, and i'm to even Completly sure if theses 3 Mods are the Cause of it. it could be anything that Changed from 1.3.5 to 1.3.6, as my Base contains quite a few things from various Mods.

sadly i can't really post a Report from the Console, as i don't own the Server and the Client Console doesn't show anything Important. (Honestly i can't tell what's error and what not, to much Red/Yellow/White text D: )

**Comment by MJRLegends** [comment]
I would need both server log and the client log to find out the issue

**Comment by MJRLegends** [comment]
Which server is it?

**Comment by ProxyPlayerHD** [comment]
the Server is Called "Frozensoul".
but then again, i don't have the Server log... or the Client.
also one of the Admins said, i should stay away from the Server to not Crash it, because the Other players want to play too...
does it help when i say that i'm the only one one the Server that Plays with a Clone (Sync mod)?

**Comment by MJRLegends** [comment]
I will see what i can do

**Comment by badgernz** [comment]
Ive been to your base and cant see any reason that you'd be crashing, it was from enderio item conduits but there is nothing in your base or inventory that would do that
[crash-2016-01-17_16.56.56-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/93612/crash-2016-01-17_16.56.56-server.txt)

**Comment by MJRLegends** [comment]
@ProxyPlayerHD please reopen if you get any more problems

**Comment by ProxyPlayerHD** [comment]
sooo, i tried to see what my Client Console says about this:
http://pastebin.com/Pnnfu0iB

say if that isn't the entire thing... but it's hard to see where the Error started xD

**Comment by MJRLegends** [comment]
The lot you have posted just shows you on the server and the server closing so that's not a problem?

**Comment by ProxyPlayerHD** [comment]
well, the Server usually close itself to proven serious Damage to the Files...
thought it might help. D:
but well, this didn't worked out as Planned

**Comment by MJRLegends** [comment]
Most servers close every few hours to reduce lag or the owner/admins of the server might of restarted it.

**Comment by ProxyPlayerHD** [comment]
the Server has a Automatic Restart System, but it warns you 10min. before the Restart.

**Comment by MJRLegends** [comment]
Yeah I know that's what I'm telling you

**Comment by ProxyPlayerHD** [comment]
opps, sry. xD

well i'll just hope that someday this gets Fixed, whatever broke in the first place.
but this isn't the only Thing that happens on the Space Astronomy Server...

**Comment by MJRLegends** [comment]
The server restart automatically isn't a bug/problem so what is there to be fixed?

**Comment by ProxyPlayerHD** [comment]
the fact that the Server shutdowns everytime i join... no matter what the Automatic system says

**Comment by MJRLegends** [comment]
Well you need to post a log showing this because the one you posted only shows the server closing by owner/admin or automatic restart

**Comment by ProxyPlayerHD** [comment]
technicly, the Server closed itself... so, there's no Crash Log.
they would need to Deactivate the System to get a Crash, or it's a Normal Server thing.

**Comment by MJRLegends** [comment]
It would still show it in the client login because all logs are saved by the client

**Comment by ProxyPlayerHD** [comment]
the last Crash log i got is from the 17.01.2016 even tho i tried to join the Server ~30min. ago...
so no Crash log, sadly

**Comment by MJRLegends** [comment]
I'm not on about a crash log I'm talking about the full client console log

**Comment by ProxyPlayerHD** [comment]
uhhh... where is that saved and what would it have to offer?

**Comment by MJRLegends** [comment]
In the logs folder or the console when the game is running and it will offer me some evidence and give me a indercator on the issue because so far all you have told me is the server has a automatic restart system which isn't a issue

**Comment by ProxyPlayerHD** [comment]
the Issue is this Automatic System... as it Provens the Server from Crashing when it Detects a Error, so there's nothing that shows what went wrong...
aslo the Newest logs only shows this:
http://pastebin.com/yhda40RR
this is literally the entire file... inside the .gz file

**Comment by MJRLegends** [comment]
Stop wasting my time
