### ISSUE TITLE
Crash after startup

### ISSUE THREAD

**Issue by Spellkaze** [MJRLegends/Space-Astronomy-Feedback-#195]
Hi, I'm having a trouble with this modpack, after the forge loads all the mods and gets to the step 7/7, I can see the menu for at least 1 second at the it suddenly closes. I know that this don't generate an actual crash report, just logs.
I already tested the 1.3.3 version, java 7, searched for anything about Reika DragonAPI, but apparently I didn't find anything, I have played in other modpacks, but I didn't have this kind of crashes, hope you can help me.
[fml-client-latest.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/95067/fml-client-latest.txt)
 (Crash report from the log http://paste.ubuntu.com/14577994/ )

**Comment by MJRLegends** [comment]
Have you tried 32bit Java?

**Comment by Spellkaze** [comment]
I have tried it, but the game doesn't even launch. The error:
"Error occurred during initialization of VM
Could not reserve enough space for object heap
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit."
Here is a crash report with java 7 x64: http://paste.ubuntu.com/14577994/

**Comment by MJRLegends** [comment]
To me it seems your having a java related issue

**Comment by MJRLegends** [comment]
Please try and run another mod pack on the same launcher your using to run my mod pack and see if it runs?

**Comment by Spellkaze** [comment]
It runs, in almost all.... all of the FTB official modpacks work, in the third-party modpacks, BeeHappy runs, but not Galactic Science (GS runs in other launcher, but not in the FTB) maybe a version or the FTB launcher is messing things.

**Comment by MJRLegends** [comment]
No problem let me know if you get any more issues
