### ISSUE TITLE
Inventory crash

### ISSUE THREAD

**Issue by Williamkers** [MJRLegends/Space-Astronomy-Feedback-#196]
Hello,

My crash begins When I'm opening a inventory like a crafting table or my inventory.
I can run this modpack well before.
Can you help me?
Thanks

**Comment by Williamkers** [comment]
sorry Its not a crash but a big lag, but I have to quit the game so I don't have a crashreport.

**Comment by MJRLegends** [comment]
Sorry but I can't do anything with that information it lags as there nothing to go on and it could be about 1000000000 things that's the cause. I need more information?

**Comment by Williamkers** [comment]
Sorry, but its late by me now. I'm going to sleep. Tomorrow I will have a look for a crash report, but it is only when I open a invetory

**Comment by MJRLegends** [comment]
Any luck with the crash reports if not send me the full log

**Comment by Williamkers** [comment]
Ow sorry man, I did forget that this was mail was active.
But yes I found the problem, my java version was tooooooo old.
sorry man

Gr. William

**Comment by Williamkers** [comment]
But this is the best modpack I ever have seen. And it is updating much. Thanks for all your work. Thanks from my friend too.

**Comment by MJRLegends** [comment]
No problem and thank you hope your enjoying playing it

**Comment by Williamkers** [comment]
That is no problem
