### ISSUE TITLE
/Dev/Null isn't working as intended - Reproduced on 3 different PCs, 7 different installs and two servers

### ISSUE THREAD

**Issue by EvitiniaOnTwitch** [MJRLegends/Space-Astronomy-Feedback-#197]
So hi and thank you for that awesome modpack. I love it and so does my viewership on twitch.
The only problem that is bothering me quiet hard is that the /Dev/Null from OpenBlocks isn't working at all.
You can put a stack of whatever into it and it will not void any additional block of the same ID at all.
As described in the title, i reproduced this Bug quiet often.
Regarding ideas the only thing I can think of is, that somehow the /Dev/Null is trying to look for items having the same ID, which is 5755 btw.
I really hope there is a way to fix the problem, it's one of my most used items throughout modded MC.

**Comment by MJRLegends** [comment]
which mod pack version are you using?

**Comment by EvitiniaOnTwitch** [comment]
1.3.6 aß 1.3.7 isn't available yet. Also tried it with 1.3.2, 1.3.3, 1.3.4, 1.3.5 -  even my stream chat threw in various ideas to fix it.  Nothing worked out.  AT least I finally managed to disable Bloodmoon from triggering 😁
Btw is it intended,  that the questbook stays at 6% regarding the inscriber presses tab and isn't showing any New quests?

**Comment by MJRLegends** [comment]
Try in v1.3.7

**Comment by MJRLegends** [comment]
Please could you let me know if it works

**Comment by aiventimptner** [comment]
to bring another idea into this round: the /dev/null item is purposed to work only for items that are dropped on ground and sucked up into your inventory. for me it is working quite well.
