### ISSUE TITLE
HQM, cargo rocket quest

### ISSUE THREAD

**Issue by BlackSymbol** [MJRLegends/Space-Astronomy-Feedback-#198]
Chapter 3, quest name: "Crafting a Cargo Rocket", what kind of cargo rocket is expected to be crafted? The one with 18 storage space doesn't work.

Was in issue in 1.3.6, remains an issue in 1.3.7.

**Comment by MJRLegends** [comment]
I will look in to this and get back to you

**Comment by MJRLegends** [comment]
Right i have had a look and i believe its the 18 storage space one that the quest is set to. I will do some more testing

**Comment by BlackSymbol** [comment]
Well, my friend on server tried to craft it and pass the quest (we're on the same team), but that doesn't work, I tried as well, but cannot pass it anyway.

**Comment by MJRLegends** [comment]
Idk probably a glitch with HQM
