### ISSUE TITLE
Mekanism bug

### ISSUE THREAD

**Issue by Dakuen** [MJRLegends/Space-Astronomy-Feedback-#20]
i found a bug where you cant use the prc (pressurized reaction chamber) to produce hdpe pallets.. it is pretty annoying cause the machines and the whole setup was for nothing now..

(it has all materials, liquid ethylene, oxygen and the substrate in it and it is full of it but the progress bar does not move)

**Comment by MJRLegends** [comment]
guessing you have sorted this?
