### ISSUE TITLE
world won't load/create

### ISSUE THREAD

**Issue by dartzmaster** [MJRLegends/Space-Astronomy-Feedback-#200]
So I updated to version 1.3.7 lately and tried to open my world. I'm getting the "loading world" screen for like  a second, but then it puts me back to the title screen. I can then acces my world selection/options/etc. but the world never loads. Tried to create a new world but same problem here. The new world won't even show up in the world selection. I also tried downgrading to version 1.3.6 again and for some reason i got the same problem there again. Tried to delete the HQMFolder, still doesn't work. I don't get a crash report but my console gives me this output: http://pastebin.com/whzCkYEt

**Comment by MJRLegends** [comment]
How much RAM are you using

**Comment by dartzmaster** [comment]
4GB and for some reason it's only this modpack. I play other modpacks via the curse client and they work fine

**Comment by MJRLegends** [comment]
You probably corrupted your world then but idk I can't reproduce this problem.

**Comment by Leslieghf** [comment]
I just registered just because I wanted to tell you Ender Storage is causing the issue. I just had the same problem so I read your log and I searched for errored mods. Ender Storage is errored so I simply removed it.
