### ISSUE TITLE
[Suggestion] Add the official server IP to the server list by default. 

### ISSUE THREAD

**Issue by brucethemoose** [MJRLegends/Space-Astronomy-Feedback-#201]
I noticed the official server IP is on the website, but not in the modpack itself. Adding the IP to where it shows up in the client by default would bring alot of traffic to the official server.  

I'm not sure how to do this in Curse/FTB (otherwise I would've just submitted a pull request), but I've seen other packs with the same launcher do it.

**Comment by MJRLegends** [comment]
Yeah I know how to do this. Also to do this I need to release a update and I don't want to post there yet because we are still working on stabilising the performance of the server before I include on the multiplayer section of a modpack

**Comment by MJRLegends** [comment]
Put it this way it will be included in the v1.3.9 update which is the one after next

**Comment by brucethemoose** [comment]
Sounds good, thanks.

**Comment by MJRLegends** [comment]
No problem I see that you are playing on the server :)
