### ISSUE TITLE
ProjectRed broken in 1.3.8

### ISSUE THREAD

**Issue by pielorz** [MJRLegends/Space-Astronomy-Feedback-#203]
Pretty sure the version of ProjectRed in modpack version 1.8.3 has a major problem with signal propagation in the Red Alloy Wires.

I updated the pack from 1.3.7 where the Red Alloy Wire was working fine and now the lever powered wire wont drop the redstone signal even when the level is turned off.

On the ProjectRed GitHub ( https://github.com/MrTJP/ProjectRed/issues/994 ) there is mention of this issue. It has been fixed in the very latest version: 1.7.10-4.7.0pre12.95

Will stick with version 1.3.7 for now :)

Cheers

**Comment by MJRLegends** [comment]
I will include the version 1.7.10-4.7.0pre12.95 in the next version.
