### ISSUE TITLE
Galacticraft oxygen gear/mask/tanks are not visible. 

### ISSUE THREAD

**Issue by brucethemoose** [MJRLegends/Space-Astronomy-Feedback-#205]
http://imgur.com/a/u5Bs2

This could be a mod conflict... or is it intentional? Not a huge bug, but either way, I like the way the oxygen gear looks on top of other armor.

**Comment by MJRLegends** [comment]
Yeah i will report this to the galacticraft developers

**Comment by radfast** [comment]
@brucethemoose 

I need to know which other "visual" mods you had installed when those screenshots were taken. Exact versions please.

Focus on:
* Optifine
* PlayerAPI
* RenderPlayerAPI
* SmartMoving
* SmartRender
* any other "client-only" mods.

**Comment by brucethemoose** [comment]
Sorry for the delay.

I'm using the stock Space Astronomy modpack, no Optifine or any other extra client-only mods.

Here's a fairly recent crash report of mine for an unrelated issue:
http://pastebin.com/rTaxbGyf


PlayerAPI is part of the modpack, but I'm not sure what mods depend on it.

**Comment by brucethemoose** [comment]
@radfast
@MJRLegends 

So I removed PlayerAPI... and nothing happened.


- The modpack starts and runs fine without PlayerAPI
- All the Oxygen gear still doesn't render.

**Comment by brucethemoose** [comment]
Ruled out the following mods, so far:

Player API
ArmorStatusHUD
DamageInicators
Hats
Sync
IngameinfoXML
Advanced Genetics
Fastcraft

Rendering issue is still there will all those removed.

**Comment by MJRLegends** [comment]
Are you wearing any amour and if so what one?

**Comment by brucethemoose** [comment]
None.

Narrowed it down to a few mods, I'll find the conflicting one in a minute,

**Comment by brucethemoose** [comment]
@radfast
It's DragonAPI v9b. Gear renders fine with the mod removed, and doesn't render with the mod added back in. Updating to v10d does not fix the issue. 

@MJRLegends
DragonAPI shouldn't even be in the pack anyway, and I don't think Player API should be either :P. There may be other unused mod dependencies in there, but just eyeballing it I don't see any.

**Comment by MJRLegends** [comment]
@brucethemoose DragonAPI cant be removed as i will mess up peoples world and they will not be playable and Player API is needed.

**Comment by MJRLegends** [comment]
Also the thing is this is a first time i have heard about this...

**Comment by brucethemoose** [comment]
Oh, ya that makes sense. I joined the server before Reika's mods were temporarily removed.  

It's repeatable on my setup though. I'll delete Curse and just start a whole new instance to be sure.

**Comment by brucethemoose** [comment]
Confirmed, it happens with nothing but Galacticraft, DragonAPI and Forge are installed:

http://imgur.com/a/qpbTl

**Comment by MJRLegends** [comment]
Have you tried changing java version or updating your graphics drivers?

**Comment by brucethemoose** [comment]
Looks like the issue will be fixed in the next Galacticraft update.

**Comment by MJRLegends** [comment]
Haha yeah
