### ISSUE TITLE
unable to get to the moon

### ISSUE THREAD

**Issue by Doc-Savage99** [MJRLegends/Space-Astronomy-Feedback-#206]
when in space i select moon  but the launch button does nothing .
all i can do is go back to overworld  or space station

**Comment by MJRLegends** [comment]
I need the console log

**Comment by Doc-Savage99** [comment]
ok  full log ?    this is part after i click  


[short (2).txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/129340/short.2.txt)


full log 

[SA-log-doc.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/129341/SA-log-doc.txt)

**Comment by MJRLegends** [comment]
Have you added any mods to the mod pack? and have you tried it in a new world?

**Comment by Doc-Savage99** [comment]
no added mod packs, im playing online .  so i just tried single player world and works fine ,
so maybe its  problem server side

**Comment by MJRLegends** [comment]
What server is it?

**Comment by Doc-Savage99** [comment]
Frozen soul     space.frozensoul.co

**Comment by MJRLegends** [comment]
I will contact the server staff and see if I can get any information to help with this issue

**Comment by MJRLegends** [comment]
The server staff are looking into it and know its a issue

**Comment by Doc-Savage99** [comment]
Ok  thanks  for  looking into  it   :D   sorry  for troubling you
