### ISSUE TITLE
Crash when interacting with tesseracts or big reactor control rods

### ISSUE THREAD

**Issue by Random-Factor** [MJRLegends/Space-Astronomy-Feedback-#208]
Crash log: http://pastebin.com/X78DmZh6 (Changed to a pastebin link by MJRLegends)

**Comment by MJRLegends** [comment]
Try assigning more RAM to the launcher

**Comment by Random-Factor** [comment]
Upped it to 4.5G and it is working now

**Comment by MJRLegends** [comment]
Yeah it was running out of memory

**Comment by Random-Factor** [comment]
Not sure if memory is it at this point, worked for a bit then started crashing again. Upped it again and worked briefly before starting again. 
The end of the crash report says that there is an old version of RF API from railcraft, with the curse launcher is it likely that one mod didn't get updated?

**Comment by MJRLegends** [comment]
Were you holding something in your hand when trying to access their GUIDE?

**Comment by Random-Factor** [comment]
no crash when nothing in hand and crash with a tinkers tool in hand

**Comment by MJRLegends** [comment]
Seems its a mod bug, i would say its a issue with the tinkers mod

See https://github.com/erogenousbeef/BigReactors/issues/468
