### ISSUE TITLE
World wont load

### ISSUE THREAD

**Issue by Hunty910** [MJRLegends/Space-Astronomy-Feedback-#209]
My world isnt loading...

[crash-2016-02-17_12.24.03-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/134309/crash-2016-02-17_12.24.03-server.txt)

**Comment by Hunty910** [comment]
Its still the best pack I played

**Comment by MJRLegends** [comment]
Try assigning more RAM to the launcher

**Comment by Hunty910** [comment]
thanks so much
