### ISSUE TITLE
Can't jump and weird falling

### ISSUE THREAD

**Issue by piml38** [MJRLegends/Space-Astronomy-Feedback-#21]
I can't jump properly. Also falling seems a bit odd. Link to video: https://youtu.be/ySIFtS9slJc

**Comment by MJRLegends** [comment]
umm, i not sure why your getting this... Is your controls setup correctly and are you using anything/wearing any armor for a mod that could cause this?

**Comment by piml38** [comment]
Controls are unchanged, not wearing any sort of armor or galacticraft stuff

**Comment by piml38** [comment]
Update: can't play in that world, minecraft just closes without error message
