### ISSUE TITLE
ProjectRed Wires stay active

### ISSUE THREAD

**Issue by aiventimptner** [MJRLegends/Space-Astronomy-Feedback-#210]
I'm working on a ProjectRed controlled "door" that opens / closes with my mobile Computer. But the problem is, that if I pulse a signal through the wire it stays even active after the signal stopped.

1. Lever off, wire inactive
![Before giving signal](https://cloud.githubusercontent.com/assets/10517363/13154571/e7e2e996-d679-11e5-9c19-af61ccc0f98c.jpg)

2. Lever on, wire active
![Signal is active](https://cloud.githubusercontent.com/assets/10517363/13154574/e8183ad8-d679-11e5-9a1f-367aefbe895a.jpg)

3. Lever off, wire still active
![Signal should be off but wire stays active](https://cloud.githubusercontent.com/assets/10517363/13154573/e814676e-d679-11e5-89ec-8c3622f2d0f8.jpg)

4. Even after removing lever wire stays active
![Still active after removing signal source](https://cloud.githubusercontent.com/assets/10517363/13154572/e8120802-d679-11e5-8cdf-a8c20a5591fd.jpg)

**Comment by MJRLegends** [comment]
See https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/203
