### ISSUE TITLE
Unable to complete "Find Tier 1 dungeon and kill Skeleton Boss" quest

### ISSUE THREAD

**Issue by pielorz** [MJRLegends/Space-Astronomy-Feedback-#212]
I've found multiple T1 dungeons and killed quite a few Skeleton bosses, however the quest journal won't make it as completed. 

Might be an updated version of Galacticraft means that the Skeleton Boss I'd doesn't match the I'd in the quest? 

In the meantime is there any way to force complete a quest as admin? 

Thanks

**Comment by MJRLegends** [comment]
What version of the mod pack are you using

**Comment by pielorz** [comment]
1.3.7 because of the ProjectRed bug.

Sorry, I did actually remember after posting this that you might already had fixed this is 1.3.8. If so I apologise :)

**Comment by MJRLegends** [comment]
Yeah it's fixed in 1.3.8 but 1.3.9 will be out soon

**Comment by pielorz** [comment]
Brilliant, thanks I'll leave you in peace then :)
