### ISSUE TITLE
Going to the moon crashes the game.  Save game will not load.

### ISSUE THREAD

**Issue by jasmine2785** [MJRLegends/Space-Astronomy-Feedback-#213]
I went to the moon, and it crashed to desktop.  I have tried a reinstalling and using the same save file.  Still doesnt work.

Here is the crash log. 

http://paste.feed-the-beast.com/view/d8c7d2d3

Edit(By MJRLegends): Crash log: http://pastebin.com/1fFyfrzG

**Comment by MJRLegends** [comment]
Are you able to send me a copy of your world

**Comment by MJRLegends** [comment]
Please post here when you have a copy of the world and i will reopen the issue

**Comment by jasmine2785** [comment]
Sorry! didn't see your first responds! 

https://dl.dropboxusercontent.com/u/5852404/New%20World.7z

Hopefully my Dropbox works according to what it says

**Comment by MJRLegends** [comment]
I was unable to fix the issue so a new world is the only option i think. if the issue hasnt fixed it self by now
