### ISSUE TITLE
Metallurgic infuser bugged

### ISSUE THREAD

**Issue by xgamingpro70** [MJRLegends/Space-Astronomy-Feedback-#214]
![2016-02-22_08 47 53](https://cloud.githubusercontent.com/assets/17411081/13223443/6c303c8e-d941-11e5-8b1f-deecb770373d.png)

**Comment by xgamingpro70** [comment]
![2016-02-22_08 52 04](https://cloud.githubusercontent.com/assets/17411081/13223474/917a9408-d941-11e5-86ef-8af04b7b2f67.png)

**Comment by MJRLegends** [comment]
Right close your game and remove fastcraft and then start the game back up and try

**Comment by xgamingpro70** [comment]
launching it now withought the fastcraft

**Comment by MJRLegends** [comment]
Fastcraft fixed it
