### ISSUE TITLE
dont know what to call this

### ISSUE THREAD

**Issue by xgamingpro70** [MJRLegends/Space-Astronomy-Feedback-#215]
![2016-02-22_08 28 19](https://cloud.githubusercontent.com/assets/17411081/13225416/03a84fa4-d94a-11e5-8e7c-74003fad14f6.png)
![2016-02-22_08 28 42](https://cloud.githubusercontent.com/assets/17411081/13225418/03adbb9c-d94a-11e5-8063-639641abb5a7.png)
![2016-02-22_08 28 49](https://cloud.githubusercontent.com/assets/17411081/13225417/03a98b80-d94a-11e5-90e0-22b0b8a3062c.png)
![2016-02-22_09 50 56](https://cloud.githubusercontent.com/assets/17411081/13225419/03ae2654-d94a-11e5-8b70-61f313f3a996.png)
![2016-02-22_08 28 17](https://cloud.githubusercontent.com/assets/17411081/13225421/049af57e-d94a-11e5-872e-0fe9b5692b70.png)

**Comment by MJRLegends** [comment]
Try updating your graphics drivers

**Comment by xgamingpro70** [comment]
i would if i could figure out how haha

**Comment by xgamingpro70** [comment]
fixed by updating drivers forcefully
