### ISSUE TITLE
Crash upon creating world interaction upgrade schematic in cyclic assembler

### ISSUE THREAD

**Issue by dartzmaster** [MJRLegends/Space-Astronomy-Feedback-#216]
As statet in the title i wanted to set a schematic to automatically craft wiu in an thermal foundation cyclic assembler, and as soon as i click the green checkmark my game crashes, tryied it twice, both same result, heres the crash report: http://pastebin.com/6PWwpQLk

**Comment by MJRLegends** [comment]
I will report this at some point to the mod devs when i have the time :P

**Comment by MJRLegends** [comment]
I will wait on reporting this issue because will will wait to see if it fixes it in the next update for the mod pack because it will include new mods for the cofh team's mods

**Comment by MJRLegends** [comment]
@dartzmaster can you test with v1.4.0 and let me know if its still broken, if so i will report it to the mod devs

**Comment by dartzmaster** [comment]
works now. :)

**Comment by MJRLegends** [comment]
Good to hear :P
