### ISSUE TITLE
Can't make Power Armor Tinker Table

### ISSUE THREAD

**Issue by aliatic** [MJRLegends/Space-Astronomy-Feedback-#22]
Have found that there's no recipe for the Power Armor Tinker Table. NEI doesn't show anything. I tried making it according to the recipe on the FTB wiki, and that doesn't work either.
Is there some other way to make it, to complete the quest?

**Comment by MJRLegends** [comment]
The recipes are showing for me? https://gyazo.com/97b5c23052fcac19431b92482e6f4dd7

**Comment by aliatic** [comment]
Not for me. 
Have re-logged a few times to try again. I'm using the latest pack update.

**Comment by MJRLegends** [comment]
Im not sure...

**Comment by MJRLegends** [comment]
Any luck with getting it working?

**Comment by aliatic** [comment]
Nope. 
In fact none of the MachineMuse items show a recipe when I click on them in NEI.
I don't know enough about mods etc to fiddle with anything config-wise.

**Comment by MJRLegends** [comment]
Try reinstalling the mod pack please

**Comment by MJRLegends** [comment]
did this fix it?
