### ISSUE TITLE
Cant figure out how to update the pack

### ISSUE THREAD

**Issue by xgamingpro70** [MJRLegends/Space-Astronomy-Feedback-#220]
I just cant figure out how to update the pack do i need to put the pack code back in for the new version?

**Comment by MJRLegends** [comment]
One can you stop creating 1000 issues that are all the same thing (your graphics card) and two you need to restart the launcher and click launch

**Comment by xgamingpro70** [comment]
i did but it didnt update

**Comment by MJRLegends** [comment]
Is the version set to recommended?

**Comment by xgamingpro70** [comment]
yes sir

**Comment by MJRLegends** [comment]
on the drop down box is there 1.3.9?

**Comment by xgamingpro70** [comment]
nope
not that it shows

**Comment by MJRLegends** [comment]
YOU NEED TO CLOSE THE LAUNCHER COMPLETELY AND RESTART IT!

**Comment by xgamingpro70** [comment]
............... thought i tried that sorry for the inconvenience

**Comment by MJRLegends** [comment]
Please stop posting issues before doing obvious solutions and if they are the same graphics issues because we know why thats happening...
