### ISSUE TITLE
having problems connecting to the official server

### ISSUE THREAD

**Issue by eekerbeeker11** [MJRLegends/Space-Astronomy-Feedback-#222]
i did have a numeric ip that did work with a port different than the default one for minecraft 25565 and this update deleted that now i cant connect since steam deleted the message i got that ip in

**Comment by MJRLegends** [comment]
What mod pack version you using?

**Comment by eekerbeeker11** [comment]
I fixed it it took changing a DNS server setting on my laptop now it recognises the server

**Comment by MJRLegends** [comment]
Ok
