### ISSUE TITLE
safari net/golden lasso not able to place mob back

### ISSUE THREAD

**Issue by dartzmaster** [MJRLegends/Space-Astronomy-Feedback-#223]
Was messing with those two to transport some mobs, but as soon as i wanted to place the mobs back into the world the net/lasso goes empty but theres no mob. Only had this issue on the official server, sp works fine.

**Comment by MJRLegends** [comment]
Its because theres a limit on the entities

**Comment by dartzmaster** [comment]
Like... per chunk or overall or???
Am 25.02.2016 12:28 vorm. schrieb "MJRLegends" <notifications@github.com>:
