### ISSUE TITLE
NEI not working

### ISSUE THREAD

**Issue by Balefire9** [MJRLegends/Space-Astronomy-Feedback-#225]
When you open inventory no NEI shows up, also when you get into the crafting table no NEI. There is no option in the bottom left to see if its just not on. This only happened after the update so it may be a result of the update and something just getting tweaked funny. Just wanted you to know.

**Comment by MJRLegends** [comment]
Try pressing O when in your inventory or crafting table inventory

**Comment by MJRLegends** [comment]
Did this fix the problem?

**Comment by Balefire9** [comment]
Yes thank u so much :)
