### ISSUE TITLE
same server errors 

### ISSUE THREAD

**Issue by xgamingpro70** [MJRLegends/Space-Astronomy-Feedback-#227]
i am still getting the same server error after re installing and restarting client 
![image](https://cloud.githubusercontent.com/assets/17411081/13359231/46d3e45e-dc70-11e5-9c68-6e05c086caef.png)

**Comment by MJRLegends** [comment]
Stop posting issues ffs

**Comment by xgamingpro70** [comment]
its an actuall issue ffs

**Comment by xgamingpro70** [comment]
an issue is when something does not work for EIGHT HOURS and this has not
