### ISSUE TITLE
server not letting me join

### ISSUE THREAD

**Issue by Entersandman133** [MJRLegends/Space-Astronomy-Feedback-#229]
hello i am new to the server and the server is giving me an error saying 
java.net.ConnectException: Connection refused: no further information:

if you can explain what is wrong and how to fix it please and thank you

**Comment by JTuck20** [comment]
This has also been happening to me since last night at 9:30pm (CST).

**Comment by Entersandman133** [comment]
see its a real issue :P

**Comment by Spellkaze** [comment]
See the closed issues, mjr and the host company are working on the server since there were network issues, and yes, since yesterday they have been doing that

**Comment by Entersandman133** [comment]
how do you check the closed issues they just seem to dissaper on my screen

**Comment by JTuck20** [comment]
I was just posting mine for a timeline. I was on when the "restart" occurred and it stopped working since then.

**Comment by Entersandman133** [comment]
so was i this is my main account im "Xgamingpro" and no one told me there was a way to view closed issues if i knew i would not have posted the issue twice and mjr muted me so i could not check anything anymore so i decided to get on my main even though it was a REAL ISSUE and he never told me to check the closed things

**Comment by MJRLegends** [comment]
Server is online
