### ISSUE TITLE
Crash While Loading 

### ISSUE THREAD

**Issue by jdadams77** [MJRLegends/Space-Astronomy-Feedback-#23]
When loading game from curse a error occurs that causes the game to crash during pre-initialization. It seems to be an error with open computers mod. next to it in the error log it says uhe and the version installed. I went to the mod creators website and replaced the mod with different versions of the mod but the same result occurred. Finally I deleted it from the mod pack all together and everything loaded fine. My question is how important is open computers to the mod pack and if it is needed how can I fix this problem. Thanks

**Comment by MJRLegends** [comment]
This is a curse launcher bug. see the know issues section here #1
