### ISSUE TITLE
Space

### ISSUE THREAD

**Issue by JTuck20** [MJRLegends/Space-Astronomy-Feedback-#231]
As I was flying in my rocket towards space I suddenly just fell out and fell back down to earth. My spaceship is gone too. 
Any reason this would have happened? 
And any chance I can get a tier 1 rocket refunded?

**Comment by MJRLegends** [comment]
Yeah sure just let me know when your next on the server

**Comment by JTuck20** [comment]
I'm getting on right now if you're on/available. 

Thank you very much
