### ISSUE TITLE
[Bug] Can't get Brine(Fluid) stored before update from Fluid Storages Cells (partitioned)

### ISSUE THREAD

**Issue by Spellkaze** [MJRLegends/Space-Astronomy-Feedback-#236]
As i said while you were in the server. I can't get brine (liquid) from the storage cells, making another cell for storage will import new brine and will show in the fluid terminal as the same place the brine made before is.

I can see that all the brine made before the update can't be get in any way, the cell will show that is full, but the brine can't get extracted from buckets or tanks or anything
![2016-03-09_19 56 39](https://cloud.githubusercontent.com/assets/10790732/13655981/3bc8873e-e631-11e5-8998-ef5066bfea12.png)

16kB is the cap a 64k Storage cell can store, so that entire brine cell is useless (and that brine is really needed in mekanism), please check it out when you can.

(This have happened in single player and multiplayer, maybe an id conflict with fluids? really don't know)

**Comment by MJRLegends** [comment]
Broken Drive: <extracells:storage.fluid:3>.withTag({filter: [{Slot: 0 as byte, id: 5240 as short, Count: 1 as byte, Damage: 62 as short}], "Fluid#0": {FluidName: "brine", Amount: 16384000}, fuzzyMode: "IGNORE_ALL"})

Working/New Drive(Without partitions): <extracells:storage.fluid:3>.withTag({filter: [], "Fluid#0": {FluidName: "brine", Amount: 21824}, fuzzyMode: "IGNORE_ALL"})

Working/New Drive(With partitions): <extracells:storage.fluid:3>.withTag({filter: [{Slot: 0 as byte, id: 5240 as short, Count: 1 as byte, Damage: 65 as short}], "Fluid#0": {FluidName: "brine", Amount: 15958625}, fuzzyMode: "IGNORE_ALL"})

Damage seems to be different so i think the meta data was changed for the liquid version

**Comment by MJRLegends** [comment]
Broken Drive: <extracells:storage.fluid:3>.withTag({filter: [{Slot: 0 as byte, id: 5240 as short, Count: 1 as byte, Damage: 62 as short}], "Fluid#0": {FluidName: "brine", Amount: 16384000}, fuzzyMode: "IGNORE_ALL"})

Working/New Drive(Without partitions): <extracells:storage.fluid:3>.withTag({filter: [], "Fluid#0": {FluidName: "brine", Amount: 21824}, fuzzyMode: "IGNORE_ALL"})

Broken Drive Drive(With new partitions set in updated version): <extracells:storage.fluid:3>.withTag({filter: [{Slot: 0 as byte, id: 5240 as short, Count: 1 as byte, Damage: 65 as short}], "Fluid#0": {FluidName: "brine", Amount: 15958625}, fuzzyMode: "IGNORE_ALL"})

Damage seems to be different so i think the meta data was changed for the liquid version

**Comment by MJRLegends** [comment]
I will do more testing to why the meta data has changed... might be from the Mekanism dev changing it or adding a new mod to the mod pack changed it
