### ISSUE TITLE
Can't break any blocks.

### ISSUE THREAD

**Issue by littlelobsterG** [MJRLegends/Space-Astronomy-Feedback-#237]
So i just started and I wanted to get some iron and made a osmium pick but i couldn't break anything not even in creative i couldn't even do any program.

**Comment by MJRLegends** [comment]
This isnt enough detail to even know what the problem is

**Comment by littlelobsterG** [comment]
I found the source of the problem. Turns out anothe mod was interfiering with the button one or left mouse button so I just changed it to another button.
