### ISSUE TITLE
[Bug] Mobius "Unstable/Stable" Ingot Crafting & and more

### ISSUE THREAD

**Issue by Spellkaze** [MJRLegends/Space-Astronomy-Feedback-#238]
Extra utilities have 2 sigils for making the unstable ingots. the Division sigil make unstable ingots that explodes within 10 seconds a limited times and can only be crafted on vanilla crafting tables. the Pseudo-Inversion Sigil (which is a bit hard to obtain) can make Mobius "Unstable/Stable" Ingot, which is like a unstable ingot that never explodes, have 2 extra recipes that are not shown in NEI (Kikoku and Super Builder Wand) and can be used in any crafting table from any mod unlimited times.

The are a few problems:
**Division sigil can be used in any table**
it does not matter if its from tinker o AE, you can use the division sigil in any table, i don't think it is intended to do that
**Inactive division sigils are usable**
As far as i know, division sigils can't be used inactive, but in this modpack that is possible for some reason (the inactive sigil is consumed in the process tho)
**Pseudo-Inversion Sigil craft normal unstable ingots**
As the title says, they craft unstable ingots that explodes, which are the normal ones and can not be used to craft the super builder wand or the kikoku that requires the mobius ingot (using creative for the mobius ingots shows that the recipes for this items work)

That are all the issues i have found, sorry for any grammar mistake that i probably made, please check them when you have time.
![2016-03-09_21 14 55](https://cloud.githubusercontent.com/assets/10790732/13657448/54d96e30-e63d-11e5-9cae-43ef8934a469.png)

**Comment by MJRLegends** [comment]
I will get around to fixing this soon, for the offical server and then will be included in the next mod pack update :P
