### ISSUE TITLE
Resevoir

### ISSUE THREAD

**Issue by electricgolfer2** [MJRLegends/Space-Astronomy-Feedback-#239]
Hi electric here, I cannot craft a resevoir because of a unknown bug (Yes im using fuzed glass and not quite clear glass) and when i put 4 fuzed glass 4 glass and 1 cauldron it WILL NOT make a resevoir. If there is a specific reason for this PLEASE let me know, My O2 supply depends on it!

**Comment by MJRLegends** [comment]
Is that the recipe that shows in NEI?

**Comment by Spellkaze** [comment]
I can craft it, i also showed him yesterday how to craft it and he could do it, the recipe only needs 2 fused glass, not 4

**Comment by electricgolfer2** [comment]
Yeah Spellkaze showed me but i was trying to craft from the NEI guide

**Comment by MJRLegends** [comment]
So the recipe is fine?
