### ISSUE TITLE
Game Crash in Main menu

### ISSUE THREAD

**Issue by TheMrTomatoMan** [MJRLegends/Space-Astronomy-Feedback-#24]
my game crash in main menu if i press anywhere with the crashreport http://pastebin.com/R3hzn10k

**Comment by MJRLegends** [comment]
I dont really know the cause of this crash? is it doing it every time you load the game?

**Comment by TheMrTomatoMan** [comment]
yes i start it it loads and crash

**Comment by MJRLegends** [comment]
Which launcher are you using? and which java version?

**Comment by TheMrTomatoMan** [comment]
java 8 and curse

**Comment by MJRLegends** [comment]
Try reinstall the mod pack, and does it do it on any other mod pack?

**Comment by TheMrTomatoMan** [comment]
Ok after reinstall it works now :) Thanks

**Comment by MJRLegends** [comment]
No problem
