### ISSUE TITLE
Not able to connect to servers

### ISSUE THREAD

**Issue by ninjahjp06** [MJRLegends/Space-Astronomy-Feedback-#240]
Whenever I try to join a server "Internal Exception: java.lang.RuntimeException: No OpenGL context found in the current thread" comes up. Single player works fine, but I don't know what's wrong with multiplayer.

**Comment by Spellkaze** [comment]
Hosting issues, Mjr is aware of it. https://twitter.com/mjrlegends/status/709070174624808961

**Comment by MJRLegends** [comment]
No he's error is because the servers he's trying to join is running a older version of the mod pack
