### ISSUE TITLE
Cant see recipes anything from PowerSuit mod

### ISSUE THREAD

**Issue by Andrene** [MJRLegends/Space-Astronomy-Feedback-#242]
As the title says. NEI isn't showing any of the recipes. Attempted to reinstall modpack, didn't fix it.

**Comment by MJRLegends** [comment]
They are for me? have you added or removed any mods and what item were you looking up....

**Comment by Andrene** [comment]
I have not added any mods, nor have i removed any, and by I can see the recipes, i mean i hit R on the item it doesnt show a recipe. I also have tried clicking on it( common way for me to see the recipe)

**Comment by MJRLegends** [comment]
Is it the same thing for you in v1.4.1 update of the mod pack

**Comment by MJRLegends** [comment]
@Andrene is there any news on this issue??

**Comment by Andrene** [comment]
After updating there is no change, but on a different computer the recipes work.

**Comment by MJRLegends** [comment]
Well if it works on another computer then its a problem on your side, Maybe try update your java, delete all mod pack files and reinstall it all....
