### ISSUE TITLE
Undergarden Biome generating in the Overworld

### ISSUE THREAD

**Issue by EchoingZen** [MJRLegends/Space-Astronomy-Feedback-#244]
The Undergarden (ID 113) biome is generating in the Overworld.  This is a nether biome.

**Steps to reproduce:**
* Create a new world
* In creative mode, give yourself a biome detector and a biome essence attuned to Undergarden.  You can give yourself the essence with the following command: "/give @p BiomesOPlenty:biomeEssence 1 0 {biomeID:113}"
* Travel in the direction indicated until you find the Undergarden.

This was done with a fresh 1.4.0 install of the modpack.

**Example**
World type: BIOMESOP
Seed: -3845537013705728942
X: 6851 Z:-3507

**Comment by MJRLegends** [comment]
Yeah seems to be a known bug for BOP mod see https://github.com/Glitchfiend/BiomesOPlenty/issues/484 but doesnt look like it was ever fixed....
