### ISSUE TITLE
No mars dungeon treasure room.

### ISSUE THREAD

**Issue by littlelobsterG** [MJRLegends/Space-Astronomy-Feedback-#245]
I was on the quest line "Exploring the universe" trying to get a tier 3 rocket but when i found the dungeon and killed the creeper boss i could not find a treasure room. even mined around the boss room and went in to creative to spawn a tier 2 chest but neither worked i don't know what to do.

**Comment by MJRLegends** [comment]
Try find another dungeon because they sometimes not generate correctly

**Comment by littlelobsterG** [comment]
I managed to find another dungeon and after siting in the corner and punching the tnt back and fourth I didn't even get the tier 3 rocket blue print.( I'm going to spawn it in but I just wanted to complain to someone)0

**Comment by MJRLegends** [comment]
There should be a issue with the dungeons, you should find the boss room then kill the boss, the boss will then drop a key which you go to a room containing the treasure chest which you use the key to unlock the chest and your will have loot and a schematic...

**Comment by littlelobsterG** [comment]
Yes but I got a different schematic

**Comment by MJRLegends** [comment]
Which planet you on?

**Comment by littlelobsterG** [comment]
I was on mars but I progressed and am on Mercury right now

**Comment by MJRLegends** [comment]
Yeah on mars with can get the tier 4 one and the tier 3 one due to the way more planets mod is setup
