### ISSUE TITLE
Quarry causing constant crashes

### ISSUE THREAD

**Issue by MrSilentPhoenix** [MJRLegends/Space-Astronomy-Feedback-#246]
so after checking closed issues and trying to solve it myself, the issue persists and is repeatable.
i've removed chickenhunk mod before and atfer placing the quarry, i've tried breaking the chunk loader before placing the quarry. i'm not sure what i could do to resolve the problem.

**Comment by MJRLegends** [comment]
I need the crash logs?

**Comment by MJRLegends** [comment]
@MrSilentPhoenix 
Any news on this?? if not please can you provide the crash logs

**Comment by MJRLegends** [comment]
I will reopen if you ever post the crash logs!
