### ISSUE TITLE
Black screen on Mercury.

### ISSUE THREAD

**Issue by littlelobsterG** [MJRLegends/Space-Astronomy-Feedback-#248]
Went to Mercury and got a black screen tried re logging and going to the specter dimension but neither worked. Don't know what to do.

**Comment by MJRLegends** [comment]
I cant reproduce this problem with just that small amount of information

**Comment by XenosTiger** [comment]
It seems to be altitude based- I've noticed it on Sirius B as well. Drop below ~Y:65 on Sirius B, and you can see things. Go above that level, and everything goes black again. Don't know if the same is true for Mercury. 
Just throwing in a bit of additional information, I hope it helps.

**Comment by MJRLegends** [comment]
Have you got night vision?

**Comment by littlelobsterG** [comment]
I have night vision on my amour

**Comment by MJRLegends** [comment]
Thats why then, because its a known issue with galacticraft
