### ISSUE TITLE
Crash when using Gravity Boots

### ISSUE THREAD

**Issue by kamyflouge** [MJRLegends/Space-Astronomy-Feedback-#249]
i was testing the pack .i was in survival mode but had enabled cheats in nei i traveled to pluto with tier 8 rocket creative.then cheated myself gravity boots and got this crash [http://pastebin.com/fax1rshv](http://pastebin.com/fax1rshv)

**Comment by MJRLegends** [comment]
Seems to be a more planet probably, might be fixed soon
