### ISSUE TITLE
parachue always deployed 

### ISSUE THREAD

**Issue by Lucidcream** [MJRLegends/Space-Astronomy-Feedback-#25]
When I crafted the parachute Everything was fine until I put it on. Even if I just fell one block I would hear the parachute sound play. When I pressed F5 I couldn't see the parachute. restarting the game didn't work and when I jumped off a ledge I was still taking damage but was falling slowly. Pease help I can't jump because the parachute forces me down when I jump.

**Comment by MJRLegends** [comment]
Which parachute are we talking about here?

**Comment by Lucidcream** [comment]
The galacticcraft parachute, it leaks to other worlds but it seems to fix after entering another dimension

**Comment by MJRLegends** [comment]
Im not sure this must be a galacticraft bug so maybe report it to them
