### ISSUE TITLE
Blutonium

### ISSUE THREAD

**Issue by aiventimptner** [MJRLegends/Space-Astronomy-Feedback-#251]
In generell Blutonium from Big Reactors are working the same way as yellorium to "feed" your reactor. But for me it doesn't working. The reactor only uses yellorium as fuel source. Is that intended to not work?

**Comment by MJRLegends** [comment]
Seems to work fine for me? what mod pack version you running? and you sure its Blutonium not cyanite? also are you able to show me some pictures of the access port that the Blutonium is in and a picture of the reactor controller? or a video showing it?

**Comment by aiventimptner** [comment]
Well found my mistake. Blutonium just works fine. I forgot to empty out the Access Port so there can't be pulled Blutonium. DERP.

**Comment by MJRLegends** [comment]
It's fine
