### ISSUE TITLE
Formally Requesting Monthly Nether Resets.

### ISSUE THREAD

**Issue by XenosTiger** [MJRLegends/Space-Astronomy-Feedback-#253]
I seem to be having an extreme issue with finding anything in the Nether. I went there in search of two simple materials- Glowstone and Quartz. After spending an hour searching, I came up with no glowstone, and about ten pieces of nether quartz. The Nether has a ridiculous number of claims in it, and I haven't found a single Glowstone deposit. 

Perhaps doing as other servers do, and resetting the nether on the tenth of every month would work?

Also, that could also be done on other heavily-visited dimensions (Except the Overworld, and other dimensions that are heavily built-on).

Just a suggestion, it's up to you whether or not you follow through with it.

**Comment by MJRLegends** [comment]
Yeah i am thinking about this because im trying to work it all out and try and find a good way to do it

**Comment by XenosTiger** [comment]
If all else fails, you could periodically drop the server and manually delete the nether file- which would cause the server to regenerate it on its own.

**Comment by MJRLegends** [comment]
I know
