### ISSUE TITLE
OpenComputers Tapes not Working + Nutrient Distillation not Craftable (1.4.0)

### ISSUE THREAD

**Issue by ProxyPlayerHD** [MJRLegends/Space-Astronomy-Feedback-#254]
i didn't saw any of theses in the Changelog.
so, the Nutrient Distillation Liquid is Uncraftable for everyone i know who plays the pack.
also Tapes won't play sound. a Friend and I Tried it Multiple Times with Different songs and Tapes.

a Tape Drive next to a Speaker and a Downloaded Song from YT on it, it just Gives a Error Code whenever i press the Play Button.
`[17:50:13] [Thread-36/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:131]: Error in class 'SourceLWJGL OpenAL'`

`[17:50:13] [Thread-36/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:132]:     Invalid name parameter.`

i Tested both Things in Multiplayer and in SinglePlayer. both with teh Same Results.
i'm sorry if this got already fixed. just want my Killer Joe and Music.

**Comment by MJRLegends** [comment]
For the Nutrient Distillation not Craftable issue see https://github.com/SleepyTrousers/EnderIO/issues/3212 im going to downgrade the version of the mod in the next update

**Comment by MJRLegends** [comment]
@ProxyPlayerHD are you testing the taps on single player or multilayer or both?

**Comment by ProxyPlayerHD** [comment]
SP and MP. (even says that in the Post. "i Tested both Things in Multiplayer and in SinglePlayer. both with the Same Results.")

and as far as i know, it's eitherway from some other Mods or the Sound card of me AND my Friend.

**Comment by MJRLegends** [comment]
@ProxyPlayerHD yeah i cant read then as i missed that part and yeah i think its a computronics problem as there from there

**Comment by Spellkaze** [comment]
This is a known  issue with Computronics, it usually appears in modpacks asiekierka/Computronics/issues/166. Apparently due to many mods the sound system ran out of memory. I just leave this here in case is helpful for anyone with the same error.

(I know this because it have happened to me in this and other modpacks)

**Comment by MJRLegends** [comment]
@Spellkaze yeah thats what i found then i looked at this problem :P
