### ISSUE TITLE
"entity.soul.name soul aspect" drops from cows

### ISSUE THREAD

**Issue by EchoingZen** [MJRLegends/Space-Astronomy-Feedback-#255]
I'm not familiar with the Practicalities mod so I'm not sure how this is dropping.

**Comment by MJRLegends** [comment]
what weapon/tool/item was you using to kill the cow?

**Comment by EchoingZen** [comment]
I believe is was with a King Slime Cleaver but I'm not sure.  I'll continue to test what tool is causing that.

**Comment by MJRLegends** [comment]
Yeah from what i can see its a Practicalities mod bug which i dont think i can do much about
