### ISSUE TITLE
Mod Request

### ISSUE THREAD

**Issue by aiventimptner** [MJRLegends/Space-Astronomy-Feedback-#256]
Will there Wireless Redstone by Chicken Bones added?

**Comment by MJRLegends** [comment]
Probably not since we already have a wireless redstone mod in the mod pack

**Comment by aiventimptner** [comment]
Okay. It would be nice to have it because Chicken Bones Wireless Redstone is more complex. (Items like Sniffer). But I think Wirelss Redstone will do it as well.

**Comment by MJRLegends** [comment]
Maybe i will think about it
