### ISSUE TITLE
Automapping all causes the game to crash (version 1.4.2)

### ISSUE THREAD

**Issue by dragonfly19981** [MJRLegends/Space-Astronomy-Feedback-#261]
http://pastebin.com/SZbJH8Rm

How to replicate: Create a new world. Open Journeymap menu. Click options then automapping . click all.

**Comment by MJRLegends** [comment]
Did it work fine in v1.4.1?

**Comment by dragonfly19981** [comment]
Yes it worked fine before I updated it.

Also it happens when trying to automap missing

**Comment by MJRLegends** [comment]
Yeah works fine for me in v1.4.2 but i think the updated of fast craft doesnt like your computer so im downgrading it in v1.4.3 anyways as theres a server side isssue with the v1.4.2 so v1.4.3 will be out soon

**Comment by MJRLegends** [comment]
@dragonfly19981 can you test in v1.4.3 please

**Comment by MJRLegends** [comment]
I will reopen this issue if a reply is made
