### ISSUE TITLE
Crash when open NASA Workbench GUI

### ISSUE THREAD

**Issue by aiventimptner** [MJRLegends/Space-Astronomy-Feedback-#262]
I'm using the DimensionChanger from Aroma's World Mod to "travel" back from different dimensions to Overworld. Now when I open at anytime NASA Workbench GUI Minecraft crashes. After restarting Space Astronomy I can open NASA Workbench as normal.

**Comment by MJRLegends** [comment]
Crash log???

**Comment by aiventimptner** [comment]
[crash-2016-04-08_20.38.57-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/210672/crash-2016-04-08_20.38.57-client.txt)

**Comment by MJRLegends** [comment]
Please user pastebin.com to post crash logs

**Comment by aiventimptner** [comment]
https://pastebin.com/7t3zUVPA

**Comment by MJRLegends** [comment]
Does it happen if you try and reproduce the problem

**Comment by aiventimptner** [comment]
Yes can reproduce it as often as i want.

**Comment by MJRLegends** [comment]
Does it happen if you do it with a empty hand

**Comment by aiventimptner** [comment]
Yes

**Comment by MJRLegends** [comment]
Ok does it do it even time you try and open the gui

**Comment by aiventimptner** [comment]
Well it only crashes the first time I try to open the gui after using the DimensionChanger. After restarting FTB i can open the gui without any problems. Anyway it doesn't matter how long i wait after using DimensionChanger.

**Comment by MJRLegends** [comment]
Do if you start up the game again and right click it with your hand does it crash?

**Comment by aiventimptner** [comment]
Okay if I understood you right I used Dimension Changer to go back to Overworld and then quit game and restarted it. After finished loading I tried to open the gui.

:arrow_right: Game did not crash.

I'm always using my empty hand to open the gui.

**Comment by MJRLegends** [comment]
So when you go in to your world and use the Dimension Changer to change worlds then you open the gui with a empty hand it crashes?

**Comment by aiventimptner** [comment]
Right! 
I'm at the Moon for example and then I charge the Dimension Changer to teleport back to Overworld. After Teleportation next to my Bed in my Overworld Base I go to the NASA Workbench. Now when I try to open the NASA Workbench gui with my empty hand it crashes.

**Comment by MJRLegends** [comment]
Thats so weird haha

**Comment by aiventimptner** [comment]
Can you reproduce it?

**Comment by MJRLegends** [comment]
i will test later on and get back to you

**Comment by aiventimptner** [comment]
Okay. It's not THAT annoying. :wink:

**Comment by aiventimptner** [comment]
I discovered today that it's not the Dimension Changer ... It crashes when I'm just teleported back to Overworld. Crash can be reproduced with Telepads, Dimension Changer or Enhanced Portals. If I exit the world (not quitting the game) and reconnect then it won't crash. (I play on my privat server.)

**Comment by MJRLegends** [comment]
Ok can you create a new world and try to reproduce it there

**Comment by MJRLegends** [comment]
@aiventimptner ?

**Comment by aiventimptner** [comment]
I can't reproduce it in a new world. Maybe its my world or the server?

**Comment by MJRLegends** [comment]
Idk then if you cant reproduce it im not sure

**Comment by MJRLegends** [comment]
Can you sent me a copy of the world
