### ISSUE TITLE
Server Files

### ISSUE THREAD

**Issue by ChrisMott97** [MJRLegends/Space-Astronomy-Feedback-#265]
Tried to download server files for 1.4.3, they appear to be the same as 1.4.1 ?
EDIT: It seems to go to the 1.4.3 URL but the actual files are the same

**Comment by MJRLegends** [comment]
There fine for me? did you restart your launcher?

**Comment by ChrisMott97** [comment]
Ah, I've just tried again, it works now! - can't have been a launcher issue because it still sent me to http://ftb.cursecdn.com/FTB2/privatepacks/SpaceAstronomy/1_4_3/SpaceAstronomyServer.zip originally - but regardless, it works now, thanks
