### ISSUE TITLE
Quest Book wont open

### ISSUE THREAD

**Issue by Thornstromb** [MJRLegends/Space-Astronomy-Feedback-#266]
after updating from 1.4.1 to 1.4.3 (and the server doing the same, but for some reason im the only one affected by this!) through Curse, trying to open the quest book results in.... NOTHING, except THIS series of logger messages:

https://gist.github.com/Thornstromb/889a83da7fc63bfdb83060fea29d8b91 (sorry for not remembering pastebins earlier)

NOTE: game does not crash, no other errors detected, just this whenever i try to open the quest book. ingame, absolutely nothing happens. no use animation plays, the book just sits there in hand while i press right click.

EDIT: have been looking around for this extremely elusive error (which i got before trying to play Mage Quest), found a related error inherent to the HQM mod that causes the player.dat to swell over 500kb and be unreadable. THIS IS NOT THAT ERROR, server host reports all current player files around 4kb.

EDIT2: and Edit Mode is NOT on on either side. getting really pissed that that issue keeps clogging up my search.

**Comment by MJRLegends** [comment]
I need both client and server logs, use www.pastebin.com to post them

**Comment by MJRLegends** [comment]
Welcome to the HQM mod bugs.. i think you will have to delete/reset your hqm player data

**Comment by Thornstromb** [comment]
Item One: having perused the server log, there are no entries that pop up during the several times i tried to open the book. no serverside errors.
Item 2: we are launching server now with the quest data reset, will leave another message about the results.

**Comment by MJRLegends** [comment]
@Thornstromb ok let me know how it goes

**Comment by Thornstromb** [comment]
ANSWER: NO CHANGE. freshly regenerated questing mode does NADA

**Comment by MJRLegends** [comment]
What files did you delete?

**Comment by Thornstromb** [comment]
serverside deleted the entire "HardcoreQuesting" folder in the server world. then re-enabled quest mode with ingame command
also, i CAN acsess the book just fine in singleplayer

**Comment by MJRLegends** [comment]
Can you send me a copy of your server log and client log

**Comment by Thornstromb** [comment]
sigh one sec

**Comment by Thornstromb** [comment]
Clientside full FML here
https://gist.github.com/Thornstromb/a25df989c3939fc515a9b880cd7a9cde

**Comment by Thornstromb** [comment]
NEW INFORMATION: upon running a copy of my friends (server-hosts) MC folder, the problem has vanished. im assuming this means the problem is in the configs somehow

**Comment by MJRLegends** [comment]
Since you have added/changed mods this problem could be due to your changes that you have made because i haven't heard of this issues before

**Comment by Thornstromb** [comment]
unfortunately it cant really be because of the mods, as noone else is getting this issue on the server. apparently i also had config errors somehow...

**Comment by MJRLegends** [comment]
Just reinstall the mod pack and it should be fixed
