### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by Grim3Is** [MJRLegends/Space-Astronomy-Feedback-#267]
Hi i cant conect to the server at all!
Everytime i try to log in i get the error message:
Connection Lost:
Mod Rejections[FMLMod:extracells{2.3.9}, .... 
after that i get kicked back to the Multiplayer Screen

Im running on Version 1.4.3 at the Curse Launcher tho. And cant find any hint on how to fix that on the forum.

Any advice?

**Comment by MJRLegends** [comment]
are you 100% sure says on the main menu v1.4.3? if so reinstall the mod pack

**Comment by Grim3Is** [comment]
Server is space.mjrlegends.com
Its definitively 1.4.3
AND .... i can neither connect to space.modrealms.net nor play.devcoftb.net       but here i get OpenGL errors (singleplayer works fine tho ... )

Reinstalling doesnt solve the problem either. Im playing singleplayer atm.
Dont know whats causing the problem. (seems to be a problem with some items from AE2 but .... i dont know) 
As it seems im the only one with this problem, so maybe its on my side ... not on yours.
Thanks for your reply tho!
*Thumbs up* (Also for the pack, its fun!)

**Comment by MJRLegends** [comment]
How weird... so are you still getting the "Mod Rejections[FMLMod:extracells{2.3.9}, .... " issue or just the open gl error

**Comment by MJRLegends** [comment]
@Grim3Is ?
