### ISSUE TITLE
Crash on loading save - seems to be IE related?

### ISSUE THREAD

**Issue by snickering** [MJRLegends/Space-Astronomy-Feedback-#269]
My save game is crashing on load. The log file is below. The other day I tried removing Immersive Engineering and was able to load it successfully. I did try to reproduce the crash by adding IE object back into my mining world/overworld, but was not able to. The next day my save loaded fine. Yesterday I am back to getting the game crash on world load. 

Since my power infrastructure in early game is waterwheels, it is quite the task to rebuild all of that along with power lines, blast furnaces, etc. Not sure what a good workaround is unless it is 'don't use IE'

(I did try to look at open issues, but this one wasn't specifically mentioned. Just chicken chunks chunk loaders. They only chunk loader in my world is the quarry in the mining world. Which was fine until I added IE power)

Crash log: http://pastebin.com/r9zZengk (Changed by MJRLegends to pastebin link)

**Comment by MJRLegends** [comment]
Sorry for the delay i will take a look at this issues as soon as i can

**Comment by snickering** [comment]
As a side note, upon further testing, I do NOT get the crash on load when using the prior version of IE. Version 1.7.4 does not crash when loading the save game created with version 1.7.5. Hope this helps!


________________________________

**Comment by MJRLegends** [comment]
@snickering sorry for the slow reply been busy with personal stuff, but this is probably a mod bug and i will have a look at what i can do for v1.4.4 of the mod pack to fix it
.

**Comment by MJRLegends** [comment]
@snickering please retest with v1.4.5

**Comment by MJRLegends** [comment]
i will reopen if it still happens @snickering
