### ISSUE TITLE
Quest: Starting Tinker's Construct

### ISSUE THREAD

**Issue by BillyPepper** [MJRLegends/Space-Astronomy-Feedback-#27]
Not a big issue, but when I did the Stencil Table the 3 other steps to the quest achivement were already marked as done and I could grab the rewards.
I did the other two tables afterwards so no big issue.

Regards

**Comment by MJRLegends** [comment]
Yeah i dont know why it doing this, i'll have a look and see if i can do something to help it

**Comment by BillyPepper** [comment]
I've just started with the quests. 
Shall I info if I find other issues with the quests.
I guess they are already known and I don't want to annoy anyone with known stuff

**Comment by MJRLegends** [comment]
Yeah thanks for letting me know, im working on getting a update out soon to fix a few quest problems.
