### ISSUE TITLE
Cannot launch pack

### ISSUE THREAD

**Issue by Triaxx2** [MJRLegends/Space-Astronomy-Feedback-#272]
[crash-2016-04-20_09.15.24-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/234566/crash-2016-04-20_09.15.24-client.txt)

**Comment by MJRLegends** [comment]
One use pastebin for crash logs and two could you explain more about that your using and what your doing and what you have tried to solve the problem...

**Comment by Triaxx2** [comment]
http://pastebin.com/RDRzMdnK

I'm using the latest version, the only mod I've changed at all is to add AppleCore. Removing it gives the same error. It loads to 6/7 Finishing up and then crashes back to the launcher.

**Comment by MJRLegends** [comment]
Well reinstall the mod pack dont mess around with adding mods and test then

**Comment by Triaxx2** [comment]
That seems to have done the job. Thanks.

**Comment by MJRLegends** [comment]
Glad its fixed :P
