### ISSUE TITLE
I get this error quite randomly, every once in a while while playing or idling in my world.

### ISSUE THREAD

**Issue by johnharry** [MJRLegends/Space-Astronomy-Feedback-#273]
Paste bin - http://pastebin.com/S5xaGGuQ

**Comment by MJRLegends** [comment]
Delete the file its saying is in use in the crash log and that should fix it

**Comment by johnharry** [comment]
Ok thanks for the quick response. Ill try thank and see if it fixes it

**Comment by MJRLegends** [comment]
Yeah it should ive had it before with a single player world
