### ISSUE TITLE
Crash reports at startup

### ISSUE THREAD

**Issue by RikB15** [MJRLegends/Space-Astronomy-Feedback-#274]
Hello MJR,

Me and a couple of friends set up this Space astronomy server 18 days ago. We have played on this server until yesterday night around 0:15. But when my friend wanted to start the server this morning, it crashed. We have never had issues with it so it was pretty much a surprise for us. This is the crash reports from this morning: 

http://pastebin.com/5u8pKyp3

When i tried to start it in the afternoon, it gave a different error:

http://pastebin.com/LadwgbWz

I'd love to hear a opinion from you.

Kind regards,

RikkertB (The Netherlands)

**Comment by MJRLegends** [comment]
See known issues or see #218
