### ISSUE TITLE
1.4.3 Fronos crash

### ISSUE THREAD

**Issue by Elvi81** [MJRLegends/Space-Astronomy-Feedback-#275]
Server crash report
http://pastebin.com/16mxYY60

**Comment by MJRLegends** [comment]
From the crash log i can see you are getting some network packet issues, these might be the main cause of the crash...

**Comment by Elvi81** [comment]
I don't see how and it only happens on fronos + the server pc is almost next to me, and yet the same thing happens to other players.

**Comment by MJRLegends** [comment]
Well im not making it up but there's network issues in your log you have posted

**Comment by Elvi81** [comment]
Just to make sure it's not that i copied the server files to my local computer and ran it, same deal, NOT network related, still testing on what could cause this.
Singleplayer isn't affected.

**Comment by MJRLegends** [comment]
The good news for you is my server is getting it to, so im looking in to it

**Comment by Elvi81** [comment]
I probably should add that i'm using Thermos-1.7.10-1614-56-server as the server jar.
1 extra mod, Morpheus-1.7.10-1.6.21, sleeping mod.
Plugins include AutoSaveWorld, Essentials, EssentialsChat, EssentialsGroupManager ,EssentialsSpawn and PurpleIRC.

**Comment by Elvi81** [comment]
I forgot about the crash report folder files but here's the latest one and i'm gueesing it's similair to the one you had.

http://pastebin.com/WgrcK1Qf

**Comment by MJRLegends** [comment]
Possible fix: try changing the option "load chunk on request" to false in cauldron.yml

**Comment by Elvi81** [comment]
So far so good, here's hoping i don't jinx it :P

**Comment by MJRLegends** [comment]
@Elvi81 glad my fix is working and yeah i've had this issue because the only way i found to fix it is world edit the blocks out and reset them up

**Comment by MJRLegends** [comment]
I've added this soultion for this issue about the planets crash to the more planets issue post i made and i've added it to the known issues pastebin for the mod pack. So you got any more issues relating to another problem then please make another issue post
