### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by NicroDeath** [MJRLegends/Space-Astronomy-Feedback-#277]
http://pastebin.com/m2TLwRPk (Changed to a pastebin link by MJRLegends)

**Comment by MJRLegends** [comment]
What the hell do you expect me to do something with this???? One you have gave no details on what your doing and using and you are ignoring the rule of using pastebin for logs.

**Comment by NicroDeath** [comment]
Oh, sorry. It's my first time I have problems with MC or modpacks.
When I click "Play" on the launcher it disappears and after 1 sec it reappears with this error. 
Not even get to the classic minecraft screen.

Again sorry for not giving info :c

**Comment by MJRLegends** [comment]
Reinstall the mod pack, and if it still fails then try a different mod pack to see if that works

**Comment by NicroDeath** [comment]
I'm trying a different mod pack on curse.
I keep you informed.

**Comment by NicroDeath** [comment]
I've tryed another mod pack and it works.
Only your pack makes problems :c

**Comment by NicroDeath** [comment]
I've also tryed to reinstall several times the modpack but still not works

**Comment by MJRLegends** [comment]
Have you tried to reinstall it

**Comment by MJRLegends** [comment]
Post the full log using pastebin

**Comment by NicroDeath** [comment]
I've also tryed to reinstall it several times but it still not work

**Comment by NicroDeath** [comment]
http://pastebin.com/PBGgz0Xv

I also add u a screenshot of the launcher.
https://gyazo.com/c8a1ecb436d8dea672a795120b031bdc

**Comment by NicroDeath** [comment]
I forget this
http://pastebin.com/med9kxue

**Comment by MJRLegends** [comment]
Please use the curse launcher or the ftb launcher and not the minecraft launcher

**Comment by NicroDeath** [comment]
When I click play on curse it opens automatically the minecraft launcher

**Comment by MJRLegends** [comment]
Use one of theses
Curse one: https://clientupdate-v6.cursecdn.com/CurseClientSetup.exe?h=[plugin-minecraft]
FTB one: http://ftb.cursecdn.com/FTB2/launcher/FTB_Launcher.exe

**Comment by MJRLegends** [comment]
try the ftb one then

**Comment by NicroDeath** [comment]
I don't find it on the ftb :o
It has a code?

**Comment by NicroDeath** [comment]
I'm trying on ftb.
I keep you informed.
Ty for your time.

**Comment by NicroDeath** [comment]
It works c:
Ty for your help <3
