### ISSUE TITLE
Local Server Problems

### ISSUE THREAD

**Issue by CrazyBaffo** [MJRLegends/Space-Astronomy-Feedback-#278]
Hy!
Me and my brother start a new local server. When we try to craft items not vanilla the crafting doesn't work. Any ideas? We have downloaded the server from ftb launcher. Have a nice day!

**Comment by MJRLegends** [comment]
Any chance those items are tools?

**Comment by CrazyBaffo** [comment]
Yeah, for example i can't craft the crafting table from tinker's construct
mod
Il 01/mag/2016 11:29 PM, "MJRLegends" <notifications@github.com> ha scritto:

**Comment by MJRLegends** [comment]
You can craft it are you sure your doing it right. Check nei for recipe

**Comment by Bulbasaur1994** [comment]
Hey. Not certain if im the only one experiencing this but im not getting the quest book upon loading the world. Also I had to download the modpack differently how do I properly download it and add it to my minecraft game?

**Comment by MJRLegends** [comment]
Have you used the ftb or curse launcher to download and run the mod pack @Bulbasaur1994
