### ISSUE TITLE
OFFICIAL SERVER DOWN!!

### ISSUE THREAD

**Issue by MJRLegends** [MJRLegends/Space-Astronomy-Feedback-#279]
Theres issues with the server on the hosting companies side and the server wont start. Im trying to fix it....

Check back here for updates on the issue...

Sorry that its down :(

**Comment by TwinMos** [comment]
:( that's very bad and sad :(

**Comment by MJRLegends** [comment]
Yep the people that can fix it are not available atm so we just have to wait it out

**Comment by Rainewood** [comment]
Seems pretty irresponsible on the part of the host, not having tech support at all available. Hopefully they get it fixed soon :/

(ObsidianFox from the server)

**Comment by MJRLegends** [comment]
They have a lot of staff but the issue is to do with something that only limited people have access to....

**Comment by TwinMos** [comment]
crap... so sad...
P.S. Fox, your chest in the hub is full with glowstone. *shy* i went to nether in the morning... :D

**Comment by MJRLegends** [comment]
It will hopefully be back online within in the next 24hrs....i cant really say much more than that :)

**Comment by Rainewood** [comment]
I'd hope sooner rather than later :) Thanks Mos, I've got a big plan to teardown my base and reconstruct it though, so it'll probably stay there for a couple days.

**Comment by TwinMos** [comment]
wow.. I was hoping that this will happen faster... but... we can't do anything with it... :(
may be we move it to you? :) (shy) it's a large chest... :P

**Comment by Rainewood** [comment]
I can probably shift it with a matter relocator. Once we get on I'll take a look.

**Comment by MJRLegends** [comment]
Please keep this issue about the server being down and not anything else please

**Comment by MJRLegends** [comment]
Back online now
