### ISSUE TITLE
Cant connect to official space astronomy server!!!

### ISSUE THREAD

**Issue by Guarnika** [MJRLegends/Space-Astronomy-Feedback-#281]
Hello,

I was "kicked" from server and when i try to log back it says (cant resolve host name).
Tryed to log with direct connect and still doest work.
Any idea what can i do to fix it.

ty :)

**Comment by Rainewood** [comment]
I receive the "unknown host" notice and it looks like the server is offline.

**Comment by Guarnika** [comment]
Ty for the info, report if you can log back on plz,

**Comment by MJRLegends** [comment]
Please use this ip address for the time being: 158.69.171.59:25588 because the hosting company fucked up the domain name ip address.

**Comment by Guarnika** [comment]
MJR ty for the quick replay, im on. :)

**Comment by MJRLegends** [comment]
Fixed please use the proper ip address from now on
