### ISSUE TITLE
augment stabilized frame from thermal expansion is not craftable

### ISSUE THREAD

**Issue by zaphrod** [MJRLegends/Space-Astronomy-Feedback-#282]
this item is a tier 2 augment for pulverizer but i cannot craft it. it does not show any recipe in the NEI when i click it.

**Comment by MJRLegends** [comment]
Seems to be fine for me 

![](https://i.gyazo.com/90bb8aba4a6bc95bb36d8bfabbf49ae7.png)

**Comment by zaphrod** [comment]
oh, i might have added some mods that conflicts with the recipe. thanks.
