### ISSUE TITLE
Extra Cells 2 Quartz Tank

### ISSUE THREAD

**Issue by Rainewood** [MJRLegends/Space-Astronomy-Feedback-#283]
I was trying to craft a fluid storage disk for an ME system on the official server. The certus quartz tank is a required piece of this, and is not on the banned interaction list. However, when I attempt to use it in the crafting recipe I get a notice stating that the item is banned and cannot be used. I can't even put them in a trash can, so they're stuck blocking my inventory. Please help!

**Comment by MJRLegends** [comment]
Now try

**Comment by Rainewood** [comment]
Thank you, I was able to craft the fluid storage disk.
