### ISSUE TITLE
Error :authentification server down

### ISSUE THREAD

**Issue by TwinMos** [MJRLegends/Space-Astronomy-Feedback-#284]
Hi.
I've tried to use Relocator at Spawn on official server and get a client crash. 
Log : http://pastebin.com/VuuMGMui
after I start game again without closing client and get that error. after closing client all works fine.

**Comment by MJRLegends** [comment]
If it's saying authentification server down thats a minecraft server issue??

**Comment by TwinMos** [comment]
idk where authentification error occured.
