### ISSUE TITLE
Mouse Disappears even when in Inventory or menu 

### ISSUE THREAD

**Issue by bendev01** [MJRLegends/Space-Astronomy-Feedback-#289]
I opened the game and I opened my inventory and couldn't see my mouse. I tabbed out and still could not see it. It makes playing the game extremely annoying I am playing on my macbook pro.

**Comment by MJRLegends** [comment]
Its because your didn't close the update message for dragon api and this has been posted about 1000x times so please check known issues page and closed issues before posting
