### ISSUE TITLE
got a extra planets crash

### ISSUE THREAD

**Issue by Williamkers** [MJRLegends/Space-Astronomy-Feedback-#290]
This is just for my modpack, but I can't find the solution
[crash-2016-05-14_15.09.09-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/264527/crash-2016-05-14_15.09.09-server.txt)

**Comment by MJRLegends** [comment]
You have put this in the wrong place but the crash is to do with a conflict of dimensions ids. If you require require help with my addon ExtraPlanets then please post it in that issue tracker
