### ISSUE TITLE
Crashes when interacting with wireless transmitters/receivers (wireless redstone mod)

### ISSUE THREAD

**Issue by johnharry** [MJRLegends/Space-Astronomy-Feedback-#291]
http://pastebin.com/n5C2Wayk
I saw that this problem had been posted before but had not been resolved due to lack of info. Sometimes when I right click a transmitter/receiver the game crashes randomly.

**Comment by MJRLegends** [comment]
Yeah i know, to be honest the mod is crappy so we are changing to ChickenBones's wireless redstone, see change log for v1.4.4

**Comment by johnharry** [comment]
Ok cool

**Comment by MJRLegends** [comment]
@johnharry tbh i've been meaning to change the mod for a while but never got around to it but it will be changed in v1.4.4
