### ISSUE TITLE
Official Server Down!!!!

### ISSUE THREAD

**Issue by MJRLegends** [MJRLegends/Space-Astronomy-Feedback-#295]
I know the server is down, im trying to get it sorted, but it seems all the companies websites are down and the owner has confirmed hes working on it to get it fixed.

**Comment by Guarnika** [comment]
Dude, you are on top of things, i came to report it and here you are already.

**Comment by MJRLegends** [comment]
Yeah i get alerted when my servers go off and that

**Comment by Guarnika** [comment]
Noticed that 1.4.5 its up for download,

**Comment by MJRLegends** [comment]
Yeah once the server is back online i will update it

**Comment by Guarnika** [comment]
Any clue if it will be back up today?

**Comment by MJRLegends** [comment]
No idea the owner said he was trying to fix it, but hasn't been fixed yet

**Comment by bravenlord** [comment]
BRAVENBUCKS IS DOWN FOREVER!!!!!!!!!!!!!!!!!! NO!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by MJRLegends** [comment]
SERVER IS BACK ONLINE YAYAYAYAYAYAY
