### ISSUE TITLE
Official Server down!

### ISSUE THREAD

**Issue by MJRLegends** [MJRLegends/Space-Astronomy-Feedback-#296]
Will keep you updated but atm the problem is once again on the hosting company side

**Comment by bravenlord** [comment]
omg I fricking hate the server company

**Comment by bravenlord** [comment]
serves up

**Comment by MJRLegends** [comment]
Yeah server is now online

**Comment by bravenlord** [comment]
I've been griefed

**Comment by bravenlord** [comment]
dude ill stop
