### ISSUE TITLE
Crash on loading world

### ISSUE THREAD

**Issue by xX-Gigi-Xx** [MJRLegends/Space-Astronomy-Feedback-#297]
Hi. I am Italian and play with your fantastic pack ... Sorry for my wrong English... Yesterday I updated the pack to version 1.4.5... Yesterday I played normally and the game did not give problems. Today, this morning, I play normally and without problems after playing for 2 hours but this night launch the Modpack and when load the world, game crash. reading the report, PERHAPS, the crash is because chunk loader... i have three Chunk Loader actually. 2 chunk in overworld, and 1 in mining world... but Yesterday with 1 in overworld and 1 in mining world i haven't any problem... today i use 2 chunk in overworld... i think my mistake was put in a total of 5 chunk, chunk loader with the first with 4 chunk and the second with 2 chunk and the chunk and the chunk intersect each other... Can this be the cause?

Crash report: http://pastebin.com/44qUtDZE

**Comment by MJRLegends** [comment]
Look at the known issues as this has been posted 1000x times

**Comment by xX-Gigi-Xx** [comment]
please help me.. i don't know to clear the error
