### ISSUE TITLE
Mekanism isn't transferring power through Tesseracts

### ISSUE THREAD

**Issue by majorpayne0055** [MJRLegends/Space-Astronomy-Feedback-#298]
Ever since the new Mekanism update, I've been having trouble with mekanism transferring power through Tesseracts. I have 4 sources of power all set to the same private tesseract channel (Big Reactor turbines, Mek solar panels, Mek reactor and Mek gas generators. The power goes to a Mek Induction Matrix with another tesseract transferring power out as needed. Prior to the update, all 4 power sources were charging the Induction Matrix. After the update, only the power from my Big reactors is coming through into the Induction Matrix.

**Comment by MJRLegends** [comment]
I think its mekanism see https://github.com/aidancbrady/Mekanism/issues/3252 and https://github.com/aidancbrady/Mekanism/issues/3303 and https://github.com/aidancbrady/Mekanism/issues/3314

**Comment by majorpayne0055** [comment]
Tried the Ender IO cable fix and it looks like it's working now. Must be a glitch with Mekanism universal cables and Tesseracts.

**Comment by Spellkaze** [comment]
Just as an extra, If the power output rate is not enough, you can always try the aluminum cables from galacticraft
