### ISSUE TITLE
Mouse vanishing

### ISSUE THREAD

**Issue by kiri970** [MJRLegends/Space-Astronomy-Feedback-#299]
When i open my inventory or pause menu, my mouse vanish and it's hard to play. Any solution?

**Comment by WalaoEgg0424** [comment]
kiri970 , press ctrl then click 'x' on the dragonapi update  , then pointer is back . Its magic :)

**Comment by kiri970** [comment]
@WalaoEgg0424 everytime i try to do that the X button can't be clicked. I click on it but nothing happen

**Comment by WalaoEgg0424** [comment]
did u press ctrl and click on the X ?

**Comment by kiri970** [comment]
@WalaoEgg0424 yes but the message doesn't disappear

**Comment by WalaoEgg0424** [comment]
@kiri970 its weird lul, using windows or mac or linux?

**Comment by kiri970** [comment]
Mac

**Comment by kiri970** [comment]
@WalaoEgg0424 apparently when i click while pressing ctrl, my mac thinks that i'm right clicking...

**Comment by WalaoEgg0424** [comment]
@kiri970 this is a known issue and only way to disable it is go to your curse modpack folder , find space astronomy , go to config/Reika/DragonAPI.cfg , find control setup , there will have show update notification for ops or wutever , change true to false. boom magic

**Comment by kiri970** [comment]
@WalaoEgg0424 thank you!

**Comment by WalaoEgg0424** [comment]
@kiri970 and @MJRLegends is trying to find a permanent fix for this 8 months ago. Mac OS's ctrl key is different with Windows's ctrl key , so the mod cant really read it as windows ctrl. You can see info in this issue posted at reika's github.
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/317

**Comment by kiri970** [comment]
@WalaoEgg0424 I solved it downloading a programm called "Karabinier" were you can change ctrl+left click= Right click in ctrl+Left click=Left click.

**Comment by WalaoEgg0424** [comment]
@kiri970 nice , but it might not a solve for others. Glad that u found a way to solve it.

**Comment by kiri970** [comment]
Thank you a lot for your help btw!
