### ISSUE TITLE
Not working after Update

### ISSUE THREAD

**Issue by cobramike** [MJRLegends/Space-Astronomy-Feedback-#3]
Ok so after the update i get this error. 

Java 7
http://pastebin.com/8bztXXn9

Java8
http://pastebin.com/607AsZKf

I only hit update Space and the start it. But now its not working anny more

**Comment by MJRLegends** [comment]
Give me 5 mins im just trying it for myself, as there shouldnt be a problem.

**Comment by cobramike** [comment]
Ok ill wait.

**Comment by MJRLegends** [comment]
I have found the problem if you go in to the edit mod pack and disable Galacticraft, Galacticraft Planets and MicdoodleCore V3.0.12.350.

For some reason two different versions have got in there, even though i tested it 5 times before uploading.. I am working on getting a bug fix update out!

**Comment by cobramike** [comment]
Ok thank you verry much.

**Comment by MJRLegends** [comment]
No problem i have no idea how the other version got it there.
