### ISSUE TITLE
Quest: "Creating an Iron Hammer"

### ISSUE THREAD

**Issue by squillis** [MJRLegends/Space-Astronomy-Feedback-#30]
This quest tasks you with creating an Iron Hammer through Tinkers Construct. The part where it has you assemble the Iron pieces, it asks for only one large Iron Plate. This should probably ask for two since it requires two to craft it. 
I'm suggesting this because the next quest tells you to actually craft the hammer, and that's not possible if you follow the quest since you only would have one Large Plate.

**Comment by MJRLegends** [comment]
This will be fixed for the next update

**Comment by squillis** [comment]
You added an extra Stone Large Plate to "creating parts" but to make a cast you only need 1 Stone Large Plate, you should have added the extra "Iron Large Plate" (You added it to the wrong spot. :( )
