### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by LycanBlackpaw** [MJRLegends/Space-Astronomy-Feedback-#300]
...Honestly I have no idea why this happens. Usually I'm good at this.

Whenever I start up the pack, it'll appear to load fine until it reaches the menu-then java will crash and I'll get sent back to the launcher.

Using the Curse launcher, version 1.4.5 of the pack.

Log attached.
http://pastebin.com/0LYx2saJ

EDIT:
Decided to try loading it through FTB, to see if it was a launcher-based issue. Same type of error.
And apparently FTB console logs are enormous so Pastebin won't let me upload it.

[Crash, Space Astronomy, 6-4-16, FTB, V. 1.4.5.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/298884/Crash.Space.Astronomy.6-4-16.FTB.V.1.4.5.txt)

**Comment by WalaoEgg0424** [comment]
@LycanBlackpaw this is not really a crashlog lel but i'll look through it

**Comment by WalaoEgg0424** [comment]
@LycanBlackpaw this need our pro @MJRLegends to look through it , too hard to scroll through it to end on my phone. I can only see tons of texture errors on the end of logs.

**Comment by LycanBlackpaw** [comment]
@WalaoEgg0424 That's the only error I could see. The game itself doesn't seem to be breaking-it's something to do with Java, but I have no idea what and haven't seen anything similar.

Yay for Java being all kinds of derp.

**Comment by WalaoEgg0424** [comment]
@LycanBlackpaw maybe disable the forge loading menu work? I googled it and it shows that disable it fix it.

**Comment by LycanBlackpaw** [comment]
...Holy crap it worked. Yay.

So...Future reference material in case this happens to anyone else:
Edit server.properties in the Config file, changing 'Enabled' from true to false.

**Comment by WalaoEgg0424** [comment]
@LycanBlackpaw server.properties or splash.cfg ?

**Comment by WalaoEgg0424** [comment]
@LycanBlackpaw its splash.properties :)
