### ISSUE TITLE
OFFICIAL SERVER DOWN

### ISSUE THREAD

**Issue by MJRLegends** [MJRLegends/Space-Astronomy-Feedback-#301]
i know its down, the issue is on the hosting side.........................

**Comment by demone775** [comment]
when the server restart ?

**Comment by MJRLegends** [comment]
Idk

**Comment by demone775** [comment]
sorry but I don't know what it means

**Comment by MJRLegends** [comment]
Idk = i dont know

**Comment by demone775** [comment]
thanks

**Comment by MJRLegends** [comment]
not really much i can do from my side we just have to wait....

**Comment by Geekerandy** [comment]
Really quick question out of curiosity due to the fact that I am starting a youtube series in singleplayer but I may try the multiplayer server for my youtube series as well: When can you expect the constant braking down on the host to slow down or stop?

**Comment by MJRLegends** [comment]
Its not my fault i don't host it myself and a few times

**Comment by MJRLegends** [comment]
Look im really trying my best to get the server back online but i have no access to fix anything and its taking ages to get fixed atm. but im really trying sorry :(

**Comment by Geekerandy** [comment]
Oh no, I didn't mean to criticize. I admit I have had some horrible times with setting up servers.

**Comment by MJRLegends** [comment]
@Geekerandy i know, its just i cant fix it because its not on my side to fix

**Comment by Geekerandy** [comment]
I hate it when a host that you need breaks down. It's like a person who you need to work with can't actually do the job.

**Comment by MJRLegends** [comment]
Server is back online
