### ISSUE TITLE
Stuttering Mouse.

### ISSUE THREAD

**Issue by Sheefou** [MJRLegends/Space-Astronomy-Feedback-#302]
So I loaded the modpack in a single player world and removed fastcraft (Causes problems with my PC) and updated DragonAPI but as i attempt to look around the looking position continues to reset to a point making the game unplayable

**Comment by WalaoEgg0424** [comment]
@Sheefou why you wanna update dragonapi? MJRLegends choose not to update it has his own reason.

**Comment by Sheefou** [comment]
updated to remove the annoying update message but even before then I still had the same issue


LividJava






On Tue, Jun 7, 2016 at 9:46 PM -0400, "WalaoEgg0424" <notifications@github.com> wrote:





@Sheefou why you wanna update dragonapi? MJRLegends choose not to update it has his own reason.

---

**Comment by WalaoEgg0424** [comment]
@Sheefou make a backup world , then try install the modpack again. btw u using windows or mac?

**Comment by Sheefou** [comment]
Windows

**Comment by WalaoEgg0424** [comment]
@Sheefou this might need @MJRLegends to solve it

**Comment by MJRLegends** [comment]
did you close this https://gyazo.com/77526ea4181c36ba6608f6ea53a68c82 ?

**Comment by Sheefou** [comment]
@MJRLegends yes i did same problem occured
