### ISSUE TITLE
Atomic Disassembler quest not working

### ISSUE THREAD

**Issue by TheDumAmerican** [MJRLegends/Space-Astronomy-Feedback-#303]
As the title states unable to complete the Atomic Disassembler quest in Chapter 5. I saw this was fixed a long time ago https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/28 but it seems to have come back. Tried crafting in different tables/with to no avail. May not be connected but I noticed there is 2 : after mode instead the usual 1.

**Comment by MetalBerto** [comment]
I confirm that. I have the same issue

**Comment by MJRLegends** [comment]
will look at it soon

**Comment by MJRLegends** [comment]
Will be fixed in the next update
