### ISSUE TITLE
Mouse Disappearing  

### ISSUE THREAD

**Issue by aophipps0927** [MJRLegends/Space-Astronomy-Feedback-#304]
When I left click my quest book, my mouse disappears. By the way, I'm on Mac.

**Comment by MJRLegends** [comment]
did you close this https://gyazo.com/77526ea4181c36ba6608f6ea53a68c82 ?

**Comment by aophipps0927** [comment]
I cannot click it, it won't let me

**Comment by aophipps0927** [comment]
Also that box pops up every time I boot up the game

**Comment by WalaoEgg0424** [comment]
@aophipps0927 this is a known issue for Mac users . 
https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/299
