### ISSUE TITLE
Coal dust not recognized in the induction smelter

### ISSUE THREAD

**Issue by MetalBerto** [MJRLegends/Space-Astronomy-Feedback-#306]
Hi! I've tried to make refined iron ingot in the induction smelter, wich requires 1 iron ingot and 2 coal dusts. When i try to do that the machine doesn't allow me to put the coal dust in neither of the 2 input slot. Hope you can solve it! Thank you!

**Comment by MJRLegends** [comment]
Use the other ways to make it then?

**Comment by rotatori** [comment]
well i had the sanìme problem to solve it you need to take the coal dust and make a hydratated the cook the hydratated coal and you will have the industrialcraft coal dust which works for the induction smelter

**Comment by MetalBerto** [comment]
@rotatori thank you for your tip!
@MJRLegends sure! i just wanted to let you know this issue. thank you!
