### ISSUE TITLE
Game freezing when I scroll through or type "Mekanism" into NEI

### ISSUE THREAD

**Issue by mike18001** [MJRLegends/Space-Astronomy-Feedback-#307]
For some reason, when I scroll through an item in NEI, it seems to freeze my client. It seems to be in the Mekanism area, cause when I scroll through NEI and manage to reach the Mekanism area, my game freezes.

**Comment by MJRLegends** [comment]
Yeah this is because its loading the tanks solutions: 
1. Just let it load and wait to it stops freezing
2. Dont type @Mekanism and be more selective with what you type

Its being fixed in the next version anyways(check change log)
