### ISSUE TITLE
Large lines of chunks not loading/rendering

### ISSUE THREAD

**Issue by BrightBotTeam** [MJRLegends/Space-Astronomy-Feedback-#308]
Likely a mod bug. Whenever I load into a world, most of the nearby chunks are loaded, but there will always be one large line of broken chunks that are just the empty black areas with no end. Reloading fixes those chunks, then I'll be going along my business only to discover a new area of broken chunks.

Possibly due to my shitty computer. No additional mods. Recommended version.

**Comment by MJRLegends** [comment]
Yeah probably your computer not loading it, try install OptiFine
