### ISSUE TITLE
HQM quests not registering items

### ISSUE THREAD

**Issue by maxills** [MJRLegends/Space-Astronomy-Feedback-#31]
Hey there, not sure if this is a known issue, but several quests are not being updated in the Quest Book when I create items, here is the list:

Machines & Mining
- Speed Mining: Not recognizing the QuarryPlus or the MarkerPlus torches
- Efficient Mining: Not recognizing the Ender-Markers

Tools & Weapons
- Crafting a Powerful Tool: Not recognizing the Atomic Dissasembler

This is the current short list, there might be more I just haven't advanced further then that.

Thanks,
MaxillS

**Comment by MJRLegends** [comment]
These have been fixed in the next update.
