### ISSUE TITLE
Please help...

### ISSUE THREAD

**Issue by DNGDynamo** [MJRLegends/Space-Astronomy-Feedback-#311]
Well when i start the modpack im in the main menu of course but then when i go in my single player world then the mouse becomes totally invisible and its hard to close it and i cant move it outside my window and i tried playing in fullscreen

**Comment by MetalBerto** [comment]
Try to press and hold the ctrl key for a few seconds

**Comment by MJRLegends** [comment]
Read all the other 10000 posts like this, before posting
