### ISSUE TITLE
Crash when loading the world.

### ISSUE THREAD

**Issue by Nikitka535** [MJRLegends/Space-Astronomy-Feedback-#312]
http://pastebin.com/AmJkm9GN

**Comment by MJRLegends** [comment]
You couldnt of gave me any less information about your issue, if you tried!!

**Comment by Neyrali** [comment]
it's happens to me to

**Comment by Neyrali** [comment]
at the moment i solved by removing chichenk chunks

**Comment by Nikitka535** [comment]
And what kind of details do you need?

**Comment by Nikitka535** [comment]
Log: http://pastebin.com/HikYYw0h

**Comment by MJRLegends** [comment]
@Nikitka535 information like what were you trying to do? single player or multiplayer server? are you in a open area or are you near your base so there will be machines around?

**Comment by germanpanda502** [comment]
I have the same problem and i am in a dimension between my quarry and reactor

**Comment by VoidArrow** [comment]
I had this issue a few times, when I had a chunk loader in the Nether and in the Mining World.  I removed Chicken Chunks (erasing chunk loaders) and then reinstalled it.  After replacing my chunk loader in the Nether, I have had no issues loading worlds.  I assume it is some issue with chunk loaders in the Mining World. :D

**Comment by MJRLegends** [comment]
Well Chicken Chunks is going in the next update anyways so im getting this will be fixed 100% then??

**Comment by MJRLegends** [comment]
I think we will leave this issue open and then see if it comes up after the next update

**Comment by tanksmontaje** [comment]
I'm having same problem hopefully update will fix... gunna try using minefactory reloaded CL instead.

**Comment by tanksmontaje** [comment]
*my current fix* i loaded server world as single player save then broke chunk loader, put that single player save as server world file... before i shut off my server now, i break the chunk loader and go back to over world. seems to work

**Comment by MJRLegends** [comment]
see #341
