### ISSUE TITLE
Crash on world loading. 

### ISSUE THREAD

**Issue by dyinglights** [MJRLegends/Space-Astronomy-Feedback-#315]
Hi all, I tried reading through the previous issues but I am just too dumb at java to know if this is an old issue or not.
I recently made a maximum sized quarryplus (256*256) with silk touch, efficiency and un-breaking enchantments. When i placed the quarry down on the boundary set by the markers my client crashed, it booted fine just had a bit of lag.
I then used chickenchunks chunk loaders both in the overworld and mining dimension, with tesseracts transferring between them. Now after these have been placed my game will not load, just crashing. I think it loaded once after i added the chunk loaders but thats it.

Log is here ~ http://pastebin.com/YvcUuPcD

Any help would be appreciated!

**Comment by WalaoEgg0424** [comment]
@dyinglights it is a known issue.

7. ChickenChunks Chunkloaders - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/221 & https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/218 - (This is a mod bug) Reported in v1.3.7!
Solution 1: Remove the ChickenChunks mod
Solution 2: Use MCEdit to remove them from your world (Should say the blocks coords in the crash log)

**Comment by dyinglights** [comment]
Thanks! removing ChickenChunks seems to let me play. quarry is also working without the need to be chunkloaded as well, its pretty great!

**Comment by WalaoEgg0424** [comment]
@dyinglights your welcome :)
