### ISSUE TITLE
World crashes

### ISSUE THREAD

**Issue by MBTKemz** [MJRLegends/Space-Astronomy-Feedback-#317]
Hello, I just started this pack. It went fine for a few days but now I get the crash when I wanted to play mu world. it says server closed and then it just closes the client. Here's the log file from the console, Hope you guys could help me

http://paste.feed-the-beast.com/view/9b4cf851

Crash log: http://pastebin.com/YvRR2W4X (Taken from the log above by MJRLegends)

**Comment by MJRLegends** [comment]
Make a backup of your player data for that world then try to delete the player data and retest then

**Comment by MBTKemz** [comment]
Hi, I started a new world but now after 1 day I get the message that Forge detected that the backup data is being used and might corrupt it. I can't go into my new world now. It's getting frustrated that I get big errors at every world I try :/

**Comment by MJRLegends** [comment]
Weird I will have a look when I can

**Comment by MJRLegends** [comment]
This will be fixed in the next update, as it seems its the cofh update checker had issues, which will be disabled in the next update
