### ISSUE TITLE
Can't move

### ISSUE THREAD

**Issue by Pjtomas** [MJRLegends/Space-Astronomy-Feedback-#319]
So, been playing your mod for a couple weeks now and all was going good, till today, i logout last night and all was fine, today when i log into my world, i can't move, every key i press changes the minimap aspect from day to night and caves, every single key in my keyboard does that, well all but esc and M, wich opens the galaxy map, all rest does the same...so dunno whats going on.

**Comment by MJRLegends** [comment]
Check your controls?  Or try to reinstall the mod pack

**Comment by Pjtomas** [comment]
yep, controls are all fine, reset everything and put all at none, left only movement ones and still same, already did force install mods on the launcher twice.

**Comment by MJRLegends** [comment]
Does it do it only in one world or every world

**Comment by Pjtomas** [comment]
only have 1 world..., ill try create a new one, brb

**Comment by MJRLegends** [comment]
Kk

**Comment by Pjtomas** [comment]
does the same

**Comment by MJRLegends** [comment]
Do the keys work normally in the OS?

**Comment by Pjtomas** [comment]
os?

**Comment by Pjtomas** [comment]
u mean like the options? to set them up and all that?, if so they do work fine there

**Comment by Pjtomas** [comment]
or unless u mean operation system, ahhaha ok brain freeze here

**Comment by Pjtomas** [comment]
yeah all good, win7 here

**Comment by MJRLegends** [comment]
Ok do they work in a different mod pack?

**Comment by Pjtomas** [comment]
all working fine, google, youtube, here, all fine, just ingame does that, and last night i played fine

**Comment by Pjtomas** [comment]
ok let me try then, brb

**Comment by MJRLegends** [comment]
ok

**Comment by Pjtomas** [comment]
ok, just tested blastoff, is the other mod pack im playing and works fine

**Comment by Pjtomas** [comment]
u want me to test some mod pack more recent maybe?

**Comment by Pjtomas** [comment]
sky factory works fine also

**Comment by MJRLegends** [comment]
umm how weird....

**Comment by MJRLegends** [comment]
have you tried making a backup of your world (other wise you will lose it after this next step!!!) and then manually deleting the mod pack files and reinstall it

**Comment by Pjtomas** [comment]
damn ok lol

**Comment by Pjtomas** [comment]
brb, sry was having a smoke

**Comment by Pjtomas** [comment]
oh...just crashed the game, tried to test it again, because i put it force update the mods again, went to my world now, tried to move and showed a msg shutting server off, and game crashed

**Comment by Pjtomas** [comment]
last night i build a little base underwater, and logged out there, dunno if anything mathers to this issue, but tought i would report that

**Comment by MJRLegends** [comment]
please try what i said above

**Comment by Pjtomas** [comment]
ok so, i deleted everything in the mods briefcase and installed all again, still doing the same

**Comment by MJRLegends** [comment]
you need to delete the whole mod pack stuff not just the mods

**Comment by Pjtomas** [comment]
ohhhhh kk sry m8, didnt got the part was everything, kk brb then again, sry about that

**Comment by Pjtomas** [comment]
ok all working fine with a new world, try now restore there my world?

**Comment by MJRLegends** [comment]
yeah can do

**Comment by Pjtomas** [comment]
woottt,  world all good, i can move again

**Comment by MJRLegends** [comment]
yeah i think your controls and settings for the mod pack got messed up but glad its fine now

**Comment by Pjtomas** [comment]
wow, that was weird, but ok, guess thats what i have to do next time, lol, well thanks for the help m8, and for been so fast in helping with that,

**Comment by Pjtomas** [comment]
and great work on the mod, having lots fun with it

**Comment by Pjtomas** [comment]
have a good day m8, cya
