### ISSUE TITLE
Bunch of fun quests

### ISSUE THREAD

**Issue by braingkk** [MJRLegends/Space-Astronomy-Feedback-#32]
'Going Wireless' is not registering the crafting of my wireless terminal

'Building the Tier 1 Rocket' only works if you make the zero chest rocket, wen most people automatically make the 3 chest one. at least a warning would be nice

'Going to the End' only one player can complete on multiplayer servers as it requires killing the dragon [intended?]

'Replanting Trees' is repeatable every 30secs or so

'Crafting a Powerful Tool' does not register when the player crafts the atomic disassembler

as mentioned in other reports, both quarry quests do not work either

**Comment by MJRLegends** [comment]
Please look at the closed issues as some of theses are been reported already loads, and i will fix them all for the next update
