### ISSUE TITLE
the reset

### ISSUE THREAD

**Issue by TheDarkKing** [MJRLegends/Space-Astronomy-Feedback-#320]
i precede excuse me for the english i'm italian.
in you server of space astronomy the game writhe reset of mining world ,end and nether on 14th of every month but today is 15/06/2016 and the world isn't reset.
i writhe here because totay on server i writhed to a moder and he dons answer me.
P.S. some italian are plaing on server we are about 10.
tank you for the time.

**Comment by MJRLegends** [comment]
Its reset now
