### ISSUE TITLE
Big Reactor Quests

### ISSUE THREAD

**Issue by perinmclaughlin** [MJRLegends/Space-Astronomy-Feedback-#322]
I believe you may have mis-entered the values for the hqm reactor quests. In the first quest you have to craft the casings 22 different times for a total of 88 casings. Also in the second quest for reactors you have to craft casings 113 different times for 452 casings. What to do with all those casings? I've seen this before in many different mod packs that use hqm. Just wondering if intentional, sorry if re-reporting.

**Comment by MJRLegends** [comment]
Will be fixed in the next update
