### ISSUE TITLE
Dna Splicer(Advanced Genetics) Freezes

### ISSUE THREAD

**Issue by perinmclaughlin** [MJRLegends/Space-Astronomy-Feedback-#323]
Occasionally the Dna Splicer will freeze for me and no progress will occur. Am on Windows 10. Apparently only occurs when the Splicer is having items withdrawn. Happens with every number of skin cell or number organic drops.
My Setup(The Splicer is receiving maximum power with leadstone or 200rf/t no upgrades in the item node either):
![screenshot 4](https://cloud.githubusercontent.com/assets/7523023/16098536/6b542ee4-3308-11e6-9d64-89fc048e4556.png)
The Bug:
![screenshot 3](https://cloud.githubusercontent.com/assets/7523023/16098518/4f214b1c-3308-11e6-8538-a1a1a85f2ca4.png)

**Comment by MJRLegends** [comment]
Yeah i know about this bug, the only fix i can think of that works is it take out the items and put them back in. Also the mod isnt updated anymore so it wont be fixed
