### ISSUE TITLE
Venus boss issues

### ISSUE THREAD

**Issue by braingkk** [MJRLegends/Space-Astronomy-Feedback-#33]
the boss in venus dungeons is dropping a diona t4 key instead of what should be venus t3.
also the boss's explosions are breaking the blocks so you need to constantly fly at it or the boss gets reset when you get pushed out of the original room

not sure if it is a pack issue or more planets, but figured i would post here

**Comment by MJRLegends** [comment]
This is a "More Planets" issue not a mod pack problem. Please report it to the developer of the "More Planets" mod
