### ISSUE TITLE
World not loading

### ISSUE THREAD

**Issue by leam360** [MJRLegends/Space-Astronomy-Feedback-#331]
Its only happening with one world.
I was in my base with a lot of machines at the time.
It first crashed when i was placing a second electrical furnace and now I can't get onto that world.
http://pastebin.com/Esg67dvQ
This is what it tells me to do but I don't wish to change it before I know it won't break it.

**Comment by MJRLegends** [comment]
Thats not even the crash log!!!

**Comment by leam360** [comment]
Is this it.
http://pastebin.com/w0fsqdrA

**Comment by MJRLegends** [comment]
Nope

**Comment by leam360** [comment]
What is then, the entire log
