### ISSUE TITLE
GalactiCraft Parachute 

### ISSUE THREAD

**Issue by BOSSthomas** [MJRLegends/Space-Astronomy-Feedback-#332]
When i Claim the Reward with the parachute and than i took the Blue parachute and turn it on 
and off and i close the menu.
I cant jump and not press F5 
when iam at Creative i can press F5 in fly and i see the parachute is on me and activated
Reload the Modpack help.

**Comment by MJRLegends** [comment]
This is a known thing with galacticraft and its weird and a rare bug also it cant be reproduced by the galacticraft devs as its been reported to them before
