### ISSUE TITLE
Missing Mouse

### ISSUE THREAD

**Issue by lookItsAPootis** [MJRLegends/Space-Astronomy-Feedback-#335]
I can't find the mouse anywhere
It's not visible

**Comment by WalaoEgg0424** [comment]
@lookItsAPootis 
https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/314

**Comment by WalaoEgg0424** [comment]
@lookItsAPootis btw , please read this :/
https://github.com/MJRLegends/Space-Astronomy-Feedback-/blob/master/CONTRIBUTING.md
follow the rules :/ , check for known issues or same issue that has already been reported
