### ISSUE TITLE
mouse

### ISSUE THREAD

**Issue by MOOZILLAONTHEGO** [MJRLegends/Space-Astronomy-Feedback-#340]
when i am on, my mouse doesn't show and it is annoying because i don't know where i am clicking

**Comment by WalaoEgg0424** [comment]
@MOOZILLAONTHEGO 
https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/314

Its a known issue , please check those closed issues :/ , you have to know that we dont have time to repeat everything that we have explain last time and explain to all of you again.
