### ISSUE TITLE
Immersive engineering Crash

### ISSUE THREAD

**Issue by epicepicgrolith** [MJRLegends/Space-Astronomy-Feedback-#341]
what had happened was that I was playing with my brother on a lan world and so we went throught the ender portal. everything was fine for a bit but shortly after I crashed and it completely exited me out of the game. when I tried to get back on I got to the main menu but when I tried to reload the world it crashed the same way as it did the first time. so I asked my brother to jump into the end portal in a creative world and he crashed the same way. I have tried deleting everything and then adding the world we were playing in and the mod chocolate quest because of the dungeons. what I believe it is is the world file itself. I think It is this because I could start space astronomy normally although I have not tried to enter the end portal again

**Comment by epicepicgrolith** [comment]
here is the long on pastbin
http://pastebin.com/JgMxWcGC

**Comment by WalaoEgg0424** [comment]
@epicepicgrolith can you provide the crash log , all i can see is just some texture error and some chunk error

**Comment by MJRLegends** [comment]
Yeah it should be in the crash logs folder not the log folder

**Comment by MJRLegends** [comment]
Yeah seems to be a mod bug and seems to be happening for a few people, i will report it to the mod dev of immersive engineering

**Comment by epicepicgrolith** [comment]
thanks for the help

**Comment by epicepicgrolith** [comment]
here is the crash log http://pastebin.com/1776LMvv

**Comment by epicepicgrolith** [comment]
is there any recommended ways i can fix this yet. i did try and remove
chicken chunks to no effect

**Comment by MJRLegends** [comment]
Removing Immersive Engineering and loading the world up then adding the mod back in but you will lose any Immersive Engineering blocks and items you have in your world

**Comment by epicepicgrolith** [comment]
ok i will try that

**Comment by epicepicgrolith** [comment]
i was able to get a little farther being able to see my player before it
had crashed. Here is the crash log http://pastebin.com/LvSZwBWL

**Comment by epicepicgrolith** [comment]
this happens with and without immersive engineering

**Comment by MJRLegends** [comment]
Its because your adding mods e.g chocolateQuest

**Comment by epicepicgrolith** [comment]
it causes the same thing meaning i can see my hotbar and player before
crashing with and without immersive engineering

**Comment by epicepicgrolith** [comment]
i will try to disable chocolate quest and immersive engineering. Chocolate
quest was the only mod i added

**Comment by epicepicgrolith** [comment]
that seemed to do it. it functions now so i will kill the ender dragon and
after that i will add the mods back in does that sound like it could work.

**Comment by epicepicgrolith** [comment]
now i have what appears to be a new issue i have removed immersive
engineering and chocolate quest but there appears to be a problem with
crossing dimensions i guess because when i went through the mining world
portal i had crashed the same way as going through the ender portal
http://pastebin.com/C7t41GKS

**Comment by WalaoEgg0424** [comment]
@epicepicgrowth https://github.com/MrTJP/ProjectRed/issues/1005
use mcedit remove those broken blocks then maybe it will be fixed?

**Comment by epicepicgrolith** [comment]
ok i will try

**Comment by MJRLegends** [comment]
This has nothing to do with ProjectRed??

**Comment by MJRLegends** [comment]
Please open a new issue if you got another issue

**Comment by MJRLegends** [comment]
We will close this issue and see if it comes up again, as chickenchunks was seen to be the issue and its now gone so hopefully its sorted

**Comment by Klade97** [comment]
@MJRLegends This doesnt help me at all and all of the other closed issues you told me to look at basically lead to this, i have not added any mods that are not in the pack originally and i still have world crashes when it hits the loading screen

**Comment by MJRLegends** [comment]
Its been posted 4 times its not hard just too look at the closed issues

**Comment by MJRLegends** [comment]
And its been reported to the mod devs so theres a issue on their issue tracker

**Comment by Klade97** [comment]
so bassically stop playing this modpack? ok fine

**Comment by MJRLegends** [comment]
At the end of the day your just being lazy and not looking, its not like it's hard to do it

**Comment by Klade97** [comment]
i have looked at the one created 6 days ago and the others and they dont help me when i dont have anything that deals with them like my world folder being named weird or having extra mods not in the gamedownload

**Comment by MJRLegends** [comment]
#341 all you had to do was go to the second page of the closed issues and its labeled "Immersive engineering Crash" so its easy to notice or go to the Immersive engineering issue tracker and its on there as a open issue too at the top

**Comment by Klade97** [comment]
this is #341 i already found this and it was the first one i clicked on

**Comment by MJRLegends** [comment]
Then you have the links to the reported issue post on their mod page

**Comment by Klade97** [comment]
so what i understood was that i should just not use quarries or IE?

**Comment by MJRLegends** [comment]
@Klade97 im not sure on the issue no one knows the issue, it seems to be a issue with them and Immersive engineering power stuff, i would suggest dont use Immersive engineering power with quarries or connect it to a power storage in the middle so Immersive engineering isnt directly interacting with the quarries

**Comment by Klade97** [comment]
oh ok sounds good then

**Comment by MJRLegends** [comment]
@Klade97 also sorry i didnt mean to sound rude beforehand just it gets annoying when people dont take the time to look at known issues page and closed issues and repost them :P

**Comment by Klade97** [comment]
yeah i understand it, also should i take out immersive integration as well?

**Comment by Klade97** [comment]
ok ik im not the best with coding and stuff like that but i moved the mod and config for IE to a folder on my desktop and loaded up minecraft and it says it couldnt be found. how would i get it to allow minecraft to load without it?

**Comment by MJRLegends** [comment]
Yeah because its a addon of the main mod and then you could add them back in and just not use them with quarries

**Comment by Klade97** [comment]
oh ok

**Comment by Klade97** [comment]
so how would i be able to load my world? cus my quarry is in the mining world with the IE water wheel and the capacitor for IE

**Comment by MJRLegends** [comment]
If you remove IE and and the integration addon and then load the world then readd the mods

**Comment by Klade97** [comment]
do i remove it before or after the mojang/fml loading at the begining?

**Comment by MJRLegends** [comment]
Close the mod pack remove it then load the mod pack and load the world then save and exit the world and close the mod pack and readd them back and load the mod pack and load the world

**Comment by Klade97** [comment]
well when i did that fml loaded everything and then it said that the mod couldnt be found and says to check the latest log for more info
