### ISSUE TITLE
Crashes on world load

### ISSUE THREAD

**Issue by EliasSvultz** [MJRLegends/Space-Astronomy-Feedback-#343]
http://pastebin.com/E1yCS9tx

**Comment by WalaoEgg0424** [comment]
@EliasSvultz its the same issue as this https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/341

**Comment by MJRLegends** [comment]
Please follow this next time https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/330
