### ISSUE TITLE
World Not Responding

### ISSUE THREAD

**Issue by CelloSuperstar** [MJRLegends/Space-Astronomy-Feedback-#344]
I'm not sure if this is a problem with the modpack, or my computer. In the two worlds I've tried to play on, they both randomly stopped working, becoming unresponsive and forcing me to exit the game. A few minutes after reloading the world it does it again without fail. I have put several hours into both worlds before the problem arose and I had really enjoyed the modpack up to this point. There's no correlation between when it started happened in either worlds, besides the fact that both happened not long after I started making machines.
![image](https://cloud.githubusercontent.com/assets/20100121/16288377/0b1115e0-38b9-11e6-8a0c-905d04055e8e.png)

**Comment by CelloSuperstar** [comment]
http://pastebin.com/Ry38PajY

**Comment by WalaoEgg0424** [comment]
@CelloSuperstar so there is no any crashlog?just some auto force exit?

**Comment by MJRLegends** [comment]
There is no problem here your computer probably just cant handle the mod pack

**Comment by CelloSuperstar** [comment]
I've never had any problems on FTB Infinity... even on servers. I guess I'll look around for another space exploration mudpack. Thanks for the help anyways.

**Comment by MJRLegends** [comment]
You could try increasing the amount of ram on the lanucher

**Comment by MJRLegends** [comment]
Or install OptiFine

**Comment by CelloSuperstar** [comment]
Alright, I will get optifine and see if it works.
