### ISSUE TITLE
Refined iron in thermal expansion induction smelter not working with pulverized coal

### ISSUE THREAD

**Issue by underspikey** [MJRLegends/Space-Astronomy-Feedback-#345]
Tried making refined iron (steel oredict) in an induction smelter. Tested around a bit and Thermal Foundation pulverized coal doesn't work, it just won't go in. Can't pipe it, can't click it in, nothing. IC2 dust works.

Version 1.4.5 of the pack.

**Comment by WalaoEgg0424** [comment]
Just tested it in my singleplayer world.

Thermal Foundation's pulverized charcoal does work , but pulverized coal doesnt works, other coal dust works. The recipe shows that you can use pulverized coal + iron ingot = refined iron but the machine doesnt accept the pulverized coal from Thermal Foundation.

**Comment by MJRLegends** [comment]
I can reproduce this bug but atm i cant find a way to solve it

**Comment by RalphFox** [comment]
Just a heads up. I've found your thread before finding the other thread, might as well as direct you people:
https://github.com/CoFH/Feedback/issues/1199
Been fixed in dev version.

**Comment by MJRLegends** [comment]
Added to the known issues page so will close this issue and i will keep a eye on the release for the fix
