### ISSUE TITLE
Digital miner

### ISSUE THREAD

**Issue by Estabane** [MJRLegends/Space-Astronomy-Feedback-#348]
I don't know if this a glitch or feature i'm unable to find documentation of but the digtal miner is not capable of mining below y 30 (i think?) i've placed a digital miner at y 70 a noticed no deep ores, then tried moving down to y 30, and y 5, still no res to my annoyance

**Comment by WalaoEgg0424** [comment]
@Estabane have you filter all the ores that you want to mine?

**Comment by MJRLegends** [comment]
Yeah you just haven't set it up correctly,therefore this is not a bug

**Comment by Estabane** [comment]
I set it up powered it set it max x+z coords to 32 and the max y coords to 255 and added in the filter ore* and let it run.it mined all the ores above it and in testing it would mine diamond or redstone ores placed near it above the y 30 mark.
