### ISSUE TITLE
Digital miner Issue

### ISSUE THREAD

**Issue by Estabane** [MJRLegends/Space-Astronomy-Feedback-#349]
I don't know if this a glitch or feature i'm unable to find documentation of but the digtal miner is not capable of mining below y 30 (i think?) i've placed a digital miner at y 70 a noticed no deep ores, then tried moving down to y 30, and y 5, still no ores to my annoyance
and
I set it up, i  powered it, set it's max x+z coords to 32 and the max y coords to 255 and added in the filter 'ore*' and let it run.it mined all the ores above 30 y and in testing it would mine diamond or redstone ores placed near it above the y 30 mark. I was unable to find any config or reason to not mine below the 30 y mark. Is there some update or feature that I'm missing in the usage of the digital miner.

**Comment by WalaoEgg0424** [comment]
@Estabane do u have skype?

**Comment by Estabane** [comment]
yes

**Comment by WalaoEgg0424** [comment]
@Estabane add me : yimer1821

**Comment by Estabane** [comment]
sent

**Comment by Estabane** [comment]
turns out i'm and idiot sorry for the trouble :P

**Comment by MJRLegends** [comment]
Please dont just repost the issue because i closed the other one

**Comment by Estabane** [comment]
I'm sorry I was unable to see the solution and felt it had not been addressed, and so I re-posted because i couldn't figure out any other options. Thank you for your patience with me, and thank you for the awesome modpack that has gotten me back into minecraft after an extended break.
