### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Speedy8g** [MJRLegends/Space-Astronomy-Feedback-#351]
I logged into my Server that 4-5 friends and myself play on and it looked like my space station got griefed, Nobody else is capable of space travel or would grief if they could. There was minecraft fences and pheunaticcraft pipes in and around my space station. The Fences i could break but when i break the pipes i get the internal server error. Also it would give me this error if i got too close to it. Somehow i got stuck in one of these pipes so every time i login i can see for a fraction of a second that im still on my space station and i can only assume that im too close to a pipe and it crashes. All of my other friends can still play and have access but it seems really weird that this happened. I can also post what the server console is saying, I am the server owner so i have access.

**Comment by MJRLegends** [comment]
Please follow these https://github.com/MJRLegends/Space-Astronomy-Feedback-/blob/master/CONTRIBUTING.md

**Comment by MJRLegends** [comment]
Also supply the crash log?

**Comment by Speedy8g** [comment]
26.06 21:49:07 [Server] Server thread/INFO [Mekanism]: Sent config to 'Speedy_8G.'
26.06 21:49:07 [Multicraft] Speedy_8g ran command Message of the Day
26.06 21:49:09 [Server] Server thread/WARN Failed to handle packet for /98.209.41.207:58226

**Comment by Speedy8g** [comment]
26.06 21:49:16 [Server] VoiceServer Listen Thread/INFO [Mekanism]: VoiceServer: Accepted new connection.
26.06 21:49:18 [Server] Server thread/WARN Can't keep up! Did the system time change, or is the server overloaded? Running 2188ms behind, skipping 43 tick(s)
26.06 21:49:21 [Server] Thread-2764743/ERROR [Mekanism]: VoiceServer: Unable to trace connection's IP address.

**Comment by MJRLegends** [comment]
Not the correct information and your ignoring this https://github.com/MJRLegends/Space-Astronomy-Feedback-/blob/master/CONTRIBUTING.md. so please repost when you have the correct information and follow the correct rules

**Comment by Speedy8g** [comment]
Really.... w/e
