### ISSUE TITLE
crashing when opening world

### ISSUE THREAD

**Issue by sgsbaihs** [MJRLegends/Space-Astronomy-Feedback-#354]
how can i do ''Solution 1: Delete this folder "ftblauncher\SpaceAstronomy\minecraft\Saves\YOURSAVE\HardcoreQuesting" replace "YOURSAVE" with your world folder name.'' if i'm playing on curse?

**Comment by WalaoEgg0424** [comment]
@sgsbaihs go into ur curse launcher folder  find spaceastronomy then minecraft\Saves\YOURSAVE\HardcoreQuesting" replace "YOURSAVE" with your world folder name.''
