### ISSUE TITLE
Gravi-Chestplate from Gravitation Suite isnt craftable

### ISSUE THREAD

**Issue by Revoolution** [MJRLegends/Space-Astronomy-Feedback-#355]
![2016-06-29_10 48 11](https://cloud.githubusercontent.com/assets/20208491/16456779/222c1134-3de7-11e6-88d7-ca44810e2aaf.png)
![2016-06-29_10 47 59](https://cloud.githubusercontent.com/assets/20208491/16456783/2472468e-3de7-11e6-97da-ca1a0af33733.png)

I believe the problem is the advanced heat exchanger has a different ID than the recipe requires, and so does the 60k coolant cell. They both have :1 at the end of them.

**Comment by MJRLegends** [comment]
Will be fixed for update v1.4.7

**Comment by MJRLegends** [comment]
Fixed see message above
![](https://i.gyazo.com/c162654b73aedd433da8e73b8bac1d92.png)
