### ISSUE TITLE
Version 1.4.6 is unstable

### ISSUE THREAD

**Issue by Markus9063** [MJRLegends/Space-Astronomy-Feedback-#356]
My pc crashed because of VeinMiner, plz remove Veinminer and fix the issue (BIG!) i do not have any crash reports because i had to turn my pc off manualy, dont uppdate

**Comment by MJRLegends** [comment]
How the hell is this a bug

**Comment by MJRLegends** [comment]
One you haven't supplied any logs and your rude being rude about it

**Comment by Markus9063** [comment]
i got two crashed, first time it was when i tried to break a tree and it was because of veinminer
first crash report: https://drive.google.com/file/d/0B9F48NUZxjYqWHdjWkxCQ0phT2M/view?usp=sharing
