### ISSUE TITLE
1.4.6 Update has invisible text everywhere on Mac OS

### ISSUE THREAD

**Issue by MineKity** [MJRLegends/Space-Astronomy-Feedback-#358]
Hi, I just upgraded to 1.4.6 on a local single player machine.

Text on the starting screen, loading screen for single and multiplayer, all text on blocks and in the quest book are blank making the build unplayable. If you know where to click on the pages, the links work fine, you just cannot read what you are clicking anywhere. I believe this is a visual bug, but it makes it very hard to play since you can't get additional information on anything.

I run on a Mac OS X Yosemite 10.10.5.
I'm running on Java 1.7.0_67, I do get a warning telling me to upgrade to 1.8, but when I try this it says 1.8 is not compatible on Mac OS.

If I downgrade FTB Launcher to 1.4.5, I still get the Java 1.8 warning, but the game works fine. I can provide any logs that you need, but I am newer to installing the game and may need some help to pull the correct log or configuration files.

**Comment by MJRLegends** [comment]
Do you have OptiFine installed? If yes removed it and try and remove fastcraft mod

**Comment by MineKity** [comment]
I verified that I do not have OptiFine Installed. I did remove fastcraft mod and restarted. Once I did this instead of invisible text I now get white blocks. This is slightly better because at least you can now see where the buttons are supposed to be as the white blocks take on the color of whatever the text is supposed to be, however you still can't read any actual writing.

**Comment by MineKity** [comment]
This almost seems like a font issue? However, I am unsure if minecraft actually uses fonts (:

**Comment by MarcasRealAccount** [comment]
@MineKity Minecraft uses fonts, check this picture from .minecraft\versions\1.7.10\1.7.10.jar\assets\minecraft\textures\font\
![unicode_page_00](https://cloud.githubusercontent.com/assets/20221636/16493189/da705f04-3ee4-11e6-82ab-4c4d25f86f6b.png)

**Comment by MineKity** [comment]
I'll have to check when I get home tonight. I'm assuming I should check
this after moving back to 1.4.6 correct?

**Comment by MineKity** [comment]
OK, I checked this in both 1.4.5 and 1.4.6. The font *.png files appear to be transparent with white text and they appear to look the same both before and after the upgrade, so it may not be a font issue. This should be the directory that the quest book and the front loading screens use for the text right? I also tried disabling a bunch of other modes (NEI, ChickenCodeCore, Waila, etc.) but the game wouldn't start with some of these disabled. I also tried removing the splash.properties file just for grins but no luck there either. I found another couple errors around the same thing both with 1.8 and 1.7 on MacOS but no definitive answers. Is there any other mods I can try disabling that might render text? I also tried searching the config files for fast render, antialiasing, or anistropic, but these hits did not yield any results. It is possible I spelled them wrong or they are case sensitive, but I wasn't sure what else to try. If this is truly a mac problem and not a mod problem I am fine closing this, but I do appreciate the help you have provided so far.

**Comment by MJRLegends** [comment]
No idea tbh it seems to be a mac only issue

**Comment by MJRLegends** [comment]
Maybe try install OptiFine?

**Comment by MJRLegends** [comment]
@MineKity whats the latest on this issue?

**Comment by MineKity** [comment]
I'm not sure how to install OptiFine. You can close this though, I can wait until the next release and see if it fixes itself. It seems to be a random Mac issue that occasionally crops up with minecraft. So far no one has a root cause.

**Comment by MJRLegends** [comment]
Yeah no problem and yeah i think its a minecraftminecraft issue or forge issue maybe contact them
