### ISSUE TITLE
Getting Upgraded Tools Quest Bug?

### ISSUE THREAD

**Issue by MineKity** [MJRLegends/Space-Astronomy-Feedback-#359]
I'm not sure if this is a bug or by design, but the "Getting Upgraded Tools Quest" seems to take every tool forge except 1255:5 which is the half high one from Tinker's Construct.

**Comment by MJRLegends** [comment]
Will look later as dont have my laptop or computer with me to test

**Comment by MineKity** [comment]
No problem! Thanks for the quick reponse!

**Comment by MJRLegends** [comment]
Please can you tell me what one is it as my i'ds are different to yours
![image](https://cloud.githubusercontent.com/assets/8526321/16471462/c0bfe614-3e54-11e6-83de-4b75cf2441ff.png)

**Comment by MineKity** [comment]
It is the last row next to the book with the note on it.

**Comment by MJRLegends** [comment]
Its because its a different block all together you need to craft this one 
You need to craft these ones
![](https://i.gyazo.com/011a2d44a60fdeaa9f93aba4e60c3cde.png)

**Comment by MineKity** [comment]
OK thanks! May want to put a note in the quest book, but just my 2 cents.
