### ISSUE TITLE
Cannot load any single player worlds

### ISSUE THREAD

**Issue by Rezendore** [MJRLegends/Space-Astronomy-Feedback-#360]
As far as I have looked for the past 10 hrs I have found nothing about this issue. There is no crash log, but whenever I attempt to load any world or even create a new world, it will start loading then bring me to the main screen. This has been happening since my power went out while in game. I have tried to remove hqm from the mod folder and that has not helped.

**Comment by MJRLegends** [comment]
Well i need more than it wont load??

**Comment by Rezendore** [comment]
When I load the game up. I encounter no issues and when I go to click around the main menu there are no issues. When I attempt to click "launch" on any world the world will start to load by showing the dirt loading screen and the word "loading". The world will stop loading and bring me back to the main menu. I am not crashing, just being re-directed to the main menu. I have no idea how to access any logs.

**Comment by MJRLegends** [comment]
I need logs?

**Comment by Rezendore** [comment]
I need to know how to get the logs.

**Comment by MJRLegends** [comment]
i need the console log which can be found in the logs folder

**Comment by Rezendore** [comment]
I can't paste the logs here and pastebin says this You have exceeded the maximum paste size of 512 kilobytes per paste.

**Comment by Rezendore** [comment]
There we go, I had to change it from a .log file to a .txt file
[fml-client-latest.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/340439/fml-client-latest.txt)

**Comment by MJRLegends** [comment]
can you send me the log with the filename "latest"

**Comment by Rezendore** [comment]
[latest.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/340446/latest.txt)

**Comment by MJRLegends** [comment]
thats not a good enough log as its like 23 lines long (latest.txt one)

**Comment by Rezendore** [comment]
So what do I do to get a better log?

**Comment by Rezendore** [comment]
[18:21:47] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[18:21:47] [Server thread/INFO]: Generating keypair
This continues to be repeated when I attempt to load my world

**Comment by Rezendore** [comment]
Okay. I have made a little bit of progress. After deleting the mod and re-installing it. I created a new world and it worked perfectly, the world loaded up and I was able to work with it. When I took the save file that initially had the issue and tried to load it up in this new instance. The same error occured. When I tried to load up the other save file that had worked earlier, I received the same error as well. So this means it is indefinitely a problem with the save file. I checked the log and it is the same as what I had posted prior. Is there any way I could get the save file to you for testing purposes?

**Comment by MarcasRealAccount** [comment]
This is the crash report from fml-client-latest
Hope it helps :)
 [Crash report.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/340988/Crash.report.txt)

**Comment by Rezendore** [comment]
@MarcasRealAccount Is this your crash report?

**Comment by WalaoEgg0424** [comment]
@MarcasRealAccount do u know what does crash report means? Its a file that is generate by minecraft if theres a crash , that fml client latest is just a log that records the launcher console like what is the minecraft and launcher doing.

**Comment by WalaoEgg0424** [comment]
@Rezendore the only thing i can think of is world files corrupted

**Comment by WalaoEgg0424** [comment]
@Rezendore all i can see is enderchest from codechicken gt problem . make a backup of ur world , then go into ur world folder , delete EnderStorage. But careful that all ur stuff that is inside the enderchest that you are having will lost.

**Comment by MarcasRealAccount** [comment]
@Rezendore it was from your fml-client-latest, found it so i could help.
@WalaoEgg0424 I know what a crash report is, but that is a crash report from fml more spesific one.

**Comment by Rezendore** [comment]
Wow. Deleting enderstorage allowed my world to load and update. Thanks for looking at my files and helping out @MarcasRealAccount and @WalaoEgg0424 . One more question though, in the new world all of my Applied Energistics items are gone, except for some ME drives. Also, all of my enderio items are gone as well :/ Any clue why these would have been replaced with stone?

**Comment by MJRLegends** [comment]
Nope

**Comment by Rezendore** [comment]
Wow! This is super odd! Apparently it reverted the chunk that had anything removed by the update to what it was like before I edited the chunk. It sliced exactly one chunk's worth of my stuff out and left everything else in tact.

**Comment by MJRLegends** [comment]
To be honest i think your world is all messed up and corrupted

**Comment by Rezendore** [comment]
I agree, but I can still play on it as of current, I will just need to backup every couple of hours to be sure. Again, thanks for looking into things for me and helping out.

**Comment by MarcasRealAccount** [comment]
No problem
