### ISSUE TITLE
1.4.6 Quest book

### ISSUE THREAD

**Issue by MarcasRealAccount** [MJRLegends/Space-Astronomy-Feedback-#363]
I think you messed up in the quest book, i know its not a bug.
![quest book](https://cloud.githubusercontent.com/assets/20221636/16481961/1ada9e1a-3eae-11e6-86fa-15b8eac64e69.png)
btw when are you going to uppdate the modpack?

**Comment by MJRLegends** [comment]
Fixed in next update

**Comment by MarcasRealAccount** [comment]
ok, btw when is the next uppdate coming up?

**Comment by MJRLegends** [comment]
Idk
