### ISSUE TITLE
1.4.6 seems to not have the electrolytic separator shown in NEI

### ISSUE THREAD

**Issue by LargeDoot** [MJRLegends/Space-Astronomy-Feedback-#365]
Hi, just upgraded my server and began playing and noticed that the electrolytic separator (mekanism) is hidden in NEI.  I'm using the FTB launcher. Not many more details i can think to give, but i can give more info if necessary.
Cheers

**Comment by MJRLegends** [comment]
You can still craft it then but i will have a look
