### ISSUE TITLE
OFFICIAL SERVER IS DOWN!

### ISSUE THREAD

**Issue by MJRLegends** [MJRLegends/Space-Astronomy-Feedback-#367]
Hosting issue again, will be back soon hopefully

**Comment by Ashdeep10** [comment]
Thanks that a relief

**Comment by Ashdeep10** [comment]
thats*

**Comment by MarcasRealAccount** [comment]
ok, well im not really playing on it but i noticed it was down thought you were uppdating it or something like that, btw im playing on Frozensoul's Space Astronomy server

**Comment by Gabei17** [comment]
Do you know when the server will be back up??

**Comment by MJRLegends** [comment]
Nope sorry :(

**Comment by Gabei17** [comment]
Will it be back up soon? :/

**Comment by MJRLegends** [comment]
You just asked that question lol

**Comment by Gabei17** [comment]
Brilliant lol

**Comment by BlackAsLight** [comment]
What's it looking like now?

**Comment by MJRLegends** [comment]
Update 1: Still awaiting a reply from them.... :(

**Comment by Gabei17** [comment]
I hope they reply soon cause i'm anxious to get back to me pies.

**Comment by MJRLegends** [comment]
Update 2: The hosting company owner is having health issues so thats why replies were slow but hes trying to fix it but thats hard when hes in hospital. But hes working on it.

**Comment by xXHastinqXx** [comment]
yeah... I'm anxious to get back to selling cream at McCream... #blame dean

**Comment by Gabei17** [comment]
Same, I'm anxious to get back to me pies

**Comment by xXHastinqXx** [comment]
ello gabei

**Comment by xXHastinqXx** [comment]
i am playing all the mods for minecraft 1.10.2 and am loving the new tinker's construct ... also love psi by vazkii but back to the topic of the server, i am kinda missing the server and i need to stop PM'ing MJR on curse and do moar github

**Comment by Revoolution** [comment]
ah yea good ol vazkii, also whattup hastinq. After seeing in 1.4.7 that the gravi chestplate was fixed, im now excited to finally make it...

**Comment by xXHastinqXx** [comment]
ello

**Comment by Gabei17** [comment]
Ello

**Comment by Gabei17** [comment]
If the server gets back on today tommorow and possibly Tuesday I won't be
able to get on cause I'm at my grandmas and I'm making pies

**Comment by Revoolution** [comment]
yea hastinq I agree, its now a casual chat, rather than to mourn for the servers death.

**Comment by MJRLegends** [comment]
This issue isn't for general related chat.

**Comment by xXHastinqXx** [comment]
did you remove my messages from this thread?...
i shun you for being antisocial XD

**Comment by Gabei17** [comment]
Any new updates from the hosting company?

**Comment by MJRLegends** [comment]
See update 2 above

**Comment by Darklord957** [comment]
Thanks for keeping us posted, hope the host gets better.

**Comment by Gabei17** [comment]
Kk

**Comment by xXHastinqXx** [comment]
I actually tried to log onto the hosting site olympusservers and the other one and it says the website for the hosting company is actually down.

**Comment by Gabei17** [comment]
Same

**Comment by Gabei17** [comment]
So I guess all servers that use that hosting service are down too?

**Comment by xXHastinqXx** [comment]
yes, through all games that use the  hosting site as well which is bad because some steam game servers may be down as well.

**Comment by MJRLegends** [comment]
Please stop using this issue for chat purposes

**Comment by xXHastinqXx** [comment]
sorry

**Comment by xXHastinqXx** [comment]
this is most likely the longest time the server has been down ... ever... and i really hope the host is okay... we should be more worried about the host than the server.

**Comment by rexrapter1234** [comment]
Is the server back up and running or still down? If so I can't seem to login to the server. (Can't connect to server) message.

**Comment by MJRLegends** [comment]
Did i say it was back up???

**Comment by rexrapter1234** [comment]
I was reading the other topic (World Crash after updating to 1.4.7 on server) and thought maybe it was backup then when down again.

**Comment by MJRLegends** [comment]
The new servers are live(restart your mod pack if loaded and the new ip will be in your server list), server 1 which this issue is about and is the original old server will be back soon its half sorted atm :P

**Comment by MJRLegends** [comment]
Server 1 is now live (old server)
