### ISSUE TITLE
Corrupted Mods Folder when Updated to 1.4.6

### ISSUE THREAD

**Issue by LuizLoyola** [MJRLegends/Space-Astronomy-Feedback-#369]
I updated the modpack to the last version, but it keeps getting NullPointerException, so I found out that the "mods" folder is corrupted. I backed up and deleted every file of the launcher and redownloaded everything, but the issue continues.

Here's the log.
[fml-client-latest.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/342542/fml-client-latest.txt)
(Srry 4 bad english, I'm brazilian)

**Comment by MJRLegends** [comment]
From what i can see your not using the launchers that the mod pack is on correctly so its a bug on your side, reinstall the launchers properly and redownload the mod pack and it will work
