### ISSUE TITLE
Found a virus in the modpack, read this

### ISSUE THREAD

**Issue by Markus9063** [MJRLegends/Space-Astronomy-Feedback-#370]
People there is Viruses in MJRLegends' mods, decompiled his mods and found a virus

**Comment by MarcasRealAccount** [comment]
My pc died today so i can't help (typing on phone) and i decompiled the mods and i didn't find a virus, and where is the proof of the virus?

**Comment by MJRLegends** [comment]
There are no virus so stop talking crap

**Comment by MJRLegends** [comment]
He's just trying to cause me pain because all my custom mods have their source code on my github

**Comment by badgernz** [comment]
Kid, stop talking crap and trying to cause trouble... I've never had any issues with any mods produced by mjrlegends. 
OP is just trying to cause shit...

**Comment by MJRLegends** [comment]
My custom mods that ive made for the mod pack https://github.com/MJRLegends/Space-Astronomy-Tweaks and https://github.com/MJRLegends/MorePlanetsExtras

**Comment by WalaoEgg0424** [comment]
@Markus9063 such a kiddo , if there is virus in MJRLegends's mods , he will get banned from posting any further mods or updates . Dont give any fucking fake information cuz i really hate them. Dont make me fucking ruin ur life.
