### ISSUE TITLE
Space Astronomy Crash when I start singleplayer World

### ISSUE THREAD

**Issue by X3rion** [MJRLegends/Space-Astronomy-Feedback-#371]
The Modpack crash when i try open the singleplayer world... After some secs the whole game crash and i get back to the Launcher
- X3rion

**Comment by MJRLegends** [comment]
Crash log????????

**Comment by X3rion** [comment]
Ehm... Now i installed the new version and the World loads... The problem is, that all Quests got deleted

**Comment by X3rion** [comment]
What up now?

**Comment by WalaoEgg0424** [comment]
@X3rion what do u mean by all quests gt deleted?
