### ISSUE TITLE
Crash when accessing 7x7x7 Big Reactor with 5 Rods and Enderium

### ISSUE THREAD

**Issue by Tithonius** [MJRLegends/Space-Astronomy-Feedback-#374]
I have a big reactor that is 7x7x7 and has 5 fuel rods. The reactor has no fuel in it yet, but when i access it the game crashes. The crash log is as follows:

[crash-2015-11-29_13.37.44-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/344497/crash-2015-11-29_13.37.44-client.txt)

**Comment by WalaoEgg0424** [comment]
@Tithonius Its the hqm problem , this is a known issue , u can check at known issues there.
