### ISSUE TITLE
AE 2 Null Checks

### ISSUE THREAD

**Issue by Tithonius** [MJRLegends/Space-Astronomy-Feedback-#377]
Game crashes upon reentering the overworld. AE 2 doesnt do proper null checks
[crash-2016-07-02_19.54.53-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/344846/crash-2016-07-02_19.54.53-client.txt)

**Comment by WalaoEgg0424** [comment]
@Tithonius you habing quantum rings?

**Comment by WalaoEgg0424** [comment]
@Tithonius Your quantum singularity links for your ME system aren't being properly chunkloaded maybe

**Comment by Tithonius** [comment]
Maybie, but you guys took out the only reliable chunk loader we had. You
removed the Chunk Loader from chicken chunks. the only other options we
really have are the world anchors, and they dont agree well with dimensions

**Comment by Tithonius** [comment]
we have the other ones that use fuel and RF too, but they only load a max of 2 chunks. We need chunk loaders back

**Comment by WalaoEgg0424** [comment]
@Tithonius im sorry , dis is all i can do cuz im not the modpack owner.

**Comment by Tithonius** [comment]
nah your right. I can make it work. thanks for the tip

**Comment by WalaoEgg0424** [comment]
@Tithonius your welcome :)

**Comment by MJRLegends** [comment]
@Tithonius please look at this next time and dont ignore it 

![](https://i.gyazo.com/3280883eada7145419fae79ec5ac98be.png)

**Comment by Tithonius** [comment]
I checked and this issue wasnt on there, so dont yell at me

**Comment by MJRLegends** [comment]
@Tithonius 
![](https://i.gyazo.com/f8c956066280ae8702f0266bf12c79f5.png)
