### ISSUE TITLE
Tinkers' Construct Lumber axe Crash

### ISSUE THREAD

**Issue by weetabixboy** [MJRLegends/Space-Astronomy-Feedback-#378]
Been playing for a while and never had this problem at first. When ever I use a lumber axe from tinkers' construct it crashes my client the moment the block is about to break. It never used to happen and has only recently started to happen, I understand the pack has vein miner installed but it's not so great with cutting down whole tall trees, I understand it's due to the area of effect config for veinminer but I tend to upgrade to a lumber axe as soon as possible because then it's a small step in progression and stops vein miner feeling so cheaty ;P

Pastebin for the crash log: [http://pastebin.com/DLg5wvJc](url)

**Comment by MJRLegends** [comment]
Update your mod pack
