### ISSUE TITLE
World Crash after updating to 1.4.7 on server

### ISSUE THREAD

**Issue by cogscreamsrage** [MJRLegends/Space-Astronomy-Feedback-#379]
Server works fine running 1.4.6, but updated to 1.4.7 and server crashes while loading the world.

http://pastebin.com/ac47saBD

**Comment by MJRLegends** [comment]
Solution 1: Remove computronics, then load the world and then readd the mod (But all computronics will be removed)
Solution 2: Use MCEdit to get rid of this block at these coords 515,72,253 (X,Y,Z)

**Comment by cogscreamsrage** [comment]
Worked, Server has been updated, and running smoothly
