### ISSUE TITLE
Crash with Travel Anchor

### ISSUE THREAD

**Issue by xXLightAngelXx** [MJRLegends/Space-Astronomy-Feedback-#381]
http://pastebin.com/raw/P3mAEn1c

**Comment by xXLightAngelXx** [comment]
Thats the log

The issue I spotted is Forge Multipart being too far ahead of requested version it also has soem other mo issues showing in the log but I brushed them aside as they are probally being worked on

**Comment by WalaoEgg0424** [comment]
@xXLightAngelXx delete ur last issue == , btw POST AT PASTEBIN.COM , or else we are not gonna help u.

**Comment by xXLightAngelXx** [comment]
sorry i will  ^-^

**Comment by xXLightAngelXx** [comment]
I cant it happend last night ...

**Comment by xXLightAngelXx** [comment]
theer ^-^ straight from pastbin

**Comment by MJRLegends** [comment]
This issue is the same as the #380 one you posted? looking at the crash logs

**Comment by MJRLegends** [comment]
Did you change your username for minecraft?

**Comment by MJRLegends** [comment]
Or did you delete any files before this came up?
