### ISSUE TITLE
Forge: Non Mods detected in Mod folder

### ISSUE THREAD

**Issue by xXLightAngelXx** [MJRLegends/Space-Astronomy-Feedback-#382]
The Modpack is beign forced by the Modloader to ru nthe Non mods that are automattically insatlled within the Mod folder, this in turn can caus serve Stabaility issues and in the logn run can break a lot of the mods depending on the serverity of the issue.

the mod loader itself reccommeds removing the non-mods fro mthe mod folder so I can save u having to lose the non-mods by reccoemding coding the modpack to load non-mods from their own folder.

The link bellow will take you to log diorectly on website it is uploaded to by default when clicking the "upload log" button on the consol:

http://paste.feed-the-beast.com/view/3bb7ef4d

**Comment by MJRLegends** [comment]
I dont see a issue in this log you can supplied also follow this
![](https://i.gyazo.com/f8c956066280ae8702f0266bf12c79f5.png)

**Comment by WalaoEgg0424** [comment]
@xXLightAngelXx why there r Modloader when ftb is using forge ._.
