### ISSUE TITLE
Forge Mod Loader has found a problem with your minecraft installation...

### ISSUE THREAD

**Issue by Gameplayer01** [MJRLegends/Space-Astronomy-Feedback-#383]
When i start the modack (from curse launcher), it say this and cant play:
Forge Mod Loader has found a problem with your minecraft installation. You have mod sources that are duplicate within your system.
Mod Id: File name
SpaceAstronomyTweaks-1.0.jar
SpaceAstronomyTweaks-1.1.jar
 
PLEASE FIX IT
 
sorry bad english

**Comment by MJRLegends** [comment]
Reinstall the mod pack
