### ISSUE TITLE
Game crashes because of EnderIO

### ISSUE THREAD

**Issue by Klade97** [MJRLegends/Space-Astronomy-Feedback-#384]
IDC if this is in the wrong place or not and i cant find anything on pastebin so help me.
[crash-2016-07-04_21.53.46-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/347111/crash-2016-07-04_21.53.46-server.txt)
idk exactly how to uninstall that rv3 and go for rv2 but its what curse downloaded for me

**Comment by WalaoEgg0424** [comment]
@Klade97 bro , pastebin is u paste ur crashlog into there and give us the link. :/

**Comment by Klade97** [comment]
dude honestly idk how any of this works cus im not a modder and normally dont have to report anything

**Comment by WalaoEgg0424** [comment]
@Klade97 u just copy the whole log and paste into pastebin then it will generate a link for u , how hard is it :/

**Comment by Klade97** [comment]
ok

**Comment by Klade97** [comment]
http://pastebin.com/xtesG9Yn

**Comment by WalaoEgg0424** [comment]
@Klade97 this is not a crash by enderio , might have something to do with Immersive Engineering.

**Comment by Klade97** [comment]
then what exactly is line 400 meaning?

**Comment by WalaoEgg0424** [comment]
@Klade97 that enderio sentence have nothing to with crash , its just like fighting with AE2 rv3 but that doesnt crash the game.

**Comment by WalaoEgg0424** [comment]
@Klade97 btw what are u doing in ur world while u get this crash?

**Comment by Klade97** [comment]
oh. so what do i do then? cus it was loading up everything and now when i create or play a world it says the first thing it normally says when loading the world and then crashes

**Comment by Klade97** [comment]
i was walking around looking for an AE2 Meteor to mine

**Comment by WalaoEgg0424** [comment]
@Klade97 you create a world crash and play a world also crash?

**Comment by Klade97** [comment]
the other day it crashed when i hit a tree with my hand and now its just crashing when i walk

**Comment by Klade97** [comment]
yup

**Comment by WalaoEgg0424** [comment]
@Klade97 @MJRLegends might know how to fix it.Its weird that theres no result when i google it , not same as urs crashlog.

**Comment by Klade97** [comment]
right
i actually opened an issue the other day and he got mad at me and closed it, idk why but he told me to update and i was already updated to the latest on curse

**Comment by WalaoEgg0424** [comment]
@Klade97 he gt mad at u cuz u didnt paste the long at pastebin.com , ur modpack is the latest version i think cuz of the version of the TiC is same as the latest version of the modpack.

**Comment by Klade97** [comment]
on curse it says im at 1.4.7

**Comment by WalaoEgg0424** [comment]
@Klade97 do u have skype?

**Comment by Klade97** [comment]
on my phone but ppl at my house are asleep

**Comment by WalaoEgg0424** [comment]
@Klade97 nvm , @MJRLegends will take care of it. im sorry that i cant help u.

**Comment by Klade97** [comment]
its all good man, thanks for trying

**Comment by MJRLegends** [comment]
Already reported issue go look at closed issues
