### ISSUE TITLE
Mod missing: AE2 Stuff

### ISSUE THREAD

**Issue by ninosfl** [MJRLegends/Space-Astronomy-Feedback-#385]
Modpack version 1.4.7
Windows 10
Java version "1.8.0_91"
Launcher version 7.1.6018.41463 Beta

Steps to recreate:
(Curse launcher)
Click Minecraft (icon)
Click BROWSE ALL MODPACKS
Search for "Space Astronomy" and install it.

Expected behaviour:
AE2 Stuff should be included as it is requirement for some quests.

What went wrong:
AE2 Stuff is missing/not installed.

**Comment by WalaoEgg0424** [comment]
@ninosfl try reinstall the modpack?

**Comment by MJRLegends** [comment]
yeah @WalaoEgg0424 @ninosfl
