### ISSUE TITLE
Official Server (Space 2) Quarry Not Mining

### ISSUE THREAD

**Issue by JackDT** [MJRLegends/Space-Astronomy-Feedback-#386]
Within the official server in the mining world dimension, i placed a quarry in my claim land powered by 4 stirling engines. At first, only one face of the frame appeared. The arm attempted to mine blocks, and it plays the breaking animation, but the block is not broken or placed into the chest. The arm then moves on to the next block and continues not breaking any blocks.

**Comment by Gabei17** [comment]
I've had this issue too but I don't get it

**Comment by Luxxx-R** [comment]
<The Quarry's Frame Must be outside of the claim.> The Quarry Block CAN be inside if you want it.

**Comment by Luxxx-R** [comment]
the frame has to be outside the claim

**Comment by Gabei17** [comment]
Well that's good to know

**Comment by JackDT** [comment]
I removed the claim and it fixed it... So it seems that the frame can not build within my claim

**Comment by MJRLegends** [comment]
Yeah you cant claim the area its mining only the quarry block and your power and storage
