### ISSUE TITLE
Game corrupts world on exit

### ISSUE THREAD

**Issue by kde99** [MJRLegends/Space-Astronomy-Feedback-#388]
When I make a world and quit the game corrupts the save file (level.dat and level.dat_old) so I can never play that map again. It happens 99% of the time and the log shows nothing. It also doesn't save other players' inventories (when the game is opened on LAN). When someone logins grabs something and the relogs it's gone and they get the starting inventory.

What can cause such behavior? This also happens with most 1.7.10 modpacks. Redownloading doesn't help. Checked the disk: no error. I'll include log in a few hours.

**Comment by MJRLegends** [comment]
This isnt anything i can reproduce and your lack of detail on the issue isnt enough for me to do anything and it seems tbh to be a issue on yourside
