### ISSUE TITLE
Questbook bug

### ISSUE THREAD

**Issue by Webster1981** [MJRLegends/Space-Astronomy-Feedback-#389]
Hello i have a problem with my Questbook
The Quest Storage System is still on the first Quest and ends

Sorry for my bad english!
![2016-07-06_18 36 18](https://cloud.githubusercontent.com/assets/20323793/16626360/cc5864ac-43a8-11e6-9bfe-98ef9ff8fcc2.png)

**Comment by Webster1981** [comment]
![2016-07-06_18 38 47](https://cloud.githubusercontent.com/assets/20323793/16626388/ef6d3080-43a8-11e6-9030-4b9efeeb8f3c.png)

**Comment by MJRLegends** [comment]
Its not a bug you just need to do other quests in other sections of it
