### ISSUE TITLE
Curse got 1 mod less

### ISSUE THREAD

**Issue by TPRammus** [MJRLegends/Space-Astronomy-Feedback-#39]
In Curse, the "[FMLMod:ae2stuff{0.5.0.56}]" is missing. I know that because I got the server files from the FTB launcher, but the client files from curse.
The version is 1.2.6 (in 1.2.5, it misses too).
Hope, I could help :)

mfg,
TPRammus

**Comment by MJRLegends** [comment]
Its showing on mine? try reinstalling the mod pack on the curse launcher.

**Comment by TPRammus** [comment]
Reinstalled but still have to paste the "ae2stuff-0.5.056-mc1.7.10.jar" manually in the mods folder.

**Comment by MJRLegends** [comment]
I have re downloaded it on the FTB and Curse Launchers and the "ae2stuff" mod is in both as intended?

**Comment by TPRammus** [comment]
You're right, sorry :)
