### ISSUE TITLE
Mekanism: Electrolytic Separator HUGE power draw

### ISSUE THREAD

**Issue by LargeDoot** [MJRLegends/Space-Astronomy-Feedback-#390]
Hi,
Really sorry if this is the wrong place for this / this is a mod bug, but the power draw required by a fully upgraded electrolytic separator is crazy (about 20.4kRF/t each), and to make enough oxygen to supply an elite purification factory (also fully upgraded with speed and energy) you need 7 of the separators. This totals to almost 150kRF/t just for ore tripling, which is obviously a substantial amount. I have a few screenshots too:
-http://prntscr.com/bpkm7w (The setup I'm using)
-http://prntscr.com/bpksm1 (Upgrades inside the separator)
-http://prntscr.com/bpkt35 (The power information in the separators)

Is this a config issue or a mod issue??
Thanks, LargeDoot

**Comment by Hazmatik** [comment]
I'm pretty sure they are intended to be that way so not to make infinite energy with the hydrogen and the gas burning generators. Galacticraft oxygen can be used in Mekanism machines however for a cheaper alternative.

**Comment by MJRLegends** [comment]
@aidancbrady is this meant to be like this?

**Comment by LargeDoot** [comment]
@Hazmatik Can you tell me how I can use the galacticraft oxygen for this as I have tried many methods suggested on forums (etc.) to no avail.
