### ISSUE TITLE
 The Modpack does not Launch

### ISSUE THREAD

**Issue by Awkiller** [MJRLegends/Space-Astronomy-Feedback-#391]
When ever I try and Launch the Game from FTB It Gives no information in the console but 

"Unable To Launch"

And I have disabled the OpenComputers mod thinking it would help and it still does not launch

**Comment by MJRLegends** [comment]
Send me the log please

**Comment by Awkiller** [comment]
Ok the link to the log is  http://paste.feed-the-beast.com/view/3a39cb3c   or  http://paste.feed-the-beast.com/view/b5a75af4

**Comment by MJRLegends** [comment]
Try reinstalling all the launcher and also try adding more ram

**Comment by Awkiller** [comment]
Ok well Reinstalling it worked
