### ISSUE TITLE
Quest: Starting Big Reactors does not complete

### ISSUE THREAD

**Issue by cungefehr** [MJRLegends/Space-Astronomy-Feedback-#393]
Hello folks,

the "Starting Big Reactors" Quest is currently not able to complete - the Detection won´t detect "Big Reactor Casings". I tried manually detect too, but it does not do the trick.

The Fuel Rod was completely accounted for.

Thanks,

**Comment by MJRLegends** [comment]
Sorry i completely missed your issue, i will take a look and get back to you

**Comment by cungefehr** [comment]
Update: Our server admin / group leader was able to finish the quest without issues. How and why this happened we don´t know.
