### ISSUE TITLE
Planet crash issue with the official server

### ISSUE THREAD

**Issue by Spellkaze** [MJRLegends/Space-Astronomy-Feedback-#394]
I found.. .something not so confortable to say, with all the problems in the server about the planets and crahses, i logged out from dark asteroids and now i crash everytime in server 1, it was a test, since i dont play in server 1 i dont mind, check it: http://pastebin.com/GaexB940

This issue seems to happend only in the official server

**Comment by MJRLegends** [comment]
Solution use direct ip for official server

Hover over player count for the server in your multiplayer server list

**Comment by MJRLegends** [comment]
Any chance you try and reproduce this again as ive made some changes to the servers

**Comment by Spellkaze** [comment]
The same crash as always, the crash report seems a bit different but i don't know if actually helps for something http://pastebin.com/F22vrBbT
The direct ip workaround still fixes this issue
