### ISSUE TITLE
Crash when opening inventory

### ISSUE THREAD

**Issue by KeepItTrill24** [MJRLegends/Space-Astronomy-Feedback-#395]
http://pastebin.com/CC2makR5

**Comment by Spellkaze** [comment]
Please use http://pastebin.com/ for the crash log

**Comment by KeepItTrill24** [comment]
http://pastebin.com/CC2makR5

**Comment by KeepItTrill24** [comment]
Done!

**Comment by MJRLegends** [comment]
You need to delete this folder \SpaceAstronomy\minecraft\saves\NEI

if its curse you can find the main folder in your docs and ftb i think is in AppData folder from your user folder by default

**Comment by KeepItTrill24** [comment]
So it's all client based? Nothing I need to do on the server? We're using a server host.

**Comment by KeepItTrill24** [comment]
Tried that and it didn't work.

**Comment by KeepItTrill24** [comment]
I joined a single player game and left and then went onto my multiplayer server and it worked. However, after I close the game and join the multiplayer it does it again. I have to join singleplayer everytime.

**Comment by MJRLegends** [comment]
Try to reinstall your whole version of the mod pack, you can make copies of your single player worlds first if needed

**Comment by MJRLegends** [comment]
@KeepItTrill24 any news on this????
