### ISSUE TITLE
Crash when putting in quest book into autonomous activator

### ISSUE THREAD

**Issue by TheDerpyCat** [MJRLegends/Space-Astronomy-Feedback-#398]
I was building a essence farm with essence berry bushes and autonomous activators and I accidentally put in my quest book into one of the activators which crashed the server I was running.
Crash Report
http://pastebin.com/0USyWzWD

**Comment by MJRLegends** [comment]
You need to MCEdit out the autonomous activators

**Comment by lorddusk** [comment]
1.7.10 is no longer supported.
