### ISSUE TITLE
Constantly opening inventory menu

### ISSUE THREAD

**Issue by Statboy1** [MJRLegends/Space-Astronomy-Feedback-#400]
Tinkers Armor GUI inventory constantly opens and won't remained closed. I found a workaround for this issue, it's caused by not having the Armor GUI bound to a key, so binding it to something fixes it. I start every mod pack by unbinding all the mod specific keys and only binding to them to something once I need them. It would be nice to be able to leave this unbound as it's not something I ever need to press. You can get to the same inventory screen by pressing E and switching to the middle inventory tab.

**Comment by MJRLegends** [comment]
This is not a bug with the mod pack

**Comment by Statboy1** [comment]
It's the only modpack i've seen this behavior on. I use tinkers quite a lot.

**Comment by MJRLegends** [comment]
Never happened to me and nothing has changed with thinkers in the mod pack so just reinstall the pack or/and start a new world

**Comment by Statboy1** [comment]
I tried both of those and that didn't change anything. For whatever reason, and I have no ability to mod so I don't know why, on this modpack only, this happens.
