### ISSUE TITLE
Personal Server Crash

### ISSUE THREAD

**Issue by themadjem** [MJRLegends/Space-Astronomy-Feedback-#404]
I tried to start my server today and received this crash, I believe it is related to Immersive Engineering, but as far as I can tell, there is now way to shut off specific items from the mod. All server settings are default. We were playing on the server the previous night, all logged off and /stop was used to turn the server off, then this crash happened the next time I tried to start it.

[crash-2016-07-12_17.41.56-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/360513/crash-2016-07-12_17.41.56-server.txt)

**Comment by MJRLegends** [comment]
https://camo.githubusercontent.com/46c893ec252ee4fdd8aaf24abdaa5362c3f1d803/68747470733a2f2f692e6779617a6f2e636f6d2f33323830383833656164613731343534313966616537396563356163393862652e706e67
![image](https://cloud.githubusercontent.com/assets/8526321/16788829/16bbe5e0-48a0-11e6-964f-c43e43be615f.png)
Also this is a known bug
