### ISSUE TITLE
Severe memory leak causing lag

### ISSUE THREAD

**Issue by xBlizzDevious** [MJRLegends/Space-Astronomy-Feedback-#406]
Something in this pack is causing a severe memory leak and subsequently crashing my server on a regular basis.

It seems to have something to do with mechanism - possibly the reactor and/or the machines to process deuterium and tritium or it could have something to do with the induction matrix.

I can provide logs if required but all I found was a Java OutOfMemory error.

**Comment by MJRLegends** [comment]
You need to add more ram to your game thats the issue

**Comment by xBlizzDevious** [comment]
Please don't close tickets without investigating them.

I initially had 6GB allocated but that got hit so I allocated 12GB. I can watch the memory usage in the Task Manager go up by about 1-2MB every second until it hits the cap and crashes.

This IS an actual issue.

**Comment by MJRLegends** [comment]
Can you send me a copy of your world and give my a full log after playing for a while when it gets to 100%

**Comment by xBlizzDevious** [comment]
I only know one place where I can store a 500MB file that I can share but I don't want to share the link publicly - is there a way I can PM you the link?

**Comment by MJRLegends** [comment]
My username is MJRLegends on FTB fourms, mc forums, curse, curse forge, skype, curse app

**Comment by xBlizzDevious** [comment]
Thanks - but it seems obsolete now.

The version I was using which had this issue was 1.4.7 which has since been removed from the launcher. I have updated to 1.4.9 and even added a few mods. All is working just fine at the moment.

Ie. Whatever it was, you fixed it with the latest update. Thanks!

**Comment by MJRLegends** [comment]
Sweet
