### ISSUE TITLE
Game wont open

### ISSUE THREAD

**Issue by SamuxD** [MJRLegends/Space-Astronomy-Feedback-#408]
my game load until i can see my worlds but when i try to open a World it  brings me back to the launcher

**Comment by SamuxD** [comment]
i think this is the changelog http://pastebin.com/Zmx3n72i

**Comment by SamuxD** [comment]
it is only one singelplayer world 
when i create a new one is everything fine 
but this world wont load

**Comment by SamuxD** [comment]
http://paste.feed-the-beast.com/view/82f7f534 this is the real changelog

**Comment by WalaoEgg0424** [comment]
@SamuxD we need the crashlog.

**Comment by SamuxD** [comment]
where can i find the crashlog 
because when it go back to the launcher the log close

**Comment by SamuxD** [comment]
WARNUNG: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
what does that mean it was red in the log

**Comment by MJRLegends** [comment]
Looks like your java is messed up reinstall your java and launcher and mod pack

**Comment by SamuxD** [comment]
means that that my world is gone ?

**Comment by MJRLegends** [comment]
No you can make a copy of that as it should be in the saves folder

**Comment by SamuxD** [comment]
from normal Minecraft or where can i find the world

**Comment by MJRLegends** [comment]
Which launcher you using

**Comment by SamuxD** [comment]
Ftb

**Comment by SamuxD** [comment]
FTB_Launcher

**Comment by MJRLegends** [comment]
Go to this folder C:\Users\YOURUSERNAMEHERE\AppData\Local\ftblauncher\SpaceAstronomy\minecraft

YOURUSERNAMEHERE = Your user account on your computer, if you go to the C:\Users\ folder your see all the users possible

**Comment by SamuxD** [comment]
http://paste.feed-the-beast.com/view/8094bf3a
it wont work but now it gives me the crashlog

**Comment by MJRLegends** [comment]
Please use pastebin for your logs and please only give me the crash logs not the whole log, and are you trying to load a world or it that just happening when loading the mod pack

**Comment by SamuxD** [comment]
im trying to load a world

**Comment by MJRLegends** [comment]
Ok what happens if you load a new world?

**Comment by SamuxD** [comment]
it load until i can nearly see my world and then it goes back to the launcher and close Minecraft

**Comment by SamuxD** [comment]
how can i see only the crashlog

**Comment by MJRLegends** [comment]
Go to this folder C:\Users\YOURUSERNAMEHERE\AppData\Local\ftblauncher\SpaceAstronomy\minecraft\crash-logs\

**Comment by MJRLegends** [comment]
And then use www.pastebin.com to post them here

**Comment by SamuxD** [comment]
http://pastebin.com/u6AVmEcS
is this better ?

**Comment by MJRLegends** [comment]
@SamuxD did you try to reinstall mod pack?

**Comment by SamuxD** [comment]
yes 4 times

**Comment by limy15** [comment]
Is this topic still actual?

**Comment by SamuxD** [comment]
Yes it is

Von meinem iPhone gesendet

**Comment by MJRLegends** [comment]
No idea i cant reproduce your issue and no one else is getting the issue???

**Comment by MJRLegends** [comment]
I will reopen the issue if you ever reply with the news on this issue.......
