### ISSUE TITLE
Game crashing on startup

### ISSUE THREAD

**Issue by Blocki92** [MJRLegends/Space-Astronomy-Feedback-#409]
My Game wont start...
I even tried reinstalling it

Here is my crashlog: http://pastebin.com/Fd51KnLh

**Comment by MJRLegends** [comment]
This isnt a mod pack issue, its a issue with your graphics card not liking java 8, so it will be the same for what ever mod pack you load. Change back to java 7 or get a newer graphics card

**Comment by MJRLegends** [comment]
http://bfy.tw/6kKg

**Comment by Blocki92** [comment]
Thanks for the quick answer...

Updating the driver helped...

And this was my first time getting this error i think it was the fault of a Windows Update

And my geforce gtx 960 with 4G isnt that old

**Comment by MJRLegends** [comment]
No problem
