### ISSUE TITLE
Unlogical Quests

### ISSUE THREAD

**Issue by TPRammus** [MJRLegends/Space-Astronomy-Feedback-#41]
In the first quest-tree, the reward of the "Upgrading Oxygen Tanks" is one Oxygen Compressor and ten Oak Leaves. But In the next quest ("Filling the Oxygen Tanks"), you'll have to craft a Oxygen Collector first, and than an Oxygen Compressor (which you already got from the Quest before...)
I hope, I could help.

mfg,
TPRammus

**Comment by MJRLegends** [comment]
I'll give it a look, thanks for reporting it
