### ISSUE TITLE
Game crashes without fail

### ISSUE THREAD

**Issue by Caboosanaitor** [MJRLegends/Space-Astronomy-Feedback-#412]
oddly enough, my game only crashes on the SA server, only when i try to enter space 2, i can join other servers, i can join other space's on the SA server, i can even play singleplayer, but i always crash when trying to join space 2. pls halp
     note: i was mining with my atomic dissasembler in the deep dark on monday the 12th. The exact moment i crashed was when i was about to destroy a tinker's construct torch

**Comment by MJRLegends** [comment]
See https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/402

**Comment by Caboosanaitor** [comment]
i feel silly for not putting two and two together >_> thank you so much for putting up with our problems ^^ it worked perfectly
