### ISSUE TITLE
Game crashes saying out of memory on official server

### ISSUE THREAD

**Issue by LoneComet** [MJRLegends/Space-Astronomy-Feedback-#414]
Here is the changelog:

http://pastebin.com/vRXdjVyZ

**Comment by MJRLegends** [comment]
Your memory seems to be fine  Memory: 1389082024 bytes (1324 MB) / 2660237312 bytes (2537 MB) up to 4056416256 bytes (3868 MB)

**Comment by LoneComet** [comment]
OK thanks for looking but it still happens journey map tells me it's out of memory in chat and then I crash

**Comment by MJRLegends** [comment]
Delete and Reinstall the mod pack

**Comment by LoneComet** [comment]
OK thanks
