### ISSUE TITLE
V1.4.7 Not being available on FTB Launcher!

### ISSUE THREAD

**Issue by DJBeatbraker** [MJRLegends/Space-Astronomy-Feedback-#417]
i want to downgrade from 1.4.9 to 1.4.7 but in my launcher i have 1.4.6 and 1.4.9. between is no other version, so i have downloadet the 1.4.7 file from curse but how i install it to the launcher

**Comment by MJRLegends** [comment]
It should be there as it is for me?

**Comment by MJRLegends** [comment]
![image](https://cloud.githubusercontent.com/assets/8526321/16900678/54c21478-4c23-11e6-86fa-fc310ba311bc.png)

**Comment by SugarDaddii** [comment]
BTW new 1.4.9. version is  shown as 1.4.8 in start window!

**Comment by MJRLegends** [comment]
Use the curse launcher for some reason the FTB team have removed v1.4.7 from the launcher

**Comment by MJRLegends** [comment]
Fixed
