### ISSUE TITLE
RFE: Update XU to v1.2.12 to add Search Nearby Inventories hotkey

### ISSUE THREAD

**Issue by merach** [MJRLegends/Space-Astronomy-Feedback-#418]
This would be extremely useful early game when there are quests that take you down several tech lines before you can get ME going.

**Comment by MJRLegends** [comment]
Ux? Extra Utilities?

**Comment by merach** [comment]
Sorry yes, Extra Utilities. v1.2.12 added the ability to bind "search nearby inventories" to a key, which makes it so that when you hover over an item in NEI and press that key, it will close the inventory and a nearby chest or other inventory will sparkle if it contains that item

**Comment by MJRLegends** [comment]
Yeah but theres something else broken in that version so im not using it

**Comment by MJRLegends** [comment]
See v1.4.1 in the change log here http://pastebin.com/Zmx3n72i

**Comment by merach** [comment]
For future reference: can't upgrade without regression in this bug: https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/238
