### ISSUE TITLE
Win 10 space astronomy 1.4.9

### ISSUE THREAD

**Issue by xr4z13l** [MJRLegends/Space-Astronomy-Feedback-#419]
Hi, I have a problem with 1.4.9 version, this is the error when I lunch the game:
http://pastebin.com/LXyNfjrp
my pc:
Win 10 pro
Java 1.8.0.91
32gb ram (4gb for minecraft)
launcher CURSE
With 1.4.7 I need to use forge 10.13.4.1566

**Comment by MJRLegends** [comment]
Try install your launcher and my mod pack

**Comment by xr4z13l** [comment]
Thanks for the help , reinstall and delete all folders CURSE worked well.
