### ISSUE TITLE
crash in tile screen

### ISSUE THREAD

**Issue by tonimark** [MJRLegends/Space-Astronomy-Feedback-#420]
when game initialized tile screen freeze and then game crashes you can see crash there:This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 281484664 bytes (268 MB) / 588251136 bytes (561 MB) up to 1193279488 bytes (1138 MB)
	JVM Flags: 3 total; -Xms256M -Xmx1280M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4331' Renderer: 'Intel(R) HD Graphics 4400'

**Comment by MJRLegends** [comment]
That's not the crash log, read the text it even says that in what you have copied and pasted

**Comment by MJRLegends** [comment]
And your using a really low amount of ram and thats probably your issue

**Comment by tonimark** [comment]
my ram 4 GB captured game ram 1.25 GB

**Comment by tonimark** [comment]
not for tile screen but for scukness crash log(notice there is from ftb launcher so you will see more data than crash)url:http://pastebin.com/HbEvrDh4

**Comment by MJRLegends** [comment]
That's not the crash log
