### ISSUE TITLE
Unable to find sulphur

### ISSUE THREAD

**Issue by AJDzerotwo** [MJRLegends/Space-Astronomy-Feedback-#421]
upon reaching the jetpack quest in the hqm quest book I realized that I had no Sulphur (which is a required ingredient in the leadstone jetpack) suspicious that I had found none at this point I went and googled the level at which you could find Sulphur , the source I found said that Sulphur was found near lava pools, I had three lava pools open already so I mined near and next to all three until there was nothing left to mine, I found no Sulphur at all, is this a world gen issue or is Sulphur merely different in this mudpack (I couldn't find a wikia for it so I can't check)

**Comment by cmears** [comment]
Try looking near lava pools in **extreme hills** biomes. (Although finding extreme hills might take a while!)
