### ISSUE TITLE
crash on loading

### ISSUE THREAD

**Issue by bartasioma** [MJRLegends/Space-Astronomy-Feedback-#423]
hello

i got this error after loading my world not sure what to do, this modpack gave me no problems before this

An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
Ender IO was build against API version rv2 and my not work with newer version.

http://pastebin.com/FCMMJYbB

**Comment by MJRLegends** [comment]
Check the known issues
