### ISSUE TITLE
Turrents missing control buttons in Official server

### ISSUE THREAD

**Issue by Spellkaze** [MJRLegends/Space-Astronomy-Feedback-#424]
The turrets are missing the control buttons even when you are the owner of them.
Normal buttons in a normal single player game.
![2016-07-23_00 54 34](https://cloud.githubusercontent.com/assets/10790732/17076149/d1a1f99e-5070-11e6-9c21-1be022d079ec.png)

Buttons no longer appears in the official server making them drop the turret or the base impossible.
![2016-07-23_00 57 12](https://cloud.githubusercontent.com/assets/10790732/17076157/177408ea-5071-11e6-999e-1f8614e39ee3.png)

Some players wants their turrets be moved and now they can't.

**Comment by MJRLegends** [comment]
I know about this @Spellkaze its hard to fix, im making a custom program to change the stuff needed to fix it. for the time being message me with all the people that need turrents removed and where and i will do it
