### ISSUE TITLE
Game crash when opening tesseract

### ISSUE THREAD

**Issue by limy15** [MJRLegends/Space-Astronomy-Feedback-#425]
Hi I need advice always open when tesseract so game crashes. Here  [crash log](http://pastebin.com/jkqFhkDZ)

**Comment by MJRLegends** [comment]
Have you tried it more than once because this error is only a network error

**Comment by limy15** [comment]
Yes this log was the fifth try

**Comment by ViZartDk** [comment]
It crashes if you have a tinkers tool in you hand when right clicking. I have seen it on other things as well, for example the reactor controller.

**Comment by WalaoEgg0424** [comment]
https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/208

**Comment by limy15** [comment]
Thanks for the advice probably that's it. I tried it with empty hands and took nothing here tinkers tool from the tinkers tool and the game fell

**Comment by MJRLegends** [comment]
So is this issue due to tinkers tools?

**Comment by ViZartDk** [comment]
Yes, just like issue #208
