### ISSUE TITLE
I Can't Find My World

### ISSUE THREAD

**Issue by BlueMoonCow** [MJRLegends/Space-Astronomy-Feedback-#426]
I can't find world in game but when i look in the ¨saves¨ folder my world is there. I haven't done anything in the folders except making a backup now and then but that haven't been an isseu befor.

**Comment by MJRLegends** [comment]
This wouldnt be a mod pack bug as my mod pack or the update for my mod pack doesnt touch the saves folder so if its not the save folder then idk sorry but this isnt a issue for my mod pack and its a issue on your side
