### ISSUE TITLE
Recipe Changes : to either the Etheric Sword or the Kikoku 

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-Feedback-#427]
Both the only difference, is Etheric Swordneed use unstable and Kikoku  Mobius

**Comment by Jin16** [comment]
https://gyazo.com/7daf75434b5b5ce5416088e9a06bd034
https://gyazo.com/b9dca17a2335474ce9d4feb95c7d0e29

**Comment by MJRLegends** [comment]
Fixed in v1.5.0
