### ISSUE TITLE
Quest Bug

### ISSUE THREAD

**Issue by SugarDaddii** [MJRLegends/Space-Astronomy-Feedback-#428]
Hey,
i cant end the pluto quest!
It says wrong dimension...but iam on planet!

![pluto bug](https://cloud.githubusercontent.com/assets/14795020/17086645/ce9b4a7e-51f7-11e6-8b5d-a4cc43710f07.jpg)

Peace

EDIT.: btw i also find all the gems!

**Comment by MJRLegends** [comment]
what are you playing on single player or multiplayer(if so what server)

**Comment by SugarDaddii** [comment]
i playing on nitrado server multiplayer 6 slot server ! do you need ip??

**Comment by MJRLegends** [comment]
Nope, i know the issue its a more planets bug to why its messing up, it seems they have crossing world providers between Jupiter and pluto

**Comment by MJRLegends** [comment]
@SugarDaddii im working on a fix for this issue that is the underline cause of it

**Comment by SugarDaddii** [comment]
Lol i regonized that you have your own galacticcraft addon! Why you not build around that when you start your work on this pack??

**Comment by MJRLegends** [comment]
Because my addon wasn't out and ready when i first built the mod pack

**Comment by 617mango** [comment]
i also have the same problem
