### ISSUE TITLE
Suggestions for better experience

### ISSUE THREAD

**Issue by uzighk** [MJRLegends/Space-Astronomy-Feedback-#429]
To make better the experience with this mod why don't you add mods like;

**_Ex Nihilo_** -> Help in obtaining the mineral resources of the game making it more balanced.
**_JABBA_** -> Help with the resources organization on the game.
**_HungerOverhaul_** -> Improves feeding difficulty and adds functionality to mod Pam 's Harvest.

Maybe if you like to do the modpack more realistic you can add this mod;

**_Envirominer_** -> Other planets would actually be more challenging if there is the need to protect the temperature or even add difficulties as air quality among others. Setting up the right way obviously (setting off the realistic physics on the mod)

**Comment by SugarDaddii** [comment]
hey
in my opinion the modpack is good as it is right now!

maybe it will be too grindy if you add mods like these! 
(crash landing,skyblock,skyfactory....all these modpacks are very grindy)

its not about to starve or protect yourself its about to explore and have fun!

**Comment by uzighk** [comment]
Yeah sure, but the JABBA and the Ex Nihilo make the game more easy and the players can make some "machines" with that mods.

**Comment by MJRLegends** [comment]
@uzighk yeah i dont think any of the mods you have suggested will fit my vision of how i want the mod pack to be sorry

**Comment by WalaoEgg0424** [comment]
@uzighk Jabba is good but Ex Nihilo is not simply easy , its TOO OVERPOWER for players when they automate it , it will result no more world exploring , the modpack will be Space Factory lul
