### ISSUE TITLE
Space Astronomy 1.4.9 - Server Crash on start

### ISSUE THREAD

**Issue by mouz1502** [MJRLegends/Space-Astronomy-Feedback-#430]
Hello Guys,

i cant start my Server anymore. I played with 2 friends. I had reinstallt the complete mod but this didn't fix the issue. 

The CrashReport:  [http://pastebin.com/zxr1y6bP](url)

Thx for your help, hope we dont lose our World.

**Comment by WalaoEgg0424** [comment]
@mouz1502 the link.doesnt work

**Comment by WalaoEgg0424** [comment]
@mouz1502 delete the hqm folder , its a known issue

**Comment by mouz1502** [comment]
Hello WalaoEgg0424,

thx for your Advice. I delete the .\Config\hqm folder, but still getting errors when i start the Server.

The new Crash Report: [http://pastebin.com/KYqE3U7x](http://pastebin.com/KYqE3U7x)

Hope we can fix this.

**Comment by WalaoEgg0424** [comment]
@mouz1502 you using LAN or batch server?

**Comment by WalaoEgg0424** [comment]
@mouz1902 btw , the hqm is in the world folder ,not config.

**Comment by WalaoEgg0424** [comment]
http://pastebin.com/R73aBeqA
known issue here

**Comment by mouz1502** [comment]
It worked! Thx for your help! :)

Now i try to restore our Quests. This Thread can be closed.

**Comment by WalaoEgg0424** [comment]
@mouz1502 you can close it by yourself :)
