### ISSUE TITLE
Dupe with Project Red Transportation

### ISSUE THREAD

**Issue by Snigzou** [MJRLegends/Space-Astronomy-Feedback-#431]
Hello, I'm aridian2 from Space 3 !
As I said earlier, I just found a dupe glitch with Project Red Transportation !
The Firewall Pipe is guilty !
(This one : http://prntscr.com/bxrrgb )
So basicly, all you have to do is fill the entire "capacity" of the pipe with whatever you want to dupe
( Here gravel, FOR TESTING PURPOSES. Don't get me wrong on that one ! http://prntscr.com/bxrrz7 )
And then, just double click on the said item, in your inventory ! ( http://prntscr.com/bxrsdd )

PS : Acutally, its well known : https://www.youtube.com/watch?v=E0nZ-kyWfAU

Hope that the thing will get patched

PS2 : What can I use to replace the pipe, I somehow need the thing that does the same thing !

Regards. -The guy that stalks admins, aka aridian2

**Comment by MJRLegends** [comment]
Added to the main section of the known issues
