### ISSUE TITLE
Mod suggestions

### ISSUE THREAD

**Issue by LeeCannonFodder** [MJRLegends/Space-Astronomy-Feedback-#432]
Here are some Mods for you to think about adding to your pack.

BuildCraft Additions   
BuildCraft Additions is a mod for Minecraft which extends BuildCraft in multiple ways.
http://minecraft.curseforge.com/projects/buildcraft-additions

Catwalks Mod
Fast travel with cool-looking catwalks!
http://minecraft.curseforge.com/projects/catwalks-2

CraftHeraldry 
This mod lets you create Heraldry ingame.
http://minecraft.curseforge.com/projects/craftheraldry

Enhanced Inventories
This mod as is aimed at adding a verity of inventories to the game.
http://minecraft.curseforge.com/projects/enhanced-inventories

Refined Relocation
http://minecraft.curseforge.com/projects/refined-relocation

MalisisDoors

Modular Systems
Build it your way!
http://mods.curse.com/mc-mods/minecraft/modular-systems

Pistronics 2
Adds Pistons, Rotators and more.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294844-pistronics-2-modular-pistons-rotators-and-statues

Roadblocks
speed boost when you walk on them.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2339054-roadblocks-1-8-v2-1-5-1-7-10-v2-1-8-updated

SimpleLabels
his mod modifies how you interact with your Deep Storage Unit by adding a DSU Label. View current the item and amount, input items with right click, extract with left click, shift left click...
http://minecraft.curseforge.com/projects/simplelabels

Super Crafting Frame
Super Crafting Frame is a simple mod that helps with repetitive crafting tasks during early game.
http://minecraft.curseforge.com/projects/super-crafting-frame

Tube Transport System
Why should items get all the fun?
http://minecraft.curseforge.com/projects/tube-transport-system

Ye Gamol Chattels 
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1276287-ivorius-mods-structures-dungeons-drugs-statues
http://minecraft-ygc.wikia.com/wiki/Minecraft_YGC_Wiki

**Comment by SugarDaddii** [comment]
Peace me again! 
i also have a suggestions  for your mod!

Its Mffs-Modular Force Fields
http://minecraft.curseforge.com/projects/modular-force-fields

i would say this mod fits in your theme 

graz and have a nice day!
