### ISSUE TITLE
server crash when loading world

### ISSUE THREAD

**Issue by Woody709** [MJRLegends/Space-Astronomy-Feedback-#433]
my mother shut the electricity down when my server was running.
after that i restarted my laptop and i tried to starting the server and it keeps shutting down.
and i have tried deleting ender storage folder but that doesn't work at all.

sorry that it isn't a pastebin.
pastebin didn't allow this big of a file

[fml-server-latest.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/386213/fml-server-latest.txt)

**Comment by WalaoEgg0424** [comment]
@Woody709 Crashlog , not the forge log

**Comment by WalaoEgg0424** [comment]
@Woody709 delete enderstorage.data from enderstorage folder in your world folder

**Comment by Woody709** [comment]
@WalaoEgg0424 there was no crashlog, and i will try that part again

**Comment by Woody709** [comment]
@WalaoEgg0424 i was looking in the enderstorage folder in my world save but there is nothing in it.
what do i do now

**Comment by WalaoEgg0424** [comment]
@Woody709 you try launch the server again then see if it generate crash log now

**Comment by Woody709** [comment]
@WalaoEgg0424 it still doesn't create any crash logs.
and me and a friend have been playing on this world for 3 months now.

oh and when i have moved the world folder and generate a new one then the server will start propperly

**Comment by Woody709** [comment]
@WalaoEgg0424  after some tinkering and removing mods and adding mods it will now produce a crash report.
[crash-2016-07-27_17.44.12-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/386478/crash-2016-07-27_17.44.12-server.txt)

**Comment by Woody709** [comment]
[crash-2016-07-24_16.05.54-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/386508/crash-2016-07-24_16.05.54-client.txt)
and a new crash log but this time on single player with same world

**Comment by MJRLegends** [comment]
@Woody709 does any other of the mod packs work?

**Comment by Woody709** [comment]
@MJRLegends do you mean like from the ftb team.
yes they do work

**Comment by MJRLegends** [comment]
Idk the error your getting i would say isnt mod pack related, try reinstalling the mod pack again completely

**Comment by MJRLegends** [comment]
Please reopen if the issue still exists

**Comment by Woody709** [comment]
@MJRLegends @WalaoEgg0424  i figured out it was the world what was corrupted
and so me and my friend started over.
but thanks for all the help everyone
