### ISSUE TITLE
Useful Mod

### ISSUE THREAD

**Issue by AtaroBlade** [MJRLegends/Space-Astronomy-Feedback-#437]
Could be possibly get a working version of the TrashSlot mod. It would be useful for those of us that go adventuring still, and collect a bunch of an item while mining or otherwise, and need to dispose of it, without leaving it to bog down the world.

**Comment by WalaoEgg0424** [comment]
@AtaroBlade you could just on utilities mode on NEI and delete items

**Comment by MJRLegends** [comment]
He means for server use, so the nei way wouldn't be possible

**Comment by WalaoEgg0424** [comment]
oh ok , misunderstanding , sorry about it

**Comment by MJRLegends** [comment]
No problem
