### ISSUE TITLE
Bug Re-Fix

### ISSUE THREAD

**Issue by Pitomiz** [MJRLegends/Space-Astronomy-Feedback-#438]
Hello i found a bug but you found it first and fixt it...

Bug: I have a leadstone jetpack and i fly log out log in and i have new inventory ... i played then the full time with the new inventory and the a update you fixt it my full inventory deletet... And i have nothing 
my question is : Can you Re-Fix this bug for 2 days... so i can and take my inventory.: Delete The Fix and Fix it in 2 days new.... pls

Pitomiz

**Comment by MJRLegends** [comment]
Your propably on the wrong server

**Comment by Pitomiz** [comment]
No i think about the full modpack

**Comment by MJRLegends** [comment]
I dont understand what you mean, do you mean on my server or single player or what

**Comment by Pitomiz** [comment]
Singelplayer

**Comment by Pitomiz** [comment]
With this modpack

**Comment by Pitomiz** [comment]
Just when im flyng with a jetpack in the fly i log out and so i swapped my inventory

**Comment by Pitomiz** [comment]
When you didnt fixed this bug already pls dont fix it...

**Comment by WalaoEgg0424** [comment]
you can just downgrade the modpack

**Comment by Pitomiz** [comment]
yea but any block deletet ?

**Comment by Pitomiz** [comment]
i playng lan with my friend

**Comment by WalaoEgg0424** [comment]
downgrade the modpack and tell ur fren to downgrade modpack too , and then put those stuff inside chest , then only you upgrade , but if u didnt make backup of ur world , then gg

**Comment by Pitomiz** [comment]
Ok i test it thx

**Comment by Pitomiz** [comment]
Nope it didnt give my stuf

**Comment by WalaoEgg0424** [comment]
well then we cant help u anymore cuz u didnt make a backup of ur world , not our fault anymore. its ur side issue.

**Comment by Pitomiz** [comment]
pls dont fix this bug :D i want my stuf and im tryng that mean you didnt fix it already ;D and i become my stuf back

**Comment by WalaoEgg0424** [comment]
np , ur world is saved that ur inventory is cleared , no way of getting it back

**Comment by WalaoEgg0424** [comment]
and please arrange ur sentence to a sentence that we can read

**Comment by Pitomiz** [comment]
I must use Google translation wait

**Comment by Pitomiz** [comment]
okey thx for help but pls didnt fix it  :D

**Comment by WalaoEgg0424** [comment]
Your inventory is saved in ur world that its empty in ur world file , theres no way you will get it back dood. and we couldnt downgrade ur modpack version , u can just downgrade it. and we have to fix bugs and not gonna downgrade the modpack version just only for u

**Comment by MJRLegends** [comment]
The mod pack wouldnt touch the inventory files so???

**Comment by WalaoEgg0424** [comment]
might be himself messed something up

**Comment by WalaoEgg0424** [comment]
we couldnt help him as his world files data has saved his inventory that is empty. u know what i mean?
