### ISSUE TITLE
Loading crash

### ISSUE THREAD

**Issue by DalenRay5** [MJRLegends/Space-Astronomy-Feedback-#439]
whenever I try to load the pack the whole launcher crashes and I have to restart my pc I cannot get the 1.5.0 version to work it may have something to do with my texture pack I'm using faithful 32 for 1.7.10

**Comment by MJRLegends** [comment]
So does the mod pack crash or the launcher and i cant sort a crash without a crash log. Im not magic

**Comment by DalenRay5** [comment]
EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and my not work with newer version.
                  * The RF API that is being used (1.7.10R1.1.0 from &lt;unknown&gt;) differes from that that is reported as being loaded (1.7.10R1.0.13 from EnderIO-1.7.10-2.3.0.422_beta.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:ON, PneumaticCraft:ON
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [F32-1.7.10.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
[13:50:15] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# c:\ftb\SpaceAstronomy\minecraft\crash-reports\crash-2016-07-28_13.50.11-client.txt
[13:50:31] [INFO] ProcessMonitor.run:43: MC process exited. return value: -1
[13:50:32] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 0 enUS to options pane
[13:50:32] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 1 cyGB to options pane
I think this is what the problem is so I assume its the actual pack

**Comment by MJRLegends** [comment]
Folllow the rules and thats not even the crash log
