### ISSUE TITLE
Quests Gone

### ISSUE THREAD

**Issue by ingeraskurai** [MJRLegends/Space-Astronomy-Feedback-#44]
I've updated to newest version, had to completely delete all files and move over save but now my quest book doesn't list any quests at all, 0/0.  I created a new test world and no quests there either.

**Comment by MJRLegends** [comment]
Im not sure why this has happened try reinstalling the mod pack

**Comment by ingeraskurai** [comment]
Will do!

**Comment by ingeraskurai** [comment]
Yup that did it, strange but ty :)

**Comment by MJRLegends** [comment]
No problem and yeah probably the launcher didnt install the update correctly
