### ISSUE TITLE
SMP World crashes as soon as I load up the world

### ISSUE THREAD

**Issue by Corrosionn** [MJRLegends/Space-Astronomy-Feedback-#440]
Having an issue loading my single player world. i have the crash report but i have no idea where to start with interpreting the issue or how to solve it. i restarted and reinstalled the pack and launcher and the world still crashes on start up.

Mod pack is space astronomy version 1.4.9

Any help will be greatly appreciated
The report is in the spoiler if anything else is required let me know.
Thanks!
[crash report.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/389379/crash.report.txt)
Pastebin link: http://pastebin.com/gvC7ATgR

**Comment by MJRLegends** [comment]
Already known issues and your using a out of date version so update
