### ISSUE TITLE
Armor Durability HUD overlaps with hotbar

### ISSUE THREAD

**Issue by hatmantop** [MJRLegends/Space-Astronomy-Feedback-#441]
The armor durability HUD overlaps with the hotbar, how do I disable the durability HUD?

**Comment by MJRLegends** [comment]
how big is your screen?

**Comment by hatmantop** [comment]
17" @ 1920x1080

**Comment by MJRLegends** [comment]
What gui size on minecraft video settings?

**Comment by hatmantop** [comment]
auto

**Comment by MJRLegends** [comment]
What happens if you change it to large or small or normal?

**Comment by hatmantop** [comment]
everything shrinks so the problem goes away

**Comment by MJRLegends** [comment]
what about on normal? is it fine then?

**Comment by hatmantop** [comment]
small, normal and large all work
If theres no way to disable the armor HUD then large works fine

**Comment by MJRLegends** [comment]
It should work fine on normal though?

**Comment by hatmantop** [comment]
yeah nothing overlaps on normal
normal is just a bit small for my liking

**Comment by MJRLegends** [comment]
yeah i think the issue is because your probably playing on large on a screen window with it will yeah

**Comment by hatmantop** [comment]
Large doesn't overlap either, auto scaling makes it really big
when I was playing on auto it overlapped, now that its on large its okay
I just want to know if there is a config file i can change or a hotkey i can assign so that i can get rid of the durability HUD

**Comment by hatmantop** [comment]
![2016-07-28_16 16 02](https://cloud.githubusercontent.com/assets/17018691/17232879/250a50e0-54e0-11e6-9315-f47b52d443c6.png)

This is what it looks like on auto

**Comment by hatmantop** [comment]
![2016-07-28_16 27 54](https://cloud.githubusercontent.com/assets/17018691/17232889/4264d6e2-54e0-11e6-8cc0-2fcdabfeb3f2.png)

And then here is large

**Comment by MJRLegends** [comment]
Yeah its because your playing on auto with a small ish screen

**Comment by hatmantop** [comment]
yeah that makes sense, is there any way to disable it though?

**Comment by MJRLegends** [comment]
Remove the   [1.7.10]ArmorStatusHUD-client-1.28 mod

**Comment by hatmantop** [comment]
cool cool cool thanks
great pack btw

**Comment by MJRLegends** [comment]
No problem :)
