### ISSUE TITLE
SMP World crashes as soon as I load up the world

### ISSUE THREAD

**Issue by Corrosionn** [MJRLegends/Space-Astronomy-Feedback-#442]
Newest version same problem
http://pastebin.com/5xrqjhHG

**Comment by MJRLegends** [comment]
Already known issues i said that in #440

**Comment by Corrosionn** [comment]
Can you tell me what this 'known issue' is then instead of just stating that. I've looked at the known issue list and I can't tell which one it is care to tell me?

**Comment by WalaoEgg0424** [comment]
go search bar of github closed issue , search the error ,and results will be on , you r just lazy to find it

**Comment by Corrosionn** [comment]
Copied my exact title nothing there mate

**Comment by WalaoEgg0424** [comment]
use mcedit , Location: World: (113,80,851), Chunk: (at 1,5,3 in 7,53; contains blocks 112,0,848 to 127,255,863), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
