### ISSUE TITLE
WateringCan and Plants

### ISSUE THREAD

**Issue by MadeByCartoon** [MJRLegends/Space-Astronomy-Feedback-#443]
When you right click a plant with a Wateringcan from xutils It Dissapears. It is not a common bug but it still happens

**Comment by MJRLegends** [comment]
What plants and which type of watering can??

**Comment by Wolf68k** [comment]
"It disappears" What is "it" the plant or the watering can?
If it's the plant (or more precisely crop from the plant), then I've had that happen before I even made a watering can. I don't remember which plant(s) this happened on, I think it was kind of random but mostly with Pam's stuff.

**Comment by MJRLegends** [comment]
Your message above isnt a reply tbh to what i asked, what im asking is what plants/crops are you watering and which watering can you using because theres a normal and a a reinforced one and also are using is of another player or using it inside machine

**Comment by MJRLegends** [comment]
@Wolf68k ????

**Comment by Wolf68k** [comment]
I was replying to the fact that I've had that happen too, chops sometimes disappear when harvesting them. The seeds remain but the crop vanishes. I've had it happen with and without a watercan (basic one) and I don't remember which plants. I think it was mostly just the Pam's Harvest but it might have happened with wheat as well.

**Comment by MJRLegends** [comment]
@MadeByCartoon and @Wolf68k I will look at this when i can, i have not forgotten about this issue

**Comment by MJRLegends** [comment]
@MadeByCartoon @Wolf68k Cant reproduce this problem, see my tests below

Both tests done with Normal Watering can and Reinforced one

**Test 1 without Particles** 
![](https://i.gyazo.com/2e5901c60eaae973a766fdc002cf9680.gif)

**Test 2 with Particles** 
![](https://i.gyazo.com/388fc85eb03734f629e9e10b332a956e.gif)

**Comment by MJRLegends** [comment]
@MadeByCartoon @Wolf68k Cant reproduce this problem, see my tests below

Both tests done with Normal Watering can and Reinforced one

**Test 1 with Particles**
![](https://i.gyazo.com/6a50945bbfdcb134d7062bb8ef80a98e.gif)

**Test 1 without Particles**
![](https://i.gyazo.com/c99fa4825e9579781b19120d390edb9d.gif)

**Comment by MJRLegends** [comment]
@MadeByCartoon @Wolf68k What you playing on single player or multiplayer and if multiplayer what server and what is it running (Forge or Thermos or KCauldron)

**Comment by MJRLegends** [comment]
I will reopen if a reply if ever made about this issue or if it comes up again....
