### ISSUE TITLE
Dupe bug with wireless crafting term. 

### ISSUE THREAD

**Issue by xXHastinqXx** [MJRLegends/Space-Astronomy-Feedback-#445]
I have a wireless crafting terminal with a magnet card in it and welp whenever i pick up thermal expansion machines and my inv is full it dupes... the magnet card picks up items and puts them in AE system...

**Comment by xXHastinqXx** [comment]
Mjr i dont like that you banned the wireless crafting terminal... ban the magnet card.
i worked hard to make this and dont want to waste it.
the bug is in the magnet card i believe, ban the card

**Comment by xXHastinqXx** [comment]
wait i think i got confused... oops or you just fixed it

**Comment by MJRLegends** [comment]
No ive banned the magnet card not the terminal

**Comment by xXHastinqXx** [comment]
i'ma close it should be dealt with now
