### ISSUE TITLE
Quarry

### ISSUE THREAD

**Issue by tempact** [MJRLegends/Space-Astronomy-Feedback-#446]
Placing the Buildcraft Quarry corrupts the world in all versions utd. No crash data is ever generated. Upon placing either block, the screen will lock to the current frame and the UI will disappear (screenshots taken in 1.5.0).  afterwards, pressing any button other than the function keys has the expected effect, but the screen doesn't update; i.e. you can move around and open inventory, but the only thing you see is the cursor appear. so i can press 'ESC' and guess where the quit button is, and it will save and quit the game; it will return to the locked screen though, rather than the menu. reloading the game doesn't work. additionally, the presence of these corrupted saves causes an "error extracting native libraries" error, and the game won't launch until the saves are removed or fixed.

the only fixes are as follows:
 delete the save
 use MCEdit to remove the block, which restores the save to a playable state. 
 go through pressing the function keys (i don't know which one fixes it, I need to reproduce it more on fresh installs
![errorcapture1](https://cloud.githubusercontent.com/assets/20714945/17267217/af344400-55b8-11e6-822a-7707264f6c20.PNG)

when i use the third fix, the bug is resolved for all worlds thereafter and becomes non-reproducible. an added factor may have been that I made sure no instances of the FTB launcher (the old one before curse) were running.

**Comment by MJRLegends** [comment]
Any chance you can some me some images to what happens, and to how you know that the quarry is causing it and have you tried to reproduce it in a a new world?? And is it  single player or multiplayer to where your having the issue

**Comment by MJRLegends** [comment]
@tempact ???

**Comment by MJRLegends** [comment]
Will reopen the issue if you ever reply back

**Comment by Arfew** [comment]
I have been going through the same issue as the OP, sadly
