### ISSUE TITLE
Can anyone explain why I'm getting this message?

### ISSUE THREAD

**Issue by Corrosionn** [MJRLegends/Space-Astronomy-Feedback-#447]
http://prntscr.com/bzth07

There's not report log for this is the only thing that pops up when i try launch into a new world

**Comment by MJRLegends** [comment]
No idea try reinstalling the mod pack

**Comment by Corrosionn** [comment]
Alright

**Comment by Corrosionn** [comment]
Seems to work again but my old world is unusable again
