### ISSUE TITLE
[Crash] When try to destroy Microblocks

### ISSUE THREAD

**Issue by SugarDaddii** [MJRLegends/Space-Astronomy-Feedback-#448]
http://paste.ee/p/8awgl

EDIT.: I also try to pick up the Microblocks with another pickaxe [Crash]
http://paste.ee/p/XRQHU

**Comment by MJRLegends** [comment]
Whar tools did you use both times and what mirco block is it

**Comment by SugarDaddii** [comment]
Hey,
TOOLS:
-Tinkers Pickaxe (Tinkers Construct) 
-Desh Pickaxe (Galacticcraft)!

WHATS BLOCKS:
- stripes of chiseled factoryblock (chisel) 
- stripes of inverted lamps white (Project Redstone)

**Comment by MJRLegends** [comment]
@SugarDaddii can you reproduce this in a different world?

**Comment by brantyr** [comment]
I encountered the same thing yesterday (trying to break an inverted lamp cover), A workaround is to break the blocks in creative mode

**Comment by MJRLegends** [comment]
Idk how to fix this so im closing the issue
