### ISSUE TITLE
Crash with Dimensional Anchors

### ISSUE THREAD

**Issue by asbestinuS** [MJRLegends/Space-Astronomy-Feedback-#449]
Hey there,
I have crashes with the Dimensional Anchors mod. It sometimes crashes if I want to DECREASE the area of effect (only tested in overworld and Nether so far)
But now I found out that it ALWAYS crashes while Opening the GUI and being in The End. I just can see the GUI then the game crashes. I was trying to do a semi-mob farm of sorts with the smeltery for some resonant ender - in case it matters.
Here is the latest pastebin: http://pastebin.com/2DRGfwmH
I'm using the latest 1.5.0 version (installed via FTB Launcher), latest java and latest AMD graphics driver. I didn't find any issue post for that. Is this a known problem?
Thanks! :)

**Comment by MJRLegends** [comment]
This problem has no direct connection to dimensional anchors and the crash log is showing the block placement packet is causibg the network crash. Tbh there is nothing i can do as they don't crash me. Does it do it if you test in a new single player world???

**Comment by asbestinuS** [comment]
Thank you fir your fast reply.
So I startet a new world, went right to The End, set up a smeltery and basicly replicated what I had in my survival world. I placed a Dimensional Anchor and nothing happended. I was able to extend, decrease change shape ect. pp. No crash forced. 
But...I got to play about 10-15 minutes then I got a crash (without opening a GUI or anything). I just hit an Enderman to get him moved in the trap and then I got the message "Server is shutting down" and Minecraft closed itself. Pastebin: http://pastebin.com/qWUSy9Pg
What's going on? 

Thanks!

**Comment by MJRLegends** [comment]
Was you using anything from the wirelesscraftingterminal mod if so this is two different issues and the first one hasnt come up yet since my last message and in the tests after that message

**Comment by asbestinuS** [comment]
Hm, don't know if edits are being notified. I just edited my former post regarding the server/client thing.
No, I was not using any wireless crafting thing. Just the ordinary Tinkers Smeltery stuff, the dimensional anchor and a few trap doors. Noting more.

**Comment by asbestinuS** [comment]
Okay, well I can't replicate the crash, it just works fine now. I also can access the Anchor's GUI and also decrese the size etc. No idea what was going on.
I'd say this issue is resolved, thanks for your help :)
