### ISSUE TITLE
Forge Lexicon crash

### ISSUE THREAD

**Issue by Felidae0** [MJRLegends/Space-Astronomy-Feedback-#450]
Not sure what happened, game was running just fine, but I finally got the resources to make a forge lexicon and set which blocks I wanted to use. As soon as I opened it up, the game froze. The Gui had opened, but it only gave me the list, no pictures of blocks. Then it crashed to desktop. Crash log attached.

[crash-2016-07-31_20.08.26-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/392882/crash-2016-07-31_20.08.26-server.txt)

**Comment by Snigzou** [comment]
Use pastebin for crashlogs.

**Comment by MJRLegends** [comment]
Please reopen when you have followed the rules
