### ISSUE TITLE
AppliedAerodynamics

### ISSUE THREAD

**Issue by Sharkmas** [MJRLegends/Space-Astronomy-Feedback-#451]
There is a bug when creating the Applied Aerodynamics Skystone Ingot. When crafting, it does not use the Skystone Dust or Iron Ingot, but only consumes the Engineer Processor.

**Comment by MJRLegends** [comment]
Proof/Showing the bug happening 
![](https://i.gyazo.com/58d46b8f4659ec1d0fabddd721bdf0f9.gif)

**Comment by MJRLegends** [comment]
Closed because i've report it to the dev and i've added it to the mod pack known issues page

**Comment by MJRLegends** [comment]
@Sharkmas Will be fixed in v1.5.2
