### ISSUE TITLE
crash when loading

### ISSUE THREAD

**Issue by greenwolfninja** [MJRLegends/Space-Astronomy-Feedback-#452]
not sure what is happening, it started right after a restart. i log-in to the hub fine, but when i go to get on the server i crash.
her is the pastbin http://pastebin.com/xpBnrbqL

**Comment by Snigzou** [comment]
have you tried basic troobleshooting (ie resintalling modpack, restarting the game) ?

**Comment by MJRLegends** [comment]
Use the direct ips @greenwolfninja

**Comment by greenwolfninja** [comment]
All I have tried so far is restart the game. I was waiting to see what you said before doing a reinstall, but will try that when I  go home for lunch.

**Comment by MJRLegends** [comment]
yeah try reinstalling too

**Comment by greenwolfninja** [comment]
well i did a reinstall and as soon as i tryed to join server 4 i crashed
