### ISSUE TITLE
Haste on Traveller's Gloves not working

### ISSUE THREAD

**Issue by trlababalan** [MJRLegends/Space-Astronomy-Feedback-#453]
I've stuck 500 redstone on that and my mining speed didn't increase a bit. I've used them in every modpack so far that had TiC in it. You can get pickaxe speeds on your bare fist while breaking cobblestone. 

Please check if it's disabled anywhere...

Edit: I think this is this modpack-specific issue. Bringing this up because I saw this:
https://gyazo.com/b1f51423346c753fa764c550df3aadcb

**Comment by MJRLegends** [comment]
@trlababalan I will look at this when i can, i have not forgotten about this issue
