### ISSUE TITLE
Worlds won't open 

### ISSUE THREAD

**Issue by Dragon1Svk** [MJRLegends/Space-Astronomy-Feedback-#456]
Every time I try to load or create a world in the Space Astronomy It goes to the loading world screen then right back to the title screen. No error message no crash just back to the title screen. It doesn't freeze or anything and I can still try to load a world again or change settings. I tried not clicking anything and just waiting when the title screen comes back but nothing happens.

**Comment by MJRLegends** [comment]
i need the full log

**Comment by Dragon1Svk** [comment]
Maybe I found problem... When I delete all worlds from saves everything goes so I think all world are damaged

**Comment by MJRLegends** [comment]
Ok so this is fixed???

**Comment by Dragon1Svk** [comment]
Yes
