### ISSUE TITLE
Tinkers construct

### ISSUE THREAD

**Issue by Tichinde** [MJRLegends/Space-Astronomy-Feedback-#457]
For reasons unknown, maybe just my client, I an unable to replace parts on my tools through the tinkers ui in the tool station/forge (i.e cannot replace stone pick-ax head with an iron one even though the tool is fully repaired). Further more I've received a slime rapier from a boss drop and i have the items to repair it but once again it wont work. This just could be the version I'm playing on or just my game all together, I'm currently playing on version 1.5.0

**Comment by trlababalan** [comment]
It's in the config. Apparently, switching of parts and leveling up the tools by using them are both disabled for some reason. It's not a bug.

**Comment by MJRLegends** [comment]
@Tichinde @trlababalan yeah its a addon for the mod which isnt in the mod pack or this isnt a bug at all
