### ISSUE TITLE
Fronos Quest is Horrible

### ISSUE THREAD

**Issue by WheresMyMtnDew** [MJRLegends/Space-Astronomy-Feedback-#458]
Since ALL the textures are missing for the stupid candy/cake stuff- its a horrible pain to get each one. Is there a fix for the missing textures, or is there a texture pack which will fix this. I was so looking forward to this planet and it's been nothing but frustration.

**Comment by WheresMyMtnDew** [comment]
I noticed 300 & 328, but neither explains how to fix this- at least not to my understanding. Currently I have managed to find all the candy cane for the quest but all I can find as far as cake is regular cake bread- no chocolate or white. Please help this is a real hassle. Not to mention that the candy biome looks totally jacked with it all consisting of black and purple tiles.

**Comment by MJRLegends** [comment]
This wasnt worth you making this issue as the quest isnt being changed

**Comment by WheresMyMtnDew** [comment]
I never read anything about it, the other two threads I found offered no information so thanks for being rude. An honest question should not be responded to in such a way. Furthermore, your git hub is confusing to navigate and so called "known" issues are hard to find as there is no comprehensive list. Thanks again for being nasty.
