### ISSUE TITLE
Diamond Blocks Are Not turning Back to Diamons

### ISSUE THREAD

**Issue by NathanD223** [MJRLegends/Space-Astronomy-Feedback-#46]
I Can convert Diamond to Diamond Blocks But cannot Put Diamond Blocks Back to Diamond I'm pretty sure it worked before the latest update

**Comment by MJRLegends** [comment]
I will get back to you on this, will have to check it out to see if there is a problem

**Comment by MJRLegends** [comment]
Will be fixed for next update

**Comment by babyblasphemy** [comment]
Doesn't seem to be fixed, I've readded the recipe with minetweaker in the meantime.

**Comment by MJRLegends** [comment]
Will be fixed for 1.2.8 update
