### ISSUE TITLE
Items flash after loading saved world

### ISSUE THREAD

**Issue by Spookdog** [MJRLegends/Space-Astronomy-Feedback-#461]
I was playing a single player game, and decided to stop. next time I loaded it up it had a bunch of flashing items.

Pictures

![screen shot 2016-08-08 at 1 52 44 pm](https://cloud.githubusercontent.com/assets/20912084/17491999/9058db36-5d6f-11e6-83ed-dee322f65f32.png)
![screen shot 2016-08-08 at 1 52 10 pm](https://cloud.githubusercontent.com/assets/20912084/17492002/92e7029c-5d6f-11e6-8666-c5dfabd40f7c.png)

**Comment by MJRLegends** [comment]
Are you using OptiFine?

**Comment by MJRLegends** [comment]
@Spookdog ^^^^ ??? also try removing fastcraft???

**Comment by MJRLegends** [comment]
I will reopen if a reply if ever made about this issue or if it comes up again....

**Comment by Spookdog** [comment]
Sorry, I'm not using optifine. This issue really buggs me, if you can't fix it, okay, but it would be nice if you could. I also am on mac.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Aug 16, 2016 at 8:23 AM -0500, "MJRLegends" <notifications@github.com<mailto:notifications@github.com>> wrote:


I will reopen if a reply if ever made about this issue or if it comes up again....

-

**Comment by MJRLegends** [comment]
@Spookdog have you tried removing Fastcraft and yeah Apple Mac's have some weird render issues, i've so many of them that are random even not with modded
