### ISSUE TITLE
INPurecore issue

### ISSUE THREAD

**Issue by Wolf68k** [MJRLegends/Space-Astronomy-Feedback-#463]
The default settings in INPurecore for BibiloCraft ends up hiding a few things.
Using this will unhide those items.

if (FML.isModLoaded("BiblioCraft") && Bibliocraft_enabled) {
	NEI.override("BiblioCraft:*Paneler", [0]);
	NEI.override("BiblioCraft:*Typewriter", [0]);
	NEI.override("BiblioCraft:*Clock", [0]);
	NEI.override("BiblioCraft:*Painting", [0]);
	NEI.override("BiblioCraft:*SwordPedestal", [0]);
	NEI.override("BiblioCraft:*FancySign", [0]);
	NEI.override("BiblioCraft:*Workbench", [0]);
	NEI.override("BiblioCraft:*theca", [0]);
	NEI.override("BiblioCraft:*Shelf", [0]);
	NEI.override("BiblioCraft:*Rack", [0]);
	NEI.override("BiblioCraft:*Case", [0]);
	NEI.override("BiblioCraft:*Label", [0]);
	NEI.override("BiblioCraft:*Desk", [0]);
	NEI.override("BiblioCraft:*Table", [0]);
	NEI.override("BiblioCraft:*Lantern", [0]);
	NEI.override("BiblioCraft:*Lamp", [0]);
	NEI.override("BiblioCraft:*MapFrames", [0]);
	NEI.override("BiblioCraft:*Seats", [0]);
	NEI.override("BiblioCraft:item.*", [0]);
}

**Comment by MJRLegends** [comment]
Yeah but its meant to be hiding them?? I don't understand that issue your trying to report here

**Comment by Wolf68k** [comment]
I know that 2 of the items it hides are the plate and the disc rack

**Comment by MJRLegends** [comment]
Yeah but are them being hidden a issue???

**Comment by MJRLegends** [comment]
It seems to me your just telling me a solution to a problem that hasnt been brought up

**Comment by Wolf68k** [comment]
Just because it hasn't been brought up to you before doesn't mean it hasn't been brought up. I've seen this same issue in a few other packs, one of which I use to work on and this was the solution.

**Comment by MJRLegends** [comment]
Well can you tell me what the issue actually is first??

**Comment by Wolf68k** [comment]
Trying looking up the recipe for the plate and disc rack in NEI. You can't because they are hidden.

Some people just might want to use those items. I've had several people complain about it about 1-2 years ago in the pack I was use to work. They know the items exist but they couldn't find them.

I'm just trying to help out. No it's not a huge issue but you also said not post any issues in the forum.

**Comment by MJRLegends** [comment]
Ok thanks it just seemed like you was giving me a solution but wasn't telling the issue

**Comment by MJRLegends** [comment]
Will be fixed in the next version and this has been added to known issues page so im closing it

**Comment by Wolf68k** [comment]
Sorry but I didn't notice this before. There was a creative only bookcase added. Add the following to that list to completely hide all of those
NEI.hide("BiblioCraft:BookcaseFilled");
