### ISSUE TITLE
Crash, pastebin included. 

### ISSUE THREAD

**Issue by glazor1** [MJRLegends/Space-Astronomy-Feedback-#465]
http://pastebin.com/L1Bxt08d EDIT
The game crashes when i try to load a save file. Had no problem last night.

**Comment by MJRLegends** [comment]
Wrong pastebin as thats my known issues pastebin??

**Comment by glazor1** [comment]
Sorry, http://pastebin.com/L1Bxt08d

**Comment by MJRLegends** [comment]
This is a known issue check the known issues
 
9. Immersive engineering TileEntityImmersiveConnectable Crash - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/341 - (This is a mod bug) - Should be fixed, please let me know if you get it!!!

**Comment by glazor1** [comment]
" dont use Immersive engineering power with quarries or connect it to a power storage in the middle so Immersive engineering isnt directly interacting with the quarries"
This, right?

**Comment by MJRLegends** [comment]
Yeah remove IE mod or uae mcedit to remove the block that the location of is in the crash log

**Comment by glazor1** [comment]
Got you, thanks for the fast response.
