### ISSUE TITLE
Mekanism Teleporter Crashing Game

### ISSUE THREAD

**Issue by NyagiKun** [MJRLegends/Space-Astronomy-Feedback-#466]
Game crashed again while teleporting to the moon using a mekanism teleporter, I've never actually posted a crash log before so i hope i did it correctly:

Log Removed by MJRLegends see message below for details

**Comment by MJRLegends** [comment]
Use pastebin for the log!!!!

**Comment by NyagiKun** [comment]
http://pastebin.com/9GbnNEeL

**Comment by MJRLegends** [comment]
The crash log has nothing to do with the Mekanism Teleporter
