### ISSUE TITLE
Game hangs after loading the world

### ISSUE THREAD

**Issue by asbestinuS** [MJRLegends/Space-Astronomy-Feedback-#467]
Hey there again...so I was trying to load my Singleplayer world and got so far as to where I see my hotbar, my tools in it and part of the base I built when I last logged out yesterday and then the game freezes. The FTB Launcher spits message after message:
_Can't keep up! Did the system time change, or is the server overloaded? Running X ms behind, skipping X tick(s)_
If I try to..you know, click somewhere to see if something happens, I get the Windows Error "Javaw.exe stopped working" and my only chance do do something again is to kill the minecraft process. I didn't change nothing since my last issue (which just disappeared) but now I can't get it working.
I tried deleting the HQM folder but it didn't help. Lowering the rendering distance to 2 didn't help either. I don't know whats going on.
The next thing is it doesn't generate a crash log, because...well..no crash, just a overloaded minecraft process.
I created a new world, that worked fine. Restarting PC, reloading modpack, nothing worked. I need help please !
I made a backup of the /saves folder just in case, I really don't want to loose that map.

The only thing I have is the FTP Launcher log I copied to clipboard after I killed the minecraft process after trying different things. Can you please have a look into it? http://paste.feed-the-beast.com/view/abe2f659

Still using the latest Java 8 version, latest display driver, no Windows Updates. It has to be something I did in the map I bet. But how do I know what? How can I change something I don't know that's causing it? Ples halp :(

**Comment by MJRLegends** [comment]
How much ram you got set for it?

**Comment by asbestinuS** [comment]
I set 6.5 GB of RAM (I have 16GB so I could increase it quite a bit if need be). Is 6.5 too less?

**Comment by MJRLegends** [comment]
Try and install the whole launcher and mod pack? and do any other mod packs work on that launcher? If not maybe try the curse launcher...

**Comment by MJRLegends** [comment]
By the looks of it your game is just lagging which would result in it being a problem on yourside

**Comment by asbestinuS** [comment]
Other modpacks work fine.
How do I correctly reinstall a mod? Just deleting the files in the root folder and re-downloading them?

**Comment by asbestinuS** [comment]
How is a PC with a i5 processor, 16GB DDR3 Ram, everything installed on a SSD, a R9 290x not fast enough? And how do I reinstall a modpack correctly? Reinstall the Launcher, deleting the root folder and then redownloading everything?

**Comment by MJRLegends** [comment]
@asbestinuS yeah

**Comment by MJRLegends** [comment]
If not try the curse launcher....

**Comment by asbestinuS** [comment]
So I made a backup of my FTB Folder, deleted everything and downloaded the (ugly...) Curse Launcher. I downloaded SpaceAstronomy through that and run it, everything is fine.
But when I copy my world backup into the saves folder and try to run it, I get the same error. I see my hotbar with everything in it and then javaw.exe stops responding.
I'm going to reinstall java itself and try again, but I think something is broken with my map, sadly. Is there any way to analyse the mod that's causing this problem? What happenes if I for example delete the Dimensional Anchor mod (Ühow with the Curse Launcher? Just the folder with the mod?), it just gets rid of the Anchor-Block, right? It shoudn't like cause a corrupt world or something?

**Comment by MJRLegends** [comment]
Please can i have a copy of the world

**Comment by asbestinuS** [comment]
Yeah, thank you.
I'm uploading it right now, it takes about 40 minutes (260mb). You have 7zip?

**Comment by MJRLegends** [comment]
Yeah

**Comment by asbestinuS** [comment]
Okay, so here are two parts, split with 7zip:
1. http://www43.zippyshare.com/v/wNEeyZBt/file.html
2. http://www43.zippyshare.com/v/ipfnTml1/file.html
Thanks

**Comment by MJRLegends** [comment]
Loads fine for me proof https://gyazo.com/2fb7df04f6e5f9cc94f16d7484ce9fd5

**Comment by MJRLegends** [comment]
@asbestinuS wait a min i tested that with Dev Version (Update v1.5.1), after me testing with v1.5.0 its hanging

**Comment by MJRLegends** [comment]
@asbestinuS if you want it fixed now remove ImmersiveEngineering and ImmersiveIntegration (WARNING BLOCKS/ITEMS FROM THEM MODS WILL BE REMOVED) as that worked for me, but if not wait for v1.5.1 which will be out in the next two days

**Comment by asbestinuS** [comment]
Huh..okay...that sounds fantastic! :+1: 
Thank you for the good news, and thanks for your help, really appreciate it :) I'm going to wait for 1.5.1 then, because I don't know what I have installed from ImmersiveEngineering and stuff. 
Thanks!!

**Comment by MJRLegends** [comment]
@asbestinuS No problem yeah waiting seems best
