### ISSUE TITLE
Textures missing

### ISSUE THREAD

**Issue by aop2** [MJRLegends/Space-Astronomy-Feedback-#469]
I know that this has been brought up in the past, such as in Issue #328, but I've read through all of the closed issues I can find and I don't understand how to fix it. Someone mentioned changing Splash Properties to "true," but I can't open or edit the splash.properties file in the config folder, so I don't know how to do that. I don't know a ton about java at all... I apologize if this is not technically a bug, or if you feel like this is a waste of time. I know maintaining a modpack like this is a lot of work.

If anyone can please explain what I'm missing and either how to fix this problem or just let me know it's unfixable, I would really appreciate it.

![2016-08-09_20 57 11](https://cloud.githubusercontent.com/assets/20940656/17541675/89c08b18-5e76-11e6-9e10-8e2b83c201c6.png)

**Comment by MJRLegends** [comment]
Simple fhe textures are missing and he won't make new ones

**Comment by aop2** [comment]
So, in theory, if I download the older version of More Planets and copy over the missing texture files into the texture folders in the modpack, it could fix the problem?

**Comment by MJRLegends** [comment]
Yeah but i dont support doing that

**Comment by aop2** [comment]
Fair enough. Thank you for the response.

**Comment by MJRLegends** [comment]
@aop2 At the end of the day i cant add the textures back in and release it as thats modifying his mod, but theres nothing stopping people doing it but just keep that version private for yourself

**Comment by aop2** [comment]
Totally understandable. I tried it, and it worked for me, so if anyone wants to have that option in their back pocket, then great. I get that it's not yours to fix, but at least there's a workaround for the determined.
