### ISSUE TITLE
Quest problem

### ISSUE THREAD

**Issue by jerped** [MJRLegends/Space-Astronomy-Feedback-#47]
Got a quest finished, but not claimable..... 
"Getting ready to smelt ores" I got the 20 coal, but no other sub-quest or button to claim reward. The coal has the 100% mark on it.

**Comment by MJRLegends** [comment]
i know personally that this quest works fine?

**Comment by jerped** [comment]
can it be related to the fact that I updated the pack with the quest complete, but not claimed?

**Comment by MJRLegends** [comment]
Probably a hqm bug
