### ISSUE TITLE
Map corrupt with multiblock in multiple chunks

### ISSUE THREAD

**Issue by Themme** [MJRLegends/Space-Astronomy-Feedback-#471]
Hello folks,

We are running our own awesome Space-Astronomy server and we had a corrupt world after a specific event that I want to share, 

here the sequence:
- We build a mekanism induction matrix, size 3x3x4.
- Location in Nether.
- Coordinates from    x-5, y119, z-1    to    x-3, y123, z1
- Notice how z coordinate crosses a chunk border.
- The induction matrix was partly chunk loaded by the ender quarry, the rest was not chunk loaded.
- The server was restarted, probably part of the induction matrix was loaded first and then immidiate crash.
- Map got corrupted with a crash log locating this specific induction matrix.
- Solved by editing this part in MCedit.

I think maps should not get corrupted when placing multiblocks over chunk borders and therefore have some kind of warning/disability or protection against this way of getting corrupt world.

**Comment by MJRLegends** [comment]
"Map got corrupted with a crash log" i need this crash log please

**Comment by Themme** [comment]
Hey MJR,

Log can be read here http://pastebin.com/zRTuzKk3
or in the attachment below.

[zRTuzKk3[1].txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/412778/zRTuzKk3.1.txt)

Regards,
Themme

**Comment by MJRLegends** [comment]
@Themme thanks for the crash log, i dont think this issue would be easy to reproduce, are you able to reproduce it?

**Comment by Themme** [comment]
Thanks for the efford, if I don't forget I will try tomorrow to see if I can reproduce.

**Comment by Themme** [comment]
I have tested it, .............. and it did not crash, that means we still do not know the cause. :(
I would advise closing this issue, and I will reopen this issue or create a new one if it happens again.

At least I am happy that I finally found a modpack that is being maintained :)
