### ISSUE TITLE
Crashing when loading into server.

### ISSUE THREAD

**Issue by triniP** [MJRLegends/Space-Astronomy-Feedback-#472]
I'm not sure why but I crash whenever I load into server 2 from the hub, it only started after a restart yesterday. Before that I was loading completely fine. I have tried re-installing the pack multiple times now and still no luck. I'm not sure what is causing me to crash either. (I was in the Deep Dark right before the server restart and now I'm unable to join)

crash log: http://pastebin.com/gKdpq1DN

**Comment by MJRLegends** [comment]
Whats in your inventory?

**Comment by triniP** [comment]
Nothing much, Tinkers construct tools, some porkchops, and I went mining so ores, but that is all I believe

**Comment by MJRLegends** [comment]
Give me 5

**Comment by triniP** [comment]
ok, thank you for responding so quickly!

**Comment by MJRLegends** [comment]
Have you tried the direct ip (space2.mjrlegends.co)

**Comment by triniP** [comment]
I have not, I will try that right now
