### ISSUE TITLE
Bronze Sword recipe conflicts

### ISSUE THREAD

**Issue by Wolf68k** [MJRLegends/Space-Astronomy-Feedback-#473]
I went to make the Mekanism Bronze Sword but because the bronze is ore dict and all the swords share the same recipe it always comes out as a Thermal Expansion Bronze Sword. There are 3 bronze swords, Mekanism, Thermal Expansion and IC2.

Suggested solutions:
1. Use MineTweaker to fix this
2. Use NoMoreRecipeConflict https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict

**Comment by MJRLegends** [comment]
No need to put solution as i know how to change recipes but thanks

**Comment by MJRLegends** [comment]
Added to the known issues and will be fixed in the next update
