### ISSUE TITLE
Gamefreezeing

### ISSUE THREAD

**Issue by optimze** [MJRLegends/Space-Astronomy-Feedback-#474]
http://prntscr.com/c4tzpy im muti player on plubic server my game freeze to were nothing can happen and no matter what i do it does not stop takes away hotbar everthing on the screen

**Comment by MJRLegends** [comment]
Not much i can do with this amount of details, i need to know your RAM set to the launcher, what server, coords and dimension.....

**Comment by optimze** [comment]
ram 11.00 gb cords i cant get
dimension miner world space 3 if i press ecs it there just the game frozen and i cant see it but, i can press disconnted it works but still frozen on what ever it froze on

**Comment by optimze** [comment]
its a chunk loading issue going thru world

**Comment by optimze** [comment]
https://youtu.be/PpMwpmEaTPQ
there what going on

**Comment by MJRLegends** [comment]
@optimze ok can you join the hub server please?

**Comment by optimze** [comment]
sure

**Comment by optimze** [comment]
@MJRLegends  in

**Comment by optimze** [comment]
Nope!

still broke

**Comment by optimze** [comment]
and i lost all my stuf

**Comment by optimze** [comment]
http://prntscr.com/c4weo8 all i can prove i had.
i had like a stack of redstone engery ducts in my inv to (filled)

**Comment by optimze** [comment]
Im dumb it createing a error in ftb lancher im have to glich my self agian .

**Comment by MJRLegends** [comment]
what?

**Comment by optimze** [comment]
im useing ftb lancher and i saw a error in the console

**Comment by MJRLegends** [comment]
whats the error?

**Comment by MJRLegends** [comment]
use pastebin to post it here

**Comment by optimze** [comment]
not sure i lanched the game...

**Comment by optimze** [comment]
im glich my self agian and get the error

**Comment by MJRLegends** [comment]
By the looks of it you have messed up your player file so its going to have to be deleted

**Comment by optimze** [comment]
everthing i have?

**Comment by optimze** [comment]
goes?

**Comment by optimze** [comment]
if so can you go to my base so its not lost forever

**Comment by MJRLegends** [comment]
stop spamming and let me explain!

**Comment by MJRLegends** [comment]
The first test we did when you joined at you was at spawn, i reset your playerdata, then because i made a copy i then removed all your inventory and thats when you joined the second time, so its not your inventory and its something in your player file so it needs to be all reset because idk what you have done but you have messed it up, the player data doesnt include your base or /home or claims just your inventory and that

**Comment by MJRLegends** [comment]
@optimze but i think i can get your inventory back for you

**Comment by MJRLegends** [comment]
@optimze but i need you to join space 3 for me to do it

**Comment by optimze** [comment]
that whould be nice
if not i wont the stuf i have proof of

**Comment by MJRLegends** [comment]
dont join space 3 a min

**Comment by optimze** [comment]
ok

**Comment by optimze** [comment]
still broke
im gliched out agian

**Comment by MJRLegends** [comment]
@optimze idk what your doing then

**Comment by optimze** [comment]
going to the miner world

**Comment by MJRLegends** [comment]
@optimze reinstall the mod pack has it sounds like you have messed stuff up

**Comment by optimze** [comment]
tryed still does it

**Comment by optimze** [comment]
it make a ton of console errors but

**Comment by MJRLegends** [comment]
i need them errors then?????????

**Comment by optimze** [comment]
ok let me try agian

**Comment by MJRLegends** [comment]
@optimze no dont try again just send me the errors??

**Comment by optimze** [comment]
i cant there so many thing in the way from when i lanched the game 2 times that i cant copy all that and paste it on a paste bin ext

**Comment by MJRLegends** [comment]
Well i cant help you then

**Comment by optimze** [comment]
im going to log in and im be broke and ill get the errors

**Comment by MJRLegends** [comment]
i cant magically guess the errors

**Comment by MJRLegends** [comment]
are you using optifine?

**Comment by optimze** [comment]
umm.
not sure let me look

**Comment by optimze** [comment]
i hear me walking but i not moveing on my screen

**Comment by MJRLegends** [comment]
as i said, i need a copy of what the errors say and i need to know are you using optifine? without them we are going in a loop here so please just get that infomation

**Comment by optimze** [comment]
no optifine but the error are not begin made anymore

**Comment by MJRLegends** [comment]
@optimze i need a full log then

**Comment by MJRLegends** [comment]
When you have that log i can help..

**Comment by optimze** [comment]
working on it in paste bin

**Comment by optimze** [comment]
to big.

**Comment by optimze** [comment]
what another way?

**Comment by MJRLegends** [comment]
just drag the log file here, and i will look at it later now as i got stuff i need to do atm

**Comment by optimze** [comment]
well thanks for ruining the chat i not able to paste it in this chat

**Comment by MJRLegends** [comment]
What

**Comment by optimze** [comment]
im not ABLE TO PASTE the console error in this chat
it happening to my friend me and my alt

**Comment by optimze** [comment]
plus i cant get the error anymore so im haveing to use cure (tryed to see if it whould fix) and i cant lanch the old ftb lancher

**Comment by MJRLegends** [comment]
I have no idea what you on about, i need the whole log, i haven't got time to waste keep telling you this

**Comment by optimze** [comment]
I GAVE YOU THE error in the other post i cant paste it in this post

**Comment by optimze** [comment]
it is not even do able to paste the hole log

**Comment by MJRLegends** [comment]
No you didnt post it right and i dont need you to spam loads of issues full of random parts of the log file

**Comment by MJRLegends** [comment]
Im not wasting my time
