### ISSUE TITLE
I cant mine with fist, like grass,dirt ext or use my builders wand?? HELP

### ISSUE THREAD

**Issue by churchishere** [MJRLegends/Space-Astronomy-Feedback-#476]
Its not letting me do anything to the land unless I have a shovel which is strange af

**Comment by MJRLegends** [comment]
I need more information than it doesn't let me

**Comment by churchishere** [comment]
like it says its not harvestable on the tool tip for fist, sword, tool ext, and when i place down dirt its showing the block i can build with the builders wand but wont let me place them idk why

**Comment by MJRLegends** [comment]
Single olayer or multiplayer

**Comment by churchishere** [comment]
single, look http://prntscr.com/c4xh3u

**Comment by MJRLegends** [comment]
Idk have you messed around with the config stuff like vein miner

**Comment by churchishere** [comment]
nope haven't touched it at all, I play everyday like normal never have messed with the config area

**Comment by MJRLegends** [comment]
Does it work in a new world

**Comment by churchishere** [comment]
ill try

**Comment by churchishere** [comment]
I can mine in a new world, but my same old world I cant -.-

**Comment by MJRLegends** [comment]
Did you change anything to do with vein miner `

**Comment by churchishere** [comment]
theirs vein miner in this pack?, like I said I haven't touched anything with it, other then chicken chunks added to the mod pack because it needed a chuck loader

**Comment by MJRLegends** [comment]
Make a copy of your world's and reinstall it and then dont add chicken chunks because there is chunk loaders in the mod pack, type dimension in nei

**Comment by churchishere** [comment]
im trying rn

**Comment by churchishere** [comment]
I copyed the save and reinstalled the pack and I still cant mine grass with my hand http://prntscr.com/c4y4ri

**Comment by churchishere** [comment]
i removed everything -.-

**Comment by MJRLegends** [comment]
Ok so this now fixed?

**Comment by churchishere** [comment]
nope still cant mine
