### ISSUE TITLE
Wooden Slabs => Ender-Thermic Pump

### ISSUE THREAD

**Issue by DrDrib** [MJRLegends/Space-Astronomy-Feedback-#477]
A player by the username of "Foste"
They reported that using 2 Vertical Wooden Slabs (From forge microblocks) by Shift-Right Clicking on an enchantment table would give you 2 objects called "Unnamed" They were also slabs.
Once placed you would be able to break them, although they would be named "Ender-Thermic Pump Slab"  You could open any crafting table and place the two slabs on top of each other and craft them together to make a normal Ender-Thermic Pump.
Foste replicated this glitch twice and gave the Ender-Thermic Pumps to me to trash them via lava pool

!!!Do not credit me, credit Foste instead!!!

**Comment by DrDrib** [comment]
I have a pastebin link here.
http://pastebin.com/YM63tBt2

**Comment by MJRLegends** [comment]
@DrDrib i cant reproduce this
