### ISSUE TITLE
HUD Crash

### ISSUE THREAD

**Issue by virus2222** [MJRLegends/Space-Astronomy-Feedback-#478]
The game loads fine... I get a few seconds of game play then suddenly the HUD vanishes. If I press ESC, all I can see is my cursor moving around but no options.. This occurs every time I try to play and it's irritating.. Please help!

**Comment by MJRLegends** [comment]
Are you using OptiFine and what java are u using and what graphics card and what operating system

**Comment by virus2222** [comment]
Yes I'm using OptiFine.

Java 8 Update 60..

Windows 7..

I honestly have no clue what graphics card I'm using... I'm playing from a laptop.. I have dual graphics on it and I installed both drivers for Intel and ATI Radeon.. Sorry, I'm a newbie when it comes to this..

**Comment by MJRLegends** [comment]
OptiFine isnt supported as it causes render issues and could be the issue of this one so im closing the issue

**Comment by virus2222** [comment]
Dude.. I added OptiFine because I thought it'd fix it.. But it still happened..
