### ISSUE TITLE
HUD Crash

### ISSUE THREAD

**Issue by virus2222** [MJRLegends/Space-Astronomy-Feedback-#479]
First of all, I'm sorry for double posting, but don't be too hasty to judge please..

Second of all, The issue occurred several times so I decided to use OptiFine in hopes to fix it not make matters worse.

Lastly, please don't judge me too fast.. I've done like 2 full quest trees.. So I really like the modpack. Please help?

> The game loads fine... I get a few seconds of game play then suddenly the HUD vanishes. If I press ESC, all I can see is my cursor moving around but no options.. This occurs every time I try to play and it's irritating.. Please help!

**Comment by MJRLegends** [comment]
This isnt a mod pack issue its probably to do with the fact your installing random graphics card drivers, its nothing to do with my mod pack
