### ISSUE TITLE
MFFS crash

### ISSUE THREAD

**Issue by AussieWarGod** [MJRLegends/Space-Astronomy-Feedback-#48]
Placing a cube or tube module in the mffs projector causes instant crash.

**Comment by MJRLegends** [comment]
i will investigate this and get back to you

**Comment by MJRLegends** [comment]
Can you please send me the crash log

**Comment by AussieWarGod** [comment]
I have no log abailable to me at this point in time. I will be able to get
it tomorrow if still required.

It is a recreatable, instant crash and it will happen on both multiplayer
and single player.

If i remember correctly it was a missing class crash.

**Comment by MJRLegends** [comment]
Dont worry and im trying to find a fix now

**Comment by MJRLegends** [comment]
Im removing this mod has the mod is filled with bugs and crashes and its not updated anymore
