### ISSUE TITLE
Quest "Building Tier 2 Rocket" does not accept rocket with chests

### ISSUE THREAD

**Issue by codewarrior0** [MJRLegends/Space-Astronomy-Feedback-#480]
Space Astronomy v1.5.0

Clicking "Manual Detect" does nothing. The quest seems to only accept a rocket without any chests on it.

**Comment by MJRLegends** [comment]
Yeah this is because of hqm's limited ability

**Comment by codewarrior0** [comment]
That can't be true! The quest "Actual Rocket Science!" in the modpack "Galactic Science" accepts a Tier 2 rocket with any number of chests.

**Comment by MJRLegends** [comment]
I will have a look

**Comment by MJRLegends** [comment]
Will be fixed in v1.5.3 and its been added to the known issues page
