### ISSUE TITLE
Vein Miner Not working with some blocks and with some tools

### ISSUE THREAD

**Issue by MJRLegends** [MJRLegends/Space-Astronomy-Feedback-#482]
Vein miner after the update doesnt work on dirt, sand, stone, cobblestone

**Comment by MJRLegends** [comment]
It seems the file reset, im working on a fast update now

**Comment by kezindustries** [comment]
The Polytool from the Minechem mod also does not seem to work on any block, hope that helps

**Comment by MJRLegends** [comment]
@kezindustries i know the file reset so its not got all the stuff i added, im working on a update now for the mod pack to fix it all

**Comment by kezindustries** [comment]
Oh of course, I see now, I didn't read your comment sorry

**Comment by Jin16** [comment]
Imbued Tool from practicalites to not work

**Comment by MJRLegends** [comment]
@kezindustries no problem :penguin:
