### ISSUE TITLE
Venus landing crash

### ISSUE THREAD

**Issue by CollinWesker** [MJRLegends/Space-Astronomy-Feedback-#483]
Everytime i log into the server my game is going to crash.
The last thing I did on the server was langing on the Venus, after I selected Venus on the space map my game going to crash.
Could you help me i can`t go to the Server, because of my game is crashing every time.

Sorry for my english (i`m swiss)

[crash-2016-08-15_07.56.58-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/417586/crash-2016-08-15_07.56.58-client.txt)

I hope you can help me
CollinWesker

**Comment by MJRLegends** [comment]
Use www.pastebin.com for the crash logs!!!!!!!!!!!

**Comment by MJRLegends** [comment]
Also use the direct ips's it will fix it

space1.mjrlegends.co
space2.mjrlegends.co
space3.mjrlegends.co
space4.mjrlegends.co
