### ISSUE TITLE
Server goes down

### ISSUE THREAD

**Issue by Jaless** [MJRLegends/Space-Astronomy-Feedback-#486]
Hi!, Yesterday there was an update, and after this update, always I entry in the game it crash. In the console of Feed the beast say that: [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded. I don't know what can I do.

Thanks

**Comment by MJRLegends** [comment]
Restart it

**Comment by Jaless** [comment]
The problem is, im playing alone! in a normal game, dont know how can i restart this

**Comment by MJRLegends** [comment]
So single player?

**Comment by MJRLegends** [comment]
I need the crash log, make sure you use pastebin.com

**Comment by Jaless** [comment]
I paste this, but if you want i can paste all log

http://pastebin.com/Wr1hFhsP

**Comment by MJRLegends** [comment]
Thats not the whole crash log there stuff before that

**Comment by MJRLegends** [comment]
Solution 1: Remove Advanced Genetics and then load the world and then add it back (will remove everything in your world related to the mod)
Solution 2: Edit the blocks out (coords can be found in the crash log above the mod list) using MCEdit
