### ISSUE TITLE
Digi/quarry

### ISSUE THREAD

**Issue by Ineedsome101** [MJRLegends/Space-Astronomy-Feedback-#487]
First off ign Ineedsome101
Second off the digi wont mine ores for me even tho there right there (no logs errors) my friend however can do it fine.
3rd quarrys/pump/digi visial effect it like takes my hot bar away and everthing on the screen and just freezes me it has limited my way of getting ores it happends with only those 4 things so far,logs are fine.i think it a server error it does not happend on any other server or in single player.there is very little info i can give becuase of how it works no log errors,nothing. im not very sure were to go with this issue i'm lookin around the mods to see if i could fix it.Any help i can get?

**Comment by MJRLegends** [comment]
Dont claim the area the quarry is mining just the quarry block and power and storage

**Comment by Ineedsome101** [comment]
I'm sorry what? that does not help im not claiming it it break my game as soon as i place it?

**Comment by MJRLegends** [comment]
What???

**Comment by Ineedsome101** [comment]
It happend to a guy named optimze i was looking on skype and he had a video of what happend's 
but my digi wont mine eather
i mainly wont my digi to work
any idea

**Comment by MJRLegends** [comment]
im not interested in what optimze has to say, and Dont claim the area the quarry is mining just the quarry block and power and storage
