### ISSUE TITLE
Crash while playing, refuses to reload world

### ISSUE THREAD

**Issue by Benworkinger** [MJRLegends/Space-Astronomy-Feedback-#488]
I wasn't doing anything specific, just walking, and the world freezes and game crashed.

http://pastebin.com/j271snMG

**Comment by Woncler** [comment]
I had the same error when starting up server today.
[http://pastebin.com/VrGgUtJs]

I guess it has something to do with my BC Quarry in Mining World. I removed DIM6 from world folder and server started up fine.

**Comment by MJRLegends** [comment]
Check the known issues page its there

**Comment by Benworkinger** [comment]
@Woncler so my world is named Home, do I remove it from the saves>Home folder?

**Comment by Woncler** [comment]
@Benworkinger Yeah, or you can rename it to DIM6.OLD so that DIM6 is regenerated

**Comment by Benworkinger** [comment]
@Woncler I deleted it and relaunched but it still crashed

**Comment by Benworkinger** [comment]
@Woncler Do I delete all of the DMI6 files in the space astronomy folder?

**Comment by Woncler** [comment]
@Benworkinger Oh, well that might not work for you then. I suggest you take a look at known issues page. If you can find out on which dimension it gets stuck while loading you can delete that dimension, I guess. Sorry I can't be more helpful.
