### ISSUE TITLE
Compact Machines preventing world from loading

### ISSUE THREAD

**Issue by MooseChip** [MJRLegends/Space-Astronomy-Feedback-#489]
My world was loading fine until I started using Compact Machines. All I used was a "Giant" sized compact machine with a Coke Oven inside. Everything was fine, the game never crashed and I eventually logged off. After trying to play again, the world refuses to load and I get some errors in the log. [http://paste.ee/p/jZfYO](http://paste.ee/p/jZfYO)  (Starts at about line 5348)

I was still using 1.5.0 and after the error, I updated to 1.5.2 and the errors persisted.
Removing the mod lets me load the world, adding it back in reverts to the errors.

Let me know if I left anything out, thanks guys.

**Comment by MJRLegends** [comment]
Reinstall the mod pack

**Comment by MooseChip** [comment]
Reinstalled, no change. Even without CM blocks in the world, I still get the errors.

**Comment by MJRLegends** [comment]
Yeah it might be your world is messed up, have you tried deleting the compact machines dimension (Dimension ID: DIM3)

**Comment by MJRLegends** [comment]
Any news @MooseChip

**Comment by MooseChip** [comment]
Sorry. Nah, deleting the dimension had no effect.

**Comment by MJRLegends** [comment]
@MooseChip can you send me a copy of your world?

**Comment by MooseChip** [comment]
Sure, what's the best way to send it to you?

**Comment by MJRLegends** [comment]
zip it up and upload it to something like dropbox then post the link here

**Comment by MooseChip** [comment]
Thanks.

[https://www.dropbox.com/s/pxn56nm21v0epeo/Astra.rar?dl=0](url)

**Comment by MJRLegends** [comment]
@MooseChip i dont know what to suggest im afraid

**Comment by MooseChip** [comment]
It's cool man, It's just one of those things that goes wrong. Thanks for trying though. If I play again I'll probably install a back-up mod. For now I'm on one of your servers.
