### ISSUE TITLE
Coke Furnace balance

### ISSUE THREAD

**Issue by cowchmonkey** [MJRLegends/Space-Astronomy-Feedback-#49]
railcraft and immersive engineering both have coke furnaces but railcraft is simpler to make so i think one of them should be disabled imo

**Comment by MJRLegends** [comment]
I dont really see the issues with having both tbh

**Comment by cowchmonkey** [comment]
well i agree theres not a huge issue it would be more pref to what one u use but one is more simple to make than the other

**Comment by MJRLegends** [comment]
Yeah, i might think about removing one but both will probably stay
