### ISSUE TITLE
Hi, i can't download space astronomy server files. is there any way to download them except dropbox?

### ISSUE THREAD

**Issue by PirateHat** [MJRLegends/Space-Astronomy-Feedback-#490]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes or No]

**Have you checked Closed Issues (if applicable):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You haven't bothered to fill out the form???? And go on the ftb launcher
