### ISSUE TITLE
crash after logout in a compact machine

### ISSUE THREAD

**Issue by tspmarco** [MJRLegends/Space-Astronomy-Feedback-#491]
Sorry but my crash log is too long to post on pastin, basically I left the world with me inside a compact machine. Then it crash the next time I enter the server

[crash log.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/422770/crash.log.txt)

**Comment by MJRLegends** [comment]
Fill out the form that was provided otherwise im not helping
