### ISSUE TITLE
Crash upon opening various inventories in LAN world; single player world unaffected

### ISSUE THREAD

**Issue by sipes42** [MJRLegends/Space-Astronomy-Feedback-#492]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue
Upon opening various inventories at various times, the client crashes. Host world (LAN) remains unaffected. There does not seem to be any specific item or inventory causing the issue, and it does not _seem_ NEI related. The same tile's inventory does not always produce the crash, even if the player has exactly the same items and attempts the same action. The crash, when it occurs, is always immediately after right-clicking the tile in question or immediately after pressing open inventory key. I have had this issue occur mostly with TCon crafting stations, chests, and hoppers. I have also had the issue occur when simply opening the player inventory.
Sometimes gameplay is able to continue for an hour or two before encountering the issue. Once the issue occurs, it seems to persist until the host world is restarted, at which point it may take 30 minutes to 2 hours to occur again. Local, single player worlds appear to be unaffected by the bug. 

### Steps to Reproduce Issue
1. Checked to be sure that Minecraft did not run out of memory (this happens sometimes on my computer).
2. Reloaded Minecraft and attempted to continue gameplay
3. Attempted removal of NEI folder; game crashed before loading the main menu
4. Replaced NEI folder; game loaded, but issue persists.
5. Restarted host world
5. Attempted further gameplay until the issue occurred again

**Crash log/Log (if applicable):** http://pastebin.com/wy63gv0X
**Version of Mod Pack using:** Recommended (1.5.2)

**Comment by MJRLegends** [comment]
This is a java/graphics driver related issue not a mod pack one

**Comment by MJRLegends** [comment]
Have you recently changed your graphics driver or/and java or anything hardware related??

**Comment by MJRLegends** [comment]
And what graphics card you got?

**Comment by sipes42** [comment]
I haven't changed anything recently. It's an Intel HD 4000. Not sure if that's detailed enough, not sure where to find more info on the card. I usually don't have any graphics related issues, I've been using the FTB launcher for a long time too.

**Comment by sipes42** [comment]
I haven't changed Java either, although in attempting to solve the problem I briefly switched the version the launcher used. It is now back to default which is JRE (1.8.0_73-b02).

**Comment by MJRLegends** [comment]
Theres nothing i can do to fix this sorry
