### ISSUE TITLE
Obsidian Stick recipe conflict

### ISSUE THREAD

**Issue by Wolf68k** [MJRLegends/Space-Astronomy-Feedback-#494]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes or No]
Yes

**Have you checked Closed Issues (if applicable):** [Yes or No]
### Description of Issue
There are conflicting recipes with the Obsidian Stick from Random Things and WR-CBE (Wireless Redstone).
They both use 2 obsidian blocks, one over the other. Random Things shows it should give you 3 Obsidian Sticks. WR-CBE shows that you get 2.

The result is the WR-CBE recipe.

### Steps to Reproduce Issue
1. Look in NEI for: Obsidian stick
2. Try crafting it

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
No crash

**Version of Mod Pack using:** [VERSION]
1.4.9 because the server I'm on hasn't updated yet. Nothing I can do.

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
I will be fixed in the next mod pack update, also tell the server owner you play on to update!

**Comment by MJRLegends** [comment]
Its been added to the known issues page so im closing the issue
