### ISSUE TITLE
Another INPureCore issue

### ISSUE THREAD

**Issue by Wolf68k** [MJRLegends/Space-Astronomy-Feedback-#495]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes or No]
Yes

**Have you checked Closed Issues (if applicable):** [Yes or No]
Yes

### Description of Issue
INPurecore is configured wrong for Mekanism Gas Tanks.
It's set to hide all but meta 100, but when you click on the tank to get the recipe nothing shows up.
If you change it to 0 then the tank recipe works. 

### Steps to Reproduce Issue
1. Search NEI for: Basic Gas Tank
2. Notice it says 1177:100
3. Left-click (or press R) to get the recipe

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
No crash

**Version of Mod Pack using:** [VERSION]
1.4.9 because the server hasn't updated.

### Additional Information
Simple fix. In the ~\config\INpureProjects\custom_nei_filters\Mekanism.js
Look for NEI.override("Mekanism:GasTank", [100]);
Change it to NEI.override("Mekanism:GasTank", [0]);

Side note: This also hides the Advanced, Elite and Ultimate Gas Tank.

Slightly off topic: The same sort of thing happens with the Mekanism Fluid Tanks. The basic tank recipe will show up but the higher tier empty ones are hidden.
I've tried for quite a while to find a away around this; to show all of the empty tanks. Was never able to find anything that worked.

**Comment by MJRLegends** [comment]
Nothing i can do about this

**Comment by MJRLegends** [comment]
Its either all are hidden or none and i'd rather all hidden

**Comment by MJRLegends** [comment]
Have you tested your fix?

**Comment by Wolf68k** [comment]
Yes I tested my fix and I'm using it. http://i.imgur.com/8xcPy04.png
I would never suggest a fix if I haven't tested it.


I think at one time the meta for the empty tank was 100 but then the mod dev changed it for whatever reason and of course INPurecore dev has stopped updating the mod it'll never be fixed, at least not by him.

**Comment by MJRLegends** [comment]
Ok i will try the fix then

**Comment by MJRLegends** [comment]
This has been added to the mod pack known issues so im closing it
