### ISSUE TITLE
Bug on the item IC2

### ISSUE THREAD

**Issue by Lestblack** [MJRLegends/Space-Astronomy-Feedback-#496]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes or No]

**Have you checked Closed Issues (if applicable):** [Yes or No]
### Description of Issue
Hello, first, i don't speak very well english, I'm sorry if you don't understant one or two words.
I report this bug, because we can't craft the Engine Boost "itemEngineBoost.name" (for craft after the Advanced Electric Jetpack)

### Steps to Reproduce Issue
1. Craft the Advanced Heat Vent
2. Craft the Engine Boost (you can't)

**Version of Mod Pack using:** 1.5.2

### Additional Information
The screen of the craft : http://www.noelshack.com/2016-34-1471911197-2016-08-23-01-58-06.png

**Comment by MJRLegends** [comment]
Its been added to the known issues page so im closing the issue
