### ISSUE TITLE
Incorrect recipe for item itemEngineBoost.name

### ISSUE THREAD

**Issue by Spellkaze** [MJRLegends/Space-Astronomy-Feedback-#497]
### Description of Issue
The recipe needed for the itemEngineBoost.name [5252:6] needs an Advanced Heat Vent.
The problem is that the Advanced Heat Vent needed in the recipe is [4229] but the only craftable Advanced Heat Vent is [4229:1], using this version is not compatible with the one in the recipe, already tested using a creative  [4229].

### Additional Information
A quick fix might be changing the needed advanced heat vent to be [4229:1]

**Comment by MJRLegends** [comment]
Sorry @Spellkaze but someone already reported it haha #496 . Thanks though :P

**Comment by MJRLegends** [comment]
@Spellkaze Also its been fixed on the official server already and will be completely in the next update for single player and other servers
