### ISSUE TITLE
Crash and unable to restart

### ISSUE THREAD

**Issue by RupsjeNG** [MJRLegends/Space-Astronomy-Feedback-#498]
**Version of Mod Pack using:** [VERSION 1. 5. 2]
### Additional Information

I was just building something with carpenters fences, and my screen went kinda blue.
I could not do anything anymore.
So i stopt my pc with holding the power button, and when i tried to restart the game, it did not start it anymore. I have tried to delete the game (saved my save on my desktop), but when i put my save back in the folder my game get currupt again.. and it won't start.
tried to make a new save, that is working, but again, if i put my old save in it, it's corrupt again, and i can't even play the new save anymore. what can i do so i can play my old game again. i was so far in the game already. do i have to delete some file, or replace something that might be corrupt? Please help.
Love the pack!!!

**Comment by MJRLegends** [comment]
Like how you just ignore the template and dont follow the rules: you say it crashed but where's the crash log since you delete that part from the template and you are not following the template correctly!!!

**Comment by RupsjeNG** [comment]
I did not have a crash log, my game just stopted and my sceen was kinda blue.. i’m sorry..

 

Van: MJRLegends [mailto:notifications@github.com] 
Verzonden: dinsdag 23 augustus 2016 10:48
Aan: MJRLegends/Space-Astronomy-Feedback-
CC: RupsjeNG; Author
Onderwerp: Re: [MJRLegends/Space-Astronomy-Feedback-] Crash and unable to restart (#498)

 

Like how you just ignore the template and dont follow the rules: you say it crashed but where's the crash log since you delete that part from the template and you are not following the template correctly!!!

**Comment by MJRLegends** [comment]
Then i need the full log???

**Comment by RupsjeNG** [comment]
Where can i find that?

 

Van: MJRLegends [mailto:notifications@github.com] 
Verzonden: dinsdag 23 augustus 2016 10:54
Aan: MJRLegends/Space-Astronomy-Feedback-
CC: RupsjeNG; Author
Onderwerp: Re: [MJRLegends/Space-Astronomy-Feedback-] Crash and unable to restart (#498)

 

Then i need the full log???

**Comment by RupsjeNG** [comment]
Is it one of the “dat” files in my save?

 

Van: MJRLegends [mailto:notifications@github.com] 
Verzonden: dinsdag 23 augustus 2016 10:54
Aan: MJRLegends/Space-Astronomy-Feedback-
CC: RupsjeNG; Author
Onderwerp: Re: [MJRLegends/Space-Astronomy-Feedback-] Crash and unable to restart (#498)

 

Then i need the full log???
