### ISSUE TITLE
AE2 conflicting?

### ISSUE THREAD

**Issue by Xray299** [MJRLegends/Space-Astronomy-Feedback-#499]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** Yes

**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue
Well I was playing on my SP world then exited it too play another game, when I went back on it won't load my world any more even though I haven't touch any of the mod files.

### Steps to Reproduce Issue
1. I restarted mine craft 
2. Checked memory
3. Reinstalled the same version
4. Tried installing an older version but problem still persists

**Crash log/Log (if applicable):** http://pastebin.com/g1LkSx2j

**Version of Mod Pack using:** Was using 1.5.2 and tried 1.5.1

### Additional Information
At the bottom of the crash log it has something about AE2 conflicting with ender io and buildcraft for some reason

**Comment by MJRLegends** [comment]
You havent check the Known issues as this is there and if you look at the crash log first few lines you will see it and its got nothing to do with AE2

**Comment by MJRLegends** [comment]
Next time actually check them and dont just put "yes"
