### ISSUE TITLE
i got a problem with the quest   (starting a farm) craft a mattock

### ISSUE THREAD

**Issue by minecrafterseppe** [MJRLegends/Space-Astronomy-Feedback-#5]
there is like a quest that says farming and it says i need to make a stone mattock  so made the stone matock and i have it in my inv  and i pressed manuel detect but its not detecting it so i cant finis the quest i tried trowing on the ground and putting it in my hot bar     (its made out al stone like the picture)  is this fixeable ?

**Comment by MJRLegends** [comment]
I will be fixed for the next update thats out soon

**Comment by minecrafterseppe** [comment]
ok

**Comment by MJRLegends** [comment]
I will try and get it fixed for the bug fix thats coming out soon to fix the 1.2.1 update.
