### ISSUE TITLE
More Planets / MP Extras Issue thread

### ISSUE THREAD

**Issue by Spellkaze** [MJRLegends/Space-Astronomy-Feedback-#501]
### Non rotating space stations.
Several (if not all) the space stations added by the mod don't rotate with spin thrusts, of course, vanilla and more planets stations rotate fine.

### White/yellow/red/ blue sun...?
Galacticraft on an update changed the sun to white. Reason detailed here: https://forum.micdoodle8.com/index.php?threads/airless-dimensions-should-use-the-space-station-sun-graphic.5523/
The yellow sun maybe have that reason, i mean, in real life the sun in space looks like a giant white ball.
This issue here is more like More planets Space stations have a yellow suns.

As an extra, maybe some color can be done to the other space station in other systems.
_I will place my suggestions of how suns looks in other planets in the suggestion thread (Ex Sirius B space station should have a huge sun since is orbiting so near of his Sun. Also, it seems red dwarfs and blue giants do emit a different type of light in space_

### Falling from Jupiter space station will make you fall to your death
Mars and Jupiter have space stations from more planets, while falling from mars space station make you fall to mars, falling on Jupiter will make you fall to the void. I know there is actually no Jupiter and is so bugged that going to Jupiter will make you go to Pluto instead, dunno if is an issue to be checked.

### ---
For the moment this is all the bugs i have found. some issues (suchs as polongnius rings not showing from the space station) are actually aesthetics for planets, which i am going to say in the suggestion thread

**Comment by MJRLegends** [comment]
I can defo fix the Non rotating space stations issue but i probably cant fix the Falling from Jupiter space station will make you fall to your death issue due to its a more planets issue and the sun and i cant change the more planets textures

**Comment by MJRLegends** [comment]
Fixed in v1.5.3 (Issue with rotating space stations & Sky Providers)
