### ISSUE TITLE
Disable skipping blood moon with Sitis Stick

### ISSUE THREAD

**Issue by Themme** [MJRLegends/Space-Astronomy-Feedback-#502]
Hello,

In the game there is an item called Sitis Stick from the Practicalities mod.
This stick allows you to skip night, rain and blood moon.
However, I think this should not have the ability to skip blood moon.
Whole idea of blood moon is gone like this.

Regards,
Themme

**Comment by MJRLegends** [comment]
I dont mind the skipping feature so im afraid its not being removed
