### ISSUE TITLE
Crash related to Deep Dark

### ISSUE THREAD

**Issue by EatYourBeetS** [MJRLegends/Space-Astronomy-Feedback-#503]
I can't login on server 2 or server 4 anymore, I was in the Deep Dark in both of them

Here's the crash log:

http://pastebin.com/HG7NyS6p

**Comment by MJRLegends** [comment]
Use the direct ip's

Direct Connect IP's
Server 1: space1.mjrlegends.co
Server 2: space2.mjrlegends.co
Server 3: space3.mjrlegends.co
Server 4: space4.mjrlegends.co
