### ISSUE TITLE
BC Builder not placing Carpenters blocks

### ISSUE THREAD

**Issue by stefanxtreme4** [MJRLegends/Space-Astronomy-Feedback-#506]
### ---Issue Report---
The BC builder is 1 of my favorite items to use when building a base mainly because it places, modifies and textures carpenters blocks from what i discovered in Primus Unabridged. this is not the case in space astronomy. i tried to let it place carpenters in survival, didnt work. whats up with that?

**Version of Mod Pack using:** [1.5.2]

### Additional Information
it did work in a creative blueprint, but corners are not placed in the right way

**Comment by MJRLegends** [comment]
Just because it works in ine pack doesn't mean it's default settings and behave so i class this as a suggestion not a issue

**Comment by stefanxtreme4** [comment]
i see. ok, fair enough. would be nice if it would work though, thats all
