### ISSUE TITLE
Flickering Textures

### ISSUE THREAD

**Issue by Snarley88** [MJRLegends/Space-Astronomy-Feedback-#507]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** Yes

**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue
Random textures flicker. It is unpredictable as to which textures flicker, they can be vanilla textures or from different mods. (Not sure if I can determine if all or only some of the mods. To date I have noticed that Tinkers, Havestcraft have had this issue. Maybe others, but can't be certain) The texture looks like a white square that flickers from bright white to black, sometimes there is a little of the original texture showing through, such as the very bottom of a sword handle.

### Steps to Reproduce Issue
1. I am unable to reproduce as different textures are affected with every unique load of the pack. However in every load of the game there are always textures that are affected. This would seem to indicate that this is a unique problem to my hardware, but I have not had this issue with other FTB packs before.

**Crash log/Log (if applicable):** http://pastebin.com/Uuwxjhvs

**Version of Mod Pack using:** 1.5.2

### Additional Information
I have attached the last log of loading the pack, I don't know if this will yield anything. In that load the Steak texture from vanilla MC was affected. I can provide screenshots if that will help.

Side note:
I would just like to say that I am really really enjoying this pack. Thank you for the massive amount of time I know you will have put into this pack.

**Comment by MJRLegends** [comment]
Are you using a Apple Mac and/or optifine?

**Comment by Snarley88** [comment]
Yes a Mac.

I am not using Optifine

**Comment by MJRLegends** [comment]
Yeah this seems to be a mac issue there is already issues posted about this and im unable to fix it as its a Apple Mac only issue
