### ISSUE TITLE
Crashed after relogged and played in mining world

### ISSUE THREAD

**Issue by Valvula** [MJRLegends/Space-Astronomy-Feedback-#508]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [No]
### Description of Issue
I started one world and after entered in the mining world and restarted the launcher, the world did not open, in this case, crashed the game. So I tried creating another world and played. When I got to the mining world after I restarted the game, It crashed and I cannot play on that worlds anymore.

In the first world, the last time I've played I was in the mining world, in the another world I was in overworld in "blood moon" time.

### Steps to Reproduce Issue
1. Open the game.
2. Open the world.
3. Crash before enter.

**Crash log/Log (if applicable):** [PASTEBIN](http://pastebin.com/MHCgmyBP)

**Version of Mod Pack using:** v1.5.2

**Comment by MJRLegends** [comment]
Already known issue so means you lied aboutxl checking the known issues lage

**Comment by Valvula** [comment]
Well sorry I didn't saw it :x but it's anyway I can bypass it?
