### ISSUE TITLE
im not able to join space 3 on the official server and when i try my game crashes

### ISSUE THREAD

**Issue by jjmaster2** [MJRLegends/Space-Astronomy-Feedback-#510]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [Yes or No]
### Description of Issue
[not able to join server 3 on official server and crashes game when i try]

### Steps to Reproduce Issue
1. [join official server]
2. [try to join server 3 by clicking the diamond]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [1.5.2]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Use the direct ip as it says in the hub
