### ISSUE TITLE
Sudden drop in FPS after Alt+Tab

### ISSUE THREAD

**Issue by Inumayobaka** [MJRLegends/Space-Astronomy-Feedback-#515]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue
[Drop in framerate per second after Alt Tab]

### Steps to Reproduce Issue
1. [Opening client and normal gameplay with 100++ FPS]
2. [Alt Tab out to read about a mod on Wiki page / watch YouTube tutorial on mod and FPS drops to lesser than 10]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [V1.5.2]

### Additional Information
[If I tab back into the game fast enough, it retains the FPS. It's like the FPS is trying to run away while I'm not looking at the game or something. pls halp]

**Comment by MJRLegends** [comment]
Theres 0 things i can do about this as its a you issue so i have nothing to go on ?????
