### ISSUE TITLE
Mekanism Fusion Reactor and Induction Matrix turned off/disconnected after world reload

### ISSUE THREAD

**Issue by MrMeat** [MJRLegends/Space-Astronomy-Feedback-#516]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** Yes

**Have you checked Closed Issues (if applicable):**  Yes
### Description of Issue
Mekanism Fusion Reactor turns off after reloading the world or changing the dimension.
Also the Induction Matrix disconnects from any source.

### Steps to Reproduce Issue
1. Start reactor/connect Induction Matrix
2.Change dimension/ reload world

**Version of Mod Pack using:** v1.5.2

**Comment by MJRLegends** [comment]
????

**Comment by MrMeat** [comment]
sorry was not intended. how can i delete that?

**Comment by MJRLegends** [comment]
Are you sure its not running out of fuel and can you please show some screenshots of your setup

**Comment by MJRLegends** [comment]
Will reopen if and when you reply
