### ISSUE TITLE
Official server issue : Command /ch g > "You do not have permission for this channel"

### ISSUE THREAD

**Issue by Snigzou** [MJRLegends/Space-Astronomy-Feedback-#517]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** Yup

**Have you checked Closed Issues (if applicable):** Yup.
### Description of Issue
I just switched to local chat using "/ch l" to have a chat with roogie8.
When I tried to swtich back to global chat, I get this message : "You do not have permission for this channel"
I can't switch back to global chat, and I'm stuck in local.
I've told "LeeCannonFodder_" about it, and he doesn't have permission either.

### Steps to Reproduce Issue
1. Just get basic player permissions, type /ch l
2. Try to switch back to global, you can't.

**Version of Mod Pack using:** 1.5.2 

### Additional Information
It's pretty boring being told by the server that "No ones listen to you"
I'm starting to feel lonely.

**Comment by MJRLegends** [comment]
Yeah you need to do /ch n
