### ISSUE TITLE
Dark Steel Armor Glitch

### ISSUE THREAD

**Issue by TheDerpySupport** [MJRLegends/Space-Astronomy-Feedback-#518]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes or No]
No
**Have you checked Closed Issues (if applicable):** [Yes or No]
No
### Description of Issue
[Description of the issue]
When using Dark Boots 4836:61 combined with flight(of any means) you can zoom quickly through water to the point where you go faster than chunks can load.

### Steps to Reproduce Issue
1. Have Dark Boots equipped with Flippers Upgrade
2. Have Flight of some kind(Genetics Flight is what I had when I learned about this glitch)
3. While still in flight; dip down into a body of water and start moving with the boots powered(having energy) and you can start zooming around; You can even barely touch a directional key and start skiing across/through the water.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Cant be fixed it so has been added to the known issues here http://pastebin.com/R73aBeqA
