### ISSUE TITLE
cant make magma cream

### ISSUE THREAD

**Issue by mblaes** [MJRLegends/Space-Astronomy-Feedback-#520]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes or No]

**Have you checked Closed Issues (if applicable):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by mblaes** [comment]
For some reason I can't make magma cream.  I put slime balls and blaze powder in the crafting table, and it doesn't work

**Comment by MJRLegends** [comment]
Fill out the issue template corrrectly and then i will help you

**Comment by mblaes** [comment]
Description
For some reason I can't make magma cream. I put slime balls and blaze powder in the crafting table, and it doesn't work

Steps to reproduce issue
1 take a slimeball from inventory
2 take blaze powder from inventory
3 insert slimeball and blaze powder next to each other  in a crafting table 
4 nothing happens

Version of modpack SpaceAstronomy-1.5.2-1.7.10.zip

**Comment by mblaes** [comment]
I figured it out  I was using blitz powder

**Comment by MJRLegends** [comment]
@mblaes Next time please check your doing it right before posting a issue
