### ISSUE TITLE
Game crashing while loading singleplayer world

### ISSUE THREAD

**Issue by PolskiSledz2001** [MJRLegends/Space-Astronomy-Feedback-#523]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** Yes

**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue
Game crashes while loading singleplayer world

### Steps to Reproduce Issue
1. Not known

**Crash log/Log (if applicable):** http://pastebin.com/PQd9ZP8D

**Version of Mod Pack using:** 1.5.2

### Additional Information
Rarely it allows me to join the singleplayer world, but most times it just crashes my game.
I tried to delete HQM folder, but it didn't change anything.

**Comment by MJRLegends** [comment]
Yoy haven't checked the known issues page since this is is there

**Comment by MJRLegends** [comment]
Number 8 in the main bugs section
