### ISSUE TITLE
Space 4 endlees restart loop

### ISSUE THREAD

**Issue by Anakardian** [MJRLegends/Space-Astronomy-Feedback-#524]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):**  Yes

**Have you checked Closed Issues (if applicable):**  N/A
### Description of Issue
Space 4 restarts a few seconds after people start to log in.

### Steps to Reproduce Issue
Log in on Space 4 if it is done restarting

**Crash log/Log (if applicable):** N/A

**Version of Mod Pack using:** 1.5.2

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Yeah your crashing it so stop joining
