### ISSUE TITLE
Dragonknight458 responding to MJRLegends

### ISSUE THREAD

**Issue by dragonknight458** [MJRLegends/Space-Astronomy-Feedback-#526]
it says i have been banned because there is an issue when ever i log into space 3. i would like to fix this problem as soon as possible. a possible solution is to let me put all my stuff away and then delete my player data.

**Comment by MJRLegends** [comment]
@dragonknight458 are you near any mob farms or have any mob farms that would be loaded through a chunk loader

**Comment by dragonknight458** [comment]
No last thing I remember being near was a tesseract

**Comment by MJRLegends** [comment]
Let me know via here when your free to come on mc
