### ISSUE TITLE
Parachest not appearing in overworld

### ISSUE THREAD

**Issue by goombatrony** [MJRLegends/Space-Astronomy-Feedback-#527]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [Yes]

### Description of Issue
When returning both from moon and mars to the overworld there is no parachest with rocket and launch pad blocks

### Steps to Reproduce Issue
1. Launch to other planet
2. Launch back to overworld
3.  Land under parachute and there is no parachest 

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [1.5.2]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Single player or multiplayer and if multiplayer what server

**Comment by goombatrony** [comment]
multiplayer 

Server 
MCP v9.0.5
FML v7.10.99.99
MC Forge 10.13.4.1614

**Comment by MJRLegends** [comment]
what is the server ip?

**Comment by MJRLegends** [comment]
what is the server ip/server name? is that i meant by what server

**Comment by goombatrony** [comment]
158.69.55.240:25570

**Comment by MJRLegends** [comment]
Weird its probably just lag on the server end so just get someone who can spawn you back in a rocket
