### ISSUE TITLE
Problems with Optifine Installation

### ISSUE THREAD

**Issue by TerrusMaximus** [MJRLegends/Space-Astronomy-Feedback-#529]
Hi, 
i am actually playing the Modpack version 1.5.2, 
cause i have sometimes low fps i installed optifine to make this better.
The Problem with the low fps is fixed, i have ofen 90fps, but i when i tried to decrease
the maximum fps per sec in the options, my game crashed.
 I can play without problems but in the ingame chat always this appear several times: 
"OpenGL Error: 1280 (Invalid enum)"

I have installed the optifine version Optifine_1.7.10_HD_U_D6

Here is the crash report too.

[crash-2016-09-14_20.27.24-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/477316/crash-2016-09-14_20.27.24-client.txt)

I hope that you can help me

**Comment by MJRLegends** [comment]
Dont support optfine as it breaks modded packs
