### ISSUE TITLE
HQM, cargo rocket quest

### ISSUE THREAD

**Issue by Ryoko** [MJRLegends/Space-Astronomy-Feedback-#530]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]
**Have you checked Closed Issues (if applicable):** [Yes]

### Description of Issue
This issue was closed, but not resolved. 
[HQM, cargo rocket quest #198
](https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/198)
I've found the reason of this issue:
The detection method must be "Fuzzy detection" but now it's "NBT independent detection"
Also this issue present in "Building Tier 2 Rocket" quest.

It's quite frustrating to craft wrong rocket type and need to craft another one, just trying to quess what kind of rocket is needed to fulfill the task request. 

### Steps to Reproduce Issue
1. [First step]
Craft Cargo rocket with 3 cargo boxes
2. [Second step]
Try to get quest reward

**Version of Mod Pack using:** [1.5.2]

**Comment by MJRLegends** [comment]
Its setup correctly its just HQM mod is bad at working right, but i will have a look again

**Comment by MJRLegends** [comment]
Yeah i cant fix it due to HQM mod and how galacticraft register the rockets

**Comment by MJRLegends** [comment]
Solution 1: Use "/hqm edit" command to complete the quest

**Comment by MJRLegends** [comment]
Fixed in v1.5.3
