### ISSUE TITLE
Forge Microblocks surrounding Galacticraft pipes. 

### ISSUE THREAD

**Issue by BrotheBear** [MJRLegends/Space-Astronomy-Feedback-#531]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]

### Description of Issue
Forge microblocks do not work with Galacticraft pipes.  - Especially the hollow slabs for oxygen and aluminum pipes.

### Steps to Reproduce Issue
1. Craft a hollow microblock and attempt to place it on an oxygen or aluminum pipe.

**Crash log/Log (if applicable):** 

**Version of Mod Pack using:** Current

### Additional Information
Should be a config file for forge microblocks where you can define additional pipes.

**Comment by MJRLegends** [comment]
There is no config file to do this, its something Galacticraft has to add support for
