### ISSUE TITLE
More Planets Mod Fromos textures fix.

### ISSUE THREAD

**Issue by Ryoko** [MJRLegends/Space-Astronomy-Feedback-#532]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]
**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue
This issue was mented in closed #300, #328, #458 issues.

I've found some textures missed in More Planets mod. Managed to fix this issue with textures from [TehporP/More-Planets](https://github.com/TehporP/More-Planets) repository.

Fixed mod can be downloaded here: [More-Planets-1.7.10-1.3.3.jar](https://www.dropbox.com/s/8zr0dnv1jqnnb9v/More-Planets-1.7.10-1.3.3.jar?dl=0)

**Version of Mod Pack using:** [1.5.2]

**Comment by MJRLegends** [comment]
Not fixable as i dont own the mod and the mod dev isn't adding them

**Comment by MJRLegends** [comment]
Also i cant add unofficical mods to the mod pack as thats copyright and could get my mod pack taken down....
