### ISSUE TITLE
ores not registering in early hqm ore collection quest

### ISSUE THREAD

**Issue by juzzyo-ffm** [MJRLegends/Space-Astronomy-Feedback-#533]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue
Ores not registering in early hqm ore collection quest

### Steps to Reproduce Issue
1. Get up to ore collection quest in HQM
2. collect ores
3. Tin and Iron fail to register as collected, even though I have collected various types (gravel, normal)

**Version of Mod Pack using:** [1.5.2]

Great mod pack so far. Thanks!

**Comment by juzzyo-ffm** [comment]
I restarted and now it is recognising the ores. Not sure what is going on. Thanks for looking at this ticket so quickly in any case. :)

And thanks again for the modpack. It's awesome.

**Comment by MJRLegends** [comment]
No problem
