### ISSUE TITLE
Magnum Torch Glitch

### ISSUE THREAD

**Issue by BrotheBear** [MJRLegends/Space-Astronomy-Feedback-#536]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue
For the magnum torch, the recipe is a healing 2 potion (ID 373:8229). Potions dropped from a witch (373:16341) then upgraded with glowstone to make the healing 2 potion give the id 373:16181, which won't work to create the magnum torch (even though it's the same potion)

Is there any chance you could add the witch drop potion to the recipe please?

Witch drop - http://prntscr.com/cly6qj
Vanilla recipe - http://prntscr.com/cly6v3

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
Thanks.

**Comment by MJRLegends** [comment]
Will be fixed in 1.5.3 and has been added to the known issues here http://pastebin.com/R73aBeqA

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/dad934356580548c0931e3dc9970ac05.png)
