### ISSUE TITLE
My world is always GLITCHING!!!

### ISSUE THREAD

**Issue by Eletrorick** [MJRLegends/Space-Astronomy-Feedback-#538]
i was playing in my normal world since 2 months ago. Today i open it and say that its better if i backup the map and click in yes to continue but I CANT PLAY IT ANYWAY PLZ HELP ME THIS IS NOT THE FIRST MAP THAT  I LOST IN THIS MODPACK
![2016-09-24 1](https://cloud.githubusercontent.com/assets/22422403/18812501/508a05ee-82ad-11e6-89e3-b1f5cd9152a2.png)

**Comment by MJRLegends** [comment]
I cant do anything with the information you have given me and your world is corrupted. You should make backups of your world incase this happens and then you wont be losing the world....
