### ISSUE TITLE
Crashing after placing Advanced Inscriber next to fluxduct.

### ISSUE THREAD

**Issue by ShadyViper** [MJRLegends/Space-Astronomy-Feedback-#540]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes or No]
Yes
**Have you checked Closed Issues (if applicable):** [Yes or No]
No
### Description of Issue
I was casually playing, one quest said to create the 'Advanced Inscriber', as soon as I placed it my game froze and crashed and I can no longer access the world which mean all my progress I made today was pointless.

### Steps to Reproduce Issue
1. Create Advanced Inscriber
2. Place Advanced Inscriber next to leadstone fluxducts (could possibly be next to other wires)

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
http://pastebin.com/hNBUzstH
**Version of Mod Pack using:** [VERSION]
SpaceAstronomy-1.4.2-1.7.10.zip (Beta) 
### Additional Information
I specifically chose that version of the mod pack because the other versions don't work on my computer for some reason since it crashes whenever it loads on a higher version.

**Comment by MJRLegends** [comment]
Update your mod pack version
