### ISSUE TITLE
World Corruption

### ISSUE THREAD

**Issue by TheGemMonkey** [MJRLegends/Space-Astronomy-Feedback-#541]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes or No]

**Have you checked Closed Issues (if applicable):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]
------------------------------------------------------------------------------------------------------------------
I have checked the Page of the issues and none were my problem.

I have not checked closed issues.

http://paste.feed-the-beast.com/view/f9d1c70a

**[EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and my not work with newer version.
                  * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from compactmachines-1.7.10-1.21.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.]**

Version: 1.7.10 (1.5.2)

When I join the world it crashes and this is what I could find out. Please look into this! My brother and I are on the weekend and are looking forward to play. I made 2 worlds and both are corrupted from something.

**Comment by MJRLegends** [comment]
Check the crashs your getting and check the known issues before posting as its there and doesnt need to be posted again as a solution is there
