### ISSUE TITLE
Compact machines related crash

### ISSUE THREAD

**Issue by Alchemistress** [MJRLegends/Space-Astronomy-Feedback-#543]
### ---Issue Report---
Have you checked the Known Issues page: Yes

Have you checked Closed Issues: Yes
### Description of Issue
After trying to enter a compact machine on space 3, my client crashed. I cannot join space 3 now, as
I keep crashing, even when using the direct IP.
### Steps to Reproduce Issue
1. Place a "big" sized compact machine.
2. Right click on it with a personal shrinking device.

Crash log: http://pastebin.com/47XUVNvR

Version of Mod Pack using: 1.5.2

### Additional Information
I don't know if only the "big" sized compact machines cause the problem.

**Comment by MJRLegends** [comment]
Your have optifine installed, which means this could be the cause and i dont provide help with any render/client issues when you have this mod installed
