### ISSUE TITLE
Items randomly dissapering from AE System

### ISSUE THREAD

**Issue by Parilia** [MJRLegends/Space-Astronomy-Feedback-#544]
### ---Issue Report---

**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue

[Items will at random vanish from the AE system, mostly all of the time it is when you place the item in the terminal and it will just be voided]
### Steps to Reproduce Issue
1. [I found this mostly with redstone but also many other items; place the redstone in an ME terminal]
2. [Its Gone]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [1.5.2]
### Additional Information

[So far I have noticed these things vanish: yellorium, redstone, energetic alloy, power conduits. Also note that when placing items in the system via ME crafting terminal everything gets voided]

**Comment by MJRLegends** [comment]
Single player or multiplayer, and if multiplayer what server? and what does the server run? forge or kcauldron or thermos?

**Comment by AWaRFISH** [comment]
I had a very similar experience to this, but I had mistakenly put the same item in 2 different deep storage units with storage busses connected to the AE system, which looked like things were disappearing when I was crafting or adding items in the terminal

**Comment by Parilia** [comment]
its on a server running forge, its which ever forge version you are running with the pack. This happens whether or not there is a deep storage unit attatched .

**Comment by MJRLegends** [comment]
I cant do anything without seeing your me system as its not a easy thing to reproduce
