### ISSUE TITLE
Can convert iron bars and dark iron bars interchangeably

### ISSUE THREAD

**Issue by mario308** [MJRLegends/Space-Astronomy-Feedback-#545]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue
Since Dark Iron Bars and Iron Bars have the same oreDictionary name you can convert one to the other with storage drawers. I know you can't do this with every item that has the same oreDictionary name but this shouldnt happen with these items because this makes dark iron bars significantly cheaper

### Steps to Reproduce Issue
1. Make Dark Iron Bars
2. Put them in a storage drawer
3. Make Iron Bars
4. Put them in the same drawer you put the Dark Iron Bars in and they will get converted into Dark Iron Bars

*This works the other way around too*

**Version of Mod Pack using:** [1.5.2]

**Comment by MJRLegends** [comment]
Will be fixed in v1.5.3 and has been added to the known issues here http://pastebin.com/R73aBeqA
