### ISSUE TITLE
Launcher Crush From Curse

### ISSUE THREAD

**Issue by Shtoota** [MJRLegends/Space-Astronomy-Feedback-#546]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** Yes

**Have you checked Closed Issues (if applicable):** Dont Know How/What
### Description of Issue
I Press On play and after 1 secend the launcher crush

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
http://pastebin.com/t8jyAREf

**Version of Mod Pack using:** Newest One ( Sownlouded Today )

### Additional Information
Nope, plz help me fast :D

**Comment by MJRLegends** [comment]
Reinstall the whole launcher and mod pack

**Comment by Shtoota** [comment]
Same Thing... Same Crush And Same Error. im trying for 2 weeks to downloud the ModPack  :(.

**Comment by MJRLegends** [comment]
Delete every part of the launcher and try then

**Comment by MJRLegends** [comment]
And its a launcher issue not a mod pack related one, maybe try use the frb launcher if not

**Comment by Shtoota** [comment]
how do i delete ever part of it?

**Comment by Shtoota** [comment]
cant use FTB every time i try it sais Error Louding Assets

**Comment by MJRLegends** [comment]
Uninstall the curse launcher like a normal program and then check if these folders are deleted

1. "Documents\Curse\"
2. "C:\Users\USERNAME\AppData\Roaming\Curse"
3. "C:\Users\USERNAME\AppData\Roaming\Curse Client"

**Comment by MJRLegends** [comment]
Also both problems are to do with you and the launchers

**Comment by Shtoota** [comment]
id deleting Fail? what should i do next?

**Comment by MJRLegends** [comment]
have you closed the curse launcher and uninstalled it?

**Comment by Shtoota** [comment]
i cant delete the Curse Client and the CurseUI... dint know why

**Comment by MJRLegends** [comment]
have you closed the curse launcher and uninstalled it?

**Comment by Shtoota** [comment]
I Uninstalled everthing i can... but this 2 ijust cant and i cloed everything

**Comment by MJRLegends** [comment]
Restart then try

**Comment by Shtoota** [comment]
now it sais  "unable to start the minecraft runtime environment this is most likely caused by a corruption curse"

**Comment by MJRLegends** [comment]
No idea, i think you need to clean everything curse launcher off and reinstall it and then reinstall your java and try again

**Comment by Shtoota** [comment]
i think i have 2 Javas Dowlouded 1 is 32 and one 64, i dont realy know about Java so can you send me a link to the downloud, i use Windows 10 64 Bit, and how do i delete the Old java?

**Comment by MJRLegends** [comment]
You can find them on the java website

**Comment by MJRLegends** [comment]
Does any other mod pack work?

**Comment by Shtoota** [comment]
Nope

**Comment by Shtoota** [comment]
Oh Actually Yes, i Played in Other SpaceCraft Mods But This is one is The Best Iv Seen From Videos... So i wanted to try out this one

**Comment by MJRLegends** [comment]
Test another mod pack on the launcher now

**Comment by Shtoota** [comment]
i couldnt play it on Curse, But I Did managed To Play Other Modpacks in Tekkit

**Comment by Shtoota** [comment]
Well I Tryed And No, I Cant Play other modpacks in curse

**Comment by MJRLegends** [comment]
Contact curse launcher aupport then as its not my mod pack that is the issue

**Comment by Shtoota** [comment]
NP
