### ISSUE TITLE
undefined loading a save game

### ISSUE THREAD

**Issue by amy290** [MJRLegends/Space-Astronomy-Feedback-#547]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue
[when the game load the backup remains in charging mode without any display. there is this phrase that keeps coming back : [12:30:32] [Client thread/ERROR]: ########## GL ERROR ##########
                                  [12:30:32] [Client thread/ERROR]: @ Post render
                                  [12:30:32] [Client thread/ERROR]: 1281: Invalid value, 
I do not know or it may come. I add 2 or 3 more mods and it functioned well from the beginning. Its made me as the launcher Curse, I thought it was a bug launcher, but no.]

**Crash log/Log (if applicable):**
[lasted_log.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/508318/lasted_log.txt)

**Version of Mod Pack using:** [1.5.2]

I gave you all the necessary information, now if it lacks some things tell me. I hope to have a fast enough response for malgrés all, I love this mod pack. I thank you. (google trad, excuse me).

**Comment by MJRLegends** [comment]
Remove OptiFine

**Comment by amy290** [comment]
it's not optifine I reload my save and crash.

**Comment by MJRLegends** [comment]
Your error is a open gl error not a mod pack one

**Comment by MJRLegends** [comment]
Plus your have added mods so i cant support you with edits to my pack as that could be the cause

**Comment by amy290** [comment]
I added, journeymap, optifine, veinminer and Schematica. I'll test in the enlevants one by one, and reload my save. I tell you if it works or not.

**Comment by MJRLegends** [comment]
As i already said its OptiFine!

**Comment by amy290** [comment]
no, no, I tried without optifine, and not walking

**Comment by MJRLegends** [comment]
Are you using a texture pack?
What GPU you got?
What Operating System you using?

**Comment by amy290** [comment]
finally I put a newer version of optifine mod and its progress, except that it spam chat me: 
"openGl Error : 1280 (invalid num)"
i have a texture pack norzetus space. and have a windows 7.

**Comment by MJRLegends** [comment]
Remove your texture pack its probably the cause

**Comment by amy290** [comment]
in fact, you're right, it's not lol optifine wants the problem is that this mod pack is actually resource hungry than its optifine it plays more nicely.

**Comment by MJRLegends** [comment]
I know

**Comment by amy290** [comment]
ok. you can not integrate the mod in a future release?

**Comment by MJRLegends** [comment]
No optifine messes things up and causes about 1000 issues lol
