### ISSUE TITLE
Crashed as soon as I loaded the game

### ISSUE THREAD

**Issue by katkatkat161** [MJRLegends/Space-Astronomy-Feedback-#549]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** No
[kzXFzSRX.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/509622/kzXFzSRX.txt)

**Have you checked Closed Issues (if applicable):** No]
### Description of Issue
load crash

### Steps to Reproduce Issue
1. Download pack on curse
2. press play

**Crash log/Log in file

**Version of Mod Pack using:** [1.5.2-1.7.10.zip]

### Additional Information
I don't know, It just crashes before minecraft opens

**Comment by MJRLegends** [comment]
see #546
