### ISSUE TITLE
Server 4 not loading

### ISSUE THREAD

**Issue by Kravyn** [MJRLegends/Space-Astronomy-Feedback-#551]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes or No]
no
**Have you checked Closed Issues (if applicable):** [Yes or No]
no
### Description of Issue
[Description of the issue]
Server says Online but no one can get on.
### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]
1.5.3
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Its coming up now
