### ISSUE TITLE
World Crashing 

### ISSUE THREAD

**Issue by fftrftrt4rfddt4r** [MJRLegends/Space-Astronomy-Feedback-#553]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes or No] Yes

**Have you checked Closed Issues (if applicable):** [Yes or No] Yes
### Description of Issue- Whenever I try logging into my world that I have previously played on yesterday, It doesnt load the world and just crashes

[Description of the issue]

### Steps to Reproduce Issue
1. [First step] Delete this folder "ftblauncher\SpaceAstronomy\minecraft\Saves\YOURSAVE\HardcoreQuesting" replace "YOURSAVE" with your world folder name. (You will lose all your quest progress!!!) But you can use "/hqm edit" command to complete the quests you did before!!!
2. [Second step] Start a New World

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]  http://pastebin.com/gA9A4s1g

**Version of Mod Pack using:** [VERSION] 1.5.3

### Additional Information
[Any other information that may be able to help me with the problem] The world was created yesterday, and in the log It has said Ender IO has been causing a problem aswell.

**Comment by MJRLegends** [comment]
Lol why the hell have you copied my known issues solutions for your setups to reproduce and why you even posting it if its on there in the first place wtf

**Comment by fftrftrt4rfddt4r** [comment]
MJRLegends I cannot figure out how to solve this issue what I mean by that is that I cannot understand your words

**Comment by MJRLegends** [comment]
Simple do this

Solution 1: Delete this folder "ftblauncher\SpaceAstronomy\minecraft\Saves\YOURSAVE\HardcoreQuesting" replace "YOURSAVE" with your world folder name. (You will lose all your quest progress!!!) But you can use "/hqm edit" command to complete the quests you did before!!!

or this 
Solution 2: Start a new world.
