### ISSUE TITLE
World Crashing

### ISSUE THREAD

**Issue by fftrftrt4rfddt4r** [MJRLegends/Space-Astronomy-Feedback-#554]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes or No] Yes

**Have you checked Closed Issues (if applicable):** [Yes or No] Yes
### Description of Issue I cant load up my world Ive seen every page that can help Im so confused at MJRLegends instructions for the first error I need just someyone to tell me step by step instructions.
[Description of the issue]

### Steps to Reproduce Issue
1. [First step] 
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION] 1.5.3

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Dont post a new issues

**Comment by fftrftrt4rfddt4r** [comment]
MJRLegends I NEED UR help

**Comment by fftrftrt4rfddt4r** [comment]
Ur the only one that I can talk to

**Comment by MJRLegends** [comment]
Stop spamming for starters
