### ISSUE TITLE
Hang on title screen

### ISSUE THREAD

**Issue by The-Flying-Guy** [MJRLegends/Space-Astronomy-Feedback-#555]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue
After loading the modpack, launching it from FTB, it shows the titlescreen briefly and then proceeds to hang forever, not redrawing the screen. 

### Steps to Reproduce Issue
1. Install FTB Launcher.
2. Launch the modpack
3. Wait 10 minutes
4. Briefly see the title screen

**Crash log/Log (if applicable):** 
https://gist.github.com/The-Flying-Guy/f8eb6c022625b3814bfa515130bec11a

**Version of Mod Pack using:** 
1.5.3 (latest on Forge)

### Additional Information
Running Linux, so unable to try it on Curse.

**Comment by MJRLegends** [comment]
Theres nothing wrong here just your computer is taking ages to load it....

**Comment by The-Flying-Guy** [comment]
But it does actually show the menu (once) and after that Java uses essentially zero CPU (between 0 and 5%). So a hang seems to be more descriptive, but I'll give it 30 minutes.

**Comment by The-Flying-Guy** [comment]
Tested it by leaving it on for 30 minutes, nothing happens and I need to kill Java to get it to exit.

**Comment by The-Flying-Guy** [comment]
Okay, I have it debugged, for some reason OpenAL audio was breaking and unlike other modpacks for Space Astronomy that didn't mean no audio, it meant that it hang.

**Comment by MJRLegends** [comment]
Your problem isnt the mod pack so im closing the issue and sorry idk what to suggest to fix it
