### ISSUE TITLE
Crash when opening world

### ISSUE THREAD

**Issue by gbele46** [MJRLegends/Space-Astronomy-Feedback-#556]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue
[Cant open world. It crashes when it says loading.]

### Steps to Reproduce Issue
1. [Clicking on Play selected world]
2. [/]

**Crash log/Log (if applicable):** [http://pastebin.com/MHq6Ed46]

**Version of Mod Pack using:** [1.5.3]

### Additional Information
[It started happening when my power went out, so my computer turned off, while I was playing. Also the computer turned off as I was crafting something. Before the computer turned off, the world was running without any problems.]

**Comment by MJRLegends** [comment]
Already known issue so check the known issues page again
