### ISSUE TITLE
i cant play this modpack

### ISSUE THREAD

**Issue by bogdan100pink** [MJRLegends/Space-Astronomy-Feedback-#557]
### ---Issue Report---
**Have you checked the Known Issues page [no]
**Have you checked Closed Issues (if applicable):** [no]
### Description of Issue
[so when i press play i wait for the modpack to load after i press singleplayer and then i try to start the world and crash]

### Steps to Reproduce Issue
1. [press start and wait  for the modpack to load]
2. [start the world]

**Crash log/Log (if applicable):** [
[
[crash-2016-10-13_14.17.54-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/526961/crash-2016-10-13_14.17.54-server.txt)
]

**Version of Mod Pack using:** [1.5.3]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You need to check the known issues as your issue is there!
