### ISSUE TITLE
I think this is a modpack error probably but reinstalling didn't work. Some Java.lang error.

### ISSUE THREAD

**Issue by Kritin2345** [MJRLegends/Space-Astronomy-Feedback-#558]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):Yes but that didn't help
**Have you checked Closed Issues (if applicable):Yes but didn't help

### Description of Issue
I've installed Space Astronomy using Curse yesterday on my PC and it downloaded the Forge and Minecraft versions. But when ever I try to open it, I get the java.lang error.

**Crash log/Log (if applicable): http://pastebin.com/pe5FWL6F 

**Version of Mod Pack using: 1.5.3

**Comment by MJRLegends** [comment]
What java you using?

**Comment by MJRLegends** [comment]
Your best bet is to reinstall the whole launcher and delete all mod packs files and reinstall them again.. as its a curse and forge/fml bug not anything to do with my mod pack, if not i dont know sorry as its nothing at my mod pack level that is a issue its the forge and launcher.

**Comment by MJRLegends** [comment]
Also the just for future reference this error normal happens when forge/fml didnt install correctly and therefore missing files to launch fml/forge
