### ISSUE TITLE
Inventory Tweaks

### ISSUE THREAD

**Issue by DeamonKnight** [MJRLegends/Space-Astronomy-Feedback-#559]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** yes
**Have you checked Closed Issues (if applicable):** yes
### Description of Issue
[Description of the issue]
When I log on I can no longer see the recipes for things as well as I am not able to turn magnet mode on or off or use any of those tools.
### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
*face palm* how can i do anything with this level of information??

**Comment by DeamonKnight** [comment]
Im just stating what Ive seen. I have no idea how to fix it or anything so how am I suppose to know what to give you. Ive given my issue what more do you need

**Comment by DeamonKnight** [comment]
if you need more info on the brokeness of it I can not search up recipes that I need to know without having an item needed for said recipe. I cannot turn on or off rain or magnet mode, make it day or night, heal or any of those other helpful things and essentially play in a either creative world and look through the tabs to find that mode or like ive stated before get something that might be used to craft one of the items in the recipe or something like that

**Comment by MJRLegends** [comment]
show your nei isnt showing?

**Comment by DeamonKnight** [comment]
![screenshot 6](https://cloud.githubusercontent.com/assets/22858269/19425777/65e69780-93fc-11e6-80da-b1017f8d4c78.png)
![screenshot 7](https://cloud.githubusercontent.com/assets/22858269/19425778/67db9860-93fc-11e6-985c-61c9d6afeaeb.png)
![screenshot 9](https://cloud.githubusercontent.com/assets/22858269/19425780/6a1cb0e6-93fc-11e6-8bdf-e1e7bbd6d891.png)
![screenshot 10](https://cloud.githubusercontent.com/assets/22858269/19425782/6c72b9ee-93fc-11e6-8b1a-0792254c31b6.png)

here are the screenshots

**Comment by MJRLegends** [comment]
Press the O key...

 and to get it up in the creative menu press this
![](https://i.gyazo.com/920a25dc730a98dd61ae91ec7ea5dd01.png)
