### ISSUE TITLE
Crash when i launch

### ISSUE THREAD

**Issue by FluffyDesire** [MJRLegends/Space-Astronomy-Feedback-#561]
So, what i get is: When i start the the curse client, and I click to play the mod pack, my minecraft opens.
it starts loading 1/7, but at 5/7 it just crashes. I have no clue how to import a crash file since there is none

**Comment by MJRLegends** [comment]
Right which is your preferred launcher?

**Comment by FluffyDesire** [comment]
either, doesn't really matter for me

**Comment by MJRLegends** [comment]
Ok does any mod pack work on them two launchers

**Comment by FluffyDesire** [comment]
seems like every modpack crashes.

**Comment by MJRLegends** [comment]
Idk then sorry maybe post something on ftb forums or do some research..
