### ISSUE TITLE
Biome ID Conflict

### ISSUE THREAD

**Issue by Mictali** [MJRLegends/Space-Astronomy-Feedback-#562]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes or No] Yes

**Have you checked Closed Issues (if applicable):** [Yes or No] No
### Description of Issue
The configuration files have both the Aroma Dimension Mining Biome and Biomes O'Plenty Mystic Grove using the same id number 74.  This results in mining biome generating in overworld and no Mystic Groves being able to generate.

**Version of Mod Pack using:** [VERSION] 1.5.3

**Comment by MJRLegends** [comment]
Thanks will fix for the next update

**Comment by MJRLegends** [comment]
And has been added to the known issues here http://pastebin.com/R73aBeqA
