### ISSUE TITLE
World cant load, cant find the problem

### ISSUE THREAD

**Issue by nikounlocked** [MJRLegends/Space-Astronomy-Feedback-#563]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes or No]
Yes
**Have you checked Closed Issues (if applicable):** [Yes or No]
Yes, Havnt found the correct issue, tried everything that were said in each
### Description of Issue
Each time I try to load my world, I get crashed in the loading.

### Steps to Reproduce Issue
N/A, each time I try to load my world
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
http://pastebin.com/zBAAiHDa
**Version of Mod Pack using:** [VERSION]
1.5.3-1.7.10
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/2dc9893133e6c04a49e93f212ce9098f.png)
