### ISSUE TITLE
Cant Craft Universal Terminal From Extra cells

### ISSUE THREAD

**Issue by shanedublin** [MJRLegends/Space-Astronomy-Feedback-#565]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [yes]

**Have you checked Closed Issues (if applicable):** [yes]
### Description of Issue
Can't craft universal terminal. 

### Steps to Reproduce Issue
1. Try to craft universal terminal

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [1.5.3]

### Additional Information
Tried on both single player and multiplayer. 
Cant seem to craft it. 
The recipe Might not be showing up in nei correctly either. 
Can't get the crafting terminal to work either. 
Running on Windows 10

**Comment by MJRLegends** [comment]
Does show? ![](https://i.gyazo.com/bea126f7f8c6ebf73360bff6124cadb3.gif)
and does work?
![](https://i.gyazo.com/beb0ddb7952e3e500ae5e0651800cbd0.gif)

**Comment by shanedublin** [comment]
My bad. I was trying to make a crafting terminal. The config for crafting is turned on but I guess that mod isn't installed.  
There is a recipe that shouldn't be in there though.  NEI says you should be able to create a universal terminal with a regular wireless terminal and a regular me terminal.
