### ISSUE TITLE
BC Factory Pump and Transfer Nodes don't mix

### ISSUE THREAD

**Issue by Moogic** [MJRLegends/Space-Astronomy-Feedback-#567]
### ---Issue Report---

**Have you checked the Known Issues page (if applicable):** Yes
**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue

When using the pump from BC Factory and using a Liquid Transfer Node to pull out oil the game crashes.
### Steps to Reproduce Issue
1. Find some oil to pump.
2. Use a pump from BC Factory and a liquid transfer node to start pumping it into some kind of container. (I was using a drum)
3. R-Click the liquid transfer node to bring out the GUI for the node itself. (You don't need to put anything in it, however my first time crashing my game I tried to add speed upgrades into the node)

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** 1.5.3
### Additional Information

I didn't try to recreate the scenario at all, however it did crash my game twice soI know it was a reoccurring issue.  Whether or not it continues to do this with another kind of liquid container I don't know. Also I believe it only does it with oil as far as I know. 

Multiplayer
Server: sa2.frozensoul.co

**Comment by Moogic** [comment]
Well my game just crashed when doing the same with lava but with a ender tank ...

**Comment by MJRLegends** [comment]
Wheres the crash log, how can i fix a crash when i cant see the crash information
