### ISSUE TITLE
When i Teleport to my base when autocrafting is in progress all Items laying on ground 

### ISSUE THREAD

**Issue by SamuxD** [MJRLegends/Space-Astronomy-Feedback-#568]
### ---Issue Report---

**Have you checked the Known Issues page (if applicable):** Yes 

**Have you checked Closed Issues (if applicable):** Yes 
### Description of Issue

When i teleport back to my Base when autocrafting is in Progress all Items laying on ground that means i have 9 million entities and i dont know how to remove them because i have 0 fps i cant delete them with trash cans/ ist there a command to remove the entities i have tried /kill @e
### Steps to Reproduce Issue
1. Make Autocrafting 16 million Me storages 
2. go far away and teleport back with the waypoint mod

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** V1.5.3
### Additional Information

[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Is it chunk loaded?

**Comment by SamuxD** [comment]
yes it is Chunk loaded

**Comment by SamuxD** [comment]
the problem is too that i used this certus quartz seeds who wont despawn and the other items should despawn but they didnt even when i stand there for 1 night

**Comment by SamuxD** [comment]
i think i solved a part of the problem with removing the dimensional anchors mod

**Comment by SamuxD** [comment]
i think now are all Items who can despawn are despawnd but there are so many of this seeds left

**Comment by SamuxD** [comment]
At the moment i have 0 fps
