### ISSUE TITLE
Flashing item graphics

### ISSUE THREAD

**Issue by drkanbs** [MJRLegends/Space-Astronomy-Feedback-#569]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue
It seems to be random, but there are various graphics that seem to be just flashing on the screen.  Each time I load the game it's something different.  Right now it's bread, tin, leather legs and a a few other things, last time it was a book and some sort of wood.  
![screen shot 2016-10-20 at 11 07 32 pm](https://cloud.githubusercontent.com/assets/22972588/19586385/2f835216-971a-11e6-8cf1-ff44033b0442.png)
It obviously can't show it flashing, but that's bread.
**Version of Mod Pack using:** [1.5.3]

### Additional Information
[I don't think there's a way to reproduce it, just happens at random, is it not enough RAM?  It's just an annoyance to open something or check something and it's just flashing.]

**Comment by MJRLegends** [comment]
Do you have optifine or/and a amd graphics card or are you using a apple mac?

**Comment by drkanbs** [comment]
Yea, I haven't had a regular PC for quite some time.  Long story short I was able to procure my grandfathers MAC.   It uses an Nvidia card, built In I assume, now that I look at it closer, that's pretty low video memory.  only 256 mb.

**Comment by MJRLegends** [comment]
seems to be a mac only issue and i cant fix it as its not just my mod pack that will have the issue

see #461
#507 
#358
