### ISSUE TITLE
Getting oxygen Quest issue

### ISSUE THREAD

**Issue by DaLukas2000** [MJRLegends/Space-Astronomy-Feedback-#572]
### ---Issue Report---

I ckecked the known reports and have not found my Problem.

There are no similar problems.
### Description of Issue

When i started crafting "Getting oxygen"(oxygen mask,gear,light tank) in the machines and equipment tab, first everything was fine but then when i was ready with everything the light tand wasnt done in the quest book, but it was in my inventory! I ckecked it multiple times but it was all the right items now i cant procced with the main "story"!
### Steps to Reproduce Issue
1. Craft Oxygen mask
2. Craft Oxygen gear
3. Craft Light oxygen tank

**Version of Mod Pack using:** V1.5.3
### Additional Information

[Any other information that may be able to help me with the problem]

**Comment by DaLukas2000** [comment]
Sorry for bad english skills.

**Comment by LarryTheLobster318** [comment]
Are you sure you are crafting the right Oxygen gear and equipment? Check in NEI just to make sure. IF that dosent work than you can do /hqm edit and you will get a OP Quest Book to complete the quest. I think you just hold LSHIFT and left click on the quest you want to complete (with OP Quest Book).
If any of those ^ dont work then your out of luck.
