### ISSUE TITLE
Minecraft Graphical Glitch

### ISSUE THREAD

**Issue by LarryTheLobster318** [MJRLegends/Space-Astronomy-Feedback-#573]
### ---Issue Report---

**Have you checked the Known Issues page (if applicable):** Yes

**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue

Minecraft is all pixely and it is sorta ruining my experience. 
### Steps to Reproduce Issue

No found steps.

**Version of Mod Pack using:** 1.5.3
### Additional Information

If the fix is using Optifine please tell me how because I dont know how I would install it on this modpack.

Ps Im using curse.
![2016-10-27_18 42 44](https://cloud.githubusercontent.com/assets/23109481/19788598/4dda69e0-9c77-11e6-9ab5-064d0a33cc36.png)

**Comment by MJRLegends** [comment]
thats something on your side as it doesnt happen to me....
