### ISSUE TITLE
10/29/16 Crash/Fatally Missing Blocks/Texture Bug

### ISSUE THREAD

**Issue by ALittleBambi** [MJRLegends/Space-Astronomy-Feedback-#574]
### ---Issue Report---

**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue

I turned on my server after i updated my GPU and It said "Fatally Missing Blocks." I reverted back to my old GPU Drivers but that didn't work. I had a memory issue but I allocated 3G more memory. That didn't fix it. I re downloaded the server files to make sure i didn't accidentally delete something and then I loaded my world save in and the game loaded I saw my world and it crashed after about 15 seconds. (All the torches were green blobs btw.)

*_Crash log/Log (if applicable):_ http://pastebin.com/embed_js/HYzbmWY9

**Version of Mod Pack using:** [1.5.3]
### Additional Information

I am very new at running a server so please bare with me. Also if this issue has came up before i apologize i tried to look at everything to figure it out

**Comment by ALittleBambi** [comment]
Do you have any advice on how i could fix this?

**Comment by MJRLegends** [comment]
Nope because im not getting the issue...
