### ISSUE TITLE
Vanilla planks not usable.

### ISSUE THREAD

**Issue by BluePower101** [MJRLegends/Space-Astronomy-Feedback-#575]
All non jungle wood planks are not usable in crafting any vanilla items and many other items

1. Take a non jungle wood plank and try and craft a crafting table

I'm am using version 1.5.3

I'm using the fire wolf and unity texture packs with priority to fire-wolf

![2016-11-01_18 52 51](https://cloud.githubusercontent.com/assets/23201214/19910767/6dfe005a-a065-11e6-9506-5ab3f05b09d6.png)
![2016-11-01_18 53 03](https://cloud.githubusercontent.com/assets/23201214/19910771/73096396-a065-11e6-866c-9b8df52e43e8.png)
![2016-11-01_18 53 13](https://cloud.githubusercontent.com/assets/23201214/19910772/7713fbf4-a065-11e6-802c-ff7776b455e0.png)
![2016-11-01_18 53 21](https://cloud.githubusercontent.com/assets/23201214/19910774/7b8b7e00-a065-11e6-94a5-ce1859809efb.png)
![2016-11-01_18 53 29](https://cloud.githubusercontent.com/assets/23201214/19910776/80007fc6-a065-11e6-9629-0e595e3b7a4b.png)

**Comment by MJRLegends** [comment]
Works all fine for me 

![](https://i.gyazo.com/e8f3be056b7fc8340289e16c022e716f.png)
![](https://i.gyazo.com/3fcac338a8abe6fc07ef674698cd1f6e.png)
![](https://i.gyazo.com/502dc8fbc1765607651f93f3543d61ba.png)
![](https://i.gyazo.com/51fd3017063599e76cf48dbf02ec6c65.png)
![](https://i.gyazo.com/9dff92dab3e71fd86179aa9dd039844d.png)
![](https://i.gyazo.com/5af7b33a2f42c1b9b708bcbfd72bd694.png)

**Comment by MJRLegends** [comment]
Will reopen if any more details on this issue comes to light...

**Comment by Meisterfuchs** [comment]
Confirmed to happen occasionally, but not reproducable for me. Restarting the game fixes it though.
