### ISSUE TITLE
Uranium Tools Quest Not Completing

### ISSUE THREAD

**Issue by ToxicOverload** [MJRLegends/Space-Astronomy-Feedback-#576]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** Yes

**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue
I am attempting to complete the uranium tools quest. I crafted the tools, but it did not show up as crafted in the quest book. I tried charging the tools in the galacticraft energy storage module, but that didn't fix it.

### Steps to Reproduce Issue
1. Find "Crafting Uranium Tools" quest in tools and weapons section.
2. Craft the tools with uranium gems and uranium sticks.
3. Open quest book. The quest will not be completed.

**Crash log/Log (if applicable):** N/A

**Version of Mod Pack using:** 1.5.3

### Additional Information
I tried to complete the quest immediately after opening the world, but I tried it again later, so that probobly isn't the problem.

**Comment by MJRLegends** [comment]
What Uranium Tools are you making, like what mod are they from? More Planets?

**Comment by ToxicOverload** [comment]
The tools are from More Planets, and I made the sword, pickaxe, axe, hoe, and shovel. The item looks the same as the quest's icon, so I know it's the right one.
