### ISSUE TITLE
Carpenters Garage Door on Mob Grinder Bug Causes Crash on Loading into Chunk 

### ISSUE THREAD

**Issue by Spydrouge** [MJRLegends/Space-Astronomy-Feedback-#578]
Husband placed a Carpenters Garage Door on a Mob Grinder. This shouldn't have done anything suspicious; it works perfectly fine elsewhere. But, here's the catch:

Husband also managed to completely *lose* a vanilla door in that exact same area, in those same blocks. Yes, lost a door. He ended up cardboard boxing it on accident, tried to put it back, and it never appeared. He never found it and assumed it destroyed. Maybe it wasn't destroyed- maybe it was the culprit. 

http://pastebin.com/JxWYZG9d

**Comment by Spydrouge** [comment]
We are trying to replicate the issue and are thinking the fact that husband was building on my claim with a carpenters block- and that carpenter's blocks are picky about knowing who placed them and therefore who can color them- and that his carpenter block is trying to displace my claim's 'invisible vanilla door' might be causing the problem.

**Comment by MJRLegends** [comment]
Yeah i will need to MCEdit out the door, as its crashing me to, i cant do it atm as the server is busy and it means restarting the server....

**Comment by Spydrouge** [comment]
We're not in a rush anymore now that the panic of 'oh shit' has subsided; we'll just head to bed. Whenever's convenient for you is convenient for us. Thank you for helping, this is really cool!

**Comment by MJRLegends** [comment]
Ok theres nothing to worry about with it, it will be done within the next 12 hours

**Comment by Spydrouge** [comment]
You're worthy of the 'legends' in your name. Thanks again!

**Comment by MJRLegends** [comment]
Fixed :D
