### ISSUE TITLE
Game crashed while looking in my chest 

### ISSUE THREAD

**Issue by YungMineGod** [MJRLegends/Space-Astronomy-Feedback-#579]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes or No] yes

**Have you checked Closed Issues (if applicable):** [Yes or No] yes
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
http://pastebin.com/G6yH0uWV
**Version of Mod Pack using:** [VERSION] 1.5.4

### Additional Information
[Any other information that may be able to help me with the problem] I was looking at the chest and its just crashed . I have no idea why

**Comment by MJRLegends** [comment]
I need more information...

**Comment by MJRLegends** [comment]
Will reopen if a reply is made :D
