### ISSUE TITLE
Wont update from 1.2.6 to 1.2.7

### ISSUE THREAD

**Issue by Islandsteve** [MJRLegends/Space-Astronomy-Feedback-#58]
Was able to download the server version 1.2.7 and run that on my server. its works.

cannot update my client version . Its asks me(backup) and all that but then dose not update and I am stuck on 1.2.6

**Comment by MJRLegends** [comment]
Yeah sorry this is a problem, im trying to get it sorted. The FTB Team updated it and for some reason its not working.

**Comment by MJRLegends** [comment]
#Blame FTBTeam :D

**Comment by Islandsteve** [comment]
so how long till its uploaded? Can you not just put 1.2.7 on curse then?
Wanted to start streaming this pack but I dont want to start on 2.6 if its going to update soonish.

**Comment by MJRLegends** [comment]
Im awaiting on a reply from the ftb team and i cant because the curse launcher is updated via the ftb team from the ftb launcher.

Sorry there is nothing i can do but message them and get them to sort this fast.

**Comment by Islandsteve** [comment]
ok thanks.
i'll just downgrade my server 1.2.6
Been waiting for a pack like this for along time.
p.s can you add veinminer in? lol make crap so much better :)

**Comment by MJRLegends** [comment]
No problem, and yeah im really sorry about the v1.2.7 not being downloadable, its not my fault haha. and yeah i will have a think about adding it.

**Comment by Islandsteve** [comment]
cool these days its just to grindy without Veinminer :)
No 1 got time for that

**Comment by MJRLegends** [comment]
This has now been fixed!!
