### ISSUE TITLE
i can´t load my old worlds on newer versions 

### ISSUE THREAD

**Issue by axelpaxel1234** [MJRLegends/Space-Astronomy-Feedback-#582]
i can´t load my old worlds on newer versions 

I have created a world in a previous beta version and can´t play it on the new release

I can start the new release of space-Astronomy and it works perfectly. And then i open the single-player list
and then i select an old world from an old beta. It loads but then crashes.

**Comment by MJRLegends** [comment]
I cant fix something i dont know so please post some logs of the errors your getting

**Comment by Meduiakar** [comment]
I have the same problem. 
[crash-2016-11-10_19.30.17-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/584109/crash-2016-11-10_19.30.17-server.txt)

**Comment by MJRLegends** [comment]
@Meduiakar your issue is listed on the known issues and theres a solution there so theres no need to post a issue

**Comment by axelpaxel1234** [comment]
how do i fix it then?

**Comment by MJRLegends** [comment]
@axelpaxel1234 you havent even given the correct information so how can i help you????

And @Meduiakar your issue is on the known issues page so please look there...
