### ISSUE TITLE
Lags in new version

### ISSUE THREAD

**Issue by AnnoyingThomas** [MJRLegends/Space-Astronomy-Feedback-#583]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes or No] yes

**Have you checked Closed Issues (if applicable):** [Yes or No] yes
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** v.1.5.4

### Additional Information
[Any other information that may be able to help me with the problem] With this version I have some lags, In version 1.5.2 the weren't.

**Comment by MJRLegends** [comment]
I cant do anything with the words " it lags"
