### ISSUE TITLE
Crash when trying to run a server

### ISSUE THREAD

**Issue by SenpaiDerp** [MJRLegends/Space-Astronomy-Feedback-#584]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue
[Upon downloading and trying to run a server, it crashes giving a couple errors that all mention ae2 being incorrect, along with EnderIO]

### Steps to Reproduce Issue
1. [Download a fresh server off of the FTB launcher]
2. [Run off of your computer once to generate log files]
3. [Stop server]
4. [Add an ip to the server properties and restart the server]

**Crash log/Log (if applicable):** [Crash log attached]
[crash-2016-11-10_08.53.47-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/583777/crash-2016-11-10_08.53.47-server.txt)

If the above doesn't work, here is (I think) the pastebin
http://pastebin.com/WRcgmsc3
**Version of Mod Pack using:** [1.5.4]

### Additional Information
[Single player works perfectly fine, so my guess is that for some reason or another, the start bin in the server download didn't specify a file that I was supposed to use.]

**Comment by MJRLegends** [comment]
Has nothing to do with ae2 and EnderIO... the error is at the top of the log not the bottom

**Comment by MJRLegends** [comment]
Your issue is the ip address you have put in the server properties file
