### ISSUE TITLE
[Pack 1.5.4]Decocraft update crash on Intel HD

### ISSUE THREAD

**Issue by victorzzt** [MJRLegends/Space-Astronomy-Feedback-#585]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [Yes]

### Description of Issue
Modpack ver : 1.5.4 (Updated from 1.5.3) also tried clean re-install.
Cannot get into title screen after update.

### Steps to Reproduce Issue

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
http://pastebin.com/3DwKWxJv

**Version of Mod Pack using:** [VERSION]
1.5.4

### Additional Information
[Any other information that may be able to help me with the problem]

It seems that the decocraft update crashed the pack.
"UCE props{2.3.4} [Decocraft] (Decocraft-2.3.4_1.7.10.jar)"

Using Intel(R) HD Graphics 4600 GL

**Comment by victorzzt** [comment]
Sorry to bother , I was able to load the client when I replace the in jar asset from 2.3.2
(Decocraft-2.3.4_1.7.10.jar\assets\props\models\Decopack\) the load will hiccup several times, but I was able to load the pack.

So it was a decocraft problem, not a mod-pack problem.

Thanks.

**Comment by MJRLegends** [comment]
Seems its a known issue https://minecraft.curseforge.com/projects/decocraft2/issues/1581

**Comment by MJRLegends** [comment]
Seems they fixed it here https://minecraft.curseforge.com/projects/decocraft2/files/2342380

**Comment by MJRLegends** [comment]
I will **try** to get the version in v1.5.5 update that is out soon
