### ISSUE TITLE
No sight on Mercury.

### ISSUE THREAD

**Issue by weirdsoul89** [MJRLegends/Space-Astronomy-Feedback-#586]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** 
Yes, saw nothing at all about Mercury

**Have you checked Closed Issues (if applicable):** 
Yes, same as above.

### Description of Issue
Upon flying to Mercury, the entire planet is completely black. I can see the sun and if I fly up rather high I can see the moons as well, but can't make out anything on Mercury itself. I attempted a new texture pack, tried falling back onto the planet from a space station, and restarting in various ways but to no avail. I can still place blocks just fine, but can't see enough of what I'm doing for it to make any difference. I CAN see Mercury while flying away in a rocket as well as from the space station itself. Eventually I killed myself on the planet and upon reviving could see. As a side note, I had night vision from the genetics mod.

### Steps to Reproduce Issue
1. Go to Mercury with night vision from genetics
2.  Don't see a damn thing

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** Newest version... I can't recall the number right now.

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Do you have night vision

**Comment by weirdsoul89** [comment]
I did at the time from advanced genetics. I wondered if that might be the problem and killed myself and it seemed to clear up. I just couldn't find the issue anywhere else. Killing yourself on a new planet is a bit of a pain in the ass, so I saved it as a last resort.

**Comment by MJRLegends** [comment]
Yeah night vision and some planets dont mix and its a known bug already
