### ISSUE TITLE
Teleported to the Moon, game crashes

### ISSUE THREAD

**Issue by NyagiKun** [MJRLegends/Space-Astronomy-Feedback-#588]
[crash-2016-11-11_00.28.56-client.txt.zip](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/585069/crash-2016-11-11_00.28.56-client.txt.zip)

**Comment by NyagiKun** [comment]
and now i crashed simply from logging into my world
[crash-2016-11-11_00.41.58-client copy.txt.zip](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/585077/crash-2016-11-11_00.41.58-client.copy.txt.zip)

**Comment by MJRLegends** [comment]
One please fill out that template that is give to you when you click new issue and two use pastebin.com for your logs as i dont want to be downloading zip files and extracting them each time i want to look at your logs as there's no reason for them to be in zip files also they are the same log..... will reope when these things has besn met
