### ISSUE TITLE
Broken quest in version 1.2.7

### ISSUE THREAD

**Issue by osh307** [MJRLegends/Space-Astronomy-Feedback-#59]
First off just want to say, loving this pack!

Ok, now to the problem. I updated to version 1.2.7 this morning and i was working on the 'Automatic Miner' quest in 'Machines & Equipment'.

I made the quarry and the book detected it. When i went to make the next item for the quest, i moused over it and it shows as 'Unknown: 0/3":
![sa-quest1](https://cloud.githubusercontent.com/assets/14968836/10270705/bca2b79c-6b45-11e5-9dde-79d1c11f2971.jpg)

From memory, it was 3x landmarks, so i made them but the book didn't detect them (to show i have just crafted them, refer to below image)
![sa-quest2](https://cloud.githubusercontent.com/assets/14968836/10270711/f9e1e380-6b45-11e5-840e-238c40512114.jpg)

Like i said, don't know if it's a broken quest or if i did something wrong, just though id better post this incase other ppl have that same issue.

**Comment by MJRLegends** [comment]
Yeah thanks i have already found this im going to try get another update out in the next few days, Its a HQM Bug, but i can fix it. For the moment just use "/HQM Edit" to complete it
