### ISSUE TITLE
Many xp in drum were gone!

### ISSUE THREAD

**Issue by jeremywu0521** [MJRLegends/Space-Astronomy-Feedback-#592]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):no

**Have you checked Closed Issues (if applicable):no
### Description of Issue
If taking off xp to have xp shower(closed)xp drum , The xp shower(closed) will open and take out same xp from before taked off them,and had the xp drum will clean and base had xp will gone.

### Steps to Reproduce Issue
No

### Additional Information
No

**Comment by MJRLegends** [comment]
You cant turn it off its not a bug its just not a feature to turn it on and off
