### ISSUE TITLE
Power Fist

### ISSUE THREAD

**Issue by Huschiro** [MJRLegends/Space-Astronomy-Feedback-#593]
Mod: Modular Power Suit

I Cant Switch to Axe, Pickaxe or Shovel
Other Install on the Power Fist works.
shift + Scroll Wheel works on Weapons, Crafting... but not on the 3 Tools

It is the Same as the Issues 174 on Dec 29 2015.

https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/174

**Comment by Huschiro** [comment]
Found a Work Around.

Cant switch with sneak + Wheel but with the table + key binding.

Activate the Function on the Table and look at the HUD then it works. VineMiner don't work on Power Fist? (Config?)

**Comment by MJRLegends** [comment]
I dont want the power fist to work with vein miner
