### ISSUE TITLE
Gameplay on LAN world is really slow & laggy, game crashing.

### ISSUE THREAD

**Issue by alexc90** [MJRLegends/Space-Astronomy-Feedback-#596]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue

When logging in to a LAN world hosted on my friend's PC, gameplay is extremely slow and laggy (often two hours behind using in-game clock) and am unable to open inventories and interact with the world. Game crashing also.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [http://pastebin.com/Qk80Q4Xxf.]

**Version of Mod Pack using:** [1.5.5]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by alexc90** [comment]
Hi there,

My apologies if my post contravened any rules or was lacking in detail. I am just trying to play the pack and am desperate to try and make it work. What should I have done/included to make it acceptable?

Regards

**Comment by MJRLegends** [comment]
One your log link doesnt work and two you havent given me any information what so ever for me to work out your problem, all the information i have atm is that it doesnt work.....

**Comment by MJRLegends** [comment]
Please fill out the correct information and i will reopen it when i feel i have enough information to be able to help you in any way i can
