### ISSUE TITLE
Tools and weapons are broken too quickly

### ISSUE THREAD

**Issue by Orlefanto** [MJRLegends/Space-Astronomy-Feedback-#598]
**Version of Mod Pack using:** [1.5.5]

Hello.
Tools and weapons are broken too quickly. For example any pickaxes are broken after 2 ores.
sry for bad english =(

**Comment by discotyme** [comment]
you cant use vanilla tools and weapons those are ONLY fro crafting but if you do want to mine ores you need to make a paxel

**Comment by Orlefanto** [comment]
Can I disable it and use standart tools? =)
