### ISSUE TITLE
Items breake after 2 hits

### ISSUE THREAD

**Issue by cobramike** [MJRLegends/Space-Astronomy-Feedback-#6]
When we use your server files and client files. All my users have the problem when using a wooden sword or a diamond pickaxe it breaks after 2 hits.

Test It also in single player. Same problem there

Please fix this. This is a game breaking bug

**Comment by MJRLegends** [comment]
*Disabled Vanilla tools effectiveness

See changelog http://pastebin.com/Zmx3n72i

You have to use tinkers tools. And the tools are not disabled due to there used in some recipes.

**Comment by MJRLegends** [comment]
Thats why the quest book only gets you to make tinkers tools D: hope this helps
