### ISSUE TITLE
Bug/Issue

### ISSUE THREAD

**Issue by OZJAMD321** [MJRLegends/Space-Astronomy-Feedback-#60]
First of all, I'd like to say thank you for putting together a fantastic pack.

I updated to the latest version which fixed the "Machines" bug (many thanks) but I am trying to collect "Raw Koentus Meteoric Iron" (the blue one) to finish the Quest book and have been scouting for more hours than I care to mention but to no avail.  It WAS working a week ago or so (as I have 2 already) but definitely isn't working any more now - only the usual red/brown meteors are falling... other people are experiencing the same on the server we are using.  I mentioned it to the Admin and they are sure it is not their side.

Are you able to help?

Kind Regards

OZ

**Comment by MJRLegends** [comment]
Nothing has changed with the more planet mod so this must be just bad luck of them not dropping. If not report it to the more planet mod developer :D
