### ISSUE TITLE
Space Astronomy 1.5.5 crashes when loading single player world

### ISSUE THREAD

**Issue by NaemNaem** [MJRLegends/Space-Astronomy-Feedback-#601]
Hi,

This is the second time that this is happening to me, I don't wanna start all over again for a third time...I have no clue what's going on in the log, please try to keep it simple for me :)

Here's the log link: http://paste.feed-the-beast.com/view/470fb62b

**Comment by MJRLegends** [comment]
Check the known issues page as its there no need to repost it
