### ISSUE TITLE
Night Vision 

### ISSUE THREAD

**Issue by Queen-Cassie** [MJRLegends/Space-Astronomy-Feedback-#607]
### ---Issue Report---
**Have you checked the Known Issues page: Yes

**Have you checked Closed Issues: Yes

### Description of Issue
Night Vision fails to work properly on the following More Planets planets: Mercury, Diona, and Sirius B, rendering all blocks and the character model completely black. This bug was encountered in SSP.

Addendum: This is also occurs on the Overworld space station.

I first noticed this issue when I first visited Diona. Everything was completely dark and invisible, including my character model. Attached images shows example with and without night vision activated, on Sirius B. 

![2016-11-29_10 48 49](https://cloud.githubusercontent.com/assets/24255393/20724714/2aedf61a-b624-11e6-9115-5f47f285ff45.png)
![2016-11-29_10 49 01](https://cloud.githubusercontent.com/assets/24255393/20724715/2aef34d0-b624-11e6-89a8-d8c45411eb5b.png)

At the time I first encountered the issue, I was using the Night Vision gene from Advanced Genetics to grant me permanent night vision. On a whim I decided to remove that to see if it was the issue and in fact it was. I have since attempted using night vision through both the Ender IO Dark Helm and the Modular Powersuits Helmet, both of which produce the same results. I have tried searching throughout the More Planets threads but have found no one else with this issue using just the mod, therefore I believe this is a result of some kind of mod interaction. I continued to encounter this on other worlds, Mercury and Sirius B. 

### Steps to Reproduce Issue
1. Obtain some form of night vision.
2. Use this night vision on Diona or Mercury or Sirius B.

**Crash log/Log (if applicable): N/A

**Version of Mod Pack using:** 1.5.5, out of the FTB Modpack launcher.

### Additional Information
I believe this may simply be a lighting calculation issue, something to do with how Night Vision changes the lighting. Normal lighting works fine; without night vision you can see everything normally, and torches light things up just as normal. It only goes completely black when you have night vision on, and it only happens on those planets; I've gone back and forth through various others where night vision still functioned as normal.

**Comment by MJRLegends** [comment]
#586
