### ISSUE TITLE
Hub Spam

### ISSUE THREAD

**Issue by ajq2014** [MJRLegends/Space-Astronomy-Feedback-#608]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yep

### Description of Issue

Hub is currently just spamming two messages - I receive each like every 4 seconds. The one about mod rejections=wrong version and the link to bring you here.

### Steps to Reproduce Issue
1. Join the hub.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
I know i wanted it that way
