### ISSUE TITLE
Need help for an account change 

### ISSUE THREAD

**Issue by Snigzou** [MJRLegends/Space-Astronomy-Feedback-#609]
### ---Issue Report---
** I really didn't know where to post this, I assumed it could go here ? I needed some help.

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING): yuyuyu
### Description of Issue
Fairly simple. Back before, my account was "aridian2", but I've got hacked or stuff, and I can't access it anymore... One friend that used to play on the server with me gave me his account, "hunter83", but he's not trusted in our base since he quit the server a long time before we did. I'm back to play more, but can't access stuff ! 

### Steps to Reproduce Issue
1. Get your account hacked
2. Borrow your friend's account
3. Open ticket

**Crash log/Log (if applicable):** None.

**Version of Mod Pack using:** Newest.

### Additional Information
I'm really confused if that didn't belong here, just contact me through Steam : http://steamcommunity.com/profiles/76561198058984887/
or Discord : Snigzou#3828
or Skype : snigz83

-Regards, Snigz.

**Comment by Snigzou** [comment]
how shall we discuss of this then ?

**Comment by MJRLegends** [comment]
@Snigzou are you able to come on the server, i've only managed to just get online
