### ISSUE TITLE
CTD Bucket of blood problem

### ISSUE THREAD

**Issue by squillis** [MJRLegends/Space-Astronomy-Feedback-#61]
When I right click in the air with a bucket of blood is crashed me to desktop, I logged back on and tried it a few times and it keep happening.

Here's pastebin of crash report. (I think? lol never used pastebin before. x-x)

http://pastebin.com/JnRpDK3L

**Comment by MJRLegends** [comment]
I will take a look but your best bet would be to report it to the mod developer.
