### ISSUE TITLE
My world is glitching out pretty bad.

### ISSUE THREAD

**Issue by ratchet457l** [MJRLegends/Space-Astronomy-Feedback-#610]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]Yes
### Description of Issue
[Description of the issue]
This happened as soon as I loaded up the game. There would be certain areas of the map that would glitch to other areas. I can get rid of them by updating the area, though.
ex: 1. http://puu.sh/sA29M/f30ab94178.png
     2. http://puu.sh/sA2e5/9a965eb312.png
This started to happen after I think it was after the second Bloodmoon where my world started to glitch really badly. there would be entire plans of just glitch, whether it was a black plane, or static, or some random colour, it would just be there. These ones I couldn't update to get rid of, It depended on where my camera positioning was. If I looked at just the right angle it would be there but I move a little and it would go away.
Ex: 1. http://puu.sh/sA2pF/41bfbafb0c.png
     2. http://puu.sh/sA2rw/503b26051d.png
     3. http://puu.sh/sA2un/23e7a0f467.png
     4. http://puu.sh/sA2xW/6597d9d5ab.png
### Steps to Reproduce Issue
1. [First step] N/A

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]
1.5.5.
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Do you have optifine installed?

**Comment by MJRLegends** [comment]
Or are you using a AMD Graphics card or a Apple Mac?

**Comment by ratchet457l** [comment]
I do have a AMD graphics card

**Comment by ratchet457l** [comment]
And if it doesn't come with the pack then i didn't install it into the client.

**Comment by MJRLegends** [comment]
Try removing fast craft

**Comment by ratchet457l** [comment]
ive removed it and i cant seem to find any, but my game has just tanked. 1-4 frames a second.

**Comment by MJRLegends** [comment]
Not sure try updating your graphics card drivers..

**Comment by ratchet457l** [comment]
Sorry, I went on a trip so I couldn't respond. I think the reason its
really slow now is because of my computer not having the greatest specs and
FastCraft really helped with, but I can't seem to find any of that stuff
anymore. So thanks. Also my drivers are up to date.

**Comment by MJRLegends** [comment]
Not sure sorry....
