### ISSUE TITLE
crash on login (space 2)

### ISSUE THREAD

**Issue by theguy404** [MJRLegends/Space-Astronomy-Feedback-#612]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
 yes

### Description of Issue
crash whenever close to my base, can't get close (nor login now due to this)

### Steps to Reproduce Issue
1. not sure the main cause but from the crash log i would say its a conduit in the new building so anyone approaching that would be sure to join us in limbo

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
http://pastebin.com/k3UXTUEp
**Version of Mod Pack using:** [VERSION]
1.5.5

### Additional Information
[Any other information that may be able to help me with the problem]
I think i can remove the crash by getting to my space station and shutting down the power to the area but since i cannot login its hard to say

**Comment by MJRLegends** [comment]
Where are the cables? as i will need to remove them from your base with mcedit

also im unable to do anything now sorry but i can tomorrow

**Comment by theguy404** [comment]
there is a building made of conduit fascade (stone brick and dark oak logs) if u removed all the cables from that building that would remove all our changes that led to the crashing issue

**Comment by MJRLegends** [comment]
@theguy404 it might be the only option to remove them, does it actually crash your client if so can you post the crash log that is located in the crash logs folder as it might contain more information

**Comment by theguy404** [comment]
it does crash my client, and dreadwinknight's and the log is in the main post

**Comment by theguy404** [comment]
oh sorry, wrong log
http://pastebin.com/mGtK9Uxp

**Comment by MJRLegends** [comment]
so you have a base out of conduit and conduit fascade?

**Comment by theguy404** [comment]
the whole building is made of fascade and we JUST started to rebuild our ME system in there when this occured. the building itself was a product of days of work so i doubt the fascade is the issue but the cables and ME controllers that its connected to are brand new when the crash started.

**Comment by MJRLegends** [comment]
ok i will look at it in the morning, its nothing i cant fix dont worry 👍

**Comment by theguy404** [comment]
cool, sorry for all the problems but just a heads up, the space station glitch is back too (different wall this time ; ;)

**Comment by MJRLegends** [comment]
@theguy404 yeah i saw your ticket....

**Comment by MJRLegends** [comment]
@theguy404 u around?

**Comment by theguy404** [comment]
yeah, i am just going live on stream lol

**Comment by MJRLegends** [comment]
@theguy404 right im currently fixing your issue, it seems to be something in the middle of the tower, whats on the floors above the 2rd?

**Comment by theguy404** [comment]
nothing, i am pretty sure its only building past that floor

**Comment by MJRLegends** [comment]
seems to be the 4th floor

**Comment by theguy404** [comment]
O_o whaaaa?

**Comment by MJRLegends** [comment]
is there any cables running up the side? or on that floor

**Comment by theguy404** [comment]
4th floor is walls and nothing else

**Comment by theguy404** [comment]
if u want to wipe out the 4th floor itself, i can rebuild (just weird)

**Comment by MJRLegends** [comment]
@theguy404 ok i will give it a test now

**Comment by theguy404** [comment]
funny thing is this building was supposed to lower our footprint on the server by putting all our chunk loads in 1 chunk, lol

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/914bbd0467c9b2902861e8fea5afabd0.png)

Its at -192 64 -92 (x,y,z) if you have problems getting there but your teleports and rocket teleporting should work at normal and will be no different

**Comment by MJRLegends** [comment]
@theguy404
![](https://i.gyazo.com/914bbd0467c9b2902861e8fea5afabd0.png)

Its at -192 64 -92 (x,y,z) if you have problems getting there let me know but your teleports and rocket teleporting should work at normal and will be no different

**Comment by theguy404** [comment]
thanks for looking at it but i lost my teir 7 rocket because the rocket teleport did not work, went to the old location. and the teleportor would not work

**Comment by MJRLegends** [comment]
Ok i will fix later

**Comment by theguy404** [comment]
would using gckeeploaded work on a planet like fronos? i ask because for some reason the chunk loaders do not seem to work after restarts.

**Comment by MJRLegends** [comment]
No don't use that command on planets
