### ISSUE TITLE
Complete game crash

### ISSUE THREAD

**Issue by Offkey2** [MJRLegends/Space-Astronomy-Feedback-#614]
Im not aprogrammer can you fix this issue
http://paste.feed-the-beast.com/view/433820ef
there is the full monty what can you do to fix it. Or why not update the mod to fix the issues.

**Comment by MJRLegends** [comment]
Already known issue please check #1 before posting :D
![](https://i.gyazo.com/84302525973eec1cbbbdeffec7de5315.png)
