### ISSUE TITLE
SecureOS Crashes with lua error

### ISSUE THREAD

**Issue by tndmadman** [MJRLegends/Space-Astronomy-Feedback-#617]
### ---Issue Report---
**Have you checked the Known Issues page: yes

**Have you checked Closed Issues: yes
### Description of Issue
SecureOS crashes with lua error

### Steps to Reproduce Issue
The settup for the server is as listed:
T3 server board
T3 CPU
4x T3.5 memory
T3 HDD
EEPROM Lua bios
T3 Graphics Card

Disk used: SecureOS 
1.Put it together
2. Boot it to get the error
**Crash log/Log (if applicable):**
http://imgur.com/a/jKOIt
**Version of Mod Pack using:** [VERSION]
1.5.5
### Additional Information
Does not matter what config you have the system in, more or less memory different tiers of cpu or gpu ect will do it no mater what. 
SecureOS Is a part of the mode "Open Security"

**Comment by MJRLegends** [comment]
Seems it works in the current dev version (so will be fixed in the next mod pack update) and thats due to updates to OC and OS so it must of got sorted or the problem was somehow fixed
