### ISSUE TITLE
big reactor crash

### ISSUE THREAD

**Issue by gamertagpls** [MJRLegends/Space-Astronomy-Feedback-#619]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes
### Description of Issue
 consistently crashes when i exit out of the controller on a 3x3x3 big reactor
[Description of the issue]

### Steps to Reproduce Issue
1. [First step] NA
2. [Second step] 
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
[crash-2016-12-10_05.35.06-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/643717/crash-2016-12-10_05.35.06-server.txt)

**Version of Mod Pack using:** [VERSION]1.5.5

### Additional Information
[Any other information that may be able to help me with the problem]
sfsef

**Comment by MJRLegends** [comment]
Please fill out the template correctly

**Comment by gamertagpls** [comment]
fixed
