### ISSUE TITLE
CTD when breaking vegetation

### ISSUE THREAD

**Issue by klomer** [MJRLegends/Space-Astronomy-Feedback-#62]
Since the 1.2.7 update, I've been getting CTDs when breaking vegetation.  3x.  Seen it both for netherroot and grass.  Restarting, I can break the block no problem.

**Comment by MJRLegends** [comment]
I need to know more detail on what vegetation

**Comment by klomer** [comment]
At this point, I've seen it one time for breaking nether root and 2x (in a row) for breaking grass on top of dirt.  Leaving the clump, doing other things, then coming back fixed the grass.

I can try and get more info.  Is there a crash log or something?

**Comment by MJRLegends** [comment]
I would need to know what crops/vegetation are crashing, then i can track it down and yeah a crash log would help
