### ISSUE TITLE
After last restart I cant load back in the game

### ISSUE THREAD

**Issue by cinimodaz** [MJRLegends/Space-Astronomy-Feedback-#623]
After the last restart, I tried to join the server and it just closes my client completely. I tried restarting still nothing. I went into single player and it is fine.  Here are the 3 crash reports. Just to let you know I was on Diona in a dungeon when the server restarted. 

[crash-2016-12-11_04.34.43-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/644357/crash-2016-12-11_04.34.43-client.txt)
[crash-2016-12-11_04.41.19-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/644356/crash-2016-12-11_04.41.19-client.txt)
[crash-2016-12-11_04.47.12-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/644358/crash-2016-12-11_04.47.12-client.txt)

### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Steps to Reproduce Issue
1. [Join Space 1 from hub]
2. [Re open game and try again]

**Comment by cinimodaz** [comment]
It let me in when i used the direct connect link. However I still can't connect through the hub. Which sucks cause my waypoints are through the hub.

**Comment by MJRLegends** [comment]
Please just use the direct ips as the are more stable

**Comment by cinimodaz** [comment]
That is great but I was hoping you could figure it out enough for me to log on long enough to at least be able to write down my waypoints so I can put them on the direct IP and also the direct IP makes me have climb yet on the hub IP I don't have climb. I hate having climb.

**Comment by MJRLegends** [comment]
You just need to logout in a vanilla dimension and then the hub will work

**Comment by cinimodaz** [comment]
Ok will do. Thanks MJR

**Comment by MJRLegends** [comment]
No problem
