### ISSUE TITLE
After Server shutdown, impossible to restart.

### ISSUE THREAD

**Issue by Artimano** [MJRLegends/Space-Astronomy-Feedback-#624]
Hello :)
Today I got some sad problems running my Server.
I shut down the Server, as always, by typing "stop" into the console and wait till the Server shut down. Then I wanna restart my Server with the "SeverStart" file. But now it will not work any more. I don't change any file. The Server was running for weeks with no problems. I don't have any auto restart script so I have manuelly restart the server every day.
What happend now? Any solution? Idea?

[crash-2016-12-11_11.18.52-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/644380/crash-2016-12-11_11.18.52-server.txt)
[fml-server-latest.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/644382/fml-server-latest.txt)
[latest.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/644383/latest.txt)

**Comment by Artimano** [comment]
If u won't trust my files. Uploaded it to pastebin:
http://pastebin.com/9T4iqq0M
http://pastebin.com/cF5kZt5F

**Comment by MJRLegends** [comment]
You have added mods so thats why it doesn't work
