### ISSUE TITLE
I have been banned For "Griefing."

### ISSUE THREAD

**Issue by Deathviper1000** [MJRLegends/Space-Astronomy-Feedback-#627]
I was banned for Griefing Which I did not do. I was wondering if there was anyway I could get unbanned. Please contact me @j.xbox99@hotmail.com

**Comment by MJRLegends** [comment]
I have proof you have griefed so nope i dont like griefers

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/59dfce27fec9e6138eee7fc5ba42b1f6.png)

**Comment by Deathviper1000** [comment]
It was not protected.


________________________________

**Comment by MJRLegends** [comment]
Thats griefing and is part of the rules
