### ISSUE TITLE
My brother got me banned.

### ISSUE THREAD

**Issue by Deathviper1000** [MJRLegends/Space-Astronomy-Feedback-#628]
I was gone for the week on a trip for my swim team and I told my brother he could use my account @Deathviper1000.I will never let my brother use my account again so don't worry about him. I will do my best to undo what he did (If you allow me back on the server.) Please Email me Orangecyder95@hotmail.com.

**Comment by MJRLegends** [comment]
Your not being unbanned and please dont make loads of tickets

**Comment by Deathviper1000** [comment]
What do you mean my brother was the one that griefed

**Comment by MJRLegends** [comment]
There is 0% proof of it wasnt you
