### ISSUE TITLE
Game gets stuck when launching

### ISSUE THREAD

**Issue by xJon510** [MJRLegends/Space-Astronomy-Feedback-#629]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
When i try to launch Space Astronomy I begin to load in seeing the Mojang screen, but get stuck at 2/7 with 70/170 left to go. But the console isn't changing or doing anything after this. Then my computer says that minecraft is unresponsive and self closes it.
### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** http://pasted.co/61725219 Sorry but my file was too big for paste bin
**Version of Mod Pack using:** 1.5.5

### Additional Information
 At first i couldn't even launch Space so i went into the config folder and changed something from enabled to false. Then i was able to launch but only got this far. This mod pack looks really cool, so if someone could help i would love to get into this space modpack. Thanks

**Comment by MJRLegends** [comment]
[20:24:04] [Client thread/WARN] [OpenComputers/ExtraUtilities]: Something went wrong!
**java.lang.OutOfMemoryError: GC overhead limit exceeded**

add more ram

**Comment by MJRLegends** [comment]
You cant run a mod pack on 1GB

**Comment by xJon510** [comment]
Thank you so much, yeah, before i could run argarian skies 2 on 1 gb but i changed it to 4 and was able to load in thank you so so much
