### ISSUE TITLE
Big reactor reactor controller crash

### ISSUE THREAD

**Issue by gamertagpls** [MJRLegends/Space-Astronomy-Feedback-#630]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] yes
### Description of Issue
game crashes when entering a 3x3x3 and 7x7x7 big reactor reactor controller

### Steps to Reproduce Issue
1. [First step] N/A
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
http://pastebin.com/3GNaEHGs
**Version of Mod Pack using:** [VERSION] 1.5.5

### Additional Information
[Any other information that may be able to help me with the problem]
launching minecraft through curse

**Comment by MJRLegends** [comment]
Are you right clicking it with anything in your hand?

**Comment by gamertagpls** [comment]
it crashes with or without, and it doesn't happen every time but it happens alot

**Comment by MJRLegends** [comment]
Yeah im not sure what is causing it sorry i have seen crashes when right clicking it with certains tools before

**Comment by gamertagpls** [comment]
ok ill try to get some more info

**Comment by gamertagpls** [comment]
i looked into it a little more and it looks like it does it a lot with a tinkers pick and hammer. might only be with nether ore tools but idk

**Comment by MJRLegends** [comment]
Yeah in that case the only solution is not to right click it with them tools :D
