### ISSUE TITLE
I can't to open the worlds

### ISSUE THREAD

**Issue by Ghibby2001** [MJRLegends/Space-Astronomy-Feedback-#632]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**Yes
### Description of Issue
When I try to open a world the game return at the home page

### Steps to Reproduce Issue
1. [First step] N/A
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** all version

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Still not enough information? Crash logs? Images? More detailed description?

**Comment by Ghibby2001** [comment]
I haven't images

**Comment by MJRLegends** [comment]
Ok not a problem but the others you do

**Comment by Ghibby2001** [comment]
I don't understand

**Comment by Ghibby2001** [comment]
The game doesn't open any worlds

**Comment by Ghibby2001** [comment]
excuse me i'm italian xD

**Comment by Ghibby2001** [comment]
Is there a solution?

**Comment by MJRLegends** [comment]
I dont know the cause or the fully issue without the crash logs

**Comment by Ghibby2001** [comment]
In the folder of the world there is a file locked

**Comment by Ghibby2001** [comment]
Do you speak italian?

**Comment by Ghibby2001** [comment]
Lock*

**Comment by Ghibby2001** [comment]
[10:33:21] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[10:33:21] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.

**Comment by Ghibby2001** [comment]
When I try open the world check this in the console

**Comment by MJRLegends** [comment]
I will reopen, if and when you post the full log or the crash log...
