### ISSUE TITLE
space station update

### ISSUE THREAD

**Issue by theguy404** [MJRLegends/Space-Astronomy-Feedback-#633]
Hey MJR,

so the blocks are still disappearing but that issue is not a big problem anymore after removing one wall and adding a second wall to the outer one but now the chunk loaders are not working so i cannot teleport to the space station, every rocket is lost that goes up to the space station (including my teir 7 which if u can replace will save me a huge headache).

btw, i now spawn at 0, 64, 0 when i spawn in space station zone and god knows where the parachute chest spawns.

**Comment by MJRLegends** [comment]
Ok i will look at it

**Comment by theguy404** [comment]
i think i fixed the chunk loader, it was throwing errors so i broke it and replaced.

**Comment by MJRLegends** [comment]
I will give something when i can to try and fix the rocket issue thing

**Comment by theguy404** [comment]
any word on the rocket issue? (waiting to use the space station till i know i'm not gonna lose another rocket)
