### ISSUE TITLE
Can't craft Practicalities Diamond Shard

### ISSUE THREAD

**Issue by TheUnderTaker11** [MJRLegends/Space-Astronomy-Feedback-#634]
### Description of Issue
I want to make the matter transporter and luminous rod but I am unable to. When trying to craft 9 diamond shards, the EnderIO recipe shows up instead.

### Steps to Reproduce Issue
Put one diamond in a crafting grid

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]
1.5.6

**Comment by MJRLegends** [comment]
Thanks will see what i can so to fix it for the next mod pack update

**Comment by MJRLegends** [comment]
Thanks fixed in the next update that will be out soon :D
