### ISSUE TITLE
connecting to server 1

### ISSUE THREAD

**Issue by jaycob12** [MJRLegends/Space-Astronomy-Feedback-#635]
hi im trying to connect to server 1 and every time i click on it the game crashed i think when the server restarted i was in the Deep is there anyway to fix this, im in the hub but cant get to server 1 please help.
thanks my characters name is jaycobe12
this is the crash log:      http://pastebin.com/izC4sRcZ

**Comment by MJRLegends** [comment]
Use the direct  ips as it tells you to do in the hub
