### ISSUE TITLE
Crash on getting recipe for Uranium Ingot

### ISSUE THREAD

**Issue by fredthead** [MJRLegends/Space-Astronomy-Feedback-#636]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
When pressing R to get the receipe for the Uranium Ingot (can no longer use yellorium in the reactor casing receipe) the game crashes

### Steps to Reproduce Issue
1. Happens every time

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
http://pastebin.com/i2XmuKL2

**Version of Mod Pack using:** [VERSION]
v1.5.6

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Thanks fixed in the next update that will be out soon :D
