### ISSUE TITLE
Uranium crash.

### ISSUE THREAD

**Issue by Rezendore** [MJRLegends/Space-Astronomy-Feedback-#637]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. view the recipe for big reactor cases.
2. attempt to view recipe for uranium.
3. Crash.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
http://pastebin.com/rfc40wfc
**Version of Mod Pack using:** [VERSION]
V1.5.6
### Additional Information
[Any other information that may be able to help me with the problem]
Why are yellorite useless??

**Comment by MJRLegends** [comment]
Update to 1.5.7
