### ISSUE TITLE
Advanced Genetics crash 

### ISSUE THREAD

**Issue by Thomas290** [MJRLegends/Space-Astronomy-Feedback-#638]
### ---Issue Report---
**Have you checked the Known Iss
step]
ues page (if applicable & PLEASE CHECK BEFORE POSTING):** 
R :Yes didn't found it

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes, not found
### Description of Issue
When having a DNA Breeder placed down and being used (meaning one cell is breeded), if you unload the chunk then reload it (like going to the nether and coming back) clicking on this dna breeder will make your game crash

### Steps to Reproduce Issue
1. Craft and place a DNA Breeder
2. Power it, then breed a cell, whatever it is 
3.Unload the chunk (go to the nether), reload it (come back for the nether to where you placed your dna breeder) then right click the Breeder, crash happens

**Crash log/Log (if applicable):** Didn't got it

**Version of Mod Pack using:** 1.5.5

### Additional Information
May be a mod bug

**Comment by MJRLegends** [comment]
Without the crash log i cant help

**Comment by MJRLegends** [comment]
And your using a old mod pack version
