### ISSUE TITLE
More Opensecurity problems. posible fix

### ISSUE THREAD

**Issue by tndmadman** [MJRLegends/Space-Astronomy-Feedback-#640]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
N/A (Approved by MJR) 

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
N/A (Approved by MJR) 

### Description of Issue
SecureOS installs, but with loads of errors. Will not work with pastebin or wget, no other known working
programs or codes will work on SecureOS ither. Dispite working in older versions.

### Steps to Reproduce Issue
1. install secure os from disk provided by mod
2. try to use pastebin/wget or use other complex codes writen for things like door controllers.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
http://imgur.com/a/iBQms a error givin when loading. 
**Version of Mod Pack using:** [VERSION]
1.5.7
### Additional Information
Sujested fix: Use Opensecurity mod from your older pack "1.3.5" This is the modpack i came from a month or so ago, every thing worked just fine no bugs. granted some things are older but it all works 100%

**Comment by MJRLegends** [comment]
see commets on https://github.com/Shuudoushi/SecureOS/issues/60 by the dev
