### ISSUE TITLE
Fluiduct servo bug

### ISSUE THREAD

**Issue by WackyWaldo** [MJRLegends/Space-Astronomy-Feedback-#641]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]
yes I have checked the closed issues. My issue is where after awhile my servo will unpower or not work while powered after awhile on a openblocks tank
### Steps to Reproduce Issue
1. Hook up a hardened fluiduct and a hardened servo to a openblocks tank filled with lava
2. power the servo and wait

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]
first joined the server on 1.5.5 and made the contraption on 1.5.5 and same thing happend on 1.5.6 and 1.5.7
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
@WackyWaldo Please could you try and reproduce this crash in single player, as i feel it could be a server thing.

**Comment by MJRLegends** [comment]
Will reopen if and when a reply is made :)
