### ISSUE TITLE
Game crashes when loading into world.

### ISSUE THREAD

**Issue by ImVadez** [MJRLegends/Space-Astronomy-Feedback-#644]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

` YES I DID

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
YES
### Description of Issue
Game crashes uppon loading into my world, happened after my computer turning off randomly and forcibly closing minecraft.
### Steps to Reproduce Issue
1. open game
2. start world
3.Crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

http://pastebin.com/3aXtgzfk

**Version of Mod Pack using:** [1.7.10]

### Additional Information
please help D:

**Comment by ImVadez** [comment]
Playing in Curse* not FTB

**Comment by MJRLegends** [comment]
Please could you try and remove fast craft and then try again, if still crashes im going to need a world download to be able to debug the issue

**Comment by Thorxham** [comment]
Hello MJR I had the same problem as the guy above and i tried removing fast craft as you asked and the world still crashed. i can attach the report too.
[crash-2017-01-04_11.32.39-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/685415/crash-2017-01-04_11.32.39-server.txt)

**Comment by MJRLegends** [comment]
@Thorxham He isnt having problem with ender io is the issue is at the top of the log not bottom

**Comment by MJRLegends** [comment]
Will reopen if and when a reply is made :)

**Comment by acarpizo** [comment]
hi, i have this same problem, i have removed fastcraft but my game is still crashing.
