### ISSUE TITLE
Dark Asteroids Crash issue

### ISSUE THREAD

**Issue by crowinvicious** [MJRLegends/Space-Astronomy-Feedback-#646]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes i did

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes i did

### Description of Issue

After upgrading my server from 1.5.5 to 1.5.7, i add a systematic crash issue.

 - When i use Rocket to go on any planets, server crash during the loading of the world. This issue appear on any planets i want to go.

### Steps to Reproduce Issue
1. From the star map, select a planet and go on it.
2. From the star map, select a planet and go on it.

**Crash log/Log (if applicable):*
[crash-2016-12-19_19.00.18-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/670711/crash-2016-12-19_19.00.18-server.txt)

**Version of Mod Pack using:** version 1.5.7 or 1.5.6
### Additional Information

When i downgrade my server to 1.5.5, i have the same crash issue

Thank you in advance for your help

Regards

**Comment by MJRLegends** [comment]
Sorry for the slow reply but have you tried to recreate this crash in a new world?
and have you got anything chunk loaded on any planet?

**Comment by crowinvicious** [comment]
Hi,

I have a chunck loader in all planets i visited.

**Comment by MJRLegends** [comment]
This is a bug, and i will need to get it fixed

**Comment by MJRLegends** [comment]
Reported to dev: https://github.com/SteveKunG/MorePlanets/issues/16

**Comment by MJRLegends** [comment]
Possible Temp fix: delete Dark Asteroids and change back to v1.5.5 of the mod pack or disable the Dark Asteroids and stay with v1.5.7 of the mod pack

**Comment by MJRLegends** [comment]
Will be fixed in v1.6.0
