### ISSUE TITLE
Oreberry Bushes not Registering in Quest Book

### ISSUE THREAD

**Issue by DocHuzz** [MJRLegends/Space-Astronomy-Feedback-#648]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING): Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
As title, Oreberry bushes are not logging in the quest book even when pressing 'Manual Detect.'

### Steps to Reproduce Issue
1. Acquire quest "Collecting Ore Berry Bushes"
2. Collect required bushes
3. Press 'Manual Detect'

**Version of Mod Pack using:** 1.5.7

### Additional Information
May not be just this quest, I had to redo the 'Coal Generator' quest twice.  I have been playing this save file for apprx. 6 hours straight.  Noticed other quests in the book seeming to lag behind on detecting things before this, such as the smeltery quest and the iron hammer quest both not registering at first.  I closed out the book, checked my inventory to make sure I had the right things, re-opened the book and they suddenly completed.

**Comment by MJRLegends** [comment]
Yeah this just buggy HQM mod im afraid there nothing i can do, you can use "/hqm edit" or "/hqm edit <player>" to complete the quest for you or a different player (if you play on a server)
