### ISSUE TITLE
Mouse icon disappearing

### ISSUE THREAD

**Issue by Serpardum** [MJRLegends/Space-Astronomy-Feedback-#65]
For some reason the mouse arrow cursor will disappear when it should be visible. I.E. It is visible when typing in chat but not visible with the map up (j key), nor is it visible when the esc key is pressed and the Minecraft menu appears. To get the cursor back I've had to reload minecraft. I talked to someone on the official server and they stated they had problems with the mouse cursor disappearing also. I'm not sure which mod is doing it.

**Comment by DiamondMiner10** [comment]
Same problem here are you using a mac?

I have reason to believe that it is the "press CTRL to close" popup but I am not entirely sure

**Comment by MJRLegends** [comment]
Report this to the mod developer has its a problem on his side, but i will try and get a fix for the next update

**Comment by johnrobertwilson** [comment]
what mod specifically is stopping it? can we see a link so we can go troll them instead? i wanna play this pack so bad but this is a non-starter for me :(

**Comment by johnrobertwilson** [comment]
on my lunchbreak and found a workaround... it's DragonAPI... type this command in the chat "/checker disable dragonapi"

ganked from this thread: https://www.reddit.com/r/feedthebeast/comments/30xpjk/how_to_turn_off_the_dragonapi_nag/cpwqsvc
