### ISSUE TITLE
i changed my nickname but im like a new player for the servers

### ISSUE THREAD

**Issue by elenillias** [MJRLegends/Space-Astronomy-Feedback-#652]
hi!
im the user elenillias 

i changed my nickname to "CiclopeBizco" but the servers dont recognize i'm elenillias

help :)

thanks

**Comment by MJRLegends** [comment]
Yeah i saw your ticket, i will fix it later for you  (within the next 12 hours)

**Comment by elenillias** [comment]
shieeeeet 
ok  :D ...thanks!

mineeeecraft :D

**Comment by MJRLegends** [comment]
Sorted your old inventory is at put in a chest here -329 75 -445
