### ISSUE TITLE
Dupe bug with Mekanism Machines

### ISSUE THREAD

**Issue by Spellkaze** [MJRLegends/Space-Astronomy-Feedback-#656]
### ---Issue Report---
**Have you checked the Known Issues page :** Yes

**Have you checked Closed Issues :** The player that reported me said that he already sent the report here, but i have not found it.
### Description of Issue
Using the basic/advanced/elite compressing and infusing machine, the purple slots can make dupes with the compressed coal/redstone/diamond and refined obsidian and osmium ingots

### Steps to Reproduce Issue
_Infusing machine_
1. Fill an elite infusing machine with compressed diamond, make the bar meter go full and leave 64 of compressed diamond in the purple slot
2. take half of that 64 comp. diamonds and put them in your first inventory slot (upper-left)
3. Shift+ left click that half. (like when you want to put all in a chest)
4. You now have 32 of compressed diamond in the machine and 64 in your inventory. This process can be repeated.

What changes is what you want to dupe, so if you want compressed coal, you just need to fill the meter with coal and take halfs of the purple slot. This only works for compressed things, no for the normal diamonds, redstone, etc as far as my tests have shown.
The plan with osmium is the same as described here, just that that the bar fills up with liquid osmium.

**Crash log/Log (if applicable):** Nein

**Version of Mod Pack using:** 1.5.7

### Additional Information
This can give some serious dis-balance in players that play fair, wonder if this most be posted in the mekanism mod github.

**Comment by MJRLegends** [comment]
Sorry it seems i did get a report about it already, and i reported it to the mod dev but they never released a version with fix see https://github.com/aidancbrady/Mekanism/issues/3686
