### ISSUE TITLE
movement seems to be bugged out

### ISSUE THREAD

**Issue by shawnli170** [MJRLegends/Space-Astronomy-Feedback-#658]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] YES

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]YES
### Description of Issue
When I try to move in game or perform any command in game, it doesnt do them sometimes, and 10 seconds after when ever taht happenes, my character will start to move randomly by it self. Also the blocks keeps flashing. 

### Steps to Reproduce Issue
1. Login
2. Try to move

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** 1.5.7(I was having same issues in 1.5.5)

### Additional Information
I have checked with other packs and games, they all worked fine

**Comment by MJRLegends** [comment]
Please provide the following details:

Java Version:
Optifine: Yes/No
Does it do it in single player too: Yes/No
Graphic card (Make and model e.g GTX 970):

**Comment by shawnli170** [comment]
Java 8 Update 111
No optifine
Yes, single player too
Gtx 960m

**Comment by MJRLegends** [comment]
No idea, sorry i dont know how this could be mc related or my mod pack related.
