### ISSUE TITLE
Game crashing when loading a (was) stable world (first crash after interacting with ME Fluid Interface)

### ISSUE THREAD

**Issue by Pigowallace** [MJRLegends/Space-Astronomy-Feedback-#659]
### ---Issue Report---

Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING): **Yes**
Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING): **Yes**

### Description of Issue

I was playing normally without any anomalies (fps drop, lag, too much memory used etc) but after I placed a recipe into a ME Fluid Interface the game crashed to desktop.
Something similar has already happened when I connected a 16k Crafting Unit to the controller but in that case I managed to re-enter in the world without any issues (even breaking and replacing the exactly same block in the same spot nothing happened).

### Steps to Reproduce Issue

1. Craft a ME Fluid Interface using the auto-crafting system from AE2
2. Place the ME Fluid Interface with a ME Fluid Assembler on each side and a Dense Cable connected to the network through a P2P tunnel.
3. Open the ME Fluid Interface and put inside a recipe (was a Crusher from Mekanism for me)
4. The pack should crash

**Crash log/Log (if applicable):** 
http://pastebin.com/actWhCfM

**Version of Mod Pack using:** 1.5.7 (from Curse)

### Additional Information

I added 4 mods at the pack, but they worked with no issues at all.
- Magical Crops
- RFTools
- Treecapitator
- NotEnoughResources
I do not use them almost at all. Few crops from magical crops and a builder from RFTools used sometimes to speed up the building process.

I have a lot of chunks loaded using the loader from ChickenChunks (I guess more than 200 all around my base and about 30 in the nether) but in theory they should just affect the performance of my client globally and not causing random crash.

Sporadically there are some freezes that lasts about 3-4 seconds but I noticed them since the first minutes of the game and they never affected the gameplay in any way.

**Comment by MJRLegends** [comment]
Sorry but you have added mods to the mod pack so im unable to help since it could be the added mods that could play a factor in the crash

**Comment by Pigowallace** [comment]
I was not using that mods when the game crashed...

**Comment by MJRLegends** [comment]
Still doesn't mean there code isn't running

**Comment by MJRLegends** [comment]
Please reproduce without them and then i can provide help

**Comment by Pigowallace** [comment]
(edited the previous message)

You are right, indeed. 

I'm trying just now to reproduce it without any added mods.

**Comment by MJRLegends** [comment]
Chicken chunks was removed for issues like this too

**Comment by Pigowallace** [comment]
Ah... I'll try to remove it too, thanks. Give me some minutes.

**Comment by Pigowallace** [comment]
Ok, I reproduced the issues without any added mods. 
Loaded the world removing all the additional blocks and everything was fine. I did exactly as I have described in the log using the recipe for a Crusher from Mekanism inserted in a ME Fluid Interface and the client crashed.

Here the pastebin: http://pastebin.com/LzvDJNqP

**Comment by Pigowallace** [comment]
Do I have to open a new issue with the updated log?

Thanks

**Comment by MJRLegends** [comment]
Why are you putting a recipe for a Crusher from Mekanism inserted in a ME Fluid Interface, the crusher doesnt do fluids?

**Comment by Pigowallace** [comment]
I was putting there because the recipe for a Crusher requires 2 lava buckets. Since I have fluid storage in AE I was trying to automatize the crafting and I thought that the ME Fluid Interface was working like ME Interface and the Molecular Assemblers. So I connected the Fluid Assemblers to the ME Fluid Interface and the put the recipe there.

I know that is not working like that (realized only later) and the recipes should be directly put inside the Fluid Assembler, but an error like this should not cause the whole world to crash. Basically it should not allow to craft anything.

**Comment by MJRLegends** [comment]
You need to edit out the blocks through mcedit, apart from that i can do anything sorry

**Comment by Foppwin** [comment]
How to see what blocks to edit out?
How to see what gives the error?

**Comment by MJRLegends** [comment]
```
-- Block entity being ticked --
Details:
    Name: tileEntityFluidInterface // extracells.tileentity.TileEntityFluidInterface
    Block type: ID #1276 (tile.extracells.block.ecbaseblock // extracells.block.ECBaseBlock)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-626,58,705), Chunk: (at 14,3,1 in -40,44; contains blocks -640,0,704 to -625,255,719), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
    Actual block type: ID #1276 (tile.extracells.block.ecbaseblock // extracells.block.ECBaseBlock)
    Actual block data value: 0 / 0x0 / 0b0000
```

**Comment by Foppwin** [comment]
So #1276 needs to be removed I cant figure out how to read the coordinates.
Is (-626,58,705) the location of the troublesome block.

**Comment by MJRLegends** [comment]
Yeah
