### ISSUE TITLE
NEI not working/showing up in inventory menu

### ISSUE THREAD

**Issue by slueths126** [MJRLegends/Space-Astronomy-Feedback-#660]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]no

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]1.7.10

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Press o key
