### ISSUE TITLE
Tinkers' Construct + Iguana Tweaks modification not working

### ISSUE THREAD

**Issue by Spaceball12** [MJRLegends/Space-Astronomy-Feedback-#661]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
When I try to add modifications to tools (I added Iguana Tweaks- if this means it's not something you can answer, sorry for wasting your time), it doesn't work. However, until I died and lost my longsword and pickaxe, it worked perfectly fine. I believe this is a mod issue, on account of the fact that others have had this problem, but unfortunately none got a decent answer. So I am posting it here in the hopes that someone can point me in the right direction.
### Steps to Reproduce Issue
1. Die (?)
2. Cheat in a pickaxe and longsword
3. Try to modify both
4. Fail

**Crash log/Log (if applicable):** 
Not applicable.
**Version of Mod Pack using:** ]
1.5.7
### Additional Information
This isn't the default modpack, but since I really like Iguana Tweaks, I added it.

**Comment by MJRLegends** [comment]
Iguana Tweaks isnt in the mod pack so im not providing help for something i didnt add

**Comment by MJRLegends** [comment]
FYI: Adding a mod and then complaining to the mod pack dev it doesn't work isn't a good idea
