### ISSUE TITLE
Game crashes on opening of inventory directly after closing a chest.

### ISSUE THREAD

**Issue by Spaceball12** [MJRLegends/Space-Astronomy-Feedback-#662]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes.

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
Game crashes on opening of inventory directly after opening a chest.

### Steps to Reproduce Issue
1. Close chest
2. Open inventory directly after doing the first.

**Crash log/Log (if applicable):** Not given.

**Version of Mod Pack using:** [VERSION]
1.5.7
### Additional Information

**Comment by MJRLegends** [comment]
I cant help you without a crash log

**Comment by Spaceball12** [comment]
Here it is: http://pastebin.com/quZ0R2ds

**Comment by MJRLegends** [comment]
Not a mod pack issue its a open gl and java crash.

**Comment by MJRLegends** [comment]
http://stackoverflow.com/a/34842953

**Comment by MJRLegends** [comment]
Also if you are using Optifine that the cause

**Comment by Spaceball12** [comment]
Yes
