### ISSUE TITLE
Game has lag spikes for no apparent reason

### ISSUE THREAD

**Issue by Spaceball12** [MJRLegends/Space-Astronomy-Feedback-#664]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
At seemingly random points in time, the game freezes for a few seconds or so, then goes back to normal. I put the render distance to minimum and all graphics settings to the least CPU intensive, but the problem persists. I stood still at one point and watched the Task Manager CPU usage readout for thirty seconds or so, and subsequently saw it spike to up to 55%. Why's this? There's nothing particularly CPU using running in the background...

### Steps to Reproduce Issue
It just happens, seemingly randomly.

**Crash log/Log (if applicable):** 
Not applicable.
**Version of Mod Pack using:** [VERSION]
1.5.7
### Additional Information
The computer is Windows 8.1, 8 CPUs, lots of RAM and general memory, but no graphics card (though I doubt that would help). It's a fairly beefy computer, so I don't see why this is happening. Even KSP usually runs at almost full speed, despite being really quite memory-intensive, *much* more so than Minecraft.

**Comment by Spaceball12** [comment]
It (Minecraft) usually runs on average 10-15% CPU, excepting the aforementioned spikes.

**Comment by MJRLegends** [comment]
Is this in one world or all of them? And if all, even in a new created world?

**Comment by Spaceball12** [comment]
It seems to ease slightly as time goes on, but not very much.

**Comment by MJRLegends** [comment]
Ok to be honset i think its related to your last issue #662 i think that you have driver or OS issues.

**Comment by MJRLegends** [comment]
Can you run /cofh tps when the issue happens and post the information from the console that comes up here (in a pastebin.com)

**Comment by Spaceball12** [comment]
Ok, thanks. Will try.

**Comment by Spaceball12** [comment]
It gives me a speech bubble in the chat menu- take a screenshot and put it in pastebin.com?

**Comment by Spaceball12** [comment]
I did it basically during the spike, so I don't know if it captured what you wanted, but it says something along the lines of 0.01 ms // 100% for all planets/etc. No console comes up, and there's no indication of anything happening according to the FTB console.

**Comment by Spaceball12** [comment]
Oh, here's the console bit. http://pastebin.com/wTXvxBHP

**Comment by Spaceball12** [comment]
Odd- the server seems to work just fine.

**Comment by Spaceball12** [comment]
Never mind

**Comment by MJRLegends** [comment]
Yeah its defo a outside of mod pack issue

**Comment by Spaceball12** [comment]
Huh. Does it come from just so many mods? Never seen that before. Any ideas on how to fix?

**Comment by MJRLegends** [comment]
i think that you have driver or OS issues.

**Comment by Spaceball12** [comment]
Ah. Turns out I hadn't allocated enough RAM to Minecraft....derp, sorry for wasting your time
