### ISSUE TITLE
Systematic crash

### ISSUE THREAD

**Issue by AShinobi** [MJRLegends/Space-Astronomy-Feedback-#665]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
I have no issue loading the world but everytime I open an UI (inentory, smeltery, crafting bench...) I get a slight lag and quite often it crashes. The problem is minecraft is all about opening UIs so I usually gat to play 5-10mn before crashing.
### Steps to Reproduce Issue
1. Just load and play around a while opening UIs

http://pastebin.com/YYXNay35
VERSION 1.5.7
### Additional Information
This must be a local issue so I expect that you won't be able to reproduce it but it really makes playing impossible.
I also get random texture glitches all the time.
I tried reinstalling the modpack, and it didn't change anything.

**Comment by MJRLegends** [comment]
See #662 same crash problem which isnt a mod pack one

**Comment by AShinobi** [comment]
Oh right thank you I hadn't seen it ^^'

**Comment by MJRLegends** [comment]
No problem sorry but because its not a mod pack thing i cant really offer much in the help department with it as ive never found a permanent fix thats works for everyone for it
