### ISSUE TITLE
Quest "Collecting Ore Berry Bushes" wont clear

### ISSUE THREAD

**Issue by thrainng94** [MJRLegends/Space-Astronomy-Feedback-#667]
Hey, I am having a problem with one of the quests under "Getting Started".

The quest "Collecting Ore Berry Bushes" wont clear. It says I need to have one of the following: Iron oreberry bush, Gold oreberry bush, Tin oreberry bush, Aluminium oreberry bush.

I have one of each, and have them in my inventory, but it won't clear. I have tried pressing Manual Detect, but still nothing happens. I have attached pictures of all the oreberry bushes in my inventory and the quest book not cleared.

https://gyazo.com/f716781bd97da7155260551b0e21d5fb
https://gyazo.com/8fa05d3fee6c5983739a34656c1bec33
https://gyazo.com/be08b7592a1cfba4ae8bd8c156b859f2
https://gyazo.com/8f042fca01faf8d248f9fc74bead5262
https://gyazo.com/d11835a4660c5fbbfa97fa22d1da2a15
https://gyazo.com/bde2e845b5eeda69306a725a8809c95b

**Comment by MJRLegends** [comment]
Update released!
