### ISSUE TITLE
NEI crash

### ISSUE THREAD

**Issue by BlueAquatics** [MJRLegends/Space-Astronomy-Feedback-#670]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** **Yes**
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** **Yes** 
### Description of Issue
My Space Astronomy modpack decides to crash every so often when i open some inventories. However this is not constant and will open before a crash and after, As far as i can tell it's random and is produced by NEI.

### Steps to Reproduce Issue
1. launch a new world / join a server
2. open and use NEI, crashes sometimes when reopening.

**Crash log/Log (if applicable):**  [http://pastebin.com/rCusuw8D](url)
**Version of Mod Pack using:** 1.5.8
### Additional Information
this happen a lot before 1.5.8 aswell, i have directed 6/8 of ram towards it aswell.

**Comment by MJRLegends** [comment]
Nothing to do with NEI and its not even a mod pack related crash. See #662
