### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AmazingELF74** [MJRLegends/Space-Astronomy-Feedback-#671]
### Steps to Reproduce Issue
1. I don't know how it happened

http://pastebin.com/wAhfBA1Q

**Version of Mod Pack using:** [1.5.8]

### Additional Information
[Would not start. did not open to title screen. sometimes started but when I went to full screen it crashed again]

**Comment by MJRLegends** [comment]
I need more information like what java version yoy using and how much ram do you have assigned and i need more information about what happened before the issue started happening

**Comment by MJRLegends** [comment]
**I need more information:**
1. Java version you are using 
2. How much ram do you have assigned
3. What happened before the issue started happening 
4. Are you using Optifine
5. Please can you supply me a full client log

**Comment by MJRLegends** [comment]
Update your java version: 1.8.0_25 is a very old version
and maybe try allocating more than 2GB of RAM

**Comment by AmazingELF74** [comment]
i had 2Gb ram

java Version 8 Update 111 build 1.8.0_111-b14

I just remembered that i deleted duplicates of the pack and backups for them before. but I did completely reinstall the pack

I am not using optifine

I'm not sure what a full client log is. i have the crash report

**Comment by AmazingELF74** [comment]
i allocated 2Gb because it used to crash with 4. I have 8 total in system

**Comment by MJRLegends** [comment]
More ram will never cause crashes, and please try updating your java

**Comment by AmazingELF74** [comment]
it says that i have the latest version (java Version 8 Update 111 build 1.8.0_111-b14)

**Comment by MJRLegends** [comment]
See the screenshot i posted, your crash log was running with java 1.8.0_25

https://camo.githubusercontent.com/2a1e0177407375064db659d15350aa00b339b4b7/68747470733a2f2f692e6779617a6f2e636f6d2f61376537326264666665633766663133366531393738376333623262383466392e706e67

**Comment by MJRLegends** [comment]
See the screenshot i posted, your crash log was running with java 1.8.0_25

![](https://i.gyazo.com/a7e72bdffec7ff136e19787c3b2b84f9.png)

**Comment by MJRLegends** [comment]
Just because its installed on your computer doesnt mean the launcher is using it

**Comment by AmazingELF74** [comment]
![image](https://cloud.githubusercontent.com/assets/22646730/21914549/0d4db176-d902-11e6-9d5a-34090a14938f.png)

i am unsure how to fix it

**Comment by MJRLegends** [comment]
That pop up has nothing to do with Minecraft...... :/

You need to go to the settings in your launcher and change it.

**Comment by AmazingELF74** [comment]
um can i ask curse settings or minecraft settings?

**Comment by MJRLegends** [comment]
Launcher, so curse.

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/6ab5299c5f92131e4ff0096092e0f689.png)
