### ISSUE TITLE
My game crashes when loading world

### ISSUE THREAD

**Issue by acarpizo** [MJRLegends/Space-Astronomy-Feedback-#675]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes 
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes 
### Description of Issue
[My game crashes when loading world]

### Steps to Reproduce Issue
1. [opening minecraft]
2. [loading world(crashing)]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
http://paste.feed-the-beast.com/view/2501d920
**Version of Mod Pack using:** [VERSION]
1.7.10
### Additional Information
[my game randomly crashes when im playing, but now it crashes when loading the world so i cant play anymore. i also found this:

EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

i have removed Ender IO and fastcraft but still the same]

**Comment by MJRLegends** [comment]
How can i fix a crash issue without the crash log???

**Comment by acarpizo** [comment]
http://paste.feed-the-beast.com/view/2501d920 is it this one?

**Comment by MJRLegends** [comment]
This is in the known issues already so please triple check before posting 

Caused by: java.lang.NullPointerException
        at blusunrize.immersiveengineering.common.blocks.TileEntityImmersiveConnectable.func_145829_t(TileEntityImmersiveConnectable.java:122) ~[TileEntityImmersiveConnectable.class:?]
        at net.minecraft.world.chunk.Chunk.func_150812_a(Chunk.java:886) ~[apx.class:?]
        at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:862) ~[apx.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:500) ~[aqk.class:?]

**Comment by acarpizo** [comment]
i dont know what that means, thats the reason why im here, i need help -.-

**Comment by MJRLegends** [comment]
I have copied the part you needed match this in the known issues bit blusunrize.immersiveengineering.common.blocks.TileEntityImmersiveConnectable.func_145829_t(

**Comment by MJRLegends** [comment]
8. Immersive engineering TileEntityImmersiveConnectable Crash - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/341 - (This is a mod bug)
Solution 1: Remove ImmersiveEngineering and then load the world and then add it back (will remove everything in your world related to the mod)
Solution 2: Edit the blocks out (coords can be found in the crash log above the mod list) using MCEdit
