### ISSUE TITLE
mod pack wont load 

### ISSUE THREAD

**Issue by acarpizo** [MJRLegends/Space-Astronomy-Feedback-#676]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
### Description of Issue
[my world wouldnt load supposedly because an immersive engeniring problem so i was told to remove the mod, load my world and then putting it back in so al immersive E data would be deleted, solving my priblem, but when i remove the mod the modpack wont even load.]

### Steps to Reproduce Issue
1. [remove mod]
2. [trying to load modpack(not working)]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
http://paste.feed-the-beast.com/view/430e0002
**Version of Mod Pack using:** [VERSION]
1.7.10
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Your texture pack your using is the cause of this

**Comment by acarpizo** [comment]
i have removed it, still the same

**Comment by acarpizo** [comment]
my main problem is immersive E as i was told, but removing the mod is not solving my problem. Is there a way i can remove all immersive E data directly from the world save folder??

**Comment by MJRLegends** [comment]
Your log you have gave me in this issue ticket is a issue with your texture pack, remove it and then repost the new log so i can see what the problem is from there...

**Comment by acarpizo** [comment]
http://paste.feed-the-beast.com/view/c3bb1174 here it is

**Comment by MJRLegends** [comment]
[17:53:57] [Client thread/ERROR] [FML]: The mod immersiveintegration (Immersive Integration) requires mods [ImmersiveEngineering] to be
