### ISSUE TITLE
minecraft crashes after moving opencomputer with matter transpoter

### ISSUE THREAD

**Issue by CiclopeBizco** [MJRLegends/Space-Astronomy-Feedback-#680]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] 
90% yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
60% yes

### Description of Issue
[Description of the issue]
Crash when interact with opencomputers computer case. 

opencomputer tier 3 set able to run holograms

crash when you move the computercase with the matter transporter, and open again the computer
 

### Steps to Reproduce Issue
1. [First step]
move with  matter transporters the computer set from opencomputers 
2. [Second step]
interact with the computer
its happen when the computer is on and also when the computer is off. 

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
http://pastebin.com/BrAQcRqT 
line 9

**Version of Mod Pack using:** [VERSION]
1.5.8
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
@CiclopeBizco Please could you check the log, as there isnt a crash log in there,. There should be a crash log in the crash-logs folder

**Comment by CiclopeBizco** [comment]
hehe :)

some of them

http://pastebin.com/7kWkFPjp
http://pastebin.com/w5ZP8Jmf
http://pastebin.com/wdyKJYDD
http://pastebin.com/VNQJFw7H

**Comment by MJRLegends** [comment]
@CiclopeBizco i need the one with the most recent date and time, if this issue was the last crash you had

**Comment by CiclopeBizco** [comment]
http://pastebin.com/7kWkFPjp

yep... all pastebins are from the same issue, same way it crash .... same day... the first one is the last

**Comment by CiclopeBizco** [comment]
anyway i know now when it happens, so i stop moving the opencomputer set

**Comment by MJRLegends** [comment]
This cant be fixed but its been added to the known issues :P
