### ISSUE TITLE
Server Crash when loading into "Dark Asteroids"

### ISSUE THREAD

**Issue by DJWadd1e** [MJRLegends/Space-Astronomy-Feedback-#681]
Upon entering the "Dark Asteroids" dimension for the first time the server crashes. Anytime it is loaded up and the player that is in the "Dark Asteriods" joins the server crashes.

Crash Log - http://pastebin.com/x9wBpLP6

Version - 1.5.5-1.7.10 (Release)(current)

**Comment by MJRLegends** [comment]
Your not using the current mod pack during 1.5.5 isn't the latest

**Comment by DJWadd1e** [comment]
Edited mistype sorry
