### ISSUE TITLE
Certain blocks not sealable (quite clear glass)

### ISSUE THREAD

**Issue by ThatGuy1oo1** [MJRLegends/Space-Astronomy-Feedback-#682]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue] Certain blocks do not count as sealable using the galacticraft sealer

### Steps to Reproduce Issue
1. [First step] Place a sealer from galacticraft (Power it and supply it with oxygen
2. [Second step] Use a glass (Most common block) from Ender IO and Tinkers', I used quite clear glass.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]
1.5.8
### Additional Information
[Any other information that may be able to help me with the problem]
Solution is here: https://wiki.micdoodle8.com/wiki/SealableIDs It shows you how to add a certain block to galacticraft sealable config, I hope you'll add some of the glasses, and the extra utilities ethereal ones?

**Comment by ThatGuy1oo1** [comment]
I learned that all but quite clear glass from ender io are listed as sealable... wow

**Comment by MJRLegends** [comment]
Added to known issues, will be fixed in next update!
