### ISSUE TITLE
Crash On Entering Dark Asteroids (Reuploaded)

### ISSUE THREAD

**Issue by DJWadd1e** [MJRLegends/Space-Astronomy-Feedback-#683]
Upon entering the "Dark Asteroids" dimension for the first time the server crashes. Anytime it is loaded up and the player that is in the "Dark Asteroids" joins the server crashes.

Crash Log - http://pastebin.com/x9wBpLP6

Version - 1.5.8-1.7.10 (Release)(current)

(Reuploaded because of mistake in last post)

**Comment by MJRLegends** [comment]
What timezone is used where the servers is run?

**Comment by DJWadd1e** [comment]
Central Time Zone (UTC-06:00)

**Comment by MJRLegends** [comment]
Thanks i will report it to the dev

**Comment by MJRLegends** [comment]
https://github.com/SteveKunG/MorePlanets/issues/17

**Comment by MJRLegends** [comment]
Will be fixed in v1.6.0
