### ISSUE TITLE
Tier 4 Chest won't spawn

### ISSUE THREAD

**Issue by ChosenOne1234** [MJRLegends/Space-Astronomy-Feedback-#685]
## ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes
### Description of Issue
[Description of the issue] Edit - It turns out it was a server problem. I'll just leave this here in case anyone else has this issue. I've been to a good 10 or so Tier 4 dungeons (Diona, Koentus, and Mercury.) In one dungeon the path to the chest didn't even spawn. The other 9 had the path to the chest room, but at the end there was no chest, just a wall. I've completely demolished these walls and the blocks nearby, and found no chest.

### Steps to Reproduce Issue
1. [First step] Reproduce? I'm not entirely sure what you mean here.
2. [Second step] ^

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.] No crash.

**Version of Mod Pack using:** [VERSION] 1.5.8

### Additional Information
[Any other information that may be able to help me with the problem]
I'm playing on another server other than the Official Server. (Not trying to advertise)

**Comment by MJRLegends** [comment]
They have probably already been looted thats why, its not a bug... Diona is the correct planet. There are recipes for the schematic and spawn egg to get the key
