### ISSUE TITLE
java.lang.SecurityException: Could not open windows registry node

### ISSUE THREAD

**Issue by CosmicTree** [MJRLegends/Space-Astronomy-Feedback-#686]
### ---Issue Report---
**Have you checked the Known Issues page : Yes
**Have you checked Closed Issues : Yes
### Description of Issue

Hi, i have downloaded your modpack with curse, when i launch the game, forge load all of the components and when it come to the 5th Step of the loading screen the game crash. I've searched on internet but i found no results. I've tried to uninstall, repair etc bbut nothing change.

### Steps to Reproduce Issue

Sorry but i don't know how can you reproduce this issue.

**Crash log/Log (if applicable):** http://pastebin.com/ZXzf3RTq

**Version of Mod Pack using:** Space Astronomy 1.5.8

### Additional Information
sorry if i've made any mistake english is not my native language.

**Comment by MJRLegends** [comment]
Please try and reinstall Java, also 1.8.0_25 isnt the latest....

**Comment by CosmicTree** [comment]
ok i will try that, i keep you in touch tomorrow.

**Comment by MJRLegends** [comment]
Will reopen if the problem turns out to be a mod pack bug
