### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by BurntTNTFreak** [MJRLegends/Space-Astronomy-Feedback-#692]
Keeps going back to the logs page. Don't know if you want them/or if they will help.
My question is do I need java 7 to run it?
Basically I've re-installed the curse launcher and the mod pack about 10 times now and still haven't got far. Only made progress when I changed the Executables to open java 7 rather than java 8. Still crashed though.
Any help is appreciated. I will provide more info if needed.

**Comment by Spellkaze** [comment]
Are you running with an nvidia gpu?, in that case read this: https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/693

**Comment by MJRLegends** [comment]
@BurntTNTFreak see @Spellkaze's comment, also you need to supply the crash log if its crashing please...

**Comment by Spellkaze** [comment]
In this case it wont give any crash log, i had the issue and it wont produce any crash log, since minecraft wont even start, and as i saw he did made the same weird aroma log i had, so i guess it was his graphic card, still waiting his reply though

**Comment by BurntTNTFreak** [comment]
Ah right thanks ok. Will try that later and let you know. It's the same log as one of the older posts
https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/690
That one. But I will try the roll back and see if that works. 
Thanks for the help :)
