### ISSUE TITLE
FTB Space Astronomy Version 1.7.10

### ISSUE THREAD

**Issue by SlarithTv** [MJRLegends/Space-Astronomy-Feedback-#694]
I used the FTB Space Astronomy Version (Recommended) 1.7.10

when i start the launcher and press start, the lancher closed and opened it again with an error

AnalyticsBackgroundThread started
FTBLaunch starting up (version 1.4.12 Build: 10412)
OS: Windows 10 10.0 (64-bit)
Launcher Install Dir: C:\FTB
System memory: 3816M free, 8174M total
From Console: Jan 26, 2017 9:17:17 PM java.util.prefs.WindowsPreferences <init>
WARNUNG: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
The FTB Launcher has found the following Java versions installed:
Java Version: 1.8.0_121 sorted as: 1.8.0_121 64 Bit Java at : C:\FTB und Java 8\bin\java.exe
Java Version: 1.8.0_121 sorted as: 1.8.0_121 64 Bit Java at : C:\FTB und Java 8\bin\java.exe
Preferred: Java Version: 1.8.0_121 sorted as: 1.8.0_121 64 Bit Java at : C:\FTB und Java 8\bin\java.exe
Using Java path entered by user: C:\FTB und Java 8\bin\java.exe
[i18n] Fallback enUS loaded
[i18n] deDE Deutsche Sprachdatei geladen!
Checking installation location
Using download server Automatic:CurseCDN on host ftb.cursecdn.com (54.239.168.165)
Loading user data
Password is now encrypted with new key
Converted password will be saved to disk after successful login
Loading modpack information for thirdparty.xml...
Password is now encrypted with new key
Converted password will be saved to disk after successful login
mojang token is now encrypted with new key
Converted token will be saved to disk after successful login
Creating Console window
Creating main window
Local Authlib Version is good, skipping Download
Adding Authlib to Classpath
[i18n] Added 0 enUS to options pane
[i18n] Added 1 cyGB to options pane
[i18n] Added 2 daDK to options pane
[i18n] Added 3 deDE to options pane
[i18n] Added 4 enGB to options pane
[i18n] Added 5 enUS to options pane
[i18n] Added 6 esES to options pane
[i18n] Added 7 fiFI to options pane
[i18n] Added 8 frCA to options pane
[i18n] Added 9 frFR to options pane
[i18n] Added 10 itIT to options pane
[i18n] Added 11 maHU to options pane
[i18n] Added 12 nlNL to options pane
[i18n] Added 13 noNO to options pane
[i18n] Added 14 plPL to options pane
[i18n] Added 15 ptBR to options pane
[i18n] Added 16 ptPT to options pane
[i18n] Added 17 ruRU to options pane
[i18n] Added 18 svSE to options pane
[i18n] Added 19 zhCN to options pane
News download failed
[i18n] deDE Deutsche Sprachdatei geladen!
Setting up Launcher
Downloading pack data
Loading modpack information for modpacks.xml...
Opening main window
loading map information...
loading texture pack information...
Adding texture pack 1 (Soartex Fanver)
Adding texture pack 2 (Jadedcat Mixpack)
Adding texture pack 3 (Invictus)
Adding texture pack 4 (Faithful)
Adding texture pack 5 (JohnSmith Technicians Remix)
Adding map 1 (FTB Trident Default Map)
Adding texture pack 6 (Familiar yet Different)
Adding map 2 (Agrarian Skies Default Map)
Adding map 3 (Agrarian Skies Flat Map)
Adding map 4 (Agrarian Skies Server Map)
Adding map 5 (Direwolf20 Map Ep.0)
Adding map 6 (FTB Pax Challenge)
Adding map 7 (Direwolf20 Map Ep.0)
Adding map 8 (Direwolf20 Map Ep.10)
Adding map 9 (Direwolf20 Map Ep.20)
Adding map 10 (Direwolf20 Map Ep.30)
Adding map 11 (Direwolf20 Map Ep.40)
Adding map 12 (Direwolf20 Map Ep.50)
Adding map 13 (Direwolf20 Map Ep.80)
Adding map 14 (FTB Normal)
Adding map 15 (FTB Insanity)
Logging in...
Beginning authlib authentication attempt
successfully created YggdrasilAuthenticationService
Login complete.
Checking local assets file, for MC version 1.7.10 Please wait! 
Setting up native libraries for Space Astronomy v Recommended Version MC 1.7.10
Syncing Assets:
Java Path: C:\FTB und Java 8\bin\java.exe
Pack: Space Astronomy 1.7.10
Setting MinMemory to 256
Setting MaxMemory to 4096
Adding Optimization Arguments: -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CICompilerCountPerCPU -XX:+TieredCompilation
[21:17:26] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:17:26] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:17:26] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[21:17:26] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[21:17:26] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_121, running on Windows 10:amd64:10.0, installed at C:\FTB und Java 8
[21:17:26] [main/INFO] [FML]: [AppEng] Core Init
[21:17:26] [main/WARN] [FML]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:17:26] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
MC process exited. return value: -1073740791
[i18n] Added 0 enUS to options pane
[i18n] Added 1 cyGB to options pane
[i18n] Added 2 daDK to options pane
[i18n] Added 3 deDE to options pane
[i18n] Added 4 enGB to options pane
[i18n] Added 5 enUS to options pane
[i18n] Added 6 esES to options pane
[i18n] Added 7 fiFI to options pane
[i18n] Added 8 frCA to options pane
[i18n] Added 9 frFR to options pane
[i18n] Added 10 itIT to options pane
[i18n] Added 11 maHU to options pane
[i18n] Added 12 nlNL to options pane
[i18n] Added 13 noNO to options pane
[i18n] Added 14 plPL to options pane
[i18n] Added 15 ptBR to options pane
[i18n] Added 16 ptPT to options pane
[i18n] Added 17 ruRU to options pane
[i18n] Added 18 svSE to options pane
[i18n] Added 19 zhCN to options pane
[i18n] deDE Deutsche Sprachdatei geladen!

i installed Java and FTB over 20 times again and the Problem is the same... i delete all Minecraft Things and Java Programms and install it... i used other Mods versions and yes... the last Thing that i have do is that i like to install an CustomNPC mod but i reinstall him... i have no idea what i can make

[The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:17:26] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft]

I Need Help :(

MFG Slarith

**Comment by MJRLegends** [comment]
The error you have provided isnt a error at all.... and use this please

**Comment by AfftaR** [comment]
The problem is connected with the latest NVIDIA Geforce driver

https://www.reddit.com/r/feedthebeast/comments/5pydv9/dont_install_nvidia_gpu_driver_version_37849_it/?st=iye1n6g8&sh=9d77d1f9

**Comment by MJRLegends** [comment]
Yeah see #693
