### ISSUE TITLE
An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).

### ISSUE THREAD

**Issue by Foppwin** [MJRLegends/Space-Astronomy-Feedback-#695]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]Yes

### Steps to Reproduce Issue
Loading a game gives me the EnderIO error but not sure how to read the error log.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
http://pastebin.com/paWHQ26s

**Version of Mod Pack using:** [VERSION]
1.5.7

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You need to check the known issues, the issue is at the top of the log


Time: 1/26/17 8:58 PM
Description: Exception getting block type in world
 
java.lang.NullPointerException: Exception getting block type in world
    at blusunrize.immersiveengineering.common.blocks.TileEntityImmersiveConnectable.func_145829_t(TileEntityImmersiveConnectable.java:122)

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/ecfc6439546b03a5a738ab4599fe013a.png)
