### ISSUE TITLE
Crashing on start

### ISSUE THREAD

**Issue by DonViper** [MJRLegends/Space-Astronomy-Feedback-#696]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
When launching game game crashes with "Game ended with bad state (exit code -1073740791)"

### Steps to Reproduce Issue
1. [First step]
start game  via curse press play game crashes to laucher
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
http://pastebin.com/Mi6nF5Gf

**Version of Mod Pack using:** [VERSION]
1.5.8

### Additional Information
[Any other information that may be able to help me with the problem]
seem to have this problem with Ultima Techno Magica modpack by master0r0 aswell

**Comment by DonViper** [comment]
extra log from the game output tap http://pastebin.com/56xQE8SR. can also confirm that this happens with Direwolf20 1.10 modpack

**Comment by MJRLegends** [comment]
see https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/693
