### ISSUE TITLE
Ender Pearl Powder from Ender IO doesn't show up in NEI

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-Feedback-#697]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes

### Description of Issue
Ender Pearl Powder from Ender IO do not show up in NEI

### Steps to Reproduce Issue
1. Try to look up Ender Pearl Powder in NEI

**Version of Mod Pack using:** [VERSION]
1.5.8

**Comment by MJRLegends** [comment]
Not sure whats causing this, its not even showing in the Creative menus either.... weird...

**Comment by MJRLegends** [comment]
Added to known issues

**Comment by Eufranio** [comment]
It won't load if another dust is loaded (like the Applied Energistics one).
