### ISSUE TITLE
Crash Space Astronomy modpack - Problems: Aroma1997 and CodeChickenCore

### ISSUE THREAD

**Issue by WCala** [MJRLegends/Space-Astronomy-Feedback-#699]
I used Curse to download this modpack, when I start the modpack on Minecraft, it crash.

Crash Log - http://pastebin.com/sjgQiP04

Version - 1.5.8-1.7.10 (Release)(current)

**Comment by MJRLegends** [comment]
No see #693

**Comment by WCala** [comment]
He has my same problem, thanks
