### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by Dantifer** [MJRLegends/Space-Astronomy-Feedback-#7]
Ive noticed that the Peaceful Table does not work, in peaceful mode. Even when the config is set to let it work in any difficulty, still nothing.

**Comment by Dantifer** [comment]
@MJRLegends

**Comment by MJRLegends** [comment]
I will look in to it and get back to you

**Comment by MJRLegends** [comment]
Just tested it and it works.

**Comment by Dantifer** [comment]
I see. I was using an Electrical Age tool. Thanks for the tip, if I find any bugs I'll report them. This pack is nice, I love how it walks through things, very progressive. Learning these mods is nice.

**Comment by MJRLegends** [comment]
Thank you

**Comment by Dantifer** [comment]
Still having problems with it, Ive tried crafting a sword from every mod and nothing, I started the game on normal and made is peaceful, maybe thats why?

**Comment by MJRLegends** [comment]
How are you giving it the sword?

**Comment by Dantifer** [comment]
Putting it in a chest next to the table about 20 blocks away from my main work area.

**Comment by MJRLegends** [comment]
@Dantifer it must be a bug with the mod. maybe report it to the developer.
