### ISSUE TITLE
missing cursor when hitting esc in game

### ISSUE THREAD

**Issue by rick3333** [MJRLegends/Space-Astronomy-Feedback-#70]
![image](https://cloud.githubusercontent.com/assets/3783930/10357387/0a92e5e0-6dc5-11e5-8d0c-eaa81a078fef.png)
As you can see the mouse is on the "forum page" button but there on no cursor even after leaving the pause menu and returning to the main menu.
The only fix that i have found so far is to restart the game.

**Comment by MJRLegends** [comment]
Please check already posted issues as this has been post multiple times and its a problem with DragonAPI

**Comment by MJRLegends** [comment]
Please repot this to the developer of dragonapi
