### ISSUE TITLE
BC Builder Cause Crashing

### ISSUE THREAD

**Issue by nsCrane** [MJRLegends/Space-Astronomy-Feedback-#702]
I used a BC builder(ID 614:3) few days ago and it has some problem but I don't know how it caused.

Now, when I login, server crashed and not only I but also everyone is disconnected.
In addition to this, It seems that everyone who approaching to the place will be affected and make server crashing.

Supplementary, Client Log : http://pastebin.com/FwqypGSP
(From login to disconnect)

**Comment by MJRLegends** [comment]
What server?

**Comment by nsCrane** [comment]
Server 4, coordinate about X:208, Z:1629

**Comment by MJRLegends** [comment]
Ok i will get it fixed for you in the next 24 hours, please dont join space 4 in the meantime in till its sorted :P

**Comment by nsCrane** [comment]
Thank you very much!

**Comment by MJRLegends** [comment]
It was your Minechem chamber that was crashing the server, please dont use thermaldynamics with that machine as its broken :P sorry for the delay
