### ISSUE TITLE
Curse launcher, Stuck on "Preparing" on new minecraft launcher

### ISSUE THREAD

**Issue by jellewie** [MJRLegends/Space-Astronomy-Feedback-#705]
**[Description of the issue]**
When trying to launch the game, Minecraft's new launcher pops up. and clicking on the play space Astronomy button will result in a load bar wich does not do anything

Image here  http://i.imgur.com/L251BO9.png

**[What I did]**
It use to work until 29-01-2017
I normally start  Space Astronomy V1.5.8 from the curse launcher

But on the 30th>:
Tried to relaunched got the new Minecraft launcher, logged in again and pressed play. 
- Didn't work - (waited 10 minutes but nothing changed)
Removed and reinstalled Space Astronomy + relaunched
- Didn't work - 
Removed and reinstalled Curse client & Space Astronomy + relaunched
- Didn't work - 
Installed Space Astronomy V1.3.8 + relaunched
- Didn't work - 

**[tested versions]**
1.5.8 (currently newest)
1.3.8 (just a random old one)

**Comment by MJRLegends** [comment]
Not my issue i dont own the curse launcher

**Comment by MJRLegends** [comment]
https://twitter.com/curseapp/status/826528914831003651

https://twitter.com/curseapp/status/826529573370286080

**Comment by jellewie** [comment]
Thank you for your response and linking the twitter messages. I just could not find anything about this problem, so I contacted all groups involved.

**Comment by MJRLegends** [comment]
Should be fixed now
