### ISSUE TITLE
Spawned without Questbook

### ISSUE THREAD

**Issue by rocker4156** [MJRLegends/Space-Astronomy-Feedback-#706]
Hi MJRLegends,

yesterday I setup the latest version of Space Astronomy on my Centos 6.8 server. 
But when we logged in, we spawned without a questbook.
Crafting it is not possible. When I drag in the recources the questbook appears but I can't take it to my inventory.
Same issue when I try to take it with NEI. It says something like "No Item with ID ....".
This issue appeared on every single player logged in to the server.

I hope that this information can help you fix this issue. If not, just let me know what you else need.

Thank you very much!
rocker4156

**Comment by MJRLegends** [comment]
run "/hqm quest"
