### ISSUE TITLE
Space 4 Crashing a lot. 

### ISSUE THREAD

**Issue by knightslayer14** [MJRLegends/Space-Astronomy-Feedback-#707]
Space 4 has gone down twice in the last 3 days. its annoying because when people are trying to get things done it lags out. i timed out 4 times before it crashed. pls fix or ban the person causing the crashes. Muddy always seems to be on when it happens.

**Comment by Arthair** [comment]
I can't connect to space 4. Always timed out. think it's down

**Comment by Arthair** [comment]
I also tried space 1,2 and 3. they work
