### ISSUE TITLE
Collecting Ore Berry Bushes (Again)

### ISSUE THREAD

**Issue by deathrite2** [MJRLegends/Space-Astronomy-Feedback-#708]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
Yes. This issue, which was fixed in update in version 1.5.8 is back.  With the update to add Essence Berry bush to the quest, I am unable to finish the quest.  It is unable to recognize the Essence Berry Bush in my inventory.

### Steps to Reproduce Issue
1. Gather oreberry bushes.
2. Go to the quest book to update quest, essence berry is not recognized.

**Version of Mod Pack using:** 1.5.8

### Additional Information
I originally was collecting the four main bushes for the quest and when I went to accept the quest, it wouldn't work despite having done it in another world.  After I logged out of minecraft, I logged back in and suddenly there were 5 bushes needed instead of four.  That's fine, the original four were recognized but the last one, the Essence Berry Bush is not.  Went online to look for issue and found the original fixed issue.

**Comment by MJRLegends** [comment]
Thats just derpy hqm, use "/hqm edit" to complete it
