### ISSUE TITLE
Power Converters Steam Producers/Consumers

### ISSUE THREAD

**Issue by dead-stroke** [MJRLegends/Space-Astronomy-Feedback-#71]
The version powerconverters-1.7.10_3.3.0-jenkins.74.jar has (known to mod author) issues with the steam producer/consumers while using them on servers. (issue is they due not produce, nor consume steam)  There is an Alpha version powerconverters-1.7.10_3.3.0-jenkins.76.jar that is supposed to correct the issue.  

Thank you

**Comment by MJRLegends** [comment]
i will upgrade the mod for the next update thanks :D
