### ISSUE TITLE
Quest Book ME Storage Bus Not  Recognised

### ISSUE THREAD

**Issue by catterz** [MJRLegends/Space-Astronomy-Feedback-#713]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
The Quest Book is not recognising the 8 ME Storage Buses that I have during the Creating Bulk Storage quest. 

The item number of the ME Storage Bus items I have created is 4366:220

I have tried dropping and picking them up again, but it still does not recognise them.  All other AE2 items have been detected correctly. Have also tried relogging.

This is on a Single Player instance of the modpack.

### Steps to Reproduce Issue
Not sure if it can be reproduced but it is not working for me,

**Version of Mod Pack using:**
1.5.8

**Comment by catterz** [comment]
Further to this, I have found the same issue is occurring on the Automating Machines quest with the ME Interface Terminal (4366:480). The ME Pattern Terminal is recognised, but not the ME Interface Terminal.

**Comment by MJRLegends** [comment]
Use "/hqm edit" to complete them
