### ISSUE TITLE
Mekanism Reactor Crash

### ISSUE THREAD

**Issue by Riplley** [MJRLegends/Space-Astronomy-Feedback-#714]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes 

### Description of Issue
Pressurized cable to gas container and reactor port crash

### Steps to Reproduce Issue
1. Build Meka reactor
2. connect a pressurized cable to a port and and a gas tank, set the port to pull and gas container to push
3. Crash and Burn

**Crash log/Log (if applicable):** 
http://pastebin.com/jk44Tr3Y
**Version of Mod Pack using:** 
1.5.8

### Additional Information
both singleplayer and multiplayer i did this,

**Comment by MJRLegends** [comment]
Yeah steam isnt a gas in minecraft so you need to edit the block out with mcedit
