### ISSUE TITLE
Iridium Ingot from Advanced Solar Panels can't be used in Galacticraft Compressors

### ISSUE THREAD

**Issue by FoxAhead** [MJRLegends/Space-Astronomy-Feedback-#719]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes
### Description of Issue
Iridium Ingot from Advanced Solar Panels can't be used in Galacticraft Compressors for crafting Compressed Iridium unlike same ingots (based on ore dictionary tag ingotIridium) from More Planets.

### Steps to Reproduce Issue
1. Smelt Iridium Ore (More Planets) in Induction Smelter (Thermal Expansion) and get Iridium Ingot (Advanced Solar Panels).
2. Put Iridium Ingot (Advanced Solar Panels) into Electric Compressor (Galactcraft) according to the recipe. Nothing happens.

**Version of Mod Pack using:**
1.5.8

### Additional Information
It's minor issue. Workaround: of course you can convert ingots with ore dictionary.

**Comment by Truemz** [comment]
you can use a mekanism oredictionificator to convert the ingots, then you can use them

**Comment by MJRLegends** [comment]
Yeah im unable to do anything to fix this... sorry...

**Comment by MJRLegends** [comment]
I think i can get this fixed, i've reported it to the more planets dev https://github.com/SteveKunG/MorePlanets/issues/22

**Comment by MJRLegends** [comment]
Will be fixed in v1.6.0
