### ISSUE TITLE
No Cursor in In-Game GUI

### ISSUE THREAD

**Issue by jeffreyhunt108** [MJRLegends/Space-Astronomy-Feedback-#72]
When you are in a world, when you open the escape menu, there is no cursor, and it is extremely hard to navigate the various parts of the menu. If they wanted it this way when they created it, they shouldn't. It is hard to navigate, and inconvenient. I would love to see it fixed in the near future.

**Comment by MJRLegends** [comment]
Please read the closed issues before posting as this has been reported 5 times.
