### ISSUE TITLE
Freeze_Fanatic's Player Corruption / Item Packet Overload and Deletion

### ISSUE THREAD

**Issue by Freeze-Fanatic** [MJRLegends/Space-Astronomy-Feedback-#720]
So we meet again MJRLegends. It appears breaking a [ Mekanism:PersonalChest ] full of ME storage cells is not the best idea. It appears to have corrupted my player file temporarily and deleted all of my storage cells in the process. If you could please rollback my claim to where the chest was never broken on this chunk coordinate.

Coordinates of Chunk:  X: -2874  Y:57  Z: -4633

With Love,
Freeze_Fanatic

**Comment by Freeze-Fanatic** [comment]
Format is N/A 🗡

**Comment by MJRLegends** [comment]
You got to be kidding me lol ok i will take a look when I can

**Comment by MJRLegends** [comment]
I can probably repair it and get the drives back without a rollback

**Comment by Freeze-Fanatic** [comment]
Much Love <3 :D

**Comment by MJRLegends** [comment]
So can you login currently, if so i have bad news about getting your stuff back

**Comment by Freeze-Fanatic** [comment]
Yes, I can login fine, but the chest that corrupted my player file deleted all the of drives in its inventory. Whats the bad news?

**Comment by MJRLegends** [comment]
Im afraid i cant get them back sorry, i can only get them back from the 7th or i can refund stuff if you know what was in there

**Comment by Freeze-Fanatic** [comment]
Um, it was my whole AE so I have no idea what I had..... damn this sucks....

**Comment by MJRLegends** [comment]
Yeah the 7th is the only option i think for a chunk rollback

**Comment by Freeze-Fanatic** [comment]
Just that chunk?
Uhhh.... my ME drives are held in a 2x2 chunk radius.... If you rolled back that 2x2 to the 7th would my AE be back?

**Comment by MJRLegends** [comment]
i can do the just me system drives and yeah its the Feb  7 06:00:01 2017 (server time / CET timezone) is what i have available to roll it back to due to backup issues

**Comment by Freeze-Fanatic** [comment]
Thats completely fine... I'll start deleting any duped items that come from the roll back.

**Comment by MJRLegends** [comment]
actually no sorry its the Feb 6 00:00:02 2017 not 7th lol

**Comment by Freeze-Fanatic** [comment]
Still fine :D

**Comment by Freeze-Fanatic** [comment]
I am willing the cost of four days for my AE.

**Comment by MJRLegends** [comment]
Yeah the backups are being a pain atm, im trying to fix them :P and ok i will get that moved across later on for you :D

**Comment by Freeze-Fanatic** [comment]
Alrighty then, thanks man!

**Comment by Freeze-Fanatic** [comment]
Do you need to the know the chunks or nah?

**Comment by MJRLegends** [comment]
is it defo -2874 Y:57 Z: -4633??

**Comment by MJRLegends** [comment]
and is it defo space 1?

**Comment by Freeze-Fanatic** [comment]
Well thats 25% of my drives.... the 2x2 chunk area hold the other 75%

Those coordinates were for the chest.

**Comment by MJRLegends** [comment]
ok thats fine :D

**Comment by Freeze-Fanatic** [comment]
Alright, and yes.... Space 1, those coords and three chunks around that coord is my me drives.

**Comment by MJRLegends** [comment]
u around?

**Comment by MJRLegends** [comment]
@Freeze-Fanatic please make you let me know everything your missing atm

**Comment by Freeze-Fanatic** [comment]
You cant handle what I'm about to tell you.

**Comment by MJRLegends** [comment]
no i feel to ill to talk, so please let me know here :D

**Comment by Freeze-Fanatic** [comment]
4 Compact Machines Containing 12 x 12 x 12 Reactors
ATM ^

**Comment by Freeze-Fanatic** [comment]
About 1.4 mil Yellorium Ingots
About 17k Ender Pearls 
About Three stacks of Molecular Assemb. [ Auto Crafting ] 
About a stack of ME Interfaces. [ Auto Crafting ]
Eight of every Elite Factory [ Automation ] 
Nine advanced Inscribers [ Automation ]
About 57 Blank Patterns

And My Soul and Happiness is also missing. 
With love,
 Freeze

**Comment by MJRLegends** [comment]
@Freeze-Fanatic whats the latest on this, sorry been to ill to come on my computer
