### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by ETG153** [MJRLegends/Space-Astronomy-Feedback-#722]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
A random crash, caused me to report due to full inventory loss

### Steps to Reproduce Issue
1. Download and play Space Astronomy
2. Run out of RAM to freeze the game (i have 3gb, 2.75 reserved for the game)
3. Close Javaw from Task Manager

**Version of Mod Pack using:** v1.5.8

**Comment by MJRLegends** [comment]
Need a crash log???? and 2.75GB of ram is defo not enough so this isnt a mod pack issue, its just you cant run it :(
