### ISSUE TITLE
Same issue as  "Local Server Problems #278"

### ISSUE THREAD

**Issue by OPEndeavors** [MJRLegends/Space-Astronomy-Feedback-#724]
We started a server, and are unable to craft several items, like the Tinker's Crafting station. I know the recipe, and can put the recipe in the crafting grid.  The item shows like it will craft on the crafting table, but when dragged to inventory or shift clicked the item does not craft.

We can craft basic vanilla stuff. I've made picks, crafting tables, torches, etc.  But Tinker's patterns, crafting stations, and even the quest book are un-makeable.

**Comment by MJRLegends** [comment]
Do "/hqm quest"

**Comment by MJRLegends** [comment]
if not redownload the files and make sure you have all the needed mods on both sides (client and server)

**Comment by OPEndeavors** [comment]
Issue was solved by redownloading server files on a different PC, and running it from there.
