### ISSUE TITLE
Visual Glitch Chest / Machine etc.

### ISSUE THREAD

**Issue by Zuckerwasser** [MJRLegends/Space-Astronomy-Feedback-#726]
Some chests and machine got a visual glitch. Example at the screenshot. All of my mates got them too. Anyone know why?

![glitch](https://cloud.githubusercontent.com/assets/17800805/22943115/9622abc4-f2ec-11e6-8568-9e854e332234.jpg)

Version - 1.5.8-1.7.10 (Release)(current)

**Comment by MJRLegends** [comment]
Do you have Optifine?

**Comment by Zuckerwasser** [comment]
not extra modded, clear install + Space Astronomy Mod. Glitch rotates sometimes to other chests.

**Comment by MJRLegends** [comment]
Remove fastcraft or if not idk sorry this isnt just my mod pack issue if your getting this issue
