### ISSUE TITLE
Yellorium and Uranium conversion

### ISSUE THREAD

**Issue by Blindsyde343** [MJRLegends/Space-Astronomy-Feedback-#73]
I am not sure if this is intended, but Yellorium ingots have the oredic of both Yellorium ingots and Uranium... The only issue I have is when trying to condense them into a block it creates an Uranium block, and when I convert it back it makes straight uranium. 

If this is intended that's fine, I figured I should ask at the very least!

**Comment by MJRLegends** [comment]
Fixed in next update
