### ISSUE TITLE
Sawmill bug

### ISSUE THREAD

**Issue by janmalte750** [MJRLegends/Space-Astronomy-Feedback-#730]
Sawmill dissapears multiple times when crushing Leather.
Mod Thermalexpansion

**Comment by MJRLegends** [comment]
Im not sure what you mean here, Please supply more details of what you mean please

**Comment by janmalte750** [comment]
I craft the Sawmill 2 times, then i put some Leather armor in the Sawmill and in cause of that the machine goes away. It dissapeared when the processing bar is just at the end. I don't know why.

**Comment by MJRLegends** [comment]
Are you playing on a server? or single player?

**Comment by janmalte750** [comment]
I am playing on Space4 and my username is janmalte750

**Comment by MJRLegends** [comment]
This is just a desync issue, nothing can be done
