### ISSUE TITLE
Progress form quest book reset

### ISSUE THREAD

**Issue by Benamo1** [MJRLegends/Space-Astronomy-Feedback-#731]
### ---Issue Report---
Quest book
### Description of Issue
I was playing and when i opened my quest book it had reset and i lost all progress from it.
**Crash log/Log (if applicable):**
It dose not crash

**Version of Mod Pack using:** [1.5.8]

### Additional Information
no additional info.

**Comment by MJRLegends** [comment]
This is a derpy hqm bug use '/hqm edit' to get it back
