### ISSUE TITLE
Space 2 still down

### ISSUE THREAD

**Issue by MineForFunCraft** [MJRLegends/Space-Astronomy-Feedback-#734]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):**Yes 

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by CiclopeBizco** [comment]
space 2 is up! :)
