### ISSUE TITLE
Error: Fatally missing blocks and items

### ISSUE THREAD

**Issue by Neythi** [MJRLegends/Space-Astronomy-Feedback-#735]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
Hi, I have problem with my server.. When I connect to my server, appered error message: Fatally missing blocks and items. What can I do with this?

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** -

**Version of Mod Pack using:** [V1.5.8]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Download the server files again or make a new world and make sure you havent broken the world some how
