### ISSUE TITLE
Please Help! Keeps crashing when I attempt to load my world

### ISSUE THREAD

**Issue by dylanmcgarrity** [MJRLegends/Space-Astronomy-Feedback-#739]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

YES

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]  YES
### Description of Issue
[Description of the issue]
Modpack loads up but when I attempt to join my world it crashes

### Steps to Reproduce Issue
1. [First step] I don't know where to start
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
http://pastebin.com/HtiJUneU
**Version of Mod Pack using:** [VERSION]
Minecraft Version 1.7.10       Space Astronomy Version 1.5.8
### Additional Information
[Any other information that may be able to help me with the problem]
My World : https://www.dropbox.com/s/nuu79g7j0n1vwr6/Astronomy.zip?dl=0

**Comment by Modziely** [comment]
That's happening to me as well. I can't join the world i'm in cause it keeps crashing on me when i try to. ;(

**Comment by MJRLegends** [comment]
Delete this folder "world/elec332/"
