### ISSUE TITLE
Only 2 Hits with any Tool

### ISSUE THREAD

**Issue by Borotes** [MJRLegends/Space-Astronomy-Feedback-#74]
I tried to craft any tool, like Pickaxe, Shovel, and Axe in every possible material. I can only destroy 2 blocks with them, till they break.

**Comment by MJRLegends** [comment]
Are you trying to make vanilla tools

**Comment by Borotes** [comment]
Yep, my friend and me started to play together on a self hosted server. Short time playing he told me that all of his tools are breaking after 2 blocks. I tried, same happed to me. I went into creative mode and this happend to every single tool.

**Comment by MJRLegends** [comment]
There disabled, use tinkers tools, it does say this in the book provided in the first quest! So please read it!!!

**Comment by Borotes** [comment]
Ok sorry dude ^^
