### ISSUE TITLE
I entered the Deep Dark in spawn and now i can't get back out!!

### ISSUE THREAD

**Issue by Modziely** [MJRLegends/Space-Astronomy-Feedback-#740]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] YES

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] YES
### Description of Issue
[Description of the issue]
When i was in spawn on Server 1 my friend and i were going to enter the DeepDark portal to see what it looked like and now i can't get back into my game to leave it cause it keeps crashing my whole game every time. I can get into the hub and it works fine but i can't get into server1 anymore..
### Steps to Reproduce Issue
1. [First step] Go to spawn on any server
2. [Second step] go into the deep dark portal

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
ok??
**Version of Mod Pack using:** [VERSION]
1.5.8(?)
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Use the direct ips and dont join the hub
