### ISSUE TITLE
New Server getting Mod rejection errors

### ISSUE THREAD

**Issue by ScarofXeno** [MJRLegends/Space-Astronomy-Feedback-#742]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
Just starting a new server for Space Astronomy.  I downloaded the modpack from curse and can log onto the official servers with no issues.  However when i try to log into a server im making for my friends, it says i have 3 mod rejections.  When try to log in, it gives me 7 mods errors. those are...
-Thermal Dynamics
-Thermal Foundation
-Thermal Expansion
-Redstone Arsenal
-MTMR
-MineFactory Reloaded
-TConstruct

I moved tried moving the mods from client side to the server side to see if that would clear anything up (because the official servers arent flagging those mods) and it doesnt help.  I ensured that i am running Forge 1.7.10-10.13..4.1614 on both client and server.

Any other suggestions would be great

**Version of Mod Pack using:** Latest version

**Comment by MJRLegends** [comment]
Redownload the mod pack and check the server has all the mods too

**Comment by MJRLegends** [comment]
Sounds like your server files are missing stuff

**Comment by janmalte750** [comment]
Otherwise try to download the Mods from their official pages. I had my own server too, but i gave up because the Server crashed completely while using autocrafting on Me-System
