### ISSUE TITLE
SUGGESTION, mod with armor stands

### ISSUE THREAD

**Issue by convict-vx** [MJRLegends/Space-Astronomy-Feedback-#75]
I was building my factory / Space center, in my space center i would setup multiple launch platforms with all the rockets, just to show them off, on the opposite wall i would have setup all the armors that are possible to be created (call that room some sort of museum). But i came to the conclusion that there is no way to show of armors (besides itemframes), So i'm here with a suggestion, can u add a mod that adds armor stands (i know bibliocraft and travelers gear do this but they might add too much other stuff). So basically add an armor stands mod, a mod that only adds armor stands. Would be neat to have armor stands showing off all the armors from the pack and so i can complete my 'museum' too. :D

Greetings,

convictvx

**Comment by MJRLegends** [comment]
I will see what i can do
