### ISSUE TITLE
Crashes why trying to play

### ISSUE THREAD

**Issue by 1RRthenderman1** [MJRLegends/Space-Astronomy-Feedback-#750]
### ---Issue Report---
NO
### Description of Issue
When I try to open the game, it crashes without a report
### Steps to Reproduce Issue
1. Open the launcher with Curse and click play
2. Enter your world
**Crash log/Log (if applicable):** 
http://pastebin.com/Ayk95KLJ (all the game output) http://pastebin.com/VnYEGL5b (Launcher Log)
**Version of Mod Pack using:** 
1.5.8

**Comment by MJRLegends** [comment]
I need the crash log not half of full logs

**Comment by MJRLegends** [comment]
Check out this #705 and #693
