### ISSUE TITLE
I can't log in because it rejects me because of mods, but I am using the current version and there is no update available. Help? this is Space Astronomy 1 server #2

### ISSUE THREAD

**Issue by girly1** [MJRLegends/Space-Astronomy-Feedback-#751]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by zValus** [comment]
If you are using curse in it still do not have the update 1.5.9

**Comment by MJRLegends** [comment]
No need to make a issue you just need to be using the correct mod pack version
