### ISSUE TITLE
"Herobrine was here"  in SAG MILL

### ISSUE THREAD

**Issue by zValus** [MJRLegends/Space-Astronomy-Feedback-#752]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
[I was playing when suddenly appeared this message, I almost infartei at the time, is short of breath, please remove this not have the least grace it]
![2017-03-02_14 56 21](https://cloud.githubusercontent.com/assets/26147542/23520649/b587b746-ff5a-11e6-9009-0a0113da64ca.png)
]

### Steps to Reproduce Issue
1. [place SAG MILL in the world]
2. [wait]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [1.5.9]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Not a bug its easter egg in the mod
