### ISSUE TITLE
When I updated, it will crash if I try to play...

### ISSUE THREAD

**Issue by TyJNinja** [MJRLegends/Space-Astronomy-Feedback-#753]
I saw that space astronomy needed an update, so I updated it and tried to log on...but it would just give me a crash report...idk what to do about it...
![screenshot 1](https://cloud.githubusercontent.com/assets/26153334/23533603/ca0666a6-ff80-11e6-8e55-6ebf713a9d68.png)

**Comment by MJRLegends** [comment]
Not a mod pack bug, its a java/open gl bug so i cant do anything
