### ISSUE TITLE
Minecraft client freezes when opening quest book in multiplayer

### ISSUE THREAD

**Issue by Shusta34** [MJRLegends/Space-Astronomy-Feedback-#76]
Everything seemed fine (mining, using machines etc) until I attempted to open the HQM quest book, then the client freezes.

The server (and my client) I play on recently updated from 1.2.6->1.2.7. (quest book behaved in previous version)

The quest book appears to work properly in a single player world I created to check.
I've tried reinstalling the modpack (FTB Launcher) and updating Java, but as logging stops when the client freezes, I don't know what the issue might be.

http://paste.feed-the-beast.com/view/517722df

**Comment by MJRLegends** [comment]
There isnt anything in the log that would cause the freezing. Would you be able to get hold of the server version of the log?

**Comment by badgernz** [comment]
Hello, I am the owner of the server he is talking about, which part of the log do you require? The mod loading and when he freezes?

**Comment by MJRLegends** [comment]
Both if possible

**Comment by Shusta34** [comment]
I attempted to use my quest book at 12:03 (GMT) 14th Oct 2015, hopefully something will show up in the server log about that time.

**Comment by MJRLegends** [comment]
Ok i just need the server log from @badgernz

**Comment by badgernz** [comment]
Here is the startup log 
http://www.mediafire.com/view/q22ufmjrw1lrj8f/log.txt (githug didnt want to upload it)
and there is nothing in the logs when the player opens the quest book, just that they disconnected

**Comment by Shusta34** [comment]
The disconnect is probably because I used the 'Kill Minecraft' button on the FTB console to close my unresponsive client after waiting for a while (I've tried waiting a couple of times for 10min to see if the client would start to respond again with no success.)

My client logs appear to stop updating when the client freezes (used quest book immediately after logging onto the server ~07:42am, killed Minecraft about 10min later at 07:53).
http://www.mediafire.com/download/yvvnkpbj61f9oiy/fml-client-latest.log
http://www.mediafire.com/download/uomzwap21vvpliq/latest.log

No idea if it's relevant, but when my client is frozen, my Javaw.exe process (in Task Manager) still shows some signs of activity, going from 25% CPU to 30, 35, 50% before falling back to 25%, with allocated memory very slowly increasing over time.

**Comment by MJRLegends** [comment]
I not sure why this issue is happening
