### ISSUE TITLE
IGW crashing the game after doing a certain action

### ISSUE THREAD

**Issue by blah265** [MJRLegends/Space-Astronomy-Feedback-#760]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes.

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes.
### Description of Issue
After viewing an item from another tab, and attempting to press the back button at the top left whilst viewing an item from a different tab, the game will crash.

### Steps to Reproduce Issue
1. Press "I" to open the IGW.
2. View an item from the bottom two tabs (OpenModular Turrets or Compact Machines).
3. Go to "Blocks and Items" tab, and select an item.
4. Press the 'back' button at the top left, and crash.

**Crash log/Log (if applicable):** [Here](http://pastebin.com/MvFifQnb).

**Version of Mod Pack using:** 1.6.0

### Additional Information
This is most likely an issue with the individual mod (IGW)

**Comment by MJRLegends** [comment]
Im probably going to remove IGW as its buggy as hell
