### ISSUE TITLE
Crash when using a Flux-Infused OmniWench on a Energy-O-Mat

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-Feedback-#765]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
Crash when trying to using the Flux-Infused OmniWench on a Energy-O-Mat

### Steps to Reproduce Issue
1. place a  IC2 Energy-O-Mat
2. try to wrench it with a Flux-Infused OmniWench

**Crash log/Log (if applicable):** http://pastebin.com/ANh6HxDY

**Version of Mod Pack using:** 1.6.0

**Comment by MJRLegends** [comment]
Added to known issues
