### ISSUE TITLE
Change veinminer config to allow use on stone/dirt etc.

### ISSUE THREAD

**Issue by WilliamLC98** [MJRLegends/Space-Astronomy-Feedback-#77]
With the latest update now live on DeVco I was so excited that veinminer was added to the pack but became quickly disappointing when I realized you couldn't veinmine stone. This was after of course making an unbreakable pickaxe. Also I wouldn't decline to having some Iguana Tinker Tweaks but beggars can't be choosers.

**Comment by MJRLegends** [comment]
I will make the change for the next update
