### ISSUE TITLE
Oxygen bar do not show on Mercury

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-Feedback-#770]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes
### Description of Issue
oxygen bar do not show on Mercury
As seen here http://imgur.com/a/ZTMvl

I have two Heavy Oxygen Tank on me, and they are getting depleted

### Steps to Reproduce Issue
1. Go to Mercury
2. See there is no GUI

**Version of Mod Pack using:** 
1.6.0

**Comment by MJRLegends** [comment]
Reported to mod dev: https://github.com/SteveKunG/MorePlanets/issues/27

**Comment by MJRLegends** [comment]
Fixed in mod pack update v1.6.1
