### ISSUE TITLE
NEI Crash?

### ISSUE THREAD

**Issue by midgetviper** [MJRLegends/Space-Astronomy-Feedback-#772]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
When i open inventory/chest minecraft stops repsonding as soon as NEI loads.

### Steps to Reproduce Issue
1. [Open inventory]

**Crash log/Log (if applicable):** [http://pastebin.com/NCa0pe7i]

**Version of Mod Pack using:** [1.60]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Not enough detail and the crash log you have gave me isnt a crash log its like random part of the log
