### ISSUE TITLE
Feeding Soap Into a Washing Machine With a Hopper Crashes the Game

### ISSUE THREAD

**Issue by Blahflarah** [MJRLegends/Space-Astronomy-Feedback-#774]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] no
### Description of Issue
[Description of the issue]
Game crashed when I tried to put a stack of soap into a hopper that was feeding into a washing machine from MrCrayfishFurnitureMod v3.4.8. Now when I try to re-load the save it keeps crashing.

### Steps to Reproduce Issue
1. [First step] Place washing machine
2. [Second step] Place Hopper ABOVE the Washing Machine
3. [Third Step] Insert Stack of Soap
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**1.6.0:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You need to fill out all fields on the issue form as the information needed hasnt been supplied here

**Comment by Blahflarah** [comment]
[crash-2017-03-17_15.58.08-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/852096/crash-2017-03-17_15.58.08-server.txt)

**Comment by MJRLegends** [comment]
[PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
