### ISSUE TITLE
Scroll wheel doesn't work in Request Table (Logistics Pipes)

### ISSUE THREAD

**Issue by Bomave** [MJRLegends/Space-Astronomy-Feedback-#777]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

No, since this issue happend in the newest available update.

### Description of Issue

Since the newest available update (1.6.0) I cannot scroll in the Crafting Monitoring Upgrade for the Request Table (Logistics Pipes) anymore. I think it could be the mouse tweaker mod which got added in the version 1.6.0 of this modpack.

### Steps to Reproduce Issue

1. [First step]

Build a functional Logistics Pipes system and order something in the Request Table. The Request Table must have the Crafting Monitoring Upgrade.

2. [Second step]

There appears an icon on the left side of the Request Table interface if you order something. Click on it and click on the button "More". Now you see how the order is being delivered / crafted. If you now try to scroll out like I did in 1.5.8 of the modpack, it doesn't scroll out anymore.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

There's no crash log or something since it's probably just overlapping / overwriting the function of the scroll wheel of the mouse.

**Version of Mod Pack using:**  1.6.0

### Additional Information

It's nothing that has high priority and breaks the game in anyway. It's just something that's a bit annoying when you order a big recipe and you can't see the whole process without moving the screen of the interface.

I'm not sure if you're able to fix it but I'd really like to hear at least a response of you :-).

Thanks in advance!

Bomave

**Comment by MJRLegends** [comment]
i will take a look and get back to you

**Comment by Bomave** [comment]
Thank you for your response!

Another thing that I found out is that the "Rusty Hatch" from the new added mod Malisis is a bit buggy. I placed it incorrectly in a spot where it appereantly wouldn't work but then it placed only the frame of the hatch with no texture. When I broke the frame my game crashed. Do you want me to open a new issue for that?
