### ISSUE TITLE
Quest Book Malfunction

### ISSUE THREAD

**Issue by MU543** [MJRLegends/Space-Astronomy-Feedback-#778]
### ---Issue Report---
**Have you checked the Known Issues page: Yes, there is nothing on this issue

**Have you checked Closed Issues (yes)
Ok, so i had just completed the "ore berry bush" quest and it had no other web pointing me in a direction of a new quest, so I thought maybe that's it for alpha quest section but it still said 11% completed for the alpha stage.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
No Crashes
**Version of Mod Pack using:** [1.7.10]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Not a bug and there is other sections
