### ISSUE TITLE
Reika's mods causing client-side server dealy (if that makes sense)

### ISSUE THREAD

**Issue by Duodong** [MJRLegends/Space-Astronomy-Feedback-#78]
In my base, I have a somewhat dense room where all of my rotarycraft and reactorcraft machines are, and they've worked fine. After the 1.2.8 update, whenever I'm around the room, I get 999ms ping lag spikes, and my interaction with the world is delayed. As soon as I move away, I'm back up to a perfect connection, and this makes no sense to me.

**Comment by MJRLegends** [comment]
I will look at this later

**Comment by MJRLegends** [comment]
Please report this to the mod developer here https://github.com/ReikaKalseki/Reika_Mods_Issues
