### ISSUE TITLE
ComputerCraft issue

### ISSUE THREAD

**Issue by EndiDragon2956** [MJRLegends/Space-Astronomy-Feedback-#780]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
The game crashed because of something relating to computer craft

### Steps to Reproduce Issue
1. [Install the modpack manually ]
2. [add computer craft]

**Crash log/Log (if applicable):** [http://pastebin.com/u7rdiNSj]

**Version of Mod Pack using:** [1.6.0] (playing on 1.7.10)

### Additional Information
[I got the modpack by going to curse forge]

**Comment by MJRLegends** [comment]
Install the mod pack through a launcher and not manually
