### ISSUE TITLE
Reactor Controller not being recognized

### ISSUE THREAD

**Issue by aerozord** [MJRLegends/Space-Astronomy-Feedback-#781]
I built a small reactor, 3x3x3, with basic components.  Once it was completed it didn't form the multiblock.  I right clicked and got the error "Only reactor casing can be used on exterior of reactor" and coordinates of the faulty block.  The block it listed as the conflict was the reactor controller.  To test I removed the reactor controller, right-clicked and got the error message that I was missing a reactor controller.  

I attempted to place it again with no luck.  I restarted and the bug persisted.  Attempted to rebuild it, same error as well as when I built a 5x5x5.  Same issue, it says a non-reactor casing block is part of the structure and led me to the controller.

The reactor controller is never interactable during all this.  When I first made the multiblock I successfully did it once, and it changed to red, but upon reload I ran into the above issue.  If I remember correctly after accessing the controller that first time I shut down minecraft before actually placing fuel inside.

PS, another related issue and possible bug.  While building the larger reactor I thought I'd try reactor glass and I accidentally placed some inside and got the error message informing me.  I removed it but still got the error message.  Since I was concerned with the first bug I didn't try to reproduce the bug and its possible I simply missed a piece of it.  However I felt it was worth mentioning

**Comment by MJRLegends** [comment]
Please post pictures of your design layer by layer

**Comment by aerozord** [comment]
pictures were taken in creative mode.  I found the same issue in both modes
![2017-03-25_16 48 50](https://cloud.githubusercontent.com/assets/26673249/24326021/902def96-117b-11e7-9fda-c7910184227d.png)
picture of the front of the reactor
![2017-03-25_16 49 38](https://cloud.githubusercontent.com/assets/26673249/24326022/92dc0ae8-117b-11e7-9d90-690a9062e5d6.png)
Top section as seen from above
![2017-03-25_16 49 51](https://cloud.githubusercontent.com/assets/26673249/24326024/94e5b5dc-117b-11e7-87fb-7fb9fff8fa88.png)
Middle as seen from above
![2017-03-25_16 50 03](https://cloud.githubusercontent.com/assets/26673249/24326025/96a2c9aa-117b-11e7-81e2-755bde415149.png)
bottom as seen from above

**Comment by MJRLegends** [comment]
![image](https://cloud.githubusercontent.com/assets/8526321/24327131/581abb10-11b8-11e7-9238-5a4a93ab60ea.png)
These blocks can be on the corrers
