### ISSUE TITLE
In-game Crash - 1.6.0

### ISSUE THREAD

**Issue by DrDerpy16** [MJRLegends/Space-Astronomy-Feedback-#782]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [To the best of my abilities]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [As above]
### Description of Issue
[I crash, and go back to either the launcher, or straight to curse, and t whenever I attempt to move, open my inventory, or anything of that sort. I load into the world, and can only look around.]

### Steps to Reproduce Issue
1. [NaN]

**Crash log/Log (if applicable):** [I am unable to use pastebin as the log is over the limit, and I'm not pro. I'll just provide a download, and if you don't want to use it, just notify me of that fact.]
https://mega.nz/#!6sZBHYQb!Q6cSGuomnCpLAEtbvSBVHOoT-5NvQ_ZXcZ6rHLljrcU
**Version of Mod Pack using:** [1.6.0/Latest]

### Additional Information
[I tested it on a singleplayer world, and it lead to the same results.]

**Comment by MJRLegends** [comment]
Your log doesnt contain any crash at all????

**Comment by MJRLegends** [comment]
i will reopen if you can give me more information on this issue :P

**Comment by DrDerpy16** [comment]
I might have gotten the wrong log, as I'm clueless on how to actually GET crash logs with the terrible new launcher... Any chance you could explain how to get the crash logs? I have no problem recreating it :/

**Comment by MJRLegends** [comment]
It should be in a folder called 'crash-reports'

**Comment by DrDerpy16** [comment]
I don't see it?

**Comment by MJRLegends** [comment]
ok do you know how to get to the folder where the configs and mods folders are?

**Comment by DrDerpy16** [comment]
Yea, I'm at it right now. There's no crash reports folder, as you can see below
![image](https://cloud.githubusercontent.com/assets/18634587/24327239/9dba12dc-1191-11e7-88b3-94fcf061d092.png)

**Comment by MJRLegends** [comment]
ok then it didnt crash...

**Comment by DrDerpy16** [comment]
Odd, I can record my screen and upload it to mega as a .mp3 or something, as it DOES crash minecraft and tells me that mc crashed

**Comment by DrDerpy16** [comment]
Sorry for taking so long, had to reinstall my recorder, and do it a second time as I was in a skype call the 1st time....
https://mega.nz/#!u9o1Ub5S!2-_IomQMwInMAKtOpu3nrGTy0J-VMsJSmRP-dfZPFQw

**Comment by DrDerpy16** [comment]
Apparently decided to start working again, sooo.... closed.
