### ISSUE TITLE
1.6.1 Resource Folder Empty & Auto Server adding mod not working

### ISSUE THREAD

**Issue by Boskosauce** [MJRLegends/Space-Astronomy-Feedback-#785]
You guys forgot to export the resources folder when preparing the update. The menu background image is not showing up and the resources folder is empty.

![untitled](https://cloud.githubusercontent.com/assets/4279112/24387858/720cdc9a-132c-11e7-8e36-631a78388dc9.png)

**Comment by truecrusader** [comment]
I have the same problem.

**Comment by MJRLegends** [comment]
Yeah i will fix it dw another update will be out soon

**Comment by MJRLegends** [comment]
@truecrusader also thank you, its because pastebin has started using https now :D will be fixed in v1.6.2
Also the official servers are running v1.6.0 anyways :D

**Comment by MJRLegends** [comment]
V1.6.2 is out fixing both of these
