### ISSUE TITLE
Machinemuse power armor

### ISSUE THREAD

**Issue by durdee253** [MJRLegends/Space-Astronomy-Feedback-#787]
Hi I'm playing on the most recent version and none of the machinemuse's items are crafting for me. I am playing on a lan from another computer... That computer was able to craft and everything works fine.. but for me it shows in the nei but when I click it it does not give me the recipes. I have checked to see if I can just place the items in a table to craft but it doesn't work. Also checked the config file and it shows the ic2 and thermal recipes in the folder... Any help would be much appreciated.

**Comment by MJRLegends** [comment]
If it works on one of your systems then please reinstall your pack, as if it works on one but not the other the mod pack version hasn't got the issue.

I will reopen if you confirm both your computers have the issue :)

**Comment by MJRLegends** [comment]
Also try delete the nei folder in your saves folder, but a reinstall of mod pack should be fine

**Comment by durdee253** [comment]
Will I lose my progress?

**Comment by MJRLegends** [comment]
Not if you make a copy else where of your saves

**Comment by durdee253** [comment]
This did not work :(

**Comment by durdee253** [comment]
Ok so just to follow up... The nei is not showing recipes for the tinker table.. I tried the above things... And finally I manually put the recipe in for it.. it did not show it in the crafted box but I clicked the empty box and it did craft it... I checked the other machinemuse's items and they are all doing the same.  It's no problem for now but is there a solution to this?
