### ISSUE TITLE
OpenFM buggy as hell...

### ISSUE THREAD

**Issue by Bomave** [MJRLegends/Space-Astronomy-Feedback-#788]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

Mod just got added in 1.6.1

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

Mod just got added in 1.6.1

### Description of Issue
OpenFM is very buggy. It doesn't play most radios. It crashes the game. It freezes up the game. It doesn't let you connect to the server after the crash ect...

### Steps to Reproduce Issue

1. [First step]

Paste links in the radio and play it.

2. [Second step]

See what happens. Reconnect to the server might crash your client. Clicking play might crash your game.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

https://pastebin.com/Xp3Ki58d

**Version of Mod Pack using:** [VERSION]

1.6.2

### Additional Information

This mod is basically a really cool idea but it doesn't work. It crashes the clients and won't let them connect again. Better remove it if there won't be any serious fixes.

**Comment by MJRLegends** [comment]
I need more information of what your setup is and how and what you were doing, maybe even pictures?

**Comment by Bomave** [comment]
I'm trying to figure out when something unpredictable happens. I had to rollback a backup yesterday because my friend and me couldn't connect to the server anymore.

What I did now was to just put this link "http://streaming214.radionomy.com:80/ABSOLUTEROCKRADIO" into the radio and click play. It froze my client up for a few minutes until it worked again but then there was no music. I then disconnected and tried to connect to the server again to see if that helps in any way but it took my client way longer to connect to the server than usual. When I finally connected there was no music playing but the play button was a square which would mean it's playing the radio / music but it's not.
Then I just clicked on the square which would stop the music and clicked the play button again. My client froze up a few minutes again.
Then I tried another radio "http://mutualbroadcast.com:8010/listen". This time it worked really well. It didn't freeze, played music and I could disconnect and connect without delay.
Then this radio "http://radyoizmirfm.radioca.st:80/streams/64kbps?yp=2" froze my client again for a few minutes. When my client worked again the play button became a square but I didn't hear any music. I then clicked the square button and it crashed my client, leaving that message in the server consol: 

https://pastebin.com/66QL4iEJ

After starting my client again, I connected to my server again and hit the play button. It froze my client again for around two minutes and the play button became the square again. I clicked the square button and this time it didn't crash my client. I clicked on the play button again and it froze up again for a few minutes until the play button became the stop (square) button. I then disconnected and tried to reconnect but it took my client way longer again to connect. When I was on the server the radio showed the stop button again but I didn't hear any music.

I tried a few other radios and they all surprisingly worked. I have no idea why it sometimes works and then it doesn't. Before it happend the first time we had just updated the server completely fresh and only kept the world folder and the server.properties. This time we did just the same. There's no difference from yesterday to today other than my teammate wasn't online today.

This is the set up:

![screenshot 2017-03-29 14 07 25](https://cloud.githubusercontent.com/assets/1887372/24453659/132df50c-1489-11e7-883d-fa2e927bc487.png)

The 10th speaker is a few blocks away. I picked the speaker up again to see any differences. When I checked the radio, I couldn't switch between the play and the stop button. It only showed the play button. Then I disconnected and connected to the server again and it took the client longer again to connect. When I checked the radio it showed the stop button again.

----------------------------------------------------------------------------------------------------------

These are my testing results. This time it wasn't as catastrophic as yesterday when nobody could connect anymore and I had to rollback a backup but it still has it's flaws. I hope my testing helps in any way!

**Comment by MJRLegends** [comment]
Open FM is being removed in the next update (v1.6.2) thanks for your issue report :P
