### ISSUE TITLE
Mod Request: Backup Mod

### ISSUE THREAD

**Issue by Bomave** [MJRLegends/Space-Astronomy-Feedback-#789]
Since this is a modpack where many things can go wrong and you wouldn't like your world to be corrupted or something bad happening like a random explosion from a nuclear reactor or something like that, how about a mod that automatically backs up your world periodically?

On curse I found several mods for that and the most downloaded one is the [AromaBackup.](https://mods.curse.com/mc-mods/minecraft/225658-aromabackup#t1:description) Here are the features I copied from Curse:

-Scheduled Backups
-Backups by executing a command
-Backups on world load
-Delete old backups

-A way of automatically restoring backups in SP.

-----------------------------------------------------------------------------------------------------------

For a different backup mod you can use this link https://mods.curse.com/search?game-slug=minecraft&search=backup#t1:mods

Thanks in advance!

Bomave

**Comment by MJRLegends** [comment]
You can add one to use theres no need for one to be in the pack by default
