### ISSUE TITLE
Going to the End. the quest don't work

### ISSUE THREAD

**Issue by mnemoshack** [MJRLegends/Space-Astronomy-Feedback-#79]
the quest book say collect 32 End stone, 10 Ender-Lily seeds and 10 Ender Pearls on the left side 
of the quest book but on the right it's say only 25 End stone.. but if you got 25, 32 even 10 stack 
you can't finish the quest i dont no what's happen with it.........

**Comment by MJRLegends** [comment]
i will sort for the next update
