### ISSUE TITLE
crashing when i enter my singleplayer world

### ISSUE THREAD

**Issue by zaza12uae** [MJRLegends/Space-Astronomy-Feedback-#790]
### ---Issue Report---
[crash-2017-03-30_19.12.03-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/882874/crash-2017-03-30_19.12.03-server.txt)

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes
### Description of Issue
so what happens is that i can enter my launcher and i can enter the game when it launches but my singleplayer world keeps crashing whenever i try to enter
[crash-2017-03-30_19.12.03-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/882879/crash-2017-03-30_19.12.03-server.txt)

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** 1.6.2

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
_**Crash log/Log (if applicable): [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]**_
