### ISSUE TITLE
Unable to find Server Files

### ISSUE THREAD

**Issue by Kaytrox** [MJRLegends/Space-Astronomy-Feedback-#791]
### ---Issue Report---
**Have you checked the Known Issues page:** Yes]
**Have you checked Closed Issues:** Yes
### Description of Issue
There are no accessible links to any version of the server files.

### Steps to Reproduce Issue
1. Open modpack pages
(https://mods.curse.com https://forum.feed-the-beast.com https://minecraft.curseforge.com http://www.minecraftforum.net) <--- no full links on purpose, I checked the according pages of this modpack on these websites
2. Search for Server File Download
3. Don't find them.

**Crash log/Log:** 
Can't crash if you don't have it!

**Version of Mod Pack using:** 
All/not bound to version

### Additional Information

Can you please make the server files more available?
I really enjoy this modpack, so do some of my friends.

And yes, I know that there are no server files for 1.6.2 yet (see change log).

If I didn't know better, you are making it very hard to find/even get these files on purpose, as I somehow found 1.6.0 one or two weeks ago. And simply replacing mods + config gives me resource loader errors. [from 1.6.0 to 1.6.2]
("Caused by: java.lang.NoClassDefFoundError: Llumien/resourceloader/loader/NormalResourceLoader;")

So, after about 1 hour of searching I've given up.
Now I want to ask you to make the download links more accessible, at least a "Server files download" spoiler on the above mentioned sites would be nice.
Because I do not enjoy playing on public servers at all and rather not play than using them.

I really hope that you read this and realize how hard it is to find the download links (If they even exist) :(
And please don't ignore it and say there are downloads available. 
Just because it is obvious to find them for you, because you created them (or not), doesn't mean that others will find them if they are not even mentioned on any modpack related pages on the internet.

Hope you appreciate this and put the links on your sites. 
Cya

**Comment by MJRLegends** [comment]
All you have to do is look on the main menu of the mod pack where the single player and that buttons are

**Comment by MJRLegends** [comment]
Even says that on curse and that too

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/0b5e9860a6cc5b767af643dad00021db.png)
![](https://i.gyazo.com/5fd429530b4155aa718c6a74ed7fb16b.png)
