### ISSUE TITLE
Server disconnected me in space, now I can't rejoin my Space 1

### ISSUE THREAD

**Issue by itsfrankiemay** [MJRLegends/Space-Astronomy-Feedback-#795]
I have searched around for the solution but I can't find out what's wrong. I can join the server, but as soon as I try joining Space 1 from the hub it crashes and I get the message;
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Could not get provider type for dimension -38, does not exist
The server crashed and disconnected me while I was floating in space.

**Comment by MJRLegends** [comment]
Use th3 direct ips as it says in the hub
