### ISSUE TITLE
Recipe conflict of ball of moss and compressed mossy cobble

### ISSUE THREAD

**Issue by vrrajesh21** [MJRLegends/Space-Astronomy-Feedback-#798]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes] 

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
[Tinker's Construct Mossy Cobblestone has the same recipe as compressed mossy cobblestone.]

### Steps to Reproduce Issue
1. Try to craft Tinker's Construct Ball of Moss with mossy cobblestone only
2. Instead, it gives you compressed mossy cobblestone

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [V 1.6.2]

### Additional Information
[Only tested in TC crafting table]

**Comment by MJRLegends** [comment]
Will be fixed in v1.6.3

**Comment by vrrajesh21** [comment]
Thanks for getting back so quickly!

**Comment by MrSkeleguy** [comment]
Thanks, that'll help a lot!
