### ISSUE TITLE
More Planets Iridium Block 

### ISSUE THREAD

**Issue by BrotheBear** [MJRLegends/Space-Astronomy-Feedback-#800]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue

Used induction smelter to double more planets iridium ore with sand, and it produced Advanced Solar Panels iridium, which can't be used to craft an Iridium block which is used for the T8 rocket boosters. 

**Version of Mod Pack using:** 1.6.2

### Additional Information
Solved for now by smelting the iridium ore to make more planets iridium.

**Comment by MJRLegends** [comment]
Fixed in v1.6.3

**Comment by MJRLegends** [comment]
Will be fixed in v1.6.3

**Comment by Maxo11x** [comment]
Alternatively for now you can craft a Mekanism oredictionificator to swap between the two without any energy
