### ISSUE TITLE
Small lag spikes leading to large ones

### ISSUE THREAD

**Issue by SergeantDeppen** [MJRLegends/Space-Astronomy-Feedback-#801]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue Yes
The world saving seems to get longer which I understand it needs to save more but along with the saving and just at random times there are some very bad lag spikes. I just thought I would say somthing not to seem like a burden but so you know.

**Version of Mod Pack using:**
1.7.10

**Comment by MJRLegends** [comment]
No where near the information required
