### ISSUE TITLE
Ticking memory connection

### ISSUE THREAD

**Issue by jed95** [MJRLegends/Space-Astronomy-Feedback-#802]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
To do with ticking memory connection according to crash report, game just randomly crashed along with my entire computer, tried to restart game and when loading my world, it would go onto the loading screen then back to the title screen. Tried loading other worlds and it would do the same. Also with creating a new world it would do this.
Tried reinstalling and the game ran with a new world, however when trying to load my world backup it would do the same and now i cannot load any of the worlds once again.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** 
https://pastebin.com/RaN05AHu

**Version of Mod Pack using:** 1.6.0

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Your using a old pack version? Please update

**Comment by jed95** [comment]
Updated the pack version and the issue still persists? Also once i load my backup its like it corrupts the entire pack so that nothing else can be played, ie i cant create a new world or anything, the world will go to loading screen and then just straight back to the title screen
