### ISSUE TITLE
missing mods off of curse website .zip download

### ISSUE THREAD

**Issue by djthekiller321** [MJRLegends/Space-Astronomy-Feedback-#803]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
the curse zip folder is missing several mods which are needed

### Steps to Reproduce Issue
1. install modpack off of curse website
2. run the game

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [1.7.10]

### Additional Information
no

**Comment by MJRLegends** [comment]
No they are not missing check any other pack its the same as you need to use a launcher to get the pack

**Comment by djthekiller321** [comment]
ok i was posting this and hit the button too soon, and my launcher was not actually downloading the profile, 
sorry for bugging you 
-top of the day to you sir
Dustin
