### ISSUE TITLE
World wont load but doesnt crash game

### ISSUE THREAD

**Issue by jed95** [MJRLegends/Space-Astronomy-Feedback-#804]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue

Updated the pack version and the issue still persists? Also once i load my backup its like it corrupts the entire pack so that nothing else can be played, ie i cant create a new world or anything, the world will go to loading screen and then just straight back to the title screen

### Steps to Reproduce Issue
1. Complete clean install of the pack
2. load backup into pack and it happens again

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** 1.6.2
### Additional Information
Got a crash report when it intially happened but now it doesnt crash just will never load the files, please help? Crash report is located in the closed issues tab - under ticking memory connection

**Comment by MJRLegends** [comment]
Not even information provided, i need logs, screen shots of things like errors if there is any...

**Comment by Xdevon64** [comment]
No error code/s appear man, mine doing the exact same thing..
All I did was update windows and my GPU drivers. Then I loaded this modpack, got in my world, for it to then crash my computer. When I rebooted and tried reloading, nothing just back to the modpack main menu. I try any of my other saves their gone too.. I try any back-up's the same as well.. can't create new world's... This is a pack problem not just one mod!!!!!

**Comment by Xdevon64** [comment]
Actually I take that back I think its enderstorage....
![screenshot 2](https://cloud.githubusercontent.com/assets/27756250/25164047/e22cd6b4-2511-11e7-9009-b3a2abc99112.png)

**Comment by Xdevon64** [comment]
![screenshot 4](https://cloud.githubusercontent.com/assets/27756250/25164162/8508ff70-2512-11e7-886a-e05e1e62ed2a.png)

**Comment by Xdevon64** [comment]
yep enderstorage disabled it and problem solved hahaha

**Comment by jed95** [comment]
Ahh nice, cheers bro! I'll give that a try and see if it fixes it!
