### ISSUE TITLE
Data Backup is being used, by the Forge Mod Loader. I can't create a backup file.

### ISSUE THREAD

**Issue by Ribez97** [MJRLegends/Space-Astronomy-Feedback-#808]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
Mod loader works and i get to save page, but when i try to open my world it says:"FORGEnODLoader has detected that the backup level.dat is being used, create a world backup efore continuing.
### Steps to Reproduce Issue
1. [First step]Start Minecraft Space Asrtonomy 1.7.10
2. [Second step]Open the saved world

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]
1.7.10

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Means your world is corrupted, you need to start a new one
