### ISSUE TITLE
Crashes when trying to mine certain blocks.

### ISSUE THREAD

**Issue by CompleteGarbage** [MJRLegends/Space-Astronomy-Feedback-#810]
### ---Issue Report---
**Have you checked the Known Issues page:** Yes.

**Have you checked Closed Issues:** Yes.
### Description of Issue
When attempting to destroy an inverted lamp slab, the game crashes and disconnects the player.

### Steps to Reproduce Issue
1. Place a lamp slab in SP.
2. Try to break that slab.

**Crash log/Log (if applicable):** The twitch launcher was being very unkind to me, and when I tried to click 'view crash report,' nothing happened. Here's what I got from the details box: https://pastebin.com/AKEC2K1y

**Version of Mod Pack using:** [1.6.2] for MC Def [1.7.10]; Forge Def [10.13.4.1614].

### Additional Information
This may apply to other blocks as well, but I didn't have the patience to try it more than twice.

**Comment by MJRLegends** [comment]
Your crash log you have provided isnt a crash log. Please supply the full crash log

**Comment by CompleteGarbage** [comment]
I am aware. As I pointed out, after the crash, the launcher window failed to properly respond. I'll try again now, if you want.

**Comment by CompleteGarbage** [comment]
Nevermind, found full log within commons, here. https://pastebin.com/JTL4DLvW
@MJRLegends

**Comment by WalaoEgg0424** [comment]
@CompleteGarbage what did you used to break the inverted lamp slab?

**Comment by MJRLegends** [comment]
Unable to solve due to the lack of information on the issue sorry, please post more information of what you was doing as @WalaoEgg0424 said above and i will reopen the issue
