### ISSUE TITLE
crash when loading world and no crash log

### ISSUE THREAD

**Issue by Anasboko** [MJRLegends/Space-Astronomy-Feedback-#813]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION] 1.6.2

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Nothing i can do if you dont give me any information lol i cant work magic

**Comment by Anasboko** [comment]
ill have to try and reinstall and see if it fixes

ill also backup my save : )


2017-04-11 17:39 GMT+01:00 MJRLegends <notifications@github.com>:
