### ISSUE TITLE
Can't Create a World

### ISSUE THREAD

**Issue by haz24hd** [MJRLegends/Space-Astronomy-Feedback-#814]
I click create world but it loads for 30 seconds and then just takes me back to the main menu screen and it still isn't in the single player menu.

**Comment by Bomave** [comment]
MJRLegends can't help if you're not specific enough. Do you have any error messages in the game or in the consol? What are your pc specifications? Have you tried to reinstall your client?

**Comment by MJRLegends** [comment]
^^^
