### ISSUE TITLE
I saw that i could not get emeralds in this modpack so i saw that i still could get it with scrap. but when i build mechinist's workbench i saw that it was not in the modpack even if the other things in the mod was there. disabeld?

### ISSUE THREAD

**Issue by Hejrobin1** [MJRLegends/Space-Astronomy-Feedback-#815]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Emeralds are in the mod pack and others are not a bug either.
