### ISSUE TITLE
Parachute won´t get off 

### ISSUE THREAD

**Issue by ItzSarius** [MJRLegends/Space-Astronomy-Feedback-#817]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by ItzSarius** [comment]
I can´t unequip it.

**Comment by MJRLegends** [comment]
@ItzSarius Please can you fill out the template above as i would like to report this to the dev but your haven't provided enough information on the issue. I cant reproduce the issue so i need your detailed information on it and what you was doing and where you were and what you have on like jetpack, genes, amour, etc

**Comment by MJRLegends** [comment]
Fill out the issue and i will reopen
