### ISSUE TITLE
Bug of launcher

### ISSUE THREAD

**Issue by Hellbrumes** [MJRLegends/Space-Astronomy-Feedback-#819]
### ---Issue Report---
Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
My laucher are invisible so i can't start the game
[Description of the issue]

### Steps to Reproduce Issue
1. I have download of the stuff
2. i click on Play and the launcher load but it steel invisible

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION] 1.6.0 but it's do the same thing for oser version

### Additional Information
i have already redownload the pack , the 2 version of java (32-64) .

**Comment by MJRLegends** [comment]
Contact the launcher support team

**Comment by Hellbrumes** [comment]
but how ?

**Comment by MJRLegends** [comment]
Curse launcher:
https://support.curse.com/hc/en-us

FTB Launcher: 
https://www.feed-the-beast.com/support
