### ISSUE TITLE
Big Reactor Quest Issues

### ISSUE THREAD

**Issue by TLomon** [MJRLegends/Space-Astronomy-Feedback-#82]
Really enjoying playing the mod pack and wanted to thank you for the hard work that you are doing. Just downloaded the newest update, and noticed some strangeness on the Big Reactor quests.

* Starting Big Reactors. Quest works fine. Seems appropriate for introducing it. Great quest.
* Upgrading Reactor: Due to crafting requirements, step discourages reusing components from original reactor. Perhaps change to detect, rather than craft? Also, an implied second step is missing. How to make the liquid Resonant Ender. Perhaps add the requirements for Magma Crucible and a Fluid Transposer. I used these to melt down extra Ender Seeds I had, which seemed to be the most efficient. Also, 20 buckets of Resonant Ender is a bit much to have at once (I ended up melting down a ton of buckets at end). Perhaps have this step be the crafting step?
* Upgrade to Actively Cooled: This is where the real problems started. It states you need a wrench. Perhaps have that be a detected item to show that it truly is needed. Two reactor coolant ports makes perfect sense. Then, the strangeness. Two Transfer Nodes (Liquid) - unexpected, but doable. Then, 128 world interaction upgrades and 320 speed upgrades? That is 896 iron, 512 lapis lazuli, 2880 redstone dust, and 186 gold ingots with 6 nuggets. The problem is, none of these items are needed in the slightest. It is a huge waste of resources, and honestly, when I realized this, I just cheated my way through that part of the quest after making the first 100. These were made using the Molecular Assembler and did not count towards completion. Due to the shear number, automation may be expected, but the quest step should be changed to detect, not crafting. I will explain my hookup in detail below.
* Recycle the Waste. Quest works fine. Appropriate area for introducing it. Great quest.
* Starting a Basic Turbine. Replace the Reactor Glass with Turbine Glass.

When setting up the reactor, I built the turbine adjacent to the new reactor, with the cooling ports aligned to each other. I let an opening near one of the ports, so I could hook up a pipe and fill the reactor with water to capacity. I then finished placing the final cooling port and missing framework, and turned it on. No pipes are needed in the finished construction as the system is a closed cooling system, and the hundreds of upgrades that we needed to craft were not used at all.

Please let me know if you need any additional information.

**Comment by MJRLegends** [comment]
I will use your comments to make changes for the next update :package: 
Thanks
