### ISSUE TITLE
Sorry but how can i contact the launcher support team ?

### ISSUE THREAD

**Issue by Hellbrumes** [MJRLegends/Space-Astronomy-Feedback-#820]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Stop making new issues ffs, it's not my bug!

**Comment by Hellbrumes** [comment]
ok no prob but how can i solved it if i don t now how to contact the launcher support
