### ISSUE TITLE
Problems with keybinding in certain mods

### ISSUE THREAD

**Issue by Maxo11x** [MJRLegends/Space-Astronomy-Feedback-#821]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
Problem with the keybinds on both Mekanism and Simply Jetpacks. Basically the keys used to switch modes in these modpacks along with all other key stuff found in the controls section of the option menu have no effect in game and nothing happens when pressed.

I have only had problems with these modpack configurations but it could be further. I have also consulted with a friend who freshlly downloaded the modpack and instantly had the exact same issue with these mods.

### Steps to Reproduce Issue
1. download
2. new world
3. give self a "simply jetpack" leadstone jetpack
4. try switching modes from normal to hover, or even try to turn off
5. attempt to fix by changing keys, find out it still doesnt work

**Crash log/Log (if applicable):** No crash report produced

**Version of Mod Pack using:** 1.6.2 (current)

### Additional Information
seems to be an old bug as has been happening since I first downloaded the game about half a year ago, I just finally uploaded this because I got too annoyed when my scuba gear didnt work (I thought it was a known issue, then I just checked).

**Comment by MJRLegends** [comment]
You can change them via controls menu on pause

**Comment by Maxo11x** [comment]
I changed them and it still did not work.
