### ISSUE TITLE
RESOLVED: Cannot pick up items in inventory - left or right clicking drops item on the ground

### ISSUE THREAD

**Issue by Werns** [MJRLegends/Space-Astronomy-Feedback-#825]
RESOLVED

### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
Whenever I click on an item in my inventory, right or left click, it gets dropped on the ground instead of being "picked up".

### Steps to Reproduce Issue
1. Load the game
2. Acquire an item (i.e. punch a tree)
3. Open inventory and click on the item, which gets dropped on the ground instead

**Version of Mod Pack using:** [1.6.2 - Current as of writing]

### Additional Information
Fresh install of the mod pack, never used it before. Went through and tried to change keybindings, but nothing was changing left mouse or right mouse.

**Comment by Werns** [comment]
Okay, I quit to the main menu and reloaded the world, the issue went away. I have no idea why that happened, but it's probably a good idea to keep this here in case anyone else gets this problem and can't solve it.

**Comment by MJRLegends** [comment]
I think this was a one off minecraft derp so i will close it and if someone does mention it i will reopen it
