### ISSUE TITLE
UU matter, paper cost 3074b 

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-Feedback-#827]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
When you scan paper in a IC2 scanner, it shows  that it need 3074b with  around 7000% more then what it require for a diamond (44.41mb) 

### Steps to Reproduce Issue
1. Scan paper 

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** 1.6.2

### Additional Information
Have not check if paper is the only one

**Comment by Spellkaze** [comment]
Not a bug, is intended by the IC2 devs for people to not use the uu matter to get everything, like iridum costing 120mb uu matter and wool 680,4mb. in a way is a method to make people less dependant of uu matter, they could help for iron, diamond or other stuff, but some things you better gather it by other ways. Also, is _3,074 B, which is 3 buckets and a bit,_ of uu matter. As an example, making one single book on uu matters costs 9 buckets, or 9,291 B
