### ISSUE TITLE
Ingame spawnpoint crash'es my client

### ISSUE THREAD

**Issue by gunnerzombie666** [MJRLegends/Space-Astronomy-Feedback-#832]
### ---Issue Report---
Ingame spawnpoint crash my client
### Description of Issue
When i enter Space3 server, my Fps goes to 0, and i cant do anything..

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** Space Astronomy version 1,6,2

### Additional Information
Set my spawnpoint to the game's original start spawn point, and its solved...tryed this before...

**Comment by MJRLegends** [comment]
Why are you reporting a bug with very little detail and no crash log?
