### ISSUE TITLE
No Wither Skeletons in any Fortresses

### ISSUE THREAD

**Issue by jaz-programming** [MJRLegends/Space-Astronomy-Feedback-#834]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
There are no Wither Skeletons spawning in any Fortresses

### Steps to Reproduce Issue
1. /rtp in the nether
2. find a Nether Fortress
3. Look for Wither Skeletons

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [1.6.2]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Not a mod pack issue
