### ISSUE TITLE
buildctaft builder is crashing the server every time i give it power

### ISSUE THREAD

**Issue by leefield1** [MJRLegends/Space-Astronomy-Feedback-#836]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes 

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [No]
### Description of Issue
when powering the bc builder . the server crashes

### Steps to Reproduce Issue
1. when I log back in after placing it,, it crashes straight away..
2. same thing happened yesterday but after a few attemps my builder lost supplied power.. so did not crash until I powered it again today

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Dont power it then...

**Comment by leefield1** [comment]
when is it safe to relog?

**Comment by MJRLegends** [comment]
#838
