### ISSUE TITLE
Space Astonomy of the crash

### ISSUE THREAD

**Issue by ZEROZEROZE** [MJRLegends/Space-Astronomy-Feedback-#837]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):
** [Yes ]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):
** [Yes]

### Description of Issue
[Crash after entering Deep Dark ]

### Steps to Reproduce Issue
1. [First,i want to go Deep Dark]
2. [Then,the minecraft suddenly crash]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [1.6.2]

### Additional Information
[The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Could not get provider type for dimension 106, does not exist]

**Comment by MJRLegends** [comment]
I cant fix it is you dont give me any information?? crash log??

**Comment by ZEROZEROZE** [comment]
At that day, i went to deep Dark in the official servers of Space 1.
When it was loading , suddenly the game crashed .
After that , i entered to official servers of the Space 1 
At last , it crashed again x n times
PS: The server ip is play.mjrlegends.co

**Comment by MJRLegends** [comment]
Them servers are closed
