### ISSUE TITLE
Parachute Stuck Permenatly

### ISSUE THREAD

**Issue by Kuhi99** [MJRLegends/Space-Astronomy-Feedback-#843]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):**  Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
Parachute Stuck Permantly

### Steps to Reproduce Issue
1. Add thermal suit
2. Put on parachute

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION] 1.6.2

### Additional Information
My Parachute is stuck on me permenatly i even when i take it off it is still there preventing me from jumping
Also the parachute stays on across worlds, like its stuck on me on my server and singleplayer

**Comment by Kobatz** [comment]
I fixed mine by updating galacticraft to the latest version. (While running 1.6.2.)

**Comment by MJRLegends** [comment]
Update to v1.6.3
