### ISSUE TITLE
Game Crash at Loading Screen 7 weeks in. Please Help!

### ISSUE THREAD

**Issue by SpaceNaught** [MJRLegends/Space-Astronomy-Feedback-#844]
I have been playing the game (v1.6.2 Space Astronomy) for quite a while now without any issues. After about 7 weeks of playing, I keep crashing trying to load my world. It began crashing suddenly during gameplay and I have tried turning off certain mods but nothing has worked. I scoured the web for a solution to this crash, but I am not quite sure what to look for as the crash logs are all different. Any help would be much appreciated. The first crash report is linked below. Let me know if there is any other information you may need. Thank you in advance!

https://pastebin.com/FZ1jnFp7

**Comment by MJRLegends** [comment]
Your world is corrupt
