### ISSUE TITLE
Crash when loading world. 

### ISSUE THREAD

**Issue by Kobatz** [MJRLegends/Space-Astronomy-Feedback-#845]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yezir

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yeza
### Description of Issue
Game crashes after loading up the world. Never had an issue with not loading the world till after 1.6.3 was released but maybe something broke last time I saved.

### Steps to Reproduce Issue
1. Load client
2. Load world
3. Crash before spawn
4. ???
5. PROFIT?

**Crash log/Log (if applicable):** https://pastebin.com/gUg2Smhe

**Version of Mod Pack using:** 1.6.3 (Tried on 1.6.2 also.)

### Additional Information
Running a couple extra mods but haven't had issues with them. 
Electric Age v1.7.10
IGWMod v1.1.12-34
MCA v1.7.10-5.2.2
RadixCore v2.1.3

Probably try fiddling around with some of the mods and see if my backups are broken. Dunno how to read crash logs so getting pointed in the right direction would be appreciated. (Guessing if its world corruption I should try to load an old backup.)

**Comment by MJRLegends** [comment]
@Kobatz Please check the known issues before posting as this one and your other one are both on there, and this one even has a fix on there

**Comment by Kobatz** [comment]
Where do I find the solution? 34 pages of closed issues.

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/1280563c9fc13821980ca4d9b40e6532.png)
