### ISSUE TITLE
Re: Crash when loading world.

### ISSUE THREAD

**Issue by Kobatz** [MJRLegends/Space-Astronomy-Feedback-#847]
(Couldn't reply to the old issue so here is the continuation.)

### ---Issue Report---
[https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/845](url)

### Additional Information
Still happening even after trying both solutions. Once I put in the HV/LW Wire Cables and the posts the issue would come back. I tested that after removing the mod saving then re-enabling it and was able to reload the world a few times but after I had put those items back onto my machines it broke again.

I did notice that with this update if the posts are close enough together it auto connects them while in the older version you had to manually wire them. 

Those wires and the posts were the only thing I put back into the world as I use those as power transfer RF->RF and RF->EU. Was IE and the extensions updated to the latest version? I might check if maybe one of the machines connected are causing the issue.

**Comment by MJRLegends** [comment]
You need to remove IE mod, please dont make more issues about a known issue

**Comment by Kobatz** [comment]
Is immersive engineering not compatible with the modpack anymore? When I updated it came with the pack.

**Comment by MJRLegends** [comment]
Yeah it's comparability just follow the fixes on the last issue you made as they work
