### ISSUE TITLE
mod issue

### ISSUE THREAD

**Issue by koolcat200** [MJRLegends/Space-Astronomy-Feedback-#848]
### ---Issue Report---
i am making a modpack for friends and i added the mod that you published and i would like to know if there is a way to re enable the vanilla tools. if it is not your mod i would love it if you could tell me what mod it is from.

### Description of Issue
[Description of the issue]

*
### Additional Information
i really hope you can help.
![image](https://cloud.githubusercontent.com/assets/28641365/25981783/fc9e1f54-368b-11e7-857b-3fac792c3dd8.png)

**Comment by koolcat200** [comment]
i did not mean to add the tri screen picture windows chose to not me i am sorry

**Comment by MJRLegends** [comment]
Nope sorry it's a change I want everyone to have
