### ISSUE TITLE
Minor Issue Harvestcraft config vs reality

### ISSUE THREAD

**Issue by Vaporous** [MJRLegends/Space-Astronomy-Feedback-#85]
As the title suggests, a minor issue between what really happens, and what the config files say. Was trying to convert buckets of water into fresh water. The config file says it should make 4 'fresh water' from a single bucket of water; actually doing the craft, however, provides a single 'fresh water' item. I haven't checked to see if milk to fresh milk is equally having this issue, however.

**Comment by MJRLegends** [comment]
This is not really a major issue. I will look more in to it soon.
