### ISSUE TITLE
space astronomy is not lunching

### ISSUE THREAD

**Issue by IBurnTurds** [MJRLegends/Space-Astronomy-Feedback-#850]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
I'm unable to help with no information!

**Comment by IBurnTurds** [comment]
im sorry i forgot to fill it out but it not loading up at all it just keeps crashing

**Comment by MJRLegends** [comment]
@IBurnTurds im unable to fix or help you without a copy of that crash log....
