### ISSUE TITLE
Modpack won't launch

### ISSUE THREAD

**Issue by Unyxos** [MJRLegends/Space-Astronomy-Feedback-#851]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
When I want to launch Space Astronomy, the Feed The Beast's launcher close and re-open, the game d'ont start.

### Steps to Reproduce Issue
1. Simply launch SA from FTB launcher

**Crash log/Log (if applicable):** https://pastebin.com/ScuXVX26

**Version of Mod Pack using:** 1.6.3

### Additional Information
I just downloaded the modpack to play with friends, still unable to play it

**Comment by IBurnTurds** [comment]
same here

**Comment by Unyxos** [comment]
I solved it by updating my graphics card's drivers to the latest verion !
