### ISSUE TITLE
Uranium=Yellorite?

### ISSUE THREAD

**Issue by SirClirks** [MJRLegends/Space-Astronomy-Feedback-#852]
Uranium is after crushing and melting it yellorite and yellorite after smelting uranium

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Yeah they are the same thing can can be used the same
