### ISSUE TITLE
Minechem Osmium Recipe conflict

### ISSUE THREAD

**Issue by EchoingZen** [MJRLegends/Space-Astronomy-Feedback-#855]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes, could not find]
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Osmium Crystals and Osmium Dust share the same recipe in the chemical synthesizer.

### Steps to Reproduce Issue
1. Check NEI for Minechem's Osmium.  It will show the two items with the same recipe.

**Version of Mod Pack using:** [1.6.3]

### Additional Information
[None.  Thanks for such a solid modpack!]

**Comment by MJRLegends** [comment]
Thanks i think i can fix this

**Comment by MJRLegends** [comment]
Will be fixed in v1.6.4
