### ISSUE TITLE
i need info please

### ISSUE THREAD

**Issue by koolcat200** [MJRLegends/Space-Astronomy-Feedback-#856]
i am making my own mod pack not modifying your pack if you don't want to publicly tell me how i can change it please send me somewhere Private i do not wish to bother you but your the only one that can or might help fix it

**Comment by MJRLegends** [comment]
@koolcat200 Yeah You can contact me privately all my usernames are MJRLegends. Just my mod pack issue tracker isnt the place for me to be helping you with your mod pack
