### ISSUE TITLE
Official Ser ver

### ISSUE THREAD

**Issue by G-Tandem** [MJRLegends/Space-Astronomy-Feedback-#857]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
I would like to create an official server for the modpack, can you please contact me if you would like that.
PS: I only posted it here because I don't know where else to post it...

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
#838
