### ISSUE TITLE
Mekanism VoiceServer causes GC spikes and higher CPU usage on clients; Servers might be affected too 

### ISSUE THREAD

**Issue by c62624** [MJRLegends/Space-Astronomy-Feedback-#858]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes
### Description of Issue
Mekanism's voice servers cause high amounts of memory allocation and garbage collection. Increased CPU usage.

### Steps to Reproduce Issue
1. It's enabled by default in the Mekanism config file so you don't need to do anything to get the issue.

**Version of Mod Pack using:** [VERSION]

### Additional Information
Can be disabled through the following line in mekanism.cfg:    B:VoiceServerEnabled=false

Known issue on Mekanism GitHub: https://github.com/aidancbrady/Mekanism/issues/3865
Apparently not fixed in the Mekanism build used for Space Astronomy.

My own Java profiling results match the one in that thread: https://i.imgur.com/sjImB1K.png

**Comment by MJRLegends** [comment]
I will make it false by default in the mod pack :D

**Comment by MJRLegends** [comment]
Will be fixed in v1.6.4
