### ISSUE TITLE
Minechem NEI Crash

### ISSUE THREAD

**Issue by obuw** [MJRLegends/Space-Astronomy-Feedback-#859]
When I hover over a common Minechem element in NEI, and press R, the game freezes for 10+ seconds and eventually crashes with an out of memory error.

I believe this happens with all elements that can be obtained from stone. Presumably because there are 1000+ stone based items that break down into these elements.

This started happening when I updated to 1.6.3. (I was on 1.5.2 beforehand, and never had a problem like this.)

I'm allocating 8gb of memory to minecraft, and I have 16gb on my machine.

Anything I can do to remedy this? Perhaps a mod to cull all the extra recipes?

**Comment by MJRLegends** [comment]
Crash log?

**Comment by obuw** [comment]
https://pastebin.com/Xcd8wqpN

The game actually hangs for ~3 minutes before crashing.

**Comment by MJRLegends** [comment]
How are you changing the allocated ram?

**Comment by obuw** [comment]
I am using the slider on the FTB Launcher (the old one). But I realized after posting the crashlog that I was also adding the "-Xms4096M -Xmx4096M" JVM flags in addition to that, which may have confused the jvm. 

I'll remove it try again, but I don't think it'll make any difference. (It would just hang for ~6 minutes before crashing).

**Comment by MJRLegends** [comment]
yeah i think you putting custom jvm args made it not work

**Comment by obuw** [comment]
Oh, indeed that seems to have fixed it!

The game still hangs for 3-5 seconds but I guess that's understandable, as it shows 658 recipes afterwards.

**Comment by MJRLegends** [comment]
yeah it still loading stuff during that 3-5 seconds

**Comment by MJRLegends** [comment]
Im glad your issue is sorted anymore issues please let me know :D
