### ISSUE TITLE
freeze on title screen

### ISSUE THREAD

**Issue by EpicDragonLord15** [MJRLegends/Space-Astronomy-Feedback-#86]
whenever i try to load up the modpack i get to the title screen then i cant click on anything, then a little while later it crashes and takes me back to the launcher

ill post crash log once i know how to do the /spoiler thing

**Comment by MJRLegends** [comment]
Ok use paste bin for the crash log

**Comment by EpicDragonLord15** [comment]
pastebin?

**Comment by MJRLegends** [comment]
Google it

**Comment by EpicDragonLord15** [comment]
found it, its to big to fit on it without becoming a pro user

**Comment by MJRLegends** [comment]
it shouldnt be that big if its just the crash log not the full log

**Comment by EpicDragonLord15** [comment]
http://pastebin.com/e5Uf9pg5

**Comment by MJRLegends** [comment]
The seems to be caused by a problem getting/registering the sponge texture. I think this might of been a memory problem. You need to increase the amount of ram the launcher uses in the settings of the launcher

**Comment by EpicDragonLord15** [comment]
it worked, thankyou
