### ISSUE TITLE
[1.7.10] Server side crash on startup

### ISSUE THREAD

**Issue by aking4125** [MJRLegends/Space-Astronomy-Feedback-#860]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes (Mostly)
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes (Mostly)
### Description of Issue
Server crash on startup

### Steps to Reproduce Issue
1. I guess simply start the server with my set of mods (Shrug)
2. Just watch it crash.
3. Removing Extra planets and the server starts normally
4. Single player works fine.

**Crash log/Log (if applicable):** https://pastebin.com/GPSfW3PC

**Version of Mod Pack using:** Private pack (?)

### Additional Information
According to part of the crash log it seems to be loading some type of Client Front stuff. And there's a part of the Galaticcraft update checker. I have enabled and disabled the update checker for GC and neither has any effect. It works perfectly fine in SSP and it works with just GC and EP installed. I'm pretty sure there's some type of mod conflict but I'm not an expert. 

Of course, I can live without the mod on the server. And of course I'm gonna get yelled at xD

**Comment by MJRLegends** [comment]
Why have you posted this here that mod isn't even in this mod pack haha

**Comment by aking4125** [comment]
Yes it is. Have you even looked at the crash log? 

http://prntscr.com/f9e5vb

**Comment by MJRLegends** [comment]
Mate your posting this on a mod pack issue tracker which the mod pack doesn't have the mod in

**Comment by aking4125** [comment]
Oh you mean the mod pack. I didn't even notice that. You're right. Fug. Where do I post this then? I posted it on the forums.

**Comment by MJRLegends** [comment]
No where it's already been reported if you go to the correct issue tracker not some random one of mine

**Comment by aking4125** [comment]
I'm sorry. I just goggled Extra planets github and this for me was the first and only result. Gotcha then. Is it possible to delete this?

**Comment by MJRLegends** [comment]
Nope github doesn't offer a delete

**Comment by aking4125** [comment]
*Sigh* well I'm extremely sorry.
