### ISSUE TITLE
can't go (stuck at space station) from pluto's space station to jupiter

### ISSUE THREAD

**Issue by tonimark** [MJRLegends/Space-Astronomy-Feedback-#861]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
[when I created a space station at pluto planet when I try to with a 7th tier rocket to go to Jupiter but when I tried this I am still here and the GUI opens again I tried to do this multiple times but still failure but I only made to go to overworld (it wasn't a log spike)
maybe: the dimension teleporter won't work for Jupiter's id ]

### Steps to Reproduce Issue
1. [launch yourself in tier 7 rocket (in creative mode) and create a space station at pluto]
2. [use the same rocket to go to Jupiter from pluto and the bug appears]

**Crash log/Log (if applicable):** [nope]

**Version of Mod Pack using:** [1.6.3]

### Additional Information
[did it glitched because I created space station on other planets ?]

**Comment by MJRLegends** [comment]
jupiter isnt a planet you can go too only a jupiter space station
