### ISSUE TITLE
crash with iron backpacks

### ISSUE THREAD

**Issue by tonimark** [MJRLegends/Space-Astronomy-Feedback-#862]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
when I got a diamond backpack and a golden backpack and go to survival inventory in creative my game crashes 

### Steps to Reproduce Issue
1. get an diamond and a golden backpack in creative mod
2. go to survival inventory

**Crash log/Log (if applicable):** link:https://pastebin.com/Wazt6pfF
**Version of Mod Pack using:** 1.6.3

### Additional Information
nope

**Comment by MJRLegends** [comment]
@tonimark This wouldnt of been caused by a creative to survival change, did you click or right click anything as thats the cause of the issue.

**Comment by MJRLegends** [comment]
ping @tonimark
