### ISSUE TITLE
Crash when placing down 3 creative OC-Minecarts

### ISSUE THREAD

**Issue by tonimark** [MJRLegends/Space-Astronomy-Feedback-#863]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
WHEN I  place down three cretix (creative OC-minecarts) the game crashes

### Steps to Reproduce Issue
1. place on the ground 3 vanilla Minecraft rails
2. place 3 creative minecarts on the rail

**Crash log/Log (if applicable):** link:https://pastebin.com/ag3pX6ns

**Version of Mod Pack using:** 1.6.3

### Additional Information
nope

**Comment by MJRLegends** [comment]
Will be fixed in v1.6.4
