### ISSUE TITLE
server crash + clientside crash with update from 1.6.4 to 1.6.5

### ISSUE THREAD

**Issue by Lots-of-goats** [MJRLegends/Space-Astronomy-Feedback-#864]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

N/A

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
### Description of Issue
Unexpected Error Occurred on Client side after updating from 1.6.4 to 1.6.5. Server crashes and shuts down as shown in log also from updating to 1.6.5

### Steps to Reproduce Issue
1. update to 1.6.5
2. crash
3. post issue here

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/HfZfANCt

**Version of Mod Pack using:** [VERSION]
1.6.5

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
By the looks of it you havent copied the files correctly over to your server, try reupload them

**Comment by MJRLegends** [comment]
Will reopen if i can see anymore than the wrong files/incomplete version update has been updated for server use
