### ISSUE TITLE
tinker i/o smart output not working

### ISSUE THREAD

**Issue by DoomSquirter** [MJRLegends/Space-Astronomy-Feedback-#865]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes

### Description of Issue
[Description of the issue]
smart output doesn't accept fluids from smeltery

### Steps to Reproduce Issue
1. build smeltery
2. put either EIO conduit or tinkers faucet above smart ouput.  does not output fluids or pour into smart output.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]
latest on curse 1.6.5
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
see point 2 here https://minecraft.curseforge.com/projects/tinker-i-o

It doesnt support using cables with it as thats not the aim on the block so its not a bug just not a feature

**Comment by DoomSquirter** [comment]
please look again at #2.  
**put either EIO conduit or tinkers faucet above smart ouput. does not output fluids or pour into smart output.**
doesn't work with tinkers faucet either.

**Comment by MJRLegends** [comment]
Thanks, will look at this

**Comment by MJRLegends** [comment]
@DoomSquirter Ok i just tried this and it works fine for me see images below
Also, Which liquid/resource was you trying to poor as it will only accept tinkers ones that you can make tools and parts out of?

![](https://i.gyazo.com/664ea9f389206ccdf3490178ceeb3808.png)
![](https://i.gyazo.com/05f2966b391dc70dd42ab6deac900fe6.png)
![](https://i.gyazo.com/91c8fc9bf2613675ce1065f00cdb5023.png)

**Comment by DoomSquirter** [comment]
well then that's really weird.  was just iron.   nothing special.  I put a ingot cast inside the smart output and nothing happens.  click on faucet and nothing.

so actually, the same iron is still in my smeltery so tried again, still not pouring.  I broke the faucet/drain and replaced it.  nothing.  broke the smart output, replaced.  nothing.  

I'm clueless what could be the issue really.  no additions to mod or removals.

**Comment by DoomSquirter** [comment]
yeah I just realized no drains/faucets are working actually lol  didn't notice that before.  well then yeah, I know what it is.  I had the fuel input machine as part of the structure of the smeltery.  *facepalm*.  used it in 1.10 and this worked fine.  1.7.10 version must work differently.  my bad.
