### ISSUE TITLE
[1.6.5] Rubber dupe

### ISSUE THREAD

**Issue by savosdarkran** [MJRLegends/Space-Astronomy-Feedback-#866]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes
### Description of Issue
[Description of the issue]
Item dupe with rubber and mimichite

### Steps to Reproduce Issue
1. raw rubber + mimichite in crafting grid = two rubber
2. rubber + mimichite in crafting grid = two rubber
3. repeat step 2

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]
1.6.5
### Additional Information
[Any other information that may be able to help me with the problem]
I noticed that there is also a recipe that shows rubber + mimichite = raw plastic.  This might have been the intended result.

**Comment by MJRLegends** [comment]
Thanks will fix this :D

**Comment by MJRLegends** [comment]
Ok looking at this more closely, i have worked out its not a dupe bug since this is the intended feature of mimichite of being able to get more of one resource for the cost of mimichite, its the same with ingots too. but i might change some of the mimichite costs though :D

**Comment by savosdarkran** [comment]
:) okay.  Sounds good.  Thanks MJR!

**Comment by MJRLegends** [comment]
@savosdarkran No problem, thanks for the bug report though any more issues let me know
