### ISSUE TITLE
Spammed errors and cloned Squiddies after server power loss

### ISSUE THREAD

**Issue by system86** [MJRLegends/Space-Astronomy-Feedback-#868]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes
### Description of Issue
[Description of the issue] Server loses power, then regains it, upon logging on i find ~1500 squids all named Squiddy with the pickaxe head hat. Only i was on the server, so it rules out greifing. There also was an error ([Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.ja
va:685)) being spammed in the console, causing huge lags and disconnections ad nauseum.

### Steps to Reproduce Issue
1. [First step] Hard restart / disconnect server power while player(s) are active
2. [Second step] repeat until the point when/if it occurs

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.] too little information to be pastebin'd, the only thing is the error mentioned above repeated indefinately,once per tick.

**Version of Mod Pack using:** [VERSION] 1.6.2

### Additional Information
[Any other information that may be able to help me with the problem] was using opencomputers and mekanism fusion reactors extensively on this world

**Comment by MJRLegends** [comment]
Your issue is someone has spawned to many entities bear you so I class this not a bug
