### ISSUE TITLE
Reward Bag Bug

### ISSUE THREAD

**Issue by PorkchopDonut** [MJRLegends/Space-Astronomy-Feedback-#87]
I am unable to claim reward bags as rewards for finishing quests.  This wouldn't normally be problematic, but I'm on the Storage quest line right now and I can't get past the very first quest because I can't claim the reward, as reward bag is my only option.

**Comment by MJRLegends** [comment]
Why cant you claim the reward bags?????

**Comment by PorkchopDonut** [comment]
...I'm not sure.  That's why I posted in the bug list -__- For example, I
click on the reward bag to select it, the claim rewards button pops up, but
when I click on the claim rewards button, nothing happens.

**Comment by PorkchopDonut** [comment]
The point where I first encountered this was the first quest in the Storage line.  It happened again on the quest where you kill the animals.

**Comment by MJRLegends** [comment]
You sure it wasnt that you didn't have enough space in your inventory for the items so you couldn't collect them?

**Comment by PorkchopDonut** [comment]
Oh my gosh I feel incredibly stupid now.  You are correct.  My inventory
was full.  I apologize.
