### ISSUE TITLE
Clicking Recipes on Chemical Decomposer Freezes Game

### ISSUE THREAD

**Issue by FiddleF** [MJRLegends/Space-Astronomy-Feedback-#870]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
[When clicking on the arrow to show recipes in the Chemical Decomposer, the game will Stop Responding. It does not seem to ever start responding again, I waited several minutes to no avail.]

### Steps to Reproduce Issue
1. [Right click on Chemical Decomposer]
2. [Click on Recipes Arrow]

**Crash log/Log (if applicable):** [No crash report, game gets stuck on Not Responding]

**Version of Mod Pack using:** [1.6.5]

### Additional Information
[
*Windows 7 Home Premium 64 Bit
*PNY Nvidia 1060 GTX
*AMD FX 8370]

**Comment by MJRLegends** [comment]
Please post your latest.log file and fml-latest.log file

**Comment by FiddleF** [comment]
Started crashing whenever I loaded up the world, something to do with Modular Power Armor. Took out the save and reinstalled the modpack and put the save back in. Still crashing.
[crash-2017-05-31_03.08.44-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/1040528/crash-2017-05-31_03.08.44-client.txt)

**Comment by MJRLegends** [comment]
@FiddleF, ok firstly you need to update your mod pack version to v1.6.6, and give it a try then.

If still crashes please post a download link for your playerdata file.

**Comment by MJRLegends** [comment]
@FiddleF, ok please post a download link for your playerdata file.

**Comment by FiddleF** [comment]
http://www.filedropper.com/playerdata

**Comment by MJRLegends** [comment]
@FiddleF Which one is yours as theres like 5 in the file??

**Comment by MJRLegends** [comment]
@FiddleF Dont worry found yours

**Comment by MJRLegends** [comment]
@FiddleF Can you delete 

the following mods (**MAKE A BACKUP/COPY OF YOUR WORLD FIRST**)
Numina
ModularPowerSuits

and put in these ones
https://minecraft.curseforge.com/projects/numina/files/2382452
https://minecraft.curseforge.com/projects/modular-powersuits/files/2402848

and let me know if it works..

**Comment by FiddleF** [comment]
Alright, I'll be on it later tomorrow and try that. 

Is there an automated backup system, like infinity evolved? Or would an external mod suffice?

**Comment by MJRLegends** [comment]
Ok and nope just copy and paste your world folder in the saves folder and work from the copy one and use the copied one when going in to the world via single player

**Comment by FiddleF** [comment]
Made a backup, deleted those mods and added the new ones. Now I get this [crash message](https://pastebin.com/XVMpCjzW)

**Comment by FiddleF** [comment]
Made a new world to test the original point of this issue. I no longer freeze when clicking on the Recipes Arrow in the decomposer. I'm not sure if this is due to something being corrupted in the old world (before the loading crashes), or something else once placed conflicts with it.

**Comment by MJRLegends** [comment]
ok in the copy of your old world that you made try deleting everything in the playerdata folder (**Make sure its the copy of your world not the real one**)

**Comment by FiddleF** [comment]
Deleted everything inside of the Playerdata folder, seems the loading lasted a bit longer, still crashes though.
[Pastebin](https://pastebin.com/rP4kyNsa)

**Comment by MJRLegends** [comment]
Ok, you have two solutions here (**Make sure to make another backup of your real world folder just incase something doesnt work or it goes wrong**)

1. Remove the ModularPowerSuits mod and start the mod pack and load your world and then re-add ModularPowerSuits back (This will remove all ModularPowerSuits items from your world but you can use creative/NEI to spawn them back for yourself) 

2. Start a new world

**Comment by FiddleF** [comment]
Removing the ModularPowerSuits mod worked. Now, for the original point of this issue. Here are the logs after I click on the Chemical Decomposer's Recipe Arrow.

Here are the [Latest Logs](http://www.filedropper.com/logs_19)

**Comment by MJRLegends** [comment]
@FiddleF Everything looks fine in them logs you post above also didnt you see it was fixed with them new mods i sent you to try out?

![](https://i.gyazo.com/d265fbc21f52a8d750a06251739489a6.png)

**Comment by FiddleF** [comment]
Everything was fine in the second world I made, but the chemical decomposer still causes freezing in the main world. 
Probably just a rare occurrence in that world. I will close this.
Thank you for the help with the world crashes.

**Comment by MJRLegends** [comment]
Yeah I'm in able to reproduce the freezing issue
