### ISSUE TITLE
most times i load my world the game freezes and crashes

### ISSUE THREAD

**Issue by lightkestral280** [MJRLegends/Space-Astronomy-Feedback-#871]
I load it up normally everything working fine I can start new world and play one those but when I try and open a old world it crashes what should I do?

**Comment by MJRLegends** [comment]
Please post your latest.log file and fml-latest.log file

**Comment by MJRLegends** [comment]
Or the crash log as I'm unable to help without the needed information

**Comment by akosoccer** [comment]
My Game is doing the same thing. This is the crash log- The game crashed whilst exception in server tick loop
The game crashed whilst exception in server tick loop
Error: java.lang.ArrayIndexOutOfBoundsException: 1

**Comment by MJRLegends** [comment]
@akosoccer That 1 line log is pointless please post the whole thing!

**Comment by akosoccer** [comment]
It won't let me open the rest

**Comment by akosoccer** [comment]
If I click view crash report nothing happens

**Comment by MJRLegends** [comment]
@akosoccer You can find the crashlog in the "\minecraft\crash-reports\" folder

**Comment by MJRLegends** [comment]
Closing due to no reply, will reopen if someone replies with a crash log and details on how they got to it crashing
