### ISSUE TITLE
Mouse scrolling bug

### ISSUE THREAD

**Issue by chadfire** [MJRLegends/Space-Astronomy-Feedback-#874]
I fixed it. You can delete this.

**Comment by rexxieboy** [comment]
how did you fix it?

**Comment by chadfire** [comment]
Rex,

Well, I originally typed in a lot of text and deleted it because **I thought I fixed it**. I was too embarrassed to change it. I'll tell you the bug and then see if you are having the same problem.

The bug, 

You can use the mouse scroll wheel to transfer items from your inventory or anything for that holds items, by scrolling up or down. I have not played in a long while but I believe this action does not work for chests. I would recommend trying the backpack if you can't replicate it with a chest. just get a stack of anything and put it into a chest and scroll up or down to change its location, but this does not work because it's doing it twice wich has a net result of zero items transferred.

Yes, I have checked all the known and fixed bugs and this was not in them.

Anyway, sorry for not replying sooner. Have a good day,

Chadfire

**Comment by pla** [comment]
I have the same problem, putting items in and out of chests with the scrollwheel doesn't work correctly. Inventory Tweaks and Mouse Tweaks both provide this functionality and negate the scroll action.

Solution:

I set WheelTweak=0 in the MouseTweaks config and it is working now.  

Pack Version: 1.7.1
