### ISSUE TITLE
I don't know what happened

### ISSUE THREAD

**Issue by ItzPnwd115** [MJRLegends/Space-Astronomy-Feedback-#876]
I up dated the mod to 1.6.6 and it won't let me even start the loading screen logs are listed below:
22:03:59	FML	The coremod lumien.randomthings.Transformer.RTLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
22:03:59	FML	The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
22:03:59	FML	The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
22:03:59	LaunchWrapper	Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
22:03:59	LaunchWrapper	Loading tweak class name fastcraft.Tweaker
22:03:59	LaunchWrapper	Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
22:03:59	LaunchWrapper	Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
22:03:59	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:03:59	LaunchWrapper	Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
22:03:59	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:03:59	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:00	FML	Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
22:04:00	FML	Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
22:04:00	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:00	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:00	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:00	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:00	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:00	Aroma1997Core	Finished data injection.
22:04:00	Aroma1997Core	Finished data injection.
22:04:00	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:00	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:00	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:00	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:00	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	IC2-core	Loaded library EJML-core-0.26.jar.
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	INpurePreloader	Attempting to detect JVM version...
22:04:01	INpurePreloader	Detected JVM: 1.8
22:04:01	INpurePreloader	Starting library configuration...
22:04:01	INpureLogInterceptor	System attached to FML. Now intercepting all logging calls.
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	STDOUT	[micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:102]: Successfully Registered Transformer
22:04:01	STDOUT	[micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
22:04:01	STDOUT	[micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	STDOUT	[pcl.opensecurity.util.SoundUnpack:load:23]: Extracting sounds from: assets/opensecurity/sounds/alarms/
22:04:01	STDOUT	[pcl.opensecurity.util.SoundUnpack:load:35]: Extracting file: klaxon1.ogg
22:04:01	STDOUT	[pcl.opensecurity.util.SoundUnpack:load:35]: Extracting file: klaxon2.ogg
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	STDOUT	[pcl.opensecurity.util.SoundUnpack:load:23]: Extracting sounds from: assets/opensecurity/sounds/alarms/
22:04:01	STDOUT	[pcl.opensecurity.util.SoundUnpack:load:35]: Extracting file: klaxon1.ogg
22:04:01	STDOUT	[pcl.opensecurity.util.SoundUnpack:load:35]: Extracting file: klaxon2.ogg
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:01	Bookshelf	Starting to apply transformations
22:04:01	Bookshelf	Starting to apply transformations
22:04:01	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:02	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:02	malisiscore	[ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
22:04:02	malisiscore	[ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
22:04:02	malisiscore	[ChunkCollisionTransformer] Hook registered for net.minecraft.item.ItemBlock
22:04:02	malisiscore	[ChunkCollisionTransformer] Hook registered for net.minecraft.network.NetHandlerPlayServer
22:04:02	malisiscore	[ChunkBlockTransformer] Hook registered for net.minecraft.world.chunk.Chunk
22:04:02	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:02	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:02	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:02	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:02	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:02	LaunchWrapper	Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
22:04:02	LaunchWrapper	Calling tweak class fastcraft.Tweaker
22:04:02	FastCraft	FastCraft loaded.
22:04:02	LaunchWrapper	Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
22:04:02	LaunchWrapper	Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
22:04:02	LaunchWrapper	Launching wrapped minecraft {net.minecraft.client.main.Main}
22:04:02	STDOUT	[micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: bdi (1 / 1)
22:04:02	STDOUT	[micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: sv (1 / 1)
22:04:02	STDOUT	[micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: sa (1 / 1)
22:04:03	AE2-CORE	func_146977_a(Lnet/minecraft/inventory/Slot;)V - Transformed
22:04:03	AE2-CORE	func_146977_a_original(Lnet/minecraft/inventory/Slot;)V - New Method
22:04:03	AE2-CORE	func_146977_a(Lnet/minecraft/inventory/Slot;)V - Invoke Virtual
22:04:03	STDOUT	[micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: ahb (1 / 1)
22:04:03	malisiscore	Found hooks for net.minecraft.world.World (ahb)
22:04:03	RandomThingsCore	Found World Class: net/minecraft/world/World
22:04:06	net.minecraft.client.Minecraft	Setting user: Hailstorm115
22:04:07	STDOUT	[micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: xk (1 / 1)
22:04:07	RandomThingsCore	Found Item Class: net/minecraft/item/Item
22:04:07	RandomThingsCore	Found Leave Class: net/minecraft/block/BlockLeavesBase
22:04:07	LaunchWrapper	Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/tileentity/TileEntity
	at net.minecraft.block.Block.func_149671_p(Block.java:227)
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287)
	at net.minecraft.client.main.Main.main(SourceFile:129)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.tileentity.TileEntity
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
Caused by: java.lang.ClassFormatError: Duplicate interface name in class file net/minecraft/tileentity/TileEntity
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 12 more
18:04:07	game	Exception in thread "main"   <log4j:Event logger="STDERR" timestamp="1496628247454" level="INFO" thread="main">
    <log4j:Message><![CDATA[[java.lang.Throwable$WrappedPrintStream:println:748]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException]]></log4j:Message>
  </log4j:Event>
18:04:07	monitor	expected <
22:04:07	STDERR	[java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
22:04:07	STDERR	[java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
22:04:07	STDERR	[java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Runtime.exit(Runtime.java:107)
22:04:07	STDERR	[java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.System.exit(System.java:968)
22:04:07	STDERR	[java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
22:04:07	STDERR	[java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by MJRLegends** [comment]
Please actually fill out the template you deleted and use pastebin.com for the log

**Comment by MJRLegends** [comment]
@ItzPnwd115 ^^^^
