### ISSUE TITLE
Curse Launcher Crash issue

### ISSUE THREAD

**Issue by ItzPnwd115** [MJRLegends/Space-Astronomy-Feedback-#877]
---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
---Description of Issue---
I updated my mod version to 1.6.6 after that I haven't been  able to get to the Mincraft Title Screen where I could select single player and play on my world. I hit play on the loader it disappears for a few seconds then comes back saying it crashed.

#876 Steps to Reproduce Issue
1. Updated to 1.6.6
2. Hit play button
3. Wait a few seconds
4.Crashes

**Crash log/Log (if applicable):** (https://pastebin.com/rG3s1yF4)
**Version of Mod Pack using:** Version 1.6.6

### Additional Information
None

**Comment by MJRLegends** [comment]
Hey reinstalling, make sure you copy your saves or you will lose them
