### ISSUE TITLE
Game randomly crashing at seemingly sporadic intervals

### ISSUE THREAD

**Issue by caribbeanstun** [MJRLegends/Space-Astronomy-Feedback-#878]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
My game randomly crashes whenever I do any meaningless task. This has been ranging from opening a chest, clicking on an item in NEI to get a recipe, opening up my inventory, etc. Sometimes I can play for an hour without a crash, and sometimes it crashes 3 times in 5 minutes.

### Steps to Reproduce Issue
1. It could literally be anything

**Crash log/Log (if applicable):** https://pastebin.com/AN1yr6PA
**Version of Mod Pack using:** 1.6.5

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by caribbeanstun** [comment]
Also, I have tried updating java, downgrading java, reinstalling modpack, reinstalling minecraft, restarting computer, allocating more/less ram, turning off uac, all my drivers are updated and it still crashes.

**Comment by MJRLegends** [comment]
Isn't s mod pack issue I'm unable to help sorry

**Comment by MJRLegends** [comment]
See https://stackoverflow.com/a/34842953

**Comment by MJRLegends** [comment]
Also see the description on here https://bugs.mojang.com/plugins/servlet/mobile#issue/MC-32606
