### ISSUE TITLE
Space Astronomy Server Startup Crash

### ISSUE THREAD

**Issue by Chewyx** [MJRLegends/Space-Astronomy-Feedback-#879]
---Issue Report---
Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):Yes

Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING): Yes
 ---Description of Issue---
While trying to start a Space Astronomy Server, it crashes when I try to start it up. When I start it, it will load everything up and when its preparing the world, it crashes.

 Steps to Reproduce Issue
1. Start up Server
2. Crash

**Crash log/Log (if applicable): https://pastebin.com/p8JtcDCH
**Version of Mod Pack using:V 1.6.6

 Additional Information
Nothing

**Comment by MJRLegends** [comment]
Remove DamageIndicatorsMod on the server files
