### ISSUE TITLE
game isnt loading the textures properly 

### ISSUE THREAD

**Issue by danghost22** [MJRLegends/Space-Astronomy-Feedback-#880]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please fill out more than just the title as I'm unable to help otherwise....

**Comment by MJRLegends** [comment]
@danghost22 Closing due to the lack of detail on the issue that has been provided
