### ISSUE TITLE
lag spike every 3 seconds 

### ISSUE THREAD

**Issue by Anasboko** [MJRLegends/Space-Astronomy-Feedback-#881]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue] every time i want to play it just lag spikes every time. but i dont know if its the modpack or my laptop pc

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION] 1.6.6

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by Jin16** [comment]
need more info :D

**Comment by MJRLegends** [comment]
@Anasboko Closing due to the lack of detail on the issue that has been provided
