### ISSUE TITLE
Can't select world in Singleplayer menu

### ISSUE THREAD

**Issue by ThatTilux** [MJRLegends/Space-Astronomy-Feedback-#882]
Hey, 

if I press the singleplayer button on the title screen, I get to the Singleplayer world tab, but can't select any world, so I can only create a new world or cancel.

I've arleady installed the newest Java and reinstalled the modpack, but the issure is still there.
In Vanilla everything is fine.

I hope you can help me,
Tilux.

(I don't know where to get the logs from :/)

**Comment by ThatTilux** [comment]
In Multiplayer everything if fine, this is the log:
[latest_log.zip](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/1069237/latest_log.zip)

**Comment by ThatTilux** [comment]
Modpack version is 1.6.6

**Comment by MJRLegends** [comment]
If your world isnt there is corrupt, and you will need to make a new world

**Comment by ThatTilux** [comment]
The world is there, but i can't click it, so if I click it, it won't outline... worst modpack support ever

**Comment by War-Wizard** [comment]
It's a vanilla minecraft bug, fixed in 1.8, no backport to 1.7, singleplayer is unusable in 1.7 if you got this problem, download the modpack server and run it, then connect to localhost. Remember to shut it down after you're done playing.

**Comment by MJRLegends** [comment]
See fix here #885
