### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by MarkusMert** [MJRLegends/Space-Astronomy-Feedback-#883]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
I had a crash with the game then my save file dissapeared. I used an old backup and made the file visible but now it gives another error when I try to open the world.

**Crash log/Log (if applicable):**

 https://pastebin.com/YsJ9knDF

**Version of Mod Pack using:** 1.6.6

**Comment by MJRLegends** [comment]
Sorry for the slow reply...

To fix this you have to go to your world in the server folder and delete the folder called "RedstoneEther".
