### ISSUE TITLE
[Suggestion] Add the mod "remain in motion" for frame-based block movement

### ISSUE THREAD

**Issue by system86** [MJRLegends/Space-Astronomy-Feedback-#884]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2104611-remain-in-motion-continuation-of-redstone-in

Remain in motion is a mod that was in my previous favorite modpack (tekkit legends) and allows you to make vehicles via frames, frame motors and electrical energy. This mod is fairly balanced, as larger (laggier) moving objects cost more (more motors and electricity). You can make extremely large (10x10+) airtight (galacticraft oxygen sealer) hangar doors easily with this mod. _It is 1.7.10 and 1.6.X exclusive, which is handy_

The frames currently in game (projectred and some other obscure mod) are completely dysfunctional.

Please actually read the text this time and don't dismiss it with a vague response

**Comment by MJRLegends** [comment]
Thanks for the suggestion but im not going to adding new mods to the mod pack for a while :D

**Comment by system86** [comment]
alrighty, thanks for responding in a clear manner, unclear responses are annoying at times.

**Comment by MJRLegends** [comment]
No problem
