### ISSUE TITLE
Unable able to select any single player worlds!

### ISSUE THREAD

**Issue by GigelyStrudels** [MJRLegends/Space-Astronomy-Feedback-#885]
### ---Issue Report---
I am not able to select my saved worlds in the menu. It acts like I'm just clicking blank space.
I did check through the known issues and there was nothing similar to my problem.
### Description of Issue
I can click over the world names but nothing happens when I do.

### Steps to Reproduce Issue
I just happens whether I restart the game or not.

Space Astronomy Version 1.6.6

### Additional Information
I don't play single player that often and usually just play on the servers so I'm not sure if it has been like this for a while or not.

**Comment by MJRLegends** [comment]
Please post a full log

**Comment by GigelyStrudels** [comment]
What do you mean by full log? I noticed this like yesterday but don't know how long it has been this way since the last time I played single player, other than today I think, was 5/13/17 12:39 PM.

**Comment by MJRLegends** [comment]
Please go the "logs" folder and drag the "latest.log" and "fml-client-latest.log" files (But make sure you have tried to go to your single player worlds before posting them here)

**Comment by GigelyStrudels** [comment]
[latest.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/1083519/latest.txt)
I could not find "fml-client-latest.log" and like I've said it won't even let me select the worlds or saves to be able to play. I can only make new games and see my old ones sitting there unusable.

**Comment by MJRLegends** [comment]
**Ok please can you try the following:**

1. Create a new world and see if that one does the same
2. Remove fastcraft
3. Make a copy of your saves and reinstall the mod pack

**Comment by GigelyStrudels** [comment]
I tried everything even reinstalling the game and I still can't select them. Should I disable fast craft now? It didn't help the first time though.

**Comment by GigelyStrudels** [comment]
![2017-06-19](https://user-images.githubusercontent.com/29524342/27299327-a4de3888-54f1-11e7-967e-5d103abdb19b.png)
I just realized that I can't see the world pictures where the play symbol usually appears.

**Comment by MJRLegends** [comment]
There isnt in 1.7.10

**Comment by MJRLegends** [comment]
Ok so can you load any world on any mod pack?

**Comment by GigelyStrudels** [comment]
I can load worlds on other ones yes.

**Comment by MJRLegends** [comment]
Write copy every out your saves folder and reinstall the mod pack. dont copy the worlds back. and make a new world and try join back, and just to be sure you are selecting a world and pressing the "Play Selected World button" not trying to click anything else?

**Comment by MJRLegends** [comment]
Right copy every out your saves folder and reinstall the mod pack. dont copy the worlds back. and make a new world and try join back, and just to be sure you are selecting a world and pressing the "Play Selected World button" not trying to click anything else?

**Comment by GigelyStrudels** [comment]
![2017-06-19 1](https://user-images.githubusercontent.com/29524342/27302062-19164ed0-54fb-11e7-81fd-07076ede64b3.png)
same thing is happening

**Comment by MJRLegends** [comment]
Ok can you explain to me what your clicking and where

**Comment by GigelyStrudels** [comment]
Well I just save and quit. Then when I want to go play on that world I can't click anything. It's like the game doesn't actually register any of the save files. I can click the name or next to it but nothing ever gets selected.

**Comment by GigelyStrudels** [comment]
I will try to make a video for you.

**Comment by GigelyStrudels** [comment]
[vid.zip](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/1086120/vid.zip)
I wonder if this would work

**Comment by MJRLegends** [comment]
Ok so you know how to get to your settings on windows 10 looks like this 
![](https://i.gyazo.com/278ff2587d2483fc0e3b38a74b90bd81.png)

**Comment by GigelyStrudels** [comment]
yes

**Comment by MJRLegends** [comment]
ok select Gaming, then go to "Gamemode" on left hand side and turn this off 
![](https://i.gyazo.com/02f4bb709758328bbcc10a80af11b355.png)

**Comment by GigelyStrudels** [comment]
okay done

**Comment by MJRLegends** [comment]
Now try :D

**Comment by GigelyStrudels** [comment]
ok brb

**Comment by MJRLegends** [comment]
Might need to restart your computer first though

**Comment by GigelyStrudels** [comment]
I'll restart because it didn't work.

**Comment by MJRLegends** [comment]
@GigelyStrudels if not try in this order

How to fix:
1. Restart PC
2. Turn Off GameMode:
(Settings, Gaming, GameMode, Switch off)
3. Launch Minecraft 1.7.10

**Comment by GigelyStrudels** [comment]
It didn't work. I think I am doomed.

**Comment by MJRLegends** [comment]
@GigelyStrudels Can you try a normal 1.7.10 vanilla version

**Comment by GigelyStrudels** [comment]
I shall

**Comment by GigelyStrudels** [comment]
It doesn't work on 1.7.10 at all for me. I just tried a vanilla version that only has FML.

**Comment by GigelyStrudels** [comment]
I also tried in 100% Vanilla Minecraft and 1.7.10 is just broken for me and I can't load anything.

**Comment by MJRLegends** [comment]
@GigelyStrudels ok so its defo not my mod pack related... umm

**Comment by GigelyStrudels** [comment]
Also I didn't mess with anything it just stopped working on its own. I guess I can just wait for an update...

**Comment by MJRLegends** [comment]
an update on what?

**Comment by GigelyStrudels** [comment]
an update to the modpack once all the mods are up to date with minecraft

**Comment by MJRLegends** [comment]
They are all the latest versions mostly for 1.7.10

**Comment by GigelyStrudels** [comment]
well you know there is a minecraft 1.10.2 right?

**Comment by MJRLegends** [comment]
Yes haha i make multiple forge mods and multiple mod packs

**Comment by GigelyStrudels** [comment]
well space astronomy is my favorite :P

**Comment by GigelyStrudels** [comment]
I tried making my own using most of the mods from it that were on 1.10.2. It works and seems promising. no space stuff though

**Comment by MJRLegends** [comment]
You could try out my new mod pack space astronomy 2 pack i released 2 days ago

**Comment by MJRLegends** [comment]
sorry i wish i could help but i dont know how to solve this issue so please let me know if anything changes, since you said it doesnt work on vanilla 1.7.10 i think this is a minecraft issue not a mod pack issue :P
