### ISSUE TITLE
Can't load my world after parachute issue

### ISSUE THREAD

**Issue by Bloodbrowser** [MJRLegends/Space-Astronomy-Feedback-#886]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue

Each time i try to load my world i crashed (only for one specific world)

### Steps to Reproduce Issue
1. 
2. 

**Crash log/Log (if applicable):** 
[crash-2017-06-21_15.46.34-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/1091749/crash-2017-06-21_15.46.34-server.txt)

**Version of Mod Pack using:** 1.6.6

### Additional Information
I was playing on my world when i got an issue with galacticraft's parachutes (not being able to jump). I tried leaving and re-entering the world to fix this issue but it didn't work so i leaved the game and now everytime i try to load my world i crash (my other worlds work fine). I re-installed  the modpack but i'm still having the same problem. i also asked a friend of mine to load the world (he have the same version of the modpack) but he is crashing just like me (we both have the gravestone mod added to the modpack)

Thank you
(Sorry for my english, it's not my mother tongue :p )

**Comment by MJRLegends** [comment]
Please remove anything you have added to the pack and then try

**Comment by Bloodbrowser** [comment]
I removed the gravestone mod (which was the only i added to the pack ) but i'm still crashing

**Comment by MJRLegends** [comment]
Ok what was you wearing and doing before the parachute thing happened

**Comment by Bloodbrowser** [comment]
i was wearing a set of iron armor with oxygen gear/mask and a thermal padding suit.
i crafted a parachute, i equipped it (everything is fine so far)
i took the coloured parachute the quests book gave me and when i tried to equipped it instead of my old one it started bugging

**Comment by MJRLegends** [comment]
Ping @radfast

**Comment by MJRLegends** [comment]
@Bloodbrowser there are two issues here, the parachute one and the crash issues. The crash issue i will lool at later and come up with a fix for you

**Comment by MJRLegends** [comment]
@Bloodbrowser Ok to fix your crash delete the "elec332" folder in your world

**Comment by MJRLegends** [comment]
@Bloodbrowser any news if my fix sorted it out for you?

**Comment by Bloodbrowser** [comment]
Yes it did fix it, thank you so much
(Sry for responding this late, i haven't been able to play mc for a while )
