### ISSUE TITLE
Cant run Server

### ISSUE THREAD

**Issue by Snipa069** [MJRLegends/Space-Astronomy-Feedback-#887]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes
### Description of Issue
[Just downloaded the server files to run a server for me and family.  Once the server file was created i input my ip wanted to run on and now the server keeps crashing.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** 
[AACxdC3Z.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/1093245/AACxdC3Z.txt)

**Version of Mod Pack using:** 1.6.6

**Comment by MJRLegends** [comment]
Try deleting all the server files and re-downloading them and create a new world, Let me know if that works :D

**Comment by Snipa069** [comment]
I downloaded the server folder from the FTB page and this one is working. The one i got from the game main menu still doesnt work though.  Thx

**Comment by MJRLegends** [comment]
they are the same files, i think something just derped :D
