### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Armageddon7200** [MJRLegends/Space-Astronomy-Feedback-#888]
### Steps to Reproduce Issue
1. Start My server on Starmine
2. Just crash

**Crash log/Log (if applicable): https://pastebin.com/q3PvzRjE

**Version of Mod Pack using: 1.6.6

**Comment by system86** [comment]
Copy your world and delete it, see if it is your world.

**Comment by MJRLegends** [comment]
I'd say its the server files that are not fully there and need redownloading

**Comment by Armageddon7200** [comment]
My bad , Java 7 was installed , not Java 8 , its fixed by my host , thanks
