### ISSUE TITLE
[Suggestion] MAtmos!

### ISSUE THREAD

**Issue by system86** [MJRLegends/Space-Astronomy-Feedback-#889]
MAtmos adds environmental sounds ie water dripping when near dripping water, rumbling while near lava, wind during storms, birds at day and crickets at night.

http://www.9minecraft.net/matmos-mod/

It is well made, modular, works with Forge, and is updated for 1.7.10.
I remember it being in the old Tekkit (google it) and on some other FTB packs, so i'm sure there is a version that will work.

Nostalgia is one hell of a drug.

**Comment by system86** [comment]
I hope you don't mind another one of my suggestions.

**Comment by MJRLegends** [comment]
Thanks for the suggestion but i wont be adding new mods to this mod pack only bug updates and mod pack updates since ive got a new mod pack im going to be working on, its called Space Astronomy 2 and its on the curse/twitch launcher

**Comment by system86** [comment]
Thanks for the quick response :P
