### ISSUE TITLE
Worlds will not load

### ISSUE THREAD

**Issue by shawn1368** [MJRLegends/Space-Astronomy-Feedback-#890]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
When I try to load any of my worlds, it simply says "loading world" then goes back to the main menu without saying anything else. This also happens when I try to create a new world. This issue did not happen beforehand, although a crash happened a day before the issue happened which may be relevant. I did not do anything on the day the issue happened.

### Steps to Reproduce Issue
1. Open up the modpack.
2. Load any world.
3. World does not load.

**Crash log/Log (if applicable):**[crash-2017-06-24_13.49.44-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/1100219/crash-2017-06-24_13.49.44-server.txt)

**Version of Mod Pack using:** v1.6.3

### Additional Information
I redownloaded the modpack in a new instance with v1.6.6, and a new world successfully loaded. However, when I copied and pasted my old world in my old v1.6.3 instance into the new v1.6.6 instance, I couldn't load that world, and I couldn't load the new world either.

Also, how do I use pastebin?

**Comment by MJRLegends** [comment]
You will need to update to latest mod pack version as there's no reason to be using a old version and yeah you will need to start a new world since your old one is messed up now, also make sure to make backups of your worlds incase this happens again
