### ISSUE TITLE
Starting quests

### ISSUE THREAD

**Issue by GManitie** [MJRLegends/Space-Astronomy-Feedback-#891]
in the starting quests you are asked to make wooden pickaxe parts only problem is the only wooden pickaxe head you can make is a magical one so it be cool if you could change the quest to makle a flint bone or some other simple material

**Comment by MJRLegends** [comment]
No you can make a normal wooden pickaxe head??

**Comment by GManitie** [comment]
idk i cant for some reason even using normal minecraft wood 
![image](https://user-images.githubusercontent.com/29692699/27524765-dffc6a8c-59fd-11e7-840b-a880259ec8f6.png)
