### ISSUE TITLE
stuck at loading screen 5/7 phase 5

### ISSUE THREAD

**Issue by Anasboko** [MJRLegends/Space-Astronomy-Feedback-#892]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
[Description of the issue]
stuck at loading screen whenever it comes to 5/7

### Steps to Reproduce Issue
1. ?
2. ?

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
no crash log

**Version of Mod Pack using:** [VERSION] 1.6.7

### Additional Information
[Any other information that may be able to help me with the problem]
so when i launch the modpack it loads all mods but when it comes to 5/7 phase 5 it just stops
i havent tried anything but i need some help

**Comment by Anasboko** [comment]
anyone? mjrlrgend?

**Comment by MJRLegends** [comment]
Im unable to help if you dont actually fill out the information needed to fix it

**Comment by Anasboko** [comment]
but what information

**Comment by Anasboko** [comment]
sorry but there is no information i can put well maybe

**Comment by Anasboko** [comment]
sriusly?!!!

**Comment by Anasboko** [comment]
no reply

**Comment by Anasboko** [comment]
how will i play!!!!!!!!!

**Comment by Anasboko** [comment]
answer me!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by MJRLegends** [comment]
Thanks for the spam you are being banned now :P
