### ISSUE TITLE
I can't look up

### ISSUE THREAD

**Issue by DIYdragon10** [MJRLegends/Space-Astronomy-Feedback-#893]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
I can't look up. It tries, but I keep looking down.

### Steps to Reproduce Issue
1. enter a LAN world
2. done

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** 1.6.6

### Additional Information
I haven't tried in singleplayer

**Comment by MJRLegends** [comment]
1.  Please test with v1.6.7
2. Please try with a new world
3. Please try in single player
4. Post latest.log and fml-latest.log files

**Comment by DIYdragon10** [comment]
I actually did have it in 1.6.7, I mistyped it. I have tried a new world and played singleplayer, nothing works.

**Comment by MJRLegends** [comment]
Does it work on any mod pack?

**Comment by MJRLegends** [comment]
ping @DIYdragon10

**Comment by FrozenDude101** [comment]
Not OP, but it works fine for me on singleplayer not open to LAN and when it is.
Maybe something to do with minecraft itself?
I know there was a bug with windows 10 where this would happen in some games.

**Comment by MJRLegends** [comment]
Yeah i cant see how this is a mod pack bug
