### ISSUE TITLE
Something to do with textures.

### ISSUE THREAD

**Issue by UltimateSpaceMan** [MJRLegends/Space-Astronomy-Feedback-#894]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yeah

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yeah
### Description of Issue
I'm launching the game it gets to stage 7 of the forge process stuff, goes through various textures and then closes! that's it ... it just crashes!

### Steps to Reproduce Issue
1. launch the game, and wait

**Crash Log/Log (if applicable):** https://pastebin.com/wdJ47Gbw

**Version of Mod Pack using:**  1.6.7

### Additional Information
I was running it fine last night, yet now it's just not even loading :(
PLEASE HURRY AND HELP        ⏲

**Comment by UltimateSpaceMan** [comment]
DON'T WORRY ABOUT IT!

**Comment by MJRLegends** [comment]
What you mean?

**Comment by MJRLegends** [comment]
Was it caused by a texture pack?

**Comment by MJRLegends** [comment]
Im closing this one as we have another issue ticket with the problem so might aswell all move this issue to one #895
