### ISSUE TITLE
Block type exception crashing Minecraft

### ISSUE THREAD

**Issue by tallyer** [MJRLegends/Space-Astronomy-Feedback-#896]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes

### Description of Issue
Failing to load save file. I recently lost a save file when updating the Space Astronomy pack through Twitch. Now I have a new world established I cannot access it. The main menu loads fine, but when I attempt to load my world it crashes Minecraft with a block type exception error: "The game crashed whilst exception getting block type in world. Error: java.lang.NullPointerException: Exception getting block type in world "

### Steps to Reproduce Issue
1. Opening saved world

**Crash log/Log (if applicable):**

[crash-2017-06-28_18.57.47-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/1109892/crash-2017-06-28_18.57.47-server.txt)

Have tried removing and replacing Ender IO mod but the problem continued.

**Version of Mod Pack using:** 
Space Astronomy 1.6.7
Minecraft Version 1.7.10 (modded) forge-10.13.4.1614

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/d6dfc7cc94fd1188cbeeff37442706af.png)
