### ISSUE TITLE
Space Astronomy

### ISSUE THREAD

**Issue by badplayz** [MJRLegends/Space-Astronomy-Feedback-#897]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

Version 1.6.7

### Additional Information
[Any other information that may be able to help me with the problem]

EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                  * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from RandomThings-2.2.4.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

I think this caused it

**Comment by MJRLegends** [comment]
Lol you havent even told me the issue or given any information on the issue haha

**Comment by badplayz** [comment]
I copied a part of the log down there

**Comment by MJRLegends** [comment]
You havent told me what your issue is, i cant guess that part

**Comment by badplayz** [comment]
my minecraft crashes when i want to open the world

**Comment by MJRLegends** [comment]
Then i need the crash log, what you posted isnt needed or isnt the cause

**Comment by badplayz** [comment]
how do i upload it here?

**Comment by MJRLegends** [comment]
Crash log/Log (if applicable): [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Comment by MJRLegends** [comment]
Please use pastebin.com ^^^

**Comment by badplayz** [comment]
https://pastebin.com/xBiMc6E1

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/d6dfc7cc94fd1188cbeeff37442706af.png)
Make sure you check and fill out the correct stuff dont just ignore it as it wastes time because you have to wait for a reply which if you checked the known issues you could of found this sooner

this is what tells you to check that

> Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING): [Yes or No]
