### ISSUE TITLE
Cant open the modpack

### ISSUE THREAD

**Issue by djzdaman1** [MJRLegends/Space-Astronomy-Feedback-#898]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
[Description of the issue]
 
The game crashes when I press play in the minecraft launcher and ive reinstalled everything but windows (well almost) and still cant get the game to launch, I was playing it the other day and I can play it on my laptop but not on my desktop anymore.

### Steps to Reproduce Issue
1. Reinstalled Modpack
2.  Reinstalled java and deleted minecraft folders from everywhere on my computer

**Crash log/Log (if applicable):** https://pastebin.com/BixYtKu9 This is all the log generated

**Version of Mod Pack using:** 1.6.6

### Additional Information
I have reinstalled and updated my graphics card drivers, I am using a rx480 4gb.

**Comment by MJRLegends** [comment]
I see no issue in the log so much be a launcher issue please contact the launcher your using support team
