### ISSUE TITLE
Massive Lag after updating to Vers. 1.6.8

### ISSUE THREAD

**Issue by 0Vesuv0** [MJRLegends/Space-Astronomy-Feedback-#899]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
### Description of Issue
[Description of the issue]
~~When updating the Version from 1.6.7 to 1.6.8~~ the mining World by Aroma1997 was flooded by fish in various chunks. When I started the map again there were about 12.000 Entities according to the GUI. 

It seems the fish spawning from the mod which was recently added causes the trouble.

![massivefish2](https://user-images.githubusercontent.com/30085660/28086718-3171b442-6680-11e7-811b-df249539fbc9.png)

A way to solve:
a) disabling the mod
b) You can edit the world with help of NBT Explorer to solve the problem. There were over 800 entrys of Entities in one Chunk which caused massive lag. You can solve the problem by deleting the chunks with massive entities. (I used the search function and searched for value fish. and this as long there were no fish's in the world.

![massivefish](https://user-images.githubusercontent.com/30085660/28082525-03c6ac80-6673-11e7-8b55-68c8da40aa20.png)
image shows where a chunk got **only** about 11513 Entities
### Steps to Reproduce Issue
1. [First step]
Entering the MiningWorld (default DIM6)
2. [Second step]
waiting for generating.
**Version of Mod Pack using:** [VERSION]
1.6.8
### Additional Information
[Any other information that may be able to help me with the problem]
Disabling the mod or setting a spawn limit.

**Comment by 0Vesuv0** [comment]
Updated! The issue does not occure while converting.

**Comment by Oftheball** [comment]
I had 100% cpu used server side when this mod is active after a while **without going to the mining world**. I went back to a normal state after disabling this mod.

**Comment by theindiandood** [comment]
After searching the JustAFewFish Minecraft forums thread, I located the fix. This was my process of fixing my server world. Back up your worlds before you do anything. I am not to blame if your world gets reset.

To fix the modpack: The standard config for Just a Few Fish (jaff.cfg) should start with 
`B:"Attempt Optifine Fix"=false`

NOTE: I copied my server world folder  to my singleplayer saves folder while attempting this fix. You should be able to do this without having to move it.

Modpack version:  1.6.8
**If you already loaded the world and are experiencing lag on your world**

1. Ensure Minecraft is closed to prevent issues.
2. Disable Just a Few Fish mod.
3. Reload modpack and open the world. When Minecraft asks if you want to continue with missing blocks/item. Click Yes. Once the world is loaded, close Minecraft.
4. Go to configs folder and open jaff.cfg and make sure the "Attempt Optifine Fix" is false. The general section should look like below.
```
general {
    # If this is true, alternate code will run to attempt to fix a bug
    # with optifine. Note that this code may cause issues and crashes,
    # so disable it if anything bad is happening. [default: true]
    B:"Attempt Optifine Fix"=false
}
```
5. Re-enable Just a Few Fish mod.
6. Reload Minecraft and your world, and you should be good to go!

**If you haven't loaded your world in the updated version of the pack**

1. Ensure Minecraft is closed to prevent issues.
2. Go to configs folder and open jaff.cfg and make sure the "Attempt Optifine Fix" is false. The general section should look like below.
```
general {
    # If this is true, alternate code will run to attempt to fix a bug
    # with optifine. Note that this code may cause issues and crashes,
    # so disable it if anything bad is happening. [default: true]
    B:"Attempt Optifine Fix"=false
}
```
3. Reload Minecraft and your world, and you should be good to go!

**Comment by Oftheball** [comment]
Thank you ! 👍 seems to be ok for me (my server is working fine again)!

**Comment by SOTMead** [comment]
17.5k cod in the garden water source block. Disabling the mod fixed the problem. I didn't even realise there was a fish mod in the SA pack.

**Comment by 0Vesuv0** [comment]
@theindiandood I tried your "fix", but the world (as soon as I entered) again loaded too many entities. It might be a solution if you have a high-end Computer which can handle all, however my Computer still struggle with the mass of entities.

**Comment by MJRLegends** [comment]
A fix will be out in the next 24hrs, dont worry
