### ISSUE TITLE
'Going to the End' quest bug.

### ISSUE THREAD

**Issue by iKrax** [MJRLegends/Space-Astronomy-Feedback-#90]
Found 2 issues with this quest. Firstly, the quest description says it requires 32 Endstone but the item requirement says 25.

Secondly, quest is not completable as Endstone requirement doesn't complete, no matter how much you hold.

Screenshot for proof: http://i.imgur.com/phVMdjd.png

**Comment by MJRLegends** [comment]
Please read closed issues before posting as this has been reported here #79
