### ISSUE TITLE
Server Problem 

### ISSUE THREAD

**Issue by Robbina17** [MJRLegends/Space-Astronomy-Feedback-#900]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
My friend and I played your modpack for a few hours with the server for 1.6.7. Since yesterday we have the problem that we couldn't load our server. It just stopped loading. Then we copied our world to the save-folder from singleplayer and played on LAN. It worked. But today we couldn't even start the singleplayer world. We can't find out where the problem comes from. The last thing we did ingame was establishing a quarry in the mining world with a big reactor. Everything worked fine. 
We have a crash-report but can't find out the problem. There is too many text. 
We tried to load another world with the server and had the same problem. 

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** https://pastebin.com/XKR6ScyU

**Version of Mod Pack using:** 1.6.7

### Additional Information
We tried to use the new version 1.6.8 for the game and for the server but still have the problem. 
We tried it on different computers but can't find a solution.
We added IguanaTinkersTweaks to the modpack and it worked fine.

**Comment by MJRLegends** [comment]
This is a known issue see issue #1

**Comment by MJRLegends** [comment]
Yours is 6 in the top list of issues
