### ISSUE TITLE
Oxygen Gear +Thermal Padding Disappeared

### ISSUE THREAD

**Issue by SpongeMatthew** [MJRLegends/Space-Astronomy-Feedback-#901]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
When i logged on i noticed that in my Galacticraft tab that my oxygen stuff and thermal Padding were gone i relogged and restarted my launcher but its still not there i suffocate in space but when i press f5 i see my oxygen gear on my body

### Steps to Reproduce Issue
1. 
2. 

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:**  1.1.4

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Was this meant for Space Astronomy 2?

**Comment by SpongeMatthew** [comment]
Yeah  Space Astronomy version 2 sorry

**Comment by MJRLegends** [comment]
Ok was it on frozen soul servers?

**Comment by SpongeMatthew** [comment]
Yes

**Comment by MJRLegends** [comment]
Please reproduce on single player as i think sponge will be the cause of this haha if you can reproduce it then please open a issue on SA2 issue tracker
