### ISSUE TITLE
Mod not working properly

### ISSUE THREAD

**Issue by wstrongvi** [MJRLegends/Space-Astronomy-Feedback-#902]
I recently tried to go to a planet but when I pressed it the map disappeared and I couldnt do anything please help

Thanks,
Wstrongvi

**Comment by MJRLegends** [comment]
Im unable to help with the level of detail you have provided, thats why the template which you deleted is there so that i can make sure the detailed is provided. Please edit your issue and use the template and provide more details and i will reopen the issue for you :)
