### ISSUE TITLE
Bounding Box issue with MFR Conveyor belt

### ISSUE THREAD

**Issue by ZEROZEROZE** [MJRLegends/Space-Astronomy-Feedback-#903]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** yes
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
The conveyor belt's bug
the monster can use conveyor belt to penetrate the block and attack player
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]
1.6.8 version
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by theindiandood** [comment]
[Just confirmed](http://imgur.com/a/62Djl). The bug is from MFR conveyor belts. The conveyer belt added by Immersive Engineering and Extra Utils shouldn't have the same issue.

**Comment by MJRLegends** [comment]
Added to know issues, its number 17 in the "Current Main Mod Mod Pack Bugs" list
