### ISSUE TITLE
Ender Storage Causing world to not load

### ISSUE THREAD

**Issue by kikisuu** [MJRLegends/Space-Astronomy-Feedback-#905]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
Can't start up my world, every time it says "loading" then goes back to the main game screen. 

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** https://pastebin.com/eSL5TpPV

**Version of Mod Pack using:** 1.6.9

### Additional Information
Problem was solved by deleting Enderstorage Data file (I assume it was corrupted) in the enderstorage folder in my world save. I just wanted to report this for anyone else experiencing issues.

**Comment by MJRLegends** [comment]
Ok thanks yeah its a rare random issue but thanks for the report :D
