### ISSUE TITLE
[1.1.5] [client side] [NEI] massive log spam

### ISSUE THREAD

**Issue by MillionLights** [MJRLegends/Space-Astronomy-Feedback-#907]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes

### Description of Issue
- Massive and continuous log spam from NEI (client side)
- The spam starts as soon as you open any form of inventory for the first time
- After that, it never stops no matter what you do.
- Even after logging out and going back to the main menu the spam continues

### Steps to Reproduce Issue
1. update modpack to 1.1.5
2. open inventory
3. check log

Isolated log part that keeps on repeating [1000 lines of code (!)]:
https://pastebin.com/p4uiWW1q

full log:
https://gist.githubusercontent.com/MillionLights/3864d43ab3f16bf62fc6b728fabca32f/raw/ad45afe3f34470ff2e06fe8a0509d1d9ee402eeb/gistfile1.txt

- unable to provide pastebin link
- smallest uncompressed (plain text) log I was able to generate is 5MB
- logspam causes .log files of 400+MB

### Additional Information
I added (and removed) the following mods before and after inspecting the bug
(doesn't affect the bug)
- TwitchIntegration_1.10.2-2.1.13
- BetterMinecraftChat_1.10.2-4.1.6

    Minecraft: 1.10.2
    Forge: 1.10.2-12.18.3.2316
    ModPack Version: 1.1.5

logfile:
[2017-07-19-4.log.gz](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/1159078/2017-07-19-4.log.gz)

**Comment by MJRLegends** [comment]
You have posted this in the wrong issue tracker lol Try posting it here https://github.com/MJRLegends/Space-Astronomy-2-Feedback-
