### ISSUE TITLE
still cant make a wooden pickaxe head

### ISSUE THREAD

**Issue by GManitie** [MJRLegends/Space-Astronomy-Feedback-#908]
i cant make a wooden pickaxe head i try to with a pickaxe head stencil and a part station with a piece of wood

Version 1.6.9

![image](https://user-images.githubusercontent.com/29692699/28400550-7da60df4-6cd9-11e7-8ebe-59bbd60274e6.png)

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/0daf54139b1562c437da74552a9c883c.png)
Im able to, have you added or removed any mods, also which wood are you using Birch Planks?

If you look the stats of the Wood on the left is different on yours?

**Comment by GManitie** [comment]
i am reinstalling the modpack right now but the stats are different and yes its birch planks and no i havent added any mods

**Comment by MJRLegends** [comment]
I think something is broken on your side.....

**Comment by GManitie** [comment]
ya i think if i reinstall it then it might work

**Comment by GManitie** [comment]
alright thanks i reinstalled it and it works now but im pretty sure i installed Archimedes' Ships totally forgot and wouldnt think it would change anything.

**Comment by MJRLegends** [comment]
Ok :D
