### ISSUE TITLE
Game crashes on world load

### ISSUE THREAD

**Issue by Spaceball12** [MJRLegends/Space-Astronomy-Feedback-#909]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
I have a world where ive gotten pretty far in - played about 30 hours of it - and, for no apparent reason, every time i try to load it, it shows my hotbar and the world but without terrain, and then crashes a tick or so later with the message "The game crashed whilst ticking memory connection
The game crashed whilst ticking memory connection
Error: java.lang.NullPointerException: Ticking memory connection"
RAM might be the problem?
### Steps to Reproduce Issue
Not sure what I was doing at the time that might've made that happen, so if it is reproduceable then idk how.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/w7SvuwAM
**Version of Mod Pack using:** [VERSION]
1.6.9
### Additional Information
[Any other information that may be able to help me with the problem]
I can give specs if you want, but unless RAM is the problem idk if that will help so i wont

**Comment by MJRLegends** [comment]
Ok i got some ideas of a fix

Test 1:

1. Try a new world
2. Report back if it works

Test 2:

1. Copy/Backup your worlds
2. Reinstall mod pack
3. Copy worlds back
4. Test

Test 3:

1. Remove PlayerAPI mod
2. Load pack and world
3. Readd PlayerAPI to the pack

**Comment by Spaceball12** [comment]
Alright, thanks for the suggestions. I'll test it out soon.

**Comment by Spaceball12** [comment]
On Test 1: new worlds function without any crashing as far as I can tell.
On Test 2: still crashes
On Test 3: still crashes....

**Comment by MJRLegends** [comment]
Try deleting your player data, if not your world is messed up sorry :D
