### ISSUE TITLE
Buged Crop Sticks

### ISSUE THREAD

**Issue by XXXTheOnlyOneXXX** [MJRLegends/Space-Astronomy-Feedback-#910]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
The Crop sticks are brocken

### Steps to Reproduce Issue
1. Till dirt
2.Place crop sticks
3.Wait

**Version of Mod Pack using:** [v1.1.7]

### Additional Information
I got some  pictures for you so you can see see bug 
![2017-07-23_22 53 53](https://user-images.githubusercontent.com/30393653/28502857-bf91c558-6ffb-11e7-8a7a-1b01bd00887d.png)
![2017-07-23_22 54 51](https://user-images.githubusercontent.com/30393653/28502855-bf8d1e90-6ffb-11e7-99fa-0b3c04d65b91.png)
![2017-07-23_22 54 58](https://user-images.githubusercontent.com/30393653/28502856-bf8fa020-6ffb-11e7-9e36-ad65a626f7b6.png)

[https://www.mediafire.com/folder/i13g8edgw3r3nn7,o5awaofh3m6db0f,gdgwkde9b4gg76a/shared](url)

**Comment by MJRLegends** [comment]
Wrong mod pack

**Comment by MJRLegends** [comment]
Read what i have put on your issue https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/56

**Comment by XXXTheOnlyOneXXX** [comment]
Oh sry i still thoght i am at Space Astronomy 2 sry
