### ISSUE TITLE
Game Lag

### ISSUE THREAD

**Issue by vikas-ahuja** [MJRLegends/Space-Astronomy-Feedback-#911]
### ---Issue Report---
**I have not checked the known issues page

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** No
### Description of Issue
Every two minutes the screen freezes 

### Steps to Reproduce Issue
1. Mine block
2. Place Block

or

1.Walk at least three blocks

**Version of Mod Pack using:** I don't know

**Where did this bug happen:** Single Player

**Comment by MJRLegends** [comment]
Im not able to help with this level of detail so im closing this, i will reopen when more detail has been added
