### ISSUE TITLE
SquidAPI chat error - starting sentence with "about" - error

### ISSUE THREAD

**Issue by trebiluk** [MJRLegends/Space-Astronomy-Feedback-#912]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] YES

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue 
On chat start with the word "about" - this error in light red - "[http://prntscr.com/g0gx83](http://prntscr.com/g0gx83)"

### Steps to Reproduce Issue
1. Space Astronomy 1.6.9
2. Thermos 1614.57
3. Server
4. Say 'about' in chat

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
[No Console Log - chat canceled]

**Screenshots (if applicable):**[1]( http://prntscr.com/g0gx83)

**Version of Mod Pack using:** [1.6.9]

**Where did this bug happen:** [Server]
### Additional Information
[There is a new SquidAPI Hotfix 1.1.1.5 at https://minecraft.curseforge.com/projects/squidapi/files for 1.7.10]

**Comment by MJRLegends** [comment]
@trebiluk Thanks for the bug report do you know if the SquidAPI Hotfix 1.1.1.5 fixes this issue?

**Comment by trebiluk** [comment]
Did not make it that far in testing.  No changelog on the plugin pages
either :-\

**Comment by MJRLegends** [comment]
Yeah i will contact the dev and ask him

**Comment by MJRLegends** [comment]
Im already using the SquidAPI Hotfix 1.1.1.5 version
