### ISSUE TITLE
play selected world button is grayed and saved worlds can't be selected.

### ISSUE THREAD

**Issue by AAAARGHHH** [MJRLegends/Space-Astronomy-Feedback-#913]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** YES

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** YES
### Description of Issue:
Hey there, 

It only happen in Space Astronomy .
Into the select world menu , play selected world button is grayed and saved worlds can't be selected.
It only give option Create new world and Cancel. 

The game was doing normal when I originally started to play few days ago. The problem occurred 
when I accidentally clicked on the close button instead of minimize. 
Since than I cannot start any saved world ..

I changed few Java versions - nothing worked.
I removed/deleted all the game folders and installed in different locations.
Created few different Twitch accounts , and downloaded few times the pack .. nothing happened..
the fu#$%$#!! button is still grayed and I still cannot continue from where I left .

Tried Space Astronomy 2 working perfectly, however ..it is not the game I want 
Tried the basic 1.12 work fine!

Please let me know of possible resolutions if you are familiar with the issue already.
I have tried almost everything ,   and it looks like the game doesn't acknowledge that there is a save in the save folder although it display that there is a save there... 

### Steps to Reproduce Issue
1. [First step] - I dont know 
2. [Second step]  - I dont know

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/30468495/28621678-69a83b38-721a-11e7-92c9-9cc59f72d2b1.png)

**Version of Mod Pack using:** [1.6.9]

**Where did this bug happen:** Single Player

### Additional Information
[Any other information that may be able to help me with the problem]
Just let me know what do you need as an additional information

**Comment by MJRLegends** [comment]
https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/885
