### ISSUE TITLE
Bug Mausrad

### ISSUE THREAD

**Issue by Gamerline14** [MJRLegends/Space-Astronomy-Feedback-#914]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] YES

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] YES
### Description of Issue
[Description of the issue] Mehrere Spieler haben das Problem das sie mit dem Mausrad keine Items mehr verschieben können.

[VERSION] 1.6.9

**Where did this bug happen:** [Single Player or Server] Server and Single Player

### Additional Information
[Any other information that may be able to help me with the problem] Ja man kann selbst testen ob es möglich ist. In das Spiel gehen und versuchen mit dem Mausrad Items von einer Kiste in das Inventar zu schieben. Es wird nicht möglich sein

**Comment by MJRLegends** [comment]
English: I've turned that feature off so it can not be used

German: Ich habe diese Funktion ausgeschaltet, damit sie nicht benutzt werden kann

**Comment by Gamerline14** [comment]
Schade das es nun aus ist. Es war eine Erleichterung zum Craften oder herausnehmen von gegendständen. Wäre schön wenn sie es beim nächsten Update wieder mit hinein nehmen können, danke

MfG 
Gamerline14
