### ISSUE TITLE
Number keys crash game in main menu and close chat ingame

### ISSUE THREAD

**Issue by pokeemerald** [MJRLegends/Space-Astronomy-Feedback-#917]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
When trying to press the normal number keys in main menu, the game crashes, and when pressing them ingame they close the chat immediately, the do work as selecting an item in the hotbar though

### Steps to Reproduce Issue
1. Start game
2. Press number key

**Crash log/Log (if applicable):** https://pastebin.com/8AqseYzj

**Screenshots (if applicable):** 

**Version of Mod Pack using:** 1.7.0

**Where did this bug happen:** Main Menu, SP and MP

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
I need the full crash log 

Example of how to get it
*How do i to locate a crash log? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Comment by pokeemerald** [comment]
Here you go!
https://pastebin.com/f5Q4N9vJ

**Comment by MJRLegends** [comment]
Thanks will be fixed in the next update

**Comment by MJRLegends** [comment]
(v1.7.1)

**Comment by oodgaard** [comment]
From the pastebin, looks like I have the same error, but it's when I'm trying to add/edit a multiplayer server. Given that I cannot add my new server I just changed to, I'll have to try SA 2 now :)

**Comment by MJRLegends** [comment]
@oodgaard as said above its been fixed and the update for the mod pack has been submitted im waiting for ftb to process it

**Comment by slyons** [comment]
It's not a crash, but the number keys seem to be closing any GUI that I have open. Same issue?

**Comment by pokeemerald** [comment]
Yes, and they crash the game in the main menu

**Comment by MJRLegends** [comment]
I know about the issue and its been fixed so please just wait for the update

**Comment by MJRLegends** [comment]
Update is out
