### ISSUE TITLE
Forge mod loader has found a problem with your minecraft installation.

### ISSUE THREAD

**Issue by MaxPlaysYT** [MJRLegends/Space-Astronomy-Feedback-#918]
It always does this. Screenshot below. Pls halp!

![space](https://user-images.githubusercontent.com/30636182/28843747-95edce46-7702-11e7-9a1b-a2f2f4017e1a.png)

**Comment by MJRLegends** [comment]
Delete the mod pack and reinstall the pack, make sure to backup worlds and dont add or remove any mods as that could be why its doing it too :D
