### ISSUE TITLE
Quest Suggestions and various quest bugs.

### ISSUE THREAD

**Issue by iKrax** [MJRLegends/Space-Astronomy-Feedback-#92]
## Suggestions
* Add AE2Stuff related quests to 'Storage System'.
* Quantum Link Ring quest in 'Storage System'. 
* Divide machines and equipment into several sections (e.g. Power Production, Thermal Expansion (incl addons like Thermal Dynamics), Mekanism etc).
* Add a Possible a 'learn to fly' quest line or something similar requiring crafting jetpacks/gravichestplate etc.
* Add an advanced genetics quest line (since this mod is rather under documented. (It's not hard I know, but many people do not know the  mod).
* Add sync quest to "Getting Started" (Honestly I didn't even know this mod was in the pack for a long time, it's so small and doesn't stand out in NEI).
* Add a RotaryCraft questline (Mainly because explaining rotary craft to everyone else playing the pack is tedious).
* Add Electrical age questline. 
* Add ReactorCraft questline (possibly merge to previously mentioned "Power Production".
* Add some sort of hoarding quest line (A lot of people enjoyed these from AS1, would be fun).
* Possible add Steve's Factory Manager (This is honestly personal preference, I like this mod and it would help with complex designs).
 
## Bugs
* 'Crafting Fronos Rock Tools' quest has no reward, therefore cannot be completed.
* Rotating some IC2 blocks with the crescent hammer crashes to desktop (TE/IC2 issue I know, but thought I'd mention it). 
* Shift Clicking Unstable Ingots out of the crafting menu will instantly block them up. Not sure if intended or mod update. (It's 4am I'm too tired to check this).

Sorry for long issue. Just a lot of things I've thought/noticed while playing through. Will add more here instead of creating multiple issues if I notice anything else.

**Comment by MJRLegends** [comment]
Will have to report the last to issues to the mod developers at some point :D

1. Rotating some IC2 blocks with the crescent hammer crashes to desktop (TE/IC2 issue I know, but thought I'd mention it).
2. Shift Clicking Unstable Ingots out of the crafting menu will instantly block them up. Not sure if intended or mod update. (It's 4am I'm too tired to check this).

**Comment by iKrax** [comment]
##Issues
"Access to the mining world" quest has no reward, therefore can never be completed.

###Question/Offer
If you want any assistance with the quest writing side of things, I wouldn't mind helping. I'll add some example quests in the current HQM file so you can see what I was going for and upload it here at some point.

**Comment by MJRLegends** [comment]
Btw the quest can be completed you just get nothing for doing it

**Comment by iKrax** [comment]
Yeah, sorry badly explained. A basic reward would add to the quest though. For example, the reward could be 16 Iron ore, 16 Copper ore, 16 Lead ore, and 16 Silver ore. This way the player actually gets to click the 'Claim Reward' button.

**Comment by MJRLegends** [comment]
I know a reward will be added at somepoint

**Comment by MJRLegends** [comment]
The next update will have more new quests

**Comment by iKrax** [comment]
Ah cool! Sounds like a fun update :)

**Comment by MJRLegends** [comment]
I need the crash log that was made from this, to be able to report this to the mod developer "Rotating some IC2 blocks with the crescent hammer crashes to desktop (TE/IC2 issue I know, but thought I'd mention it)."
