### ISSUE TITLE
Biomes O' Plenty have no End dimention ore

### ISSUE THREAD

**Issue by fixfell7** [MJRLegends/Space-Astronomy-Feedback-#920]
### ---Issue Report---
**Have you checked the Known Issues page:** Yes

**Have you checked Open/Closed Issues:** Yes
### Description of Issue
The end dimention doesn't have Biomes O' Plenty ore.

### Steps to Reproduce Issue
1. Go to the end
2. See that there is no Ender Amethyst Ore and Biome Essence Ore

**Screenshots:** 
![1](https://user-images.githubusercontent.com/30707948/28949165-ecd586d6-7888-11e7-9e0f-8f4de15e6ad5.PNG)
![2](https://user-images.githubusercontent.com/30707948/28949247-75c6c0cc-7889-11e7-8b9f-ebc10a749871.PNG)

**Version of Mod Pack using:** 1.7.1
1.7.1 (in 1.7.10)
**Where did this bug happen:**
 In single player and server.

**Comment by MJRLegends** [comment]
Did you generate your world as Biomes o Plenty?

**Comment by fixfell7** [comment]
I tested, as Biomes o Plenty and normal, and there is no ore (just Mimichite).

**Comment by Spellkaze** [comment]
I think that was not fully implemented for this version of minecraft, there was a place called Promised land where you found it, such thing was removed way years ago and the ores were relocated to the End by the 1.8.9 and 1.9.4 versions of minecraft. This applies to the biome essence ore, celestial crystals and ender amethytst, judging by the last update of the mod for1.7.10, i doubt they are going to be for this version unless @MJRLegends  wants to re-add them by himself through code.

**Comment by MJRLegends** [comment]
Thanks @Spellkaze for the message
