### ISSUE TITLE
Corrupted galacticraft server file

### ISSUE THREAD

**Issue by kubeleq** [MJRLegends/Space-Astronomy-Feedback-#921]
---Issue Report---

Have you checked the Known Issues page: Yes

Have you checked Open/Closed Issues: Yes

### Steps to Reproduce Issue
1. Download server files for version 1.7.1 (1.7.10 minecraft).
2.Get this message while unpacking.

![corruptedfiles](https://user-images.githubusercontent.com/30746869/28994385-593805de-79cd-11e7-9af7-258f38984f73.png)

3.Unpack anyway.

![crashmmm](https://user-images.githubusercontent.com/30746869/28994405-d3f7bd78-79cd-11e7-9be5-f9d85d59a5b6.png)

ServerStart.bat tells me there isn't galacticraft in mods folder, I searched and there isn't one in mods folder.
Downloading new files directly from galacricraft page seems to fix the problem.

Version: 1.7.1 modpack, minecraft 1.7.10.

Multiplayer only.

**Comment by MJRLegends** [comment]
Sorry for the lack of reply im trying to get this fixed as the files on my side and the one i uploaded are fine but the ones on the ftb server are messed up somehow.... but you can download the Galacticraft jars here https://ci.micdoodle8.com/job/Galacticraft-1.7/ and delete the old ones

**Comment by MJRLegends** [comment]
@kubeleq Or download them here and they will be fine https://www.dropbox.com/s/gdomjpikgdl6hbi/%5B1.7.10%5D%20Space%20Astronomy%20Server%20Files%201.7.1.zip?dl=0

**Comment by MJRLegends** [comment]
Should be fixed now

**Comment by MJRLegends** [comment]
Please redownload them should be fixed now
