### ISSUE TITLE
crash upon checking recipe for compressed desh from galacticraft 

### ISSUE THREAD

**Issue by analoguy** [MJRLegends/Space-Astronomy-Feedback-#924]
Confirmed by my own attempt at repetition.  Happened twice in a row.  

### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
### Description of Issue
[Description of the issue]
recipe check crashes for compressed desh
### Steps to Reproduce Issue
1) check the recipe for what I think was compressed desh, lagout and crash, item selection glow still visible in box.    
1. open quest book, get to laser gun under tools, hit r while hovering over the laser gun, hit r again on compressed desh... lagout and crash
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
https://pastebin.com/WyDuRCSz
start reading at: micdoodle8.mods.galacticraft.core.nei.IngotCompressorRecipeHandler$CompressorRecipe.getOtherStack(IngotCompressorRecipeHandler.java:236)

Sorry about the slow update on the report before.  Please reopen the issue, I realized I had somewhere to be.  Thanks for the work maintaining this project, it is the first modpack I have liked enough to really get back into minecraft.  I am a fellow dev, though more of a linux, python, c/c++, sql, hardware, software, and firmware guy.  
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please put some work in to actually filling out the templete and including the crash log

**Comment by analoguy** [comment]
crash log given, looks to be a recipe handler issue or a missing recipe.  Please reopen the issue, thanks.

**Comment by MJRLegends** [comment]
Please fill out the following

Version of Mod Pack using: [VERSION]
Where did this bug happen: [Single Player or Server]

**Comment by MJRLegends** [comment]
Also i cant reproduce this, any change you could make a video showing how you are doing it, and does it happen everytime?

**Comment by analoguy** [comment]
It happens every time, consistently.  I did it 3 times in a row.  I would
start the saved game up and fairly quickly go to either the item search or
the quest book.  I would get to the compressed desh item or containing
recipe, hit r for recipe while hovering over it, see a white highlight
around the compressed desh in the crafting box or the item search screen on
the right and freeze to crash.  I suspect an infinite loop as I may have
heard a minor fan spinup on crash.

Hardware/software spec: custom desktop i7-4790, gtx980, gigabyte mobo, 16gb
of 2400mhz ram, 4gb allocated to Java.  I am using twitch client.  No
custom Java options, no extra mods, haven't yet updated gpu drivers but I
doubt it's that.

I can't investigate too much into save game specific wierdness now as my
save game got corrupted while going to the nether to get my ender tank of
lava on that side loaded.  My life as a student got busier too.  I should
really get a save game backup utility, were I in Linux, I would write it
myself in bash or python.
Unfortunately I am stuck in windows 10 because of games and Fusion360.
 There should really be a Minecraft feature that backs up before
transferring dimension.  I will try to make a video later if I get time.

On Aug 12, 2017 6:58 PM, "MJRLegends" <notifications@github.com> wrote:

Also i cant reproduce this, any change you could make a video showing how
you are doing it, and does it happen everytime?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/924#issuecomment-322011014>,
or mute the thread
