### ISSUE TITLE
Won't Log UP!!!

### ISSUE THREAD

**Issue by HumanJourney** [MJRLegends/Space-Astronomy-Feedback-#925]
![image](https://user-images.githubusercontent.com/30988197/29253644-e384bcd0-8050-11e7-95bd-ca0b73ea60f6.png)

I am hoping the image works!!! My brother and I play a world together my brother has it on his computer and it does this. he clicked yes brings him back to here. Clicks no same thing. he tried to delete that file but it didn't work!!! Can anyone tell me if its a glitch or it can be fixed one of my favourite parts and we got so far finally!!

**Comment by MJRLegends** [comment]
Your save is broke i can't fix that you need to restore to a backup

**Comment by HumanJourney** [comment]
I don;t know if you can just explain to me what that means? MJRLegends. How do I restore a backup?

**Comment by MJRLegends** [comment]
You need to start a new world, the backups would of had to be made by you.

**Comment by MJRLegends** [comment]
If the yes button doesnt work do above ^^

**Comment by HumanJourney** [comment]
Is there a reason this is happening?

**Comment by MJRLegends** [comment]
No idea

**Comment by HumanJourney** [comment]
So its a problem on your end or our computer

**Comment by MJRLegends** [comment]
Probably your world didnt save correctly or something its not mod pack related so im unable to fix it
