### ISSUE TITLE
Inventory Cleared

### ISSUE THREAD

**Issue by XDefoeRedstoneX** [MJRLegends/Space-Astronomy-Feedback-#926]
My INventory Is cleared after i save and quit the next day i play again then my inventory have nothing een the challenge book
But My House Is still there

Im in singleplayer
 That is really weird

**Comment by MJRLegends** [comment]
Does it do it on a new world?

**Comment by Timeworp17** [comment]
i also am having this problem. yes it happens to me in every world every time i lode up the saves. completely wipes my inventory and drops me at the spawn point. even if i sleep first. then it gives me 2 books, open computers manual and materials and you volume 1. love the mod pack but am getting anoid at this bug pleas help.
