### ISSUE TITLE
Is this intentional?

### ISSUE THREAD

**Issue by Ellipzocore** [MJRLegends/Space-Astronomy-Feedback-#927]
This mod pack might have a balancing issue when it comes to playing survival. One or several mods (I cannot find which mod(s) are causing this problem) disabled the vanilla crafting recipe for Flint and Steel, and now requires steel to be used instead. The only problem is that it seems that the steel can only be obtained after going to the nether, and with no flint and steel, you really have to jump through **a lot** of hoops which I think is rather excessive.

**Comment by MJRLegends** [comment]
No you can get steal though mekanism without going to the nether
