### ISSUE TITLE
openblocks glider

### ISSUE THREAD

**Issue by rexrapter1234** [MJRLegends/Space-Astronomy-Feedback-#929]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

yes

Each time I use the openblocks glider, it is making beeping sounds.

### Steps to Reproduce Issue
1. [First step] use the openblocks glider
2. [Second step] Use any of the buttons space bar, w,s,a,d or shift.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

I can add a video of the bug with needed ?

**Version of Mod Pack using:** [VERSION]

1.7.2

**Where did this bug happen:** [Single Player or Server]

Use the openblocks glider is used.

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by rexrapter1234** [comment]
It has been making the sound for some time now, just when to recorded a video or the bug sound from openblocks glider and the bug did not happen. So some how it fixed its self.

**Comment by MJRLegends** [comment]
You need to fill it all out...

**Where did this bug happen:** [Single Player or Server]

**Comment by rexrapter1234** [comment]
Server on sa1

**Comment by MJRLegends** [comment]
Its a server only issue due to the software they use, so i cant do anything sorry

**Comment by rexrapter1234** [comment]
Okay thanks
