### ISSUE TITLE
Performance collapse with 1.2.9

### ISSUE THREAD

**Issue by Berserker66** [MJRLegends/Space-Astronomy-Feedback-#93]
My server was running a solid 15-20 tps. Updated today to 1.2.9 and now it's down to 0.5 - 0.6 tps.
Note that client side tps and fps is fine (on windows anyway).

Server is running on:
Headless Ubuntu 14.04
Intel Core Duo
4 GB Ram
100 GB SSD
100/100 mbit

from top:

  PID USER  PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 7991 root      20   0 4993252 2,379g  26548 S 105,8 40,8  12:12.91 java

Note 106% CPU use.

We make heavy use of AE2/Mekanism in base and have a QuarryPlus in the mining age. Nothing else is chunk-loaded. The above usage is without anyone logged in.

**Comment by MJRLegends** [comment]
Try installing opis and use it to find what is causing the lag.

**Comment by Berserker66** [comment]
mean 305 ms update time on QuarryPlus' QuarryPlus
However, before the update that was not the case. Hm. I'll try replacing the block and see how that goes.

**Comment by Berserker66** [comment]
Well, it's better now. I suspect the lag comes from all the water that is now in the giant hole. Put down a Pumpplus and now it seems to slowly remove the source blocks and let the water settle. At the current rate, the water might take a few hours to disappear :(

**Comment by MJRLegends** [comment]
Yeah probably
