### ISSUE TITLE
Not really a bug, so you can delete this if you want, just a (very) small issue...

### ISSUE THREAD

**Issue by Pokemonpurson** [MJRLegends/Space-Astronomy-Feedback-#930]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

YES (An using all caps so my answers stand out)

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

YES

### Description of Issue
[Description of the issue]

I am playing on a Peaceful world (I know, I'm a wimp) and I would like to use the "Peaceful table" from Extra Utilities. The problem is that since Tinker's construct is installed, normal weapons have 1 durability, and the peaceful table does not support any Tinker's Construct weapons. I would try to uncheck the "vanilla weapons 1 durability" option in the mod configurations in game, but the modpack will not let me edit the mod options. Is it possible to implement this?  I know I can change to creative mode and change the difficulty to gather drops that way and to do some of the quests on the moon, but I'm new to programming so I can't edit the files directly... Sorry for bothering you...

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]

1.5.8

**Where did this bug happen:** [Single Player or Server]

SINGLEPLAYER

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Yeah you need to play on non Peaceful to be able to access everything
