### ISSUE TITLE
Space Astronomy error download

### ISSUE THREAD

**Issue by omerx552** [MJRLegends/Space-Astronomy-Feedback-#931]
![ekran alintisi](https://user-images.githubusercontent.com/31383165/29748658-3403b63e-8b23-11e7-86f5-75c9949094ab.PNG)

**Comment by MJRLegends** [comment]
Not a mod pack sorry

**Comment by MJRLegends** [comment]
The Twitch App mod pack install/update issues have been solved, You just need to switch to be using the Beta Version and then install or update the mod pack/s. This is how you change your launcher to the Beta Version: http://imgur.com/a/un33N
