### ISSUE TITLE
Evaporation Chamber and Chemical Injector Inconsistent Material Usage

### ISSUE THREAD

**Issue by BigDaddyJay76** [MJRLegends/Space-Astronomy-Feedback-#932]
### ---Issue Report---
**Have you checked the Known Issues page Yes
**Have you checked Open/Closed Issues Yes

### Description of Issue
Incorrect amount of materials are being outputted from the Basic Solar Evaporation Chamber & Basic Chemical Injector

### Steps to Reproduce Issue
1. Put 1 potash shard in the Evaporation Chamber, receive 1 potassium
2. Put a stack of potash shards in the Evaporation Chamber, receive 6 potassium. 
3. Any amount between 1 & 12 shards in the evaporation chamber at the same time will yield 1 potassium.

1. Put 1 potassium and 1 salt in the basic chemical injector, receive 1 Potassium Iodide
2. Put as stack of salt and a stack of potassium in the chemical injector and receive 11 potassium iodide, with 31 salt leftover
3. Putting more than 1 each in the injector uses up to 3 salt and 6 potassium per potassium Iodide process

**Crash log/Log (if applicable):** N/A
**Screenshots (if applicable):** N/A

**Version of Mod Pack using: 1.2.7

**Where did this bug happen: Server

### Additional Information
N/A

**Comment by MJRLegends** [comment]
You have posted this on the wrong mod pack issue tracker please repost on the correct one
