### ISSUE TITLE
I can't play any save more than once

### ISSUE THREAD

**Issue by Utaylan01** [MJRLegends/Space-Astronomy-Feedback-#935]
When i close modpack i can't open my old save i try 3 saves but i can't play any of them. Actually when i click on saves game didnt select any of them

**Comment by MJRLegends** [comment]
Please fill out the template, as it has much needed information. I will reopen when the issue has been edited

**Comment by MJRLegends** [comment]
Also remove any edits you have made to the pack also check out closed issues as this has been posted before

**Comment by MJRLegends** [comment]
#360
