### ISSUE TITLE
I cannot craft a machinist's workbench on version 1.7.2

### ISSUE THREAD

**Issue by Phanact** [MJRLegends/Space-Astronomy-Feedback-#937]
https://cdn.discordapp.com/attachments/247064367844032512/357771374841823232/unknown.png
https://puu.sh/xzmb3/671e407d43.png

Neither recipe works

**Comment by MJRLegends** [comment]
Yeah its been removed from NEI and there is no recipe as its disabled

**Comment by Phanact** [comment]
How then, can I enable it in the pack? Its necessary in the use of the cyclic assembler?

**Comment by MJRLegends** [comment]
Unless its in the recipe of the cyclic assembler then its not needed so will remain disabled

**Comment by Phanact** [comment]
The cyclic assembler does not come with predefined recipes I thought
Was that a change made recently?

**Comment by Phanact** [comment]
Oh yeah, upon further inspection, schematics are no longer necessary in the Cyclic assembler, you can define what you want to have be created on the right hand side.
