### ISSUE TITLE
Game dosnt load needs backup

### ISSUE THREAD

**Issue by diamondlord1000** [MJRLegends/Space-Astronomy-Feedback-#938]
I run this on a single player world and it says my world might be corrupted and I should make a backup, I did this and it still says I need a backup. I can click yes multiple times before it closes Minecraft and I have to re load the modpack. is there a fix please help! 
![minecraft 1 7 10 9_19_2017 9_23_37 pm](https://user-images.githubusercontent.com/32119605/30626759-dde174a6-9d80-11e7-9dde-a25ab7a94624.png)

**Comment by MJRLegends** [comment]
Your world is broke nothing i can do there sorry
