### ISSUE TITLE
Massive FPS drops every 5 seconds or when opening any inventory

### ISSUE THREAD

**Issue by Kozova1** [MJRLegends/Space-Astronomy-Feedback-#939]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]
yes
### Steps to Reproduce Issue
1. have same spoecs as me?
A10-6800K
16GB RAM
R9 380 4gb

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
`how much ram so you have assigned to mc`

**Comment by Kozova1** [comment]
how do I change it from the legacy FTB launcher?

**Comment by MJRLegends** [comment]
What is it current on?

**Comment by Kozova1** [comment]
where is that setting?

**Comment by Kozova1** [comment]
I changed it to max 4GB
let's see if it helps

**Comment by Kozova1** [comment]
OK SO ram WAS IT
