### ISSUE TITLE
Wooden Plank Recipes Bugged / Not Working

### ISSUE THREAD

**Issue by cjhrjone54** [MJRLegends/Space-Astronomy-Feedback-#940]
### ---Issue Report---
**Have you checked the Known Issues page:** [Yes]

**Have you checked Open/Closed Issues:** [Yes]
### Description of Issue
A lot of major recipes using Wooden Planks do not work (sticks, crafting tables, chests, doors, etc.). Blocks like stairs, BiblioCraft and other mod items/blocks will however work.

In this case, only Jungle Wood is making the correct recipes. Any other type of wood will not register as a recipe.
This also happened yesterday, where this time Jungle Wood was the non-working Wooden Plank in recipes. I thought this was part of the game initially since I got the Jungle Wood from rubber trees, so I thought it was unusable in crafting. When the problem replicated itself today, however, I knew it wasn't just Jungle.

This seems to be a recurring problem involving several different types of woods, with only one of them 'working' and the other ones not; and it changes which wood does what every time (yesterday was Jungle not working, now it's Oak and Spruce).
Normal recipes were working fine when I first logged on, and have only just stopped working again now.

My theory is that this is an item conflict with the Chisel mod, which somehow seems to be affecting every other wooden plank block. Since you can't craft items with Chiseled blocks, I wouldn't be surprised if this turns out to be true.

### Steps to Reproduce Issue
*I'm unaware of how this issue occurs, since it seems to happen unexpectedly/randomly. If I find a possible cause I'll post an update.

**Crash log/Log (if applicable):**
N/A

**Screenshots (if applicable):** 
![bug1](https://user-images.githubusercontent.com/32696049/31423820-9bcbf7b6-aea2-11e7-8126-9b2f95a0aba7.png)
![bug2](https://user-images.githubusercontent.com/32696049/31423822-9c124e32-aea2-11e7-858e-3bfd31260612.png)
![bug3](https://user-images.githubusercontent.com/32696049/31423823-9c45ab2e-aea2-11e7-880a-9c49ee383ee4.png)
![bug4](https://user-images.githubusercontent.com/32696049/31423824-9c7b8b54-aea2-11e7-9e00-051fc34a4a2a.png)
![bug5](https://user-images.githubusercontent.com/32696049/31423825-9cb0c026-aea2-11e7-973f-01add29e5da3.png)
![bug6](https://user-images.githubusercontent.com/32696049/31423826-9cf8f6d4-aea2-11e7-9e04-ecff75f6872a.png)
![bug7](https://user-images.githubusercontent.com/32696049/31423827-9d6aa4c8-aea2-11e7-91d0-a075f7f3bee7.png)

**Version of Mod Pack using:** [v1.7.3]

**Where did this bug happen:** [Single Player]

### Additional Information
Restarting the entire game seems to fix this problem, but it's awfully inconvenient to have to close MC and endure the long loading times just to fix a simple problem.

**Comment by MJRLegends** [comment]
Yeah your using the tinker table from tinkers not a crafting table

**Comment by cjhrjone54** [comment]
Even using a normal crafting table and the INV crafting doesn't work.
