### ISSUE TITLE
Mekanism machines disappearing upon breaking with silktouch pickaxe

### ISSUE THREAD

**Issue by laumichael73** [MJRLegends/Space-Astronomy-Feedback-#941]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** N/A
### Description of Issue
Using a tinker Obsidian pick with sponge as tool binder, breaking mekanism machines does not drop the machine as items.

### Steps to Reproduce Issue
1. Place mekanism machine
2. Break machine with said pickaxe (obsidian head, sponge binder, wooden tool rod)

**Version of Mod Pack using:** Space Astronomy 2 1.3.0

**Where did this bug happen:** Server

### Additional Information
Unable to recreate this in single player.

**Comment by MJRLegends** [comment]
Wrong issue tracker, This is for Space Astronomy 1 mod pack
