### ISSUE TITLE
Problem for Transport

### ISSUE THREAD

**Issue by iProMC** [MJRLegends/Space-Astronomy-Feedback-#942]
Hello i use  Dimensional Transceiver /Ender Chest to move my ore from earth to space staion when i go to space the teleporter stop else if my friend still near  Dimensional Transceiver /Ender Chest in earth

**Comment by MJRLegends** [comment]
You need to use chunk loaders

**Comment by iProMC** [comment]
how?

**Comment by iProMC** [comment]
how l found the chunk loders?

**Comment by MJRLegends** [comment]
Chunk loaders are block you need to craft them, type in chunk loaders in NEI
