### ISSUE TITLE
DNA analyzer bug

### ISSUE THREAD

**Issue by TheShadowSpirit** [MJRLegends/Space-Astronomy-Feedback-#943]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
A visual bug when using the DNA analyzer from Advanced Genetics.

### Steps to Reproduce Issue
1. Put any cells in the input slot (more than one). Provide power too.
2. On a random chance (i'd say 70% of the time), the bug will happen.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):**
https://gyazo.com/d251479e5e7494fce36584c6484b6fbf

**Version of Mod Pack using:** [1.6.6]

**Where did this bug happen:** [Single Player]

### Additional Information
[The DNA analyzer still works, though this bug is quite annoying.]

**Comment by MJRLegends** [comment]
Its a known issue and the mod isnt being developed anymore but thanks for the bug report also your mod pack version is very out of date
