### ISSUE TITLE
how do i launch it 

### ISSUE THREAD

**Issue by asssef** [MJRLegends/Space-Astronomy-Feedback-#944]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
How Do I Install Space Astronomy 1 & 2 On The New Twitch App? http://imgur.com/a/CYxre

How Do I Play A Mod Pack On The New Twitch App? http://imgur.com/a/cBNZs
