### ISSUE TITLE
Cauldron not compatible with mod pack. 

### ISSUE THREAD

**Issue by TheDukeofDoog** [MJRLegends/Space-Astronomy-Feedback-#945]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue] No

### Steps to Reproduce Issue
1. [First step] install cauldron for minecraft version 1.7.10
2. [Second step] Run the server

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them] Know issue is that the launch wrapper for the forge server included with the mod pack and the one used with cauldron are different. Cauldron uses 1.12 while the mod pack uses 1.11 in the net folder which is located in the libraries folder
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]
1.7.3
**Where did this bug happen:** [Single Player or Server]
Server
### Additional Information
[Any other information that may be able to help me with the problem]
I would like to add plugins to my server but don't seem to know a good jar to use or how to install one properly if that is the issue.

**Comment by MJRLegends** [comment]
Not a bug dude, theres kcauldron and thermos.
