### ISSUE TITLE
Minecraft server file does not route to mods.

### ISSUE THREAD

**Issue by tridings** [MJRLegends/Space-Astronomy-Feedback-#946]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
No
### Description of Issue
[Description of the issue]
The when the server is running (minecraft_server.1.7.10.jar) mods are not able to be placed. I do not believe this file is routed to the mod files in the mods directory.

### Steps to Reproduce Issue
1. Run the Server
2. Start the game in the server
3. Try to place a modded item
   - it will place and instantly disappear

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
This isnt a mod pack bug sorry

**Comment by tridings** [comment]
No worries. I'll tinker around with it.
