### ISSUE TITLE
Weird Visual glitch

### ISSUE THREAD

**Issue by alaskamounds** [MJRLegends/Space-Astronomy-Feedback-#948]
I do not know where or how to post this correctly. If you point me in the right direction, i am happy to post elsewhere.

I'm getting this weird glitch with my landscape/some blocks, and i don't know what to do. Some players are also rendering "translucent" the same way these blocks are.

My chest lids are also rendering weird.

I've attached screenshots, and I'm happy to do whatever else you need. The other players on the server are not having these same issues.

I'm in 1.7.10.

thanks!
![scrnsht1](https://user-images.githubusercontent.com/34013600/33247034-019bf4fa-d2e9-11e7-9585-2b623c800c9d.png)
![scrnsht2](https://user-images.githubusercontent.com/34013600/33247035-01a9e0ec-d2e9-11e7-87cf-db1328a0c9b3.png)
![scrnsht3](https://user-images.githubusercontent.com/34013600/33247036-01b51458-d2e9-11e7-8f2c-247ba220e825.png)
![scrnsht4](https://user-images.githubusercontent.com/34013600/33247037-01c35e78-d2e9-11e7-8e04-6f4275d6354c.png)
![scrnsht5](https://user-images.githubusercontent.com/34013600/33247066-3846b85a-d2e9-11e7-8298-54327c0d01bd.png)

**Comment by MJRLegends** [comment]
Are you using optifine?

**Comment by alaskamounds** [comment]
I am not. The only thing I have found online has blamed the chest lid problem on optifine, but I am only using the mods that are part of the pack.

**Comment by MJRLegends** [comment]
Please screenshot your video settings and post the screenshot here

**Comment by alaskamounds** [comment]
![scrnsht6](https://user-images.githubusercontent.com/34013600/33247682-0cef96f4-d2ee-11e7-97e0-6293b6b9cc11.png)

**Comment by MJRLegends** [comment]
Please try the following:

Try reinstalling the pack
Try removing fastcraft,
Try reinstalling java
Try reinstalling your GPU drivers

This isn't a pack related thing, it seems to be a OS/Issue with your certain setup

**Comment by alaskamounds** [comment]
I had already reinstalled java and my GPU. I tried removing fastcraft, and it did not fix either problem. Deleting and reinstalling the pack fixed the "ghost block" problem, but the chests are still broken. I can deal with weird chests, but that white business was awful. Thanks!

**Comment by MJRLegends** [comment]
Are you using a apple system?
