### ISSUE TITLE
Crops Hidden and not working for IC2

### ISSUE THREAD

**Issue by Holick364** [MJRLegends/Space-Astronomy-Feedback-#949]
### ---Issue Report---
Yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
Crops will not work, load or viable frome IC2

### Steps to Reproduce Issue
1. just search item in JEI
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots note applicable

**Version of Mod Pack using:** 1.3.6

**Where did this bug happen:** Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Its disabled so it won't work sorry

**Comment by Holick364** [comment]
Well is there reason for disabled? Without it its pain to harvest rubber which is needed to do most of IC2? Have another solution for rubber with you mod?

**Comment by MJRLegends** [comment]
You can still get rubber and its compatible with ic2
