### ISSUE TITLE
Minecraft doesnt start!

### ISSUE THREAD

**Issue by Sebixxu** [MJRLegends/Space-Astronomy-Feedback-#95]
Modpack Name: Space Astronomy

Modpack Version: 1.2.9 i think

Link to Log: http://pastebin.com/s1F85JgW

Extra Details: I dont know what i should do, please help.. I dont know what I should do.

**Comment by MJRLegends** [comment]
Try reinstalling the mod pack.

**Comment by Sebixxu** [comment]
now its work i force update in option :)

**Comment by MJRLegends** [comment]
Ok :D
