### ISSUE TITLE
it wont let me join frozensoul node 3

### ISSUE THREAD

**Issue by DragonianSoul** [MJRLegends/Space-Astronomy-Feedback-#951]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes i have

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
yes i have
### Description of Issue
it wont let me join the frozensoul sa3 server for space astronomy 1. it said exactly this... "Internal Exception: Java.Lang.NullPointerException"

### Steps to Reproduce Issue
1. launch modpack
2. try to join server

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using:** 1.7.4

**Where did this bug happen:** server

### Additional Information
no restarting of anything will fix the problem.

**Comment by MJRLegends** [comment]
They are not my servers, i dont own them

**Comment by badgernz** [comment]
Downgrade your client to 1.7.3, We have not updated yet. Make sure you check our twitter or servers versions page to see when you can update.

**Comment by DragonianSoul** [comment]
thank you
