### ISSUE TITLE
Can't insert tier 4 nose cone into Nasa Workbench

### ISSUE THREAD

**Issue by Rohmerr** [MJRLegends/Space-Astronomy-Feedback-#952]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue

I recently experienced the "Dark Asteroids Crash issue" #646.  I updated to version 1.7.3 of the modpack, which repaired that issue.  When I re-loaded the game, I re-spawned in mid-space without my rocket/landing pod.  I used a backup low tier rocket I was carrying to return to the Overworld.  Now when I attempt to build a new rocket of any tier (4,5,or 6) which requires a Tier 4 nose cone, the Nasa Workbench will not accept the nose cone into the designated slot.  All the other rocket parts will assemble correctly into their respective slots, but not the nose cone.  I have not found any reference to this in the "known issues" reports.]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [V1.7.3]

**Where did this bug happen:** [Single Player]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
If your playing space astronomy 1 this isnt the mod that is in it

**Comment by MJRLegends** [comment]
Thanks will take a look

**Comment by Rohmerr** [comment]
Thanks.  Yes, playing Space Astronomy 1, and yes, this mod is in it.  I had previously built a Tier 5 rocket to get to the Dark Asteroids, which was lost when I had the 'Dark Asteroids Crash issue'.  Now I cannot rebuild that rocket, and it won't let me build a Tier 6 rocket either.  Kinda' leaves me dead in space, so to speak.  I actually have two separate games going, starting from different world gens, running parallel.  Both games have experienced the same glitch after fixing the Dark Asteroids crash.

 

Kent (Rohmerr)

**Comment by MJRLegends** [comment]
Works ok for me 

Crafting Tier 6 Rocket
![](https://i.gyazo.com/9a076c2eed1c95409b7edfd561aaa72c.png)
