### ISSUE TITLE
Re: Failure to start 

### ISSUE THREAD

**Issue by yodarocks2000** [MJRLegends/Space-Astronomy-Feedback-#958]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] yes
### Description of Issue
[Description of the issue] The game lunches until it attempts to preInitialization of Decocraft, when it stops responding and crashes.

### Steps to Reproduce Issue
1. [First step] launch game
2. [Second step] wait for it to crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC
https://pastebin.com/kyS1ZB6N
**Screenshots (if applicable):** 
N/A
**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION] 1.7.5

**Where did this bug happen:** [Single Player or Server] launch sequence

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You need allocate more than 1gb of ram haha you wont be able to get any pack to load with that

**Comment by yodarocks2000** [comment]
how do I change that?

**Comment by MJRLegends** [comment]
How Do I Change My Ram Assignment/Usage For Minecraft On Curse/TwitchApp? http://imgur.com/a/MBcw8
How Do I Change My Ram Assignment/Usage on FTB Launcher? https://imgur.com/a/WP4lB
