### ISSUE TITLE
Help pb crash

### ISSUE THREAD

**Issue by Natha95150** [MJRLegends/Space-Astronomy-Feedback-#959]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

My launcher crash after 2 seconds and puts an error occurred and the game crashed.
![capture](https://user-images.githubusercontent.com/35466539/34957877-be9a6e16-fa2f-11e7-9d18-13bb1941ec2f.PNG)

**Comment by MJRLegends** [comment]
You have not filled out the issue template with the needed information, you need to supply the crash log too. i will reopen when done so

**Comment by Natha95150** [comment]
---Issue Report---
(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)

Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING): YES

Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING): YES

Description of Issue
My launcher crash after 2 seconds and puts an error occurred and the game crashed.

Steps to Reproduce Issue 
Start the launcher.
The crash appears after the launch.

Crash log/Log (if applicable): 
I do not have crash log in the folder.
Screenshots (if applicable):
![capture](https://user-images.githubusercontent.com/35466539/34959542-3d7fd0d4-fa37-11e7-9cd4-7ddb41e0b797.PNG)

Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'): VERSION 1.7.5

Where did this bug happen: Single player

Additional Information
![capture](https://user-images.githubusercontent.com/35466539/34959466-ec7c3ed4-fa36-11e7-8830-8c4574ab2b4a.PNG)

**Comment by MJRLegends** [comment]
Please post your fml-client-latest.log file, its located in the logs folder

**Comment by Natha95150** [comment]
[fml-client-latest.log](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/1632952/fml-client-latest.log)

**Comment by MJRLegends** [comment]
You need to redownload the pack, if not contact curse support as the pack isnt installing correctly

**Comment by Natha95150** [comment]
Thx for help

**Comment by MJRLegends** [comment]
No problem :D
