### ISSUE TITLE
Framerate Issues 

### ISSUE THREAD

**Issue by TheCaptain1** [MJRLegends/Space-Astronomy-Feedback-#96]
So I downloaded this pack about a month ago, and it's the best pack I've played in a long time. :D
But I am getting serious framerate issues. After around 10 mins of playing at 60-70 fps, it'll freeze for a few seconds, then the framerate halves to around 30-35. This continues until I am literally playing at 1 frame. This only happens on this pack; I have never experienced anything like this with other packs.
Restarting the pack seems to alleviate it, but this gets extremely tedious after while.

I would like to point out that I have a pretty decent computer, and hardware-wise, I should be able to handle this pack fine (I can run other large packs such as SkyFactory and Resonant Rise at 80+ fps).
I believe EzTerry touched on this matter on page 1 of the Space Astronomy thread; it only seems to happen on Linux.

I am using Sphax x64 with this pack (the Resonant Rise patch, as it covers most of the mods in Space Astronomy).

System Specs:

OS: Ubuntu 14.04 64-bit
Java version: 8
CPU: AMD A10-7700K Radeon R7
GPU: nVidia GeForce GTX 970, with latest nVidia driver
RAM: 16GB (with 5GB allocated to the FTB launcher)

I have tried installing OptiFine, which improves framerate but doesn't stop deterioration. I have also tried multiple GC optimisation commands in the launcher, but none seem to have much effect.

If anyone has an idea what's causing this I would love to know because this is pretty much unplayable. :(
Thanks

**Comment by MJRLegends** [comment]
Can you upload your world and post the link please so i can do some lag finding to get to the source of the lag

**Comment by TheCaptain1** [comment]
Not sure what you mean.
I'm playing on a multiplayer server.

**Comment by MJRLegends** [comment]
Have you ever used opis? and how much ram does your server have thats running the mod pack?

**Comment by TheCaptain1** [comment]
I've never used Opis - didn't know what it did until now. Should I install it?

I think the server uses around 10GB.

**Comment by MJRLegends** [comment]
Would you be open to allowing me to come on the server to find out the source of the lag

**Comment by TheCaptain1** [comment]
It's not my server but sure the IP is space.modrealms.net

**Comment by MJRLegends** [comment]
You will need to contact the sever owners then because it might be just players have machines and that in there base causing lag/

**Comment by TheCaptain1** [comment]
Ok I tried FTB Infinity just now and this seems to do the same, ATLauncher packs don't, however...

**Comment by MJRLegends** [comment]
Not sure maybe try reinstalling the FTB launcher and all the mod packs

**Comment by TheCaptain1** [comment]
Just found this - http://ftbforums.org/topic/2649-increasing-lag-on-a-powerful-machine/

Hey, at least I'm not alone...

"Bottom line was it needed more RAM available to Java" - Is this done in the launcher with optimisation arguments? Or is it a command prompt thing?

Reinstalling as we speak.
