### ISSUE TITLE
Report issue

### ISSUE THREAD

**Issue by T3ST0NE** [MJRLegends/Space-Astronomy-Feedback-#960]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]  Yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes
### Description of Issue
[Description of the issue]
When I open the serverstart button it crashes in a few seconds

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them] https://pastebin.com/raw/kPSXT7As
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION] 1.7.5

**Where did this bug happen:** [Single Player or Server] Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
No where near enough information, also you probably just need to accept the eula thing as it says in the console
