### ISSUE TITLE
packet with id 0 was not handled

### ISSUE THREAD

**Issue by LaneaLucy** [MJRLegends/Space-Astronomy-Feedback-#961]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] search function dont find anything
### Description of Issue
[Description of the issue]
I have build a big Frame Quarry, but if i move there foarward, the game disconnect from server with "packet with id 0 was not handled"

### Steps to Reproduce Issue
1. [Here](http://www.mediafire.com/file/nbqymvdk2qot94m/world.zip) is a download link from my world.
2. go to [this](http://prntscr.com/i2l46x) coordinates
3. here you see 3 wireles redstone receiver with 3 lever. First switch the lever with the 234 receiver on and off. Then switch the lever with the 123 receiver on and off. Last switch the lever with the 345 receiver on and of.
4. Crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

http://paste.feed-the-beast.com/view/a2f40cc7

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION] 1.7.5

**Where did this bug happen:** [Single Player or Server] Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
The log you provided, shows that you tried to join a server with mods removed either on the client side or server side, i dont see anything with a packet error. Please post the log containing the packet error and please make sure you havent edited the pack in anyway

**Comment by LaneaLucy** [comment]
I havent edited anything, i use the stock modpack from FTB launcher and use
the sever files from it too without any change...

Am 19.01.2018 14:36 schrieb "MJRLegends" <notifications@github.com>:

**Comment by MJRLegends** [comment]
Please post the log containing the packet error as the one you have posted doesnt seem to include the error message

**Comment by LaneaLucy** [comment]
dont find any log where it writed down. The message is only showed on the connection lost screen: 
http://prntscr.com/i8pmn6

[logs.zip](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/1686074/logs.zip)

**Comment by LaneaLucy** [comment]
and here the logs from server...

[server_logs.zip](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/1686091/server_logs.zip)

**Comment by MJRLegends** [comment]
Ok im 98% sure its a plugin that you have installed that is the issue. Please remove all plugins and test, if it still happens please post back
