### ISSUE TITLE
Server Crash Upon Death

### ISSUE THREAD

**Issue by beefingschmeefing** [MJRLegends/Space-Astronomy-Feedback-#963]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
While hosting Space Astronomy Server, the server will crash for everyone if someone dies. Does not happen 100% of the time, and it appears to only apply to certain players. I may be wrong however.

### Steps to Reproduce Issue
1. Replace Space Astronomy mods with server mods available for download from the main menu
2. Launch server with server file provided

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
https://pastebin.com/Fr2dszRi

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.7.5] (MODS WERE REPLACED WITH SERVER FILE MODS)

**Where did this bug happen:** [SERVER]

### Additional Information
The server crashes when someone dies, the most recent crash happened when slain by a zombie. 
Keep inventory is on.

**Comment by MJRLegends** [comment]
Your quest book data is corrupted it seems, delete the HardcoreQuesting folder on your server it will delete everyones progress for the quest book, you can use /hqm edit <username> to finish quests without actually doing them to get progress back for players.
