### ISSUE TITLE
Crashing upon loading world

### ISSUE THREAD

**Issue by theplastichero** [MJRLegends/Space-Astronomy-Feedback-#964]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
### Description of Issue
[Description of the issue]
game is crashing upon loading world due to being unable to find a block
### Steps to Reproduce Issue
1. [First step] load my world is all
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
Im useless with comps so i hope this is what you wanted

https://pastebin.com/NAJhnhaB

> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.7.5

**Where did this bug happen:** [Single Player or Server]
Single player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please use pastebin for the crash log, i will reopen when you have changed it :D

**Comment by theplastichero** [comment]
hope thats what you wanted

**Comment by MJRLegends** [comment]
For me to even look at this issue, Please post which block is being placed, as the error is on the PlayerBlockPlacement packet, without this information since it doesnt seem apart from in your world i would be able to do anything for this. It would be like looking for a needle in a ocean

**Comment by theplastichero** [comment]
well thats the problem i logged out just standing around and now this is happening

**Comment by MJRLegends** [comment]
Without knowing what the block being placed is, theres is nothing i can do sorry

**Comment by theplastichero** [comment]
ok no problem ill start a new world i guess wasnt very far through yet, thanks for your help anyway

**Comment by MJRLegends** [comment]
Yeah you should always make backups of your world so you can change back to one of the backups if something like this happens again
