### ISSUE TITLE
Immersive engineering TileEntityImmersiveConnectable Crash

### ISSUE THREAD

**Issue by stormking93** [MJRLegends/Space-Astronomy-Feedback-#965]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes ]

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
[Description of the issue]
"The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded." As I load my world, the server crashes, with this being the first line of information
### Steps to Reproduce Issue
1. [First step]As far as i can tell, opening my world.
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

https://pastebin.com/NwNbniUB

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.7.5
**Where did this bug happen:** [Single Player or Server]
Single
### Additional Information
[Any other information that may be able to help me with the problem]
my launcher asked me to update to 1.4.6. Thats when I started having issues. I use FTB.

**Comment by MJRLegends** [comment]
Immersive engineering TileEntityImmersiveConnectable Crash - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/341 - (This is a mod bug)
Solution 1: Remove ImmersiveEngineering and then load the world and then add it back (will remove everything in your world related to the mod)
Solution 2: Edit the blocks out (coords can be found in the crash log above the mod list) using MCEdit
