### ISSUE TITLE
Circuit Fabricator not working correctly or wiki wrong

### ISSUE THREAD

**Issue by ipwnjustin** [MJRLegends/Space-Astronomy-Feedback-#967]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

Yes.

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

Yes

### Description of Issue
[Description of the issue]

The GalacticCraft Circuit Fabrictor wiki (link here: https://wiki.micdoodle8.com/wiki/Circuit_Fabricator) says under the automation part, "silicon will spread evenly between the two silicon slots (isn't that smart?)" but. In practice when using applied energistics interfaces to input the recipe all the silicon stacks up and doesn't spread.

### Steps to Reproduce Issue
1. Set up a ME System
2. Have a interface connected to the circuit fabricator (anywhere but the bottem cause it outputs from the bottom)
3. Have a pattern made to produce something like a advanced wafer and put that pattern in the me interface connected to the circuit fabricator
4. tell the ME system to craft the wafer
5. boom the silicon stacks up in one place

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

Recommended version (1.7.5 I believe is the recommended one)

**Where did this bug happen:** [Single Player or Server]

Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
@ping radfast , please could you take a look when you get free time, its not a major issue. Once again i appreciate your hard work you put in for Galacticraft.

PS if you need any information please let me know :D

**Comment by MJRLegends** [comment]
ping @radfast , please could you take a look when you get free time, its not a major issue. Once again i appreciate your hard work you put in for Galacticraft.

PS if you need any information please let me know :D

**Comment by radfast** [comment]
which MC and GC version is this?

**Comment by MJRLegends** [comment]
@radfast 1.7.10 & build 502 i believe but could be 1.8+ too

**Comment by radfast** [comment]
this is an issue which is - I think - fixed in 1.8+ but not backported to 1.7.10

**Comment by MJRLegends** [comment]
@radfast Yeah personally i dont do this sort of thing often enough to know, i dont play on survival gameplay much these days. Appreciate the replies though

**Comment by MJRLegends** [comment]
@ipwnjustin Please review the comments above about the hopper use :D

**Comment by ipwnjustin** [comment]
I will give it a try very soon.

**Comment by MJRLegends** [comment]
@ipwnjustin no problem I will call this closed, but if the hopper idea doesn't work i will reopen :P 

@radfast If possible could you match 1.8+ function for this or maybe add a clause to wiki which defines the differences
