### ISSUE TITLE
Cannot jump after equipping Galacticraft parachute

### ISSUE THREAD

**Issue by Fluffgar** [MJRLegends/Space-Astronomy-Feedback-#97]
I can't jump and a strange machine sound plays whenever I try.  

I've found out what it is, but not why. For some reason it happens the first time I put a parachute on (Galacticraft). The arms of the thermal suit stick up as if I'm falling, which looks quite odd given that my character's arms remain as normal. Closing Minecraft and relaunching fixes it. Am also wearing the power armour (without any flight capability).

**Comment by MJRLegends** [comment]
Thanks, I will report this to the galacticraft developers at some point as its a bug on their mod :D

**Comment by TheBlackSlayer** [comment]
Hi everyone I've this bug too and I solved this by replace GalacticraftCore, GalacticraftPlanets and MicdoodleCore with the new 12.460 version from the website: https://micdoodle8.com/mods/galacticraft/downloads
Please correct this bug to everyone in the next modpack version.

**Comment by MJRLegends** [comment]
Thats not the latest version lol

**Comment by MJRLegends** [comment]
Its good your looking at closed issues but you could of posted that on the open issues about this problem
