### ISSUE TITLE
Lag when opening inventory

### ISSUE THREAD

**Issue by Yices** [MJRLegends/Space-Astronomy-Feedback-#973]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
I am lagging when im opening an inventory/chest

### Steps to Reproduce Issue

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
Version: 1.7.5

Usually happens on server and single player.

Never had any problems with opening an inventory or chest in any other modpack

PC specs
i5-7600k
8gb ram ddr4
msi gtx 970
250 gb ssd

**Comment by MJRLegends** [comment]
This isnt a mod pack related thing sorry i dont think i can do anything
