### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by tosstheross** [MJRLegends/Space-Astronomy-Feedback-#975]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] yes
### Description of Issue  
On the quest book When i did the first quest for the storage systems no new quest popped up on that page and it says section only 6% complete so

### Steps to Reproduce Issue
1. [First step] i honestly dont know im sorry
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/37434830/37507889-ac2304f6-28be-11e8-94e1-cc262b8d1950.png)

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION] 1.7.5

**Where did this bug happen:** [Single Player or Server] single player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You need to compete quests in other areas
