### ISSUE TITLE
Don't Know What Happened?

### ISSUE THREAD

**Issue by CatCentaur** [MJRLegends/Space-Astronomy-Feedback-#977]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

When i was playing i opened up on eof my worlds and this happened 
![screen shot 2018-03-19 at 19 15 49](https://user-images.githubusercontent.com/37554964/37617212-58cb670a-2baa-11e8-97c2-486167db2352.png)

Hope you can fix it 
thanks

**Comment by CatCentaur** [comment]
I was using the twitch service through Curse

**Comment by MJRLegends** [comment]
This is to do with your world not a bug
