### ISSUE TITLE
World crashing on load

### ISSUE THREAD

**Issue by limebowler** [MJRLegends/Space-Astronomy-Feedback-#979]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
[Description of the issue]
The server crashed in the middle of the day with no one on after a "No space left on drive" exception. The downloaded world now crashes launching locally.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** https://pastebin.com/0cSmgMPr

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION] 1.7.5

**Where did this bug happen:** [Single Player or Server] Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Delete this folder "world/elec332/"
