### ISSUE TITLE
Problem Completing the "Getting Fuel" quest

### ISSUE THREAD

**Issue by MJRLegends** [MJRLegends/Space-Astronomy-Feedback-#98]
Galacticraft has changed the way you get oil so this quest isnt completable. Use "/hqm edit" to complete the quest, you now need to collect the oil using buckets and then place the bucket in to the refinery like normal, you might have to pause the game and click "Open to Lan" to allow cheats so you can run this command.

**Comment by Jayjayx5x1** [comment]
O_O I thank you very very very much for this first of all now I can continue second I HAVE ULTAMATE QUESTING POWER!!!!!!..... ahem thanks :)

**Comment by MJRLegends** [comment]
@Jayjayx5x1 haha, it should be fixed in the v1.3.0 thats out soon anyways :P
