### ISSUE TITLE
Serverstart.bat will NOT work

### ISSUE THREAD

**Issue by Enalaps** [MJRLegends/Space-Astronomy-Feedback-#980]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
[So I made a server for 3 - 4 people to play on. I tried using the ServerStart.bat but my friends were never able to get on the server. (We are all using hamachi) So instead of using the ServerStart.bat file, I used the forge server .jar file. It works and we are all able to play together but there is a lot of lag. I am trying every way I can to add more RAM or fix the ServerStart.bat file but nothing seems to work for me. If you could help I would tremendously appreciate it!]

### Steps to Reproduce Issue
1. [Download server file and run serverstart.bat]
2. [Change eula.txt to true]
3. [Change server properties, my ip, BIOMESOP, everything is good]
4. [Run serverstart.bat and tell friends to join]
5. [Friends cannot join so i run the forge server .jar file instead (which is really laggy)]

**Crash log/Log (if applicable):** [There is no crash log because the serverstart.bat file runs fine and lets me join but my friends cannot]

**Screenshots (if applicable):** [Everything works on my end so nothing that i screenshot will help]

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [V1.7.5]

**Where did this bug happen:** [Server]

### Additional Information
[None that i can think of]

**Comment by MJRLegends** [comment]
All that does is start the server, its down to you to accept the eula when asked to and get it working with port forwarding.

**Comment by MJRLegends** [comment]
Server files are tested and confined working on each update so i know they 1000% work fine. Im unable to help with port forwarding and issues on your end sorry

**Comment by MJRLegends** [comment]
If you join my discord links on the mod pack description but do be aware no bugs are to be posted there only server and gameplay help and make sure to use the space astronomy channel
