### ISSUE TITLE
Bug with Mekanism liquids

### ISSUE THREAD

**Issue by ContainedShadow** [MJRLegends/Space-Astronomy-Feedback-#982]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [**Yes**] 

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [**Yes**]
### Description of Issue 
Mekanism fluids are not reconised as fluids but as gas.

### Steps to Reproduce Issue
1. Create HCl or Sulfuric Acid (Mekanism).
2. Convert either of them to its liquid form with a rotary condensentrator.
3. Try to get the liquid HCl or the liquid Sulfuric Acid into an dynamic tank or any other fluid tank.

**Screenshots (if applicable):** 
![2018-04-14_22 27 52](https://user-images.githubusercontent.com/25088716/38772283-42b67282-4033-11e8-8aee-d82b0cb9713d.png)
![2018-04-14_22 28 01](https://user-images.githubusercontent.com/25088716/38772284-42cf46d6-4033-11e8-8f37-0cd5f7b1e167.png)
![2018-04-14_22 26 37](https://user-images.githubusercontent.com/25088716/38772285-42eb0c86-4033-11e8-8c98-558fb150411f.png)
![2018-04-14_22 26 54](https://user-images.githubusercontent.com/25088716/38772286-43069a6e-4033-11e8-9505-1c3c68b632ea.png)
![2018-04-14_22 26 57](https://user-images.githubusercontent.com/25088716/38772287-431e9c54-4033-11e8-8ad6-5ca2974b5254.png)
![2018-04-14_22 27 12](https://user-images.githubusercontent.com/25088716/38772288-43518790-4033-11e8-9ce5-5a160306bcba.png)

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [Version 1.7.5]

**Where did this bug happen:** [**Server**]

### Additional Information
As you can see in the first picture it outputs the Liquid Sulfuric Acid to a gas conduit.
Therefor I'm assuming it sees the Liquid Sulfuric Acid as regular Sulfuric Acid.

**Comment by MJRLegends** [comment]
Thanks for the bug report guess you fixed the issue?

**Comment by ContainedShadow** [comment]
Yea a server restart did the trick.

**Comment by MJRLegends** [comment]
Nice glad it you got it working :D
