### ISSUE TITLE
Minecraft crashes when opening

### ISSUE THREAD

**Issue by Nightingale1776** [MJRLegends/Space-Astronomy-Feedback-#983]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
My minecraft launcher opens the game fine, but when I click to load my world it crashes and gives me this as the first line: "Description: Exception getting block type in world"

### Steps to Reproduce Issue
1. [First step] Simply opening my world from the single player worlds list
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC
[crash-2018-04-16_19.12.00-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/1917639/crash-2018-04-16_19.12.00-server.txt)

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.7.5]
**Where did this bug happen:** [Single Player]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by Nightingale1776** [comment]
[crash-2018-04-16_19.12.00-server.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/1917645/crash-2018-04-16_19.12.00-server.txt)

**Comment by MJRLegends** [comment]
Uae pastebin please it says not to upload the file and you have done just that

**Comment by MJRLegends** [comment]
Also your crash is in the known issues. Please read them to fix your issue this has been posted 1000 times already and we dont need more issues reports for it when you can just take 1 min to use the search bar or look at the known issues
