### ISSUE TITLE
Server files not functioning properly?

### ISSUE THREAD

**Issue by Spaceball12** [MJRLegends/Space-Astronomy-Feedback-#985]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
When I attempt to run the Server.bat file after extracting the folder containing the server files, it simply...does not run. I checked and have the latest version of Java, and have attempted one redownload with the same results. (If it requires a version of Java other than the latest I would like to know which version this is)

### Steps to Reproduce Issue
1. Run the minecraft_server.1.7.10.jar file
2. Open the eula.txt file that then appears and change eula=false to eula=true
3. Try to run the Server.bat file with latest Java

**Crash log/Log (if applicable):** (took a screenshot since it's pretty short and don't know how exactly to copy Command Prompt window text) https://cdn.discordapp.com/attachments/315006726384386048/440299574494625813/Screenshot_690.png
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.7.5

**Where did this bug happen:** Server

### Additional Information
I could not find any up-to-date tutorial on setting up the server, and I tried to follow this one (https://www.youtube.com/watch?v=0E0U1pvHjK8) as closely as I could, but it still does not quite work. If there is some more up-to-date documentation on doing this and it is simply user error on my part, please do point me in the right direction :D

**Comment by MJRLegends** [comment]
What java you using?

**Comment by CuttlefishEmpire** [comment]
10.0.01

**Comment by MJRLegends** [comment]
thats your issue minecraft doesnt work with java 9 or 10

**Comment by CuttlefishEmpire** [comment]
Like...minecraft, as a whole?

**Comment by MJRLegends** [comment]
Modded mc yeah
