### ISSUE TITLE
Issue in launcher

### ISSUE THREAD

**Issue by SirPuggo** [MJRLegends/Space-Astronomy-Feedback-#987]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] yes

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]
I open the launcher and it says "Launch Failed the version you are trying to play inherits properties from an  unknown version."

### Steps to Reproduce Issue
1. Open twitch
2. Click play
3. Minecraft launcher opens
4. Click play
5. issue shows up

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them] no
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
http://prntscr.com/jk5xys
**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.7.5
**Where did this bug happen:** [Single Player or Server]
In launcher
### Additional Information
[Any other information that may be able to help me with the problem]
I managed to get in last night but that was after many tries

**Comment by MJRLegends** [comment]
Contact the people who make the launcher they can help as we dont offer launcher support here i only make packs not launchers
