### ISSUE TITLE
Minechem Instability

### ISSUE THREAD

**Issue by Grant4455** [MJRLegends/Space-Astronomy-Feedback-#988]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes 

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
Minechem has been, in the short time I've played with it, rather unstable. Specifically, it freezes (though does not crash) when certain items are decomposed, and the decomposer itself has a GUI issue such that whenever a player disconnects and then reconnects, it will display itself as unpowered, with no inventory contents until broken and replaced. 

### Steps to Reproduce Issue
1. Start a local server and join it.
2. Place a chemical decompose, power it with Immersive Engineering junctures, decompose something
3. Disconnect & Reconnect

**Crash log/Log (if applicable): N/A

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.7.5

**Where did this bug happen:** Server

### Additional Information
N/A

**Comment by MJRLegends** [comment]
No idea sorry without loads more detail this issue cant be even locked at let alone find the issue. it could be about 1 in 100 things wrong
