### ISSUE TITLE
Big Reactors Interaction crash

### ISSUE THREAD

**Issue by diggerdude1001** [MJRLegends/Space-Astronomy-Feedback-#989]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes
### Description of Issue
[Description of the issue]
When clicking on a Big Reactors Controller or Turbine Controller GUI I get this crash. This also happens when destroying other blocks or clicking on other modded GUIs. It seems to happen at random with other blocks, but almost always happens with the Big Reactors Controllers.
### Steps to Reproduce Issue
1. [First step]
Open up save and load it in.
2. [Second step]
Click on Big Reactor/Turbine Controller (though it is not just limited to those blocks as I have said).
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them] https://pastebin.com/x0Tx1yn3
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.7.5
**Where did this bug happen:** [Single Player or Server]
Single Player
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
i believe this is a already known bug, cant remember the issue number will take a look in a bit

**Comment by MJRLegends** [comment]
I've added it to https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/934 Sorry that it cant be fixed :P

**Comment by diggerdude1001** [comment]
Thanks anyway :)
