### ISSUE TITLE
Immersive Engineering Wires Disappearing.

### ISSUE THREAD

**Issue by BloodravenD** [MJRLegends/Space-Astronomy-Feedback-#99]
As the title suggests, I've had quite a few wires disappearing, and I'm not sure what is causing it.  Not all of them have done it, the 3-4 on a windmill to MV relays were still there, however the bottom ones were missing, as were the ones from my watermills going to my MFR farm, and the ones inside my basement where I have my immersive engineering setup to produce biodiesel.  I know it's not caused by going to a different dimension, I have a nether portal and a portal to the miner's dimension, and the wires were fine when I closed the game earlier, and the previous version of the modpack as well, so it must've been something in the latest update.

**Comment by MJRLegends** [comment]
I will report to the mod developer at some point. But the next update for the mod might fix it so we will see how it goes in the v1.3.0 update

**Comment by BluSunrize** [comment]
What version of IE?

**Comment by MJRLegends** [comment]
It would be v0.5.4

**Comment by BluSunrize** [comment]
Update IE then.

**Comment by MJRLegends** [comment]
It will be in the update for my mod pack that's coming out soon but I'm having problems with a few mods atm so the update is delayed. But I thought I'd report the bug just in case.

**Comment by BluSunrize** [comment]
Reporting bugs on outdated versions isn't very helpful, but thanks. x3
