### ISSUE TITLE
Space Astronomy 1 Quest Book Crashes Game

### ISSUE THREAD

**Issue by MrRed4802** [MJRLegends/Space-Astronomy-Feedback-#991]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
Whenever I go to open my quest book my game freezes and won't respond at all.  There is no error given and nothing is shown in the log about why.  Everything was working fine not too long ago but yesterday this issue started happening and I cant figure out why.  

### Steps to Reproduce Issue
Unknown

**Crash log/Log (if applicable):** https://pastebin.com/Wa4saSWg

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.7.5

**Where did this bug happen:** Server

### Additional Information
The only other info I could find on this bug was from a 3 year old thread where another guy had the same problem and they didn't know what the fix for it was.

**Comment by MJRLegends** [comment]
This wont be fixed sorry

**Comment by MrRed4802** [comment]
Why? Ive tried reinstalling the whole mudpack and that did work so is it something hardware related?  I didn't think it would be that since the mudpack has been working fine for a while now

**Comment by MJRLegends** [comment]
1.7.10 mods are not being updated now so things like this wont get ever touched/fixed
