### ISSUE TITLE
Crash when entering a server

### ISSUE THREAD

**Issue by ImCrashKing** [MJRLegends/Space-Astronomy-Feedback-#993]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
YES
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
YES
### Description of Issue
When i connect to a server, 20sec after the loading ( cannot move duirng) the game crash "Java platform se binary stopped working"
### Steps to Reproduce Issue
I just launch space astnomy
Try to connect to any server, and crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC
Nocrash log i dont know why
**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
SPace astronomy 1.7.5
**Where did this bug happen:** [Single Player or Server]
server
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You need a crash log or im unable to help otherwise
