### ISSUE TITLE
0 fps

### ISSUE THREAD

**Issue by dj-gubs** [MJRLegends/Space-Astronomy-Feedback-#994]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
[quando ho aperto il gioco si è caricato il mondo e dopo qualche secondo gli fps scendono da 70 a 0 per circa 3 secondi e poi risalgono a 70 per 5 secondi prima che si riverifica il problema e continua per tutto il tempo]

### Steps to Reproduce Issue
1. apro il modpack
2. si avvia il server offline e esce il problema

**Crash log/Log no

**Screenshots (no):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.7.5

**Where did this bug happen:** [Single Player]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Nothing i can do for you there, sorry. Also i only understand English, sorry
