### ISSUE TITLE
Crashing when going through an end portal

### ISSUE THREAD

**Issue by dropveter37** [MJRLegends/Space-Astronomy-Feedback-#998]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
No, because it told me there weren't any known issues

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]
Yes

### Steps to Reproduce Issue
1. 
Create a new world with biomes o' plenty biomes
2. 
Go to the strong hold and try to go through the end portal
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
https://pastebin.com/4FEhD0V3

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Version 1.7.7
**Where did this bug happen:** [Single Player or Server]
Single player
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You pastebin for the log, will reopen when you have changed it

**Comment by MJRLegends** [comment]
You have edited the mod pack so your issue will not be looked at in till a crash report is posted without your edits

```
PackGuard: VERSION_MISMATCH: ae2stuff v0.5.1.9, MISSING: Hats v4.0.1,
ADDED: movillages v1.4.2, ADDED: StartingInventory v1.7.10.r03,
ADDED: backpacks16840 v3.5.4, ADDED: chancecubes v1.7.10-2.4.1.0,
ADDED: ChestTransporter v2.0.6, ADDED: chocolateQuest v1.0,
ADDED: lootbags v2.0.17, ADDED: MoreFurnaces v1.3.9,
ADDED: Morph v0.9.3, ADDED: rftools v4.23, ADDED: IguanaTweaksTConstruct v1.7.10-2.1.6.163,
```
